// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

#include "go_asm.h"
#include "funcdata.h"
#include "textflag.h"

TEXT ·__f32toa_entry__(SB), NOSPLIT, $0-8
	MOV $·__f32toa_riscv64_entry__(SB), A0
	MOV A0, ret+0(FP)
	RET

TEXT ·__f32toa_riscv64_entry__(SB), NOSPLIT, $0
	NO_LOCAL_POINTERS
f32toa:
	WORD $0xe0050653  // fmv.x.w	a2, fa0
	WORD $0x02161593  // slli	a1, a2, 33
	WORD $0x0385d593  // srli	a1, a1, 56
	WORD $0x0ff00693  // li	a3, 255
	BEQ X11, X13, LBB0_117  // beq	a1, a3, .LBB0_117
	WORD $0x02d00693  // li	a3, 45
	WORD $0x01f6529b  // srliw	t0, a2, 31
	WORD $0xf00007d3  // fmv.w.x	fa5, zero
	WORD $0x00d50023  // sb	a3, 0(a0)
	WORD $0xa0f526d3  // feq.s	a3, fa0, fa5
	WORD $0x00550333  // add	t1, a0, t0
	BEQZ X13, LBB0_3  // beqz	a3, .LBB0_3
	WORD $0x03000593  // li	a1, 48
	WORD $0x40a30533  // sub	a0, t1, a0
	WORD $0x00b30023  // sb	a1, 0(t1)
	WORD $0x0015051b  // addiw	a0, a0, 1
	RET  // ret
LBB0_3:
	WORD $0xff010113  // addi	sp, sp, -16
	WORD $0x00813423  // sd	s0, 8(sp)
	WORD $0x00913023  // sd	s1, 0(sp)
	WORD $0x02961613  // slli	a2, a2, 41
	WORD $0x02965713  // srli	a4, a2, 41
	BEQZ X11, LBB0_118  // beqz	a1, .LBB0_118
	WORD $0x00800637  // lui	a2, 2048
	WORD $0xf8158793  // addi	a5, a1, -127
	WORD $0x01700693  // li	a3, 23
	WORD $0x00e66633  // or	a2, a2, a4
	WORD $0xf6a58813  // addi	a6, a1, -150
	BLTU X13, X15, LBB0_6  // bltu	a3, a5, .LBB0_6
	WORD $0x09600793  // li	a5, 150
	WORD $0x40b787b3  // sub	a5, a5, a1
	WORD $0xfff00693  // li	a3, -1
	WORD $0x00f696b3  // sll	a3, a3, a5
	WORD $0xfff6c693  // not	a3, a3
	WORD $0x00c6f6b3  // and	a3, a3, a2
	BEQZ X13, LBB0_30  // beqz	a3, .LBB0_30
LBB0_6:
	WORD $0x00167893  // andi	a7, a2, 1
	WORD $0x00173693  // seqz	a3, a4
	WORD $0x0025b713  // sltiu	a4, a1, 2
	WORD $0x00261593  // slli	a1, a2, 2
	WORD $0x00134637  // lui	a2, 308
	WORD $0xfff807b7  // lui	a5, 1048448
	WORD $0xffe573b7  // lui	t2, 1048151
	WORD $0x01f00e13  // li	t3, 31
	WORD $0x00174713  // xori	a4, a4, 1
	WORD $0x10178793  // addi	a5, a5, 257
	WORD $0x00e6f6b3  // and	a3, a3, a4
	WORD $0x40d0073b  // negw	a4, a3
	WORD $0x00f77733  // and	a4, a4, a5
	MOV $·p590e8398564ef85b_pow10_ceil_sig_f32_g(SB), X15  // lui	a5, %hi(pow10_ceil_sig_f32.g)
	// addi	a5, a5, %lo(pow10_ceil_sig_f32.g) (skipped, covered by MOV address load)
	WORD $0x41360613  // addi	a2, a2, 1043
	WORD $0x02c80633  // mul	a2, a6, a2
	WORD $0x00e60633  // add	a2, a2, a4
	WORD $0xfff00e93  // li	t4, -1
	WORD $0xcb13871b  // addiw	a4, t2, -847
	WORD $0x4166539b  // sraiw	t2, a2, 22
	WORD $0x02e38633  // mul	a2, t2, a4
	WORD $0x01365613  // srli	a2, a2, 19
	WORD $0x01060633  // add	a2, a2, a6
	WORD $0x02800813  // li	a6, 40
	WORD $0x407e0733  // sub	a4, t3, t2
	WORD $0x00371713  // slli	a4, a4, 3
	WORD $0x00f70733  // add	a4, a4, a5
	WORD $0x00258793  // addi	a5, a1, 2
	WORD $0x021e9e93  // slli	t4, t4, 33
	WORD $0x00b6e6b3  // or	a3, a3, a1
	WORD $0xffe68693  // addi	a3, a3, -2
	WORD $0x00160613  // addi	a2, a2, 1
	WORD $0x00073703  // ld	a4, 0(a4)
	WORD $0x00c696bb  // sllw	a3, a3, a2
	WORD $0x00c595bb  // sllw	a1, a1, a2
	WORD $0x00c7963b  // sllw	a2, a5, a2
	WORD $0x02069693  // slli	a3, a3, 32
	WORD $0x02059593  // slli	a1, a1, 32
	WORD $0x02061613  // slli	a2, a2, 32
	WORD $0x0206d693  // srli	a3, a3, 32
	WORD $0x0205de13  // srli	t3, a1, 32
	WORD $0x02065613  // srli	a2, a2, 32
	WORD $0x02e6b5b3  // mulhu	a1, a3, a4
	WORD $0x02e686b3  // mul	a3, a3, a4
	WORD $0x01d6f6b3  // and	a3, a3, t4
	WORD $0x00d036b3  // snez	a3, a3
	WORD $0x00d5e5b3  // or	a1, a1, a3
	WORD $0x02e636b3  // mulhu	a3, a2, a4
	WORD $0x02e60633  // mul	a2, a2, a4
	WORD $0x01d67633  // and	a2, a2, t4
	WORD $0x00c03633  // snez	a2, a2
	WORD $0x00c6e6b3  // or	a3, a3, a2
	WORD $0x02ee34b3  // mulhu	s1, t3, a4
	WORD $0x01158f3b  // addw	t5, a1, a7
	WORD $0x411685bb  // subw	a1, a3, a7
	BLTU X9, X16, LBB0_8  // bltu	s1, a6, .LBB0_8
	WORD $0x000cd8b7  // lui	a7, 205
	WORD $0x020f1f93  // slli	t6, t5, 32
	WORD $0x02059693  // slli	a3, a1, 32
	WORD $0xccd8879b  // addiw	a5, a7, -819
	WORD $0x020fd893  // srli	a7, t6, 32
	WORD $0x0206d413  // srli	s0, a3, 32
	WORD $0x00c79793  // slli	a5, a5, 12
	WORD $0xccd78793  // addi	a5, a5, -819
	WORD $0x02f487b3  // mul	a5, s1, a5
	WORD $0x0257df93  // srli	t6, a5, 37
	WORD $0x030f87b3  // mul	a5, t6, a6
	WORD $0x02878693  // addi	a3, a5, 40
	WORD $0x00d436b3  // sltu	a3, s0, a3
	WORD $0x0016c693  // xori	a3, a3, 1
	WORD $0x0117b7b3  // sltu	a5, a5, a7
	BEQ X15, X13, LBB0_13  // beq	a5, a3, .LBB0_13
LBB0_8:
	WORD $0xffc4f613  // andi	a2, s1, -4
	WORD $0x0006069b  // sext.w	a3, a2
	WORD $0x0046079b  // addiw	a5, a2, 4
	WORD $0x00f5b5b3  // sltu	a1, a1, a5
	WORD $0x0015c593  // xori	a1, a1, 1
	WORD $0x01e6b7b3  // sltu	a5, a3, t5
	WORD $0x0024d693  // srli	a3, s1, 2
	BEQ X15, X11, LBB0_12  // beq	a5, a1, .LBB0_12
	WORD $0x02ee05b3  // mul	a1, t3, a4
	WORD $0x01d5f5b3  // and	a1, a1, t4
	WORD $0x00b035b3  // snez	a1, a1
	WORD $0x0095e5b3  // or	a1, a1, s1
	WORD $0x00266713  // ori	a4, a2, 2
	WORD $0x00100613  // li	a2, 1
	BLTU X14, X11, LBB0_11  // bltu	a4, a1, .LBB0_11
	WORD $0x00e5c5b3  // xor	a1, a1, a4
	WORD $0x0015b613  // seqz	a2, a1
	WORD $0x00d67633  // and	a2, a2, a3
LBB0_11:
	WORD $0x00d60fb3  // add	t6, a2, a3
	JMP LBB0_14  // j	.LBB0_14
LBB0_12:
	WORD $0x00b68fb3  // add	t6, a3, a1
	JMP LBB0_14  // j	.LBB0_14
LBB0_13:
	WORD $0x00df8fb3  // add	t6, t6, a3
	WORD $0x00138393  // addi	t2, t2, 1
LBB0_14:
	WORD $0x000185b7  // lui	a1, 24
	WORD $0x6a05859b  // addiw	a1, a1, 1696
	BLTU X31, X11, LBB0_18  // bltu	t6, a1, .LBB0_18
	WORD $0x000f45b7  // lui	a1, 244
	WORD $0x2405859b  // addiw	a1, a1, 576
	WORD $0x00600e13  // li	t3, 6
	BLTU X31, X11, LBB0_22  // bltu	t6, a1, .LBB0_22
	WORD $0x009895b7  // lui	a1, 2441
	WORD $0x6805859b  // addiw	a1, a1, 1664
	WORD $0x00700e13  // li	t3, 7
	BLTU X31, X11, LBB0_22  // bltu	t6, a1, .LBB0_22
	WORD $0x05f5e5b7  // lui	a1, 24414
	WORD $0x1005859b  // addiw	a1, a1, 256
	WORD $0x00bfb5b3  // sltu	a1, t6, a1
	WORD $0x0095ce13  // xori	t3, a1, 9
	JMP LBB0_22  // j	.LBB0_22
LBB0_18:
	WORD $0x00a00593  // li	a1, 10
	WORD $0x00100e13  // li	t3, 1
	BLTU X31, X11, LBB0_22  // bltu	t6, a1, .LBB0_22
	WORD $0x06400593  // li	a1, 100
	WORD $0x00200e13  // li	t3, 2
	BLTU X31, X11, LBB0_22  // bltu	t6, a1, .LBB0_22
	WORD $0x3e800593  // li	a1, 1000
	WORD $0x00300e13  // li	t3, 3
	BLTU X31, X11, LBB0_22  // bltu	t6, a1, .LBB0_22
	WORD $0x004fd593  // srli	a1, t6, 4
	WORD $0x2715b593  // sltiu	a1, a1, 625
	WORD $0x0055ce13  // xori	t3, a1, 5
LBB0_22:
	WORD $0x007e0833  // add	a6, t3, t2
	WORD $0xfea80593  // addi	a1, a6, -22
	WORD $0xfe400693  // li	a3, -28
	BLTU X13, X11, LBB0_26  // bltu	a3, a1, .LBB0_26
	WORD $0x00130893  // addi	a7, t1, 1
	WORD $0x004fd593  // srli	a1, t6, 4
	WORD $0x27100713  // li	a4, 625
	WORD $0x01c886b3  // add	a3, a7, t3
	BLTU X11, X14, LBB0_29  // bltu	a1, a4, .LBB0_29
	WORD $0x68db95b7  // lui	a1, 429497
	WORD $0xffffe737  // lui	a4, 1048574
	WORD $0xbad5859b  // addiw	a1, a1, -1107
	WORD $0x02bf85b3  // mul	a1, t6, a1
	WORD $0x02c5d413  // srli	s0, a1, 44
	WORD $0x8f070713  // addi	a4, a4, -1808
	WORD $0x02e40733  // mul	a4, s0, a4
	WORD $0x01f7063b  // addw	a2, a4, t6
	WORD $0xffc68693  // addi	a3, a3, -4
	BEQZ X12, LBB0_54  // beqz	a2, .LBB0_54
	WORD $0x00000393  // li	t2, 0
	WORD $0x51eb8737  // lui	a4, 335544
	WORD $0x02061793  // slli	a5, a2, 32
	WORD $0x51f70713  // addi	a4, a4, 1311
	WORD $0x02071713  // slli	a4, a4, 32
	WORD $0x02e7b733  // mulhu	a4, a5, a4
	WORD $0x06400793  // li	a5, 100
	WORD $0x02575713  // srli	a4, a4, 37
	WORD $0x02f707b3  // mul	a5, a4, a5
	WORD $0x40f6063b  // subw	a2, a2, a5
	MOV $·p590e8398564ef85b_Digits(SB), X15  // lui	a5, %hi(Digits)
	// addi	a5, a5, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x00171713  // slli	a4, a4, 1
	WORD $0x00f70733  // add	a4, a4, a5
	WORD $0x0016161b  // slliw	a2, a2, 1
	WORD $0x00f60633  // add	a2, a2, a5
	WORD $0xcc517057  // vsetivli	zero, 2, e8, mf8, ta, ma
	WORD $0x02060407  // vle8.v	v8, (a2)
	WORD $0x02070487  // vle8.v	v9, (a4)
	WORD $0xcc527057  // vsetivli	zero, 4, e8, mf8, ta, ma
	WORD $0x3a8134d7  // vslideup.vi	v9, v8, 2
	WORD $0x020684a7  // vse8.v	v9, (a3)
	JMP LBB0_55  // j	.LBB0_55
LBB0_26:
	BLTZ X7, LBB0_33  // bltz	t2, .LBB0_33
	WORD $0x004fd593  // srli	a1, t6, 4
	WORD $0x27100693  // li	a3, 625
	WORD $0x01c30433  // add	s0, t1, t3
	BLTU X11, X13, LBB0_36  // bltu	a1, a3, .LBB0_36
	WORD $0x68db95b7  // lui	a1, 429497
	WORD $0xffffe6b7  // lui	a3, 1048574
	WORD $0x51eb87b7  // lui	a5, 335544
	WORD $0xbad5859b  // addiw	a1, a1, -1107
	WORD $0x8f068693  // addi	a3, a3, -1808
	WORD $0x51f78793  // addi	a5, a5, 1311
	WORD $0x02bf85b3  // mul	a1, t6, a1
	WORD $0x02079793  // slli	a5, a5, 32
	WORD $0x02c5d593  // srli	a1, a1, 44
	WORD $0x02d586b3  // mul	a3, a1, a3
	WORD $0x01f68633  // add	a2, a3, t6
	WORD $0x02061693  // slli	a3, a2, 32
	WORD $0x02f6b6b3  // mulhu	a3, a3, a5
	WORD $0x06400793  // li	a5, 100
	WORD $0x0256d693  // srli	a3, a3, 37
	WORD $0x02f687b3  // mul	a5, a3, a5
	WORD $0x40f6063b  // subw	a2, a2, a5
	MOV $·p590e8398564ef85b_Digits(SB), X15  // lui	a5, %hi(Digits)
	// addi	a5, a5, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x00169693  // slli	a3, a3, 1
	WORD $0x00f686b3  // add	a3, a3, a5
	WORD $0x0016161b  // slliw	a2, a2, 1
	WORD $0x00f60633  // add	a2, a2, a5
	WORD $0xcc517057  // vsetivli	zero, 2, e8, mf8, ta, ma
	WORD $0x02060407  // vle8.v	v8, (a2)
	WORD $0x02068487  // vle8.v	v9, (a3)
	WORD $0xffc40693  // addi	a3, s0, -4
	WORD $0xcc527057  // vsetivli	zero, 4, e8, mf8, ta, ma
	WORD $0x3a8134d7  // vslideup.vi	v9, v8, 2
	WORD $0x020684a7  // vse8.v	v9, (a3)
	WORD $0x00058f93  // mv	t6, a1
	JMP LBB0_37  // j	.LBB0_37
LBB0_29:
	WORD $0x00000393  // li	t2, 0
	WORD $0x000f8413  // mv	s0, t6
	JMP LBB0_55  // j	.LBB0_55
LBB0_30:
	WORD $0x00f652bb  // srlw	t0, a2, a5
	WORD $0x000185b7  // lui	a1, 24
	WORD $0x6a05859b  // addiw	a1, a1, 1696
	MOV $·p590e8398564ef85b_Digits(SB), X17  // lui	a7, %hi(Digits)
	// addi	a7, a7, %lo(Digits) (skipped, covered by MOV address load)
	BLTU X5, X11, LBB0_50  // bltu	t0, a1, .LBB0_50
	WORD $0x000f45b7  // lui	a1, 244
	WORD $0x2405859b  // addiw	a1, a1, 576
	BGEU X5, X11, LBB0_77  // bgeu	t0, a1, .LBB0_77
	WORD $0x00600713  // li	a4, 6
	JMP LBB0_78  // j	.LBB0_78
LBB0_33:
	BGTZ X16, LBB0_89  // bgtz	a6, .LBB0_89
	WORD $0x03000593  // li	a1, 48
	WORD $0x00230693  // addi	a3, t1, 2
	WORD $0x02e00713  // li	a4, 46
	WORD $0x00b30023  // sb	a1, 0(t1)
	WORD $0x00e300a3  // sb	a4, 1(t1)
	BLTZ X16, LBB0_87  // bltz	a6, .LBB0_87
	WORD $0x00068313  // mv	t1, a3
	JMP LBB0_89  // j	.LBB0_89
LBB0_36:
	WORD $0x00040693  // mv	a3, s0
LBB0_37:
	WORD $0x06400893  // li	a7, 100
	BLTU X31, X17, LBB0_40  // bltu	t6, a7, .LBB0_40
	WORD $0xffe68693  // addi	a3, a3, -2
	WORD $0x51eb85b7  // lui	a1, 335544
	MOV $·p590e8398564ef85b_Digits(SB), X7  // lui	t2, %hi(Digits)
	// addi	t2, t2, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x51f58593  // addi	a1, a1, 1311
	WORD $0x02059593  // slli	a1, a1, 32
	WORD $0x27000e93  // li	t4, 624
	WORD $0xcc517057  // vsetivli	zero, 2, e8, mf8, ta, ma
LBB0_39:
	WORD $0x020f9793  // slli	a5, t6, 32
	WORD $0x02b7b7b3  // mulhu	a5, a5, a1
	WORD $0x0257d793  // srli	a5, a5, 37
	WORD $0x031784b3  // mul	s1, a5, a7
	WORD $0x409f863b  // subw	a2, t6, s1
	WORD $0x0016161b  // slliw	a2, a2, 1
	WORD $0x00760633  // add	a2, a2, t2
	WORD $0x02060407  // vle8.v	v8, (a2)
	WORD $0x004fd61b  // srliw	a2, t6, 4
	WORD $0x02068427  // vse8.v	v8, (a3)
	WORD $0xffe68693  // addi	a3, a3, -2
	WORD $0x00078f93  // mv	t6, a5
	BLTU X29, X12, LBB0_39  // bltu	t4, a2, .LBB0_39
	JMP LBB0_41  // j	.LBB0_41
LBB0_40:
	WORD $0x000f8793  // mv	a5, t6
LBB0_41:
	WORD $0x00a00593  // li	a1, 10
	BLTU X15, X11, LBB0_43  // bltu	a5, a1, .LBB0_43
	WORD $0x0017959b  // slliw	a1, a5, 1
	MOV $·p590e8398564ef85b_Digits(SB), X12  // lui	a2, %hi(Digits)
	// addi	a2, a2, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x00c585b3  // add	a1, a1, a2
	WORD $0xcc517057  // vsetivli	zero, 2, e8, mf8, ta, ma
	WORD $0x02058407  // vle8.v	v8, (a1)
	WORD $0x02030427  // vse8.v	v8, (t1)
	JMP LBB0_44  // j	.LBB0_44
LBB0_43:
	WORD $0x0307e593  // ori	a1, a5, 48
	WORD $0x00b30023  // sb	a1, 0(t1)
LBB0_44:
	WORD $0x010305b3  // add	a1, t1, a6
	BGEU X28, X16, LBB0_113  // bgeu	t3, a6, .LBB0_113
	WORD $0x00a282b3  // add	t0, t0, a0
	WORD $0x005e0e33  // add	t3, t3, t0
	WORD $0x001e0613  // addi	a2, t3, 1
	WORD $0x00580833  // add	a6, a6, t0
	BLTU X16, X12, LBB0_47  // bltu	a6, a2, .LBB0_47
	WORD $0x00080613  // mv	a2, a6
LBB0_47:
	WORD $0x41c60633  // sub	a2, a2, t3
	WORD $0xfc000693  // li	a3, -64
	BLTU X12, X13, LBB0_75  // bltu	a2, a3, .LBB0_75
	WORD $0x03000613  // li	a2, 48
LBB0_49:
	WORD $0x00140693  // addi	a3, s0, 1
	WORD $0x00c40023  // sb	a2, 0(s0)
	WORD $0x00068413  // mv	s0, a3
	BLTU X13, X11, LBB0_49  // bltu	a3, a1, .LBB0_49
	JMP LBB0_113  // j	.LBB0_113
LBB0_50:
	WORD $0x00a00593  // li	a1, 10
	WORD $0x00100813  // li	a6, 1
	BLTU X5, X11, LBB0_53  // bltu	t0, a1, .LBB0_53
	WORD $0x06400593  // li	a1, 100
	WORD $0x00200813  // li	a6, 2
	BLTU X5, X11, LBB0_53  // bltu	t0, a1, .LBB0_53
	WORD $0x3e700593  // li	a1, 999
	WORD $0x00300813  // li	a6, 3
	BLTU X11, X5, LBB0_115  // bltu	a1, t0, .LBB0_115
LBB0_53:
	WORD $0x00680833  // add	a6, a6, t1
	WORD $0x00080713  // mv	a4, a6
	JMP LBB0_80  // j	.LBB0_80
LBB0_54:
	WORD $0xffc00393  // li	t2, -4
LBB0_55:
	WORD $0x06400e93  // li	t4, 100
	BLTU X8, X29, LBB0_58  // bltu	s0, t4, .LBB0_58
	WORD $0xffe68693  // addi	a3, a3, -2
	WORD $0x51eb8637  // lui	a2, 335544
	MOV $·p590e8398564ef85b_Digits(SB), X30  // lui	t5, %hi(Digits)
	// addi	t5, t5, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x51f60793  // addi	a5, a2, 1311
	WORD $0x02079793  // slli	a5, a5, 32
	WORD $0x27000713  // li	a4, 624
	WORD $0xcc517057  // vsetivli	zero, 2, e8, mf8, ta, ma
LBB0_57:
	WORD $0x02041613  // slli	a2, s0, 32
	WORD $0x02f63633  // mulhu	a2, a2, a5
	WORD $0x02565613  // srli	a2, a2, 37
	WORD $0x03d604b3  // mul	s1, a2, t4
	WORD $0x409405bb  // subw	a1, s0, s1
	WORD $0x0015959b  // slliw	a1, a1, 1
	WORD $0x01e585b3  // add	a1, a1, t5
	WORD $0x02058407  // vle8.v	v8, (a1)
	WORD $0x0044559b  // srliw	a1, s0, 4
	WORD $0x02068427  // vse8.v	v8, (a3)
	WORD $0xffe68693  // addi	a3, a3, -2
	WORD $0x00060413  // mv	s0, a2
	BLTU X14, X11, LBB0_57  // bltu	a4, a1, .LBB0_57
	JMP LBB0_59  // j	.LBB0_59
LBB0_58:
	WORD $0x00040613  // mv	a2, s0
LBB0_59:
	WORD $0x00a00593  // li	a1, 10
	BLTU X12, X11, LBB0_61  // bltu	a2, a1, .LBB0_61
	WORD $0x0016159b  // slliw	a1, a2, 1
	MOV $·p590e8398564ef85b_Digits(SB), X12  // lui	a2, %hi(Digits)
	// addi	a2, a2, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x00b60633  // add	a2, a2, a1
	WORD $0x00064583  // lbu	a1, 0(a2)
	WORD $0x00b300a3  // sb	a1, 1(t1)
	WORD $0x00164603  // lbu	a2, 1(a2)
	WORD $0x00c30123  // sb	a2, 2(t1)
	JMP LBB0_62  // j	.LBB0_62
LBB0_61:
	WORD $0x03066593  // ori	a1, a2, 48
	WORD $0x00b88023  // sb	a1, 0(a7)
LBB0_62:
	WORD $0x00538633  // add	a2, t2, t0
	WORD $0x00138393  // addi	t2, t2, 1
	WORD $0x00a60633  // add	a2, a2, a0
	WORD $0x03000693  // li	a3, 48
LBB0_63:
	WORD $0x01c60733  // add	a4, a2, t3
	WORD $0x00074703  // lbu	a4, 0(a4)
	WORD $0xfff60613  // addi	a2, a2, -1
	WORD $0xfff38393  // addi	t2, t2, -1
	BEQ X14, X13, LBB0_63  // beq	a4, a3, .LBB0_63
	WORD $0x00b30023  // sb	a1, 0(t1)
	WORD $0x01c383b3  // add	t2, t2, t3
	WORD $0x00200593  // li	a1, 2
	WORD $0x01c60633  // add	a2, a2, t3
	BLT X7, X11, LBB0_66  // blt	t2, a1, .LBB0_66
	WORD $0x00260613  // addi	a2, a2, 2
	WORD $0x02e00593  // li	a1, 46
	WORD $0x00b88023  // sb	a1, 0(a7)
	JMP LBB0_67  // j	.LBB0_67
LBB0_66:
	WORD $0x00160613  // addi	a2, a2, 1
LBB0_67:
	WORD $0x06500593  // li	a1, 101
	WORD $0x00b60023  // sb	a1, 0(a2)
	BLEZ X16, LBB0_69  // blez	a6, .LBB0_69
	WORD $0xfff80813  // addi	a6, a6, -1
	WORD $0x02b00593  // li	a1, 43
	JMP LBB0_70  // j	.LBB0_70
LBB0_69:
	WORD $0x00100593  // li	a1, 1
	WORD $0x41058833  // sub	a6, a1, a6
	WORD $0x02d00593  // li	a1, 45
LBB0_70:
	WORD $0x00b600a3  // sb	a1, 1(a2)
	WORD $0x06400693  // li	a3, 100
	WORD $0x00260593  // addi	a1, a2, 2
	BLTU X16, X13, LBB0_72  // bltu	a6, a3, .LBB0_72
	WORD $0xccccd6b7  // lui	a3, 838861
	WORD $0x02081713  // slli	a4, a6, 32
	WORD $0x00a00793  // li	a5, 10
	WORD $0xccd68693  // addi	a3, a3, -819
	WORD $0x02069693  // slli	a3, a3, 32
	WORD $0x02d736b3  // mulhu	a3, a4, a3
	MOV $·p590e8398564ef85b_Digits(SB), X14  // lui	a4, %hi(Digits)
	// addi	a4, a4, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x0236d693  // srli	a3, a3, 35
	WORD $0x02f687b3  // mul	a5, a3, a5
	WORD $0x00169693  // slli	a3, a3, 1
	WORD $0x00e686b3  // add	a3, a3, a4
	WORD $0xcc517057  // vsetivli	zero, 2, e8, mf8, ta, ma
	WORD $0x02068407  // vle8.v	v8, (a3)
	WORD $0x40f806bb  // subw	a3, a6, a5
	WORD $0x0306e693  // ori	a3, a3, 48
	WORD $0x00d60223  // sb	a3, 4(a2)
	WORD $0x02058427  // vse8.v	v8, (a1)
	WORD $0x00560593  // addi	a1, a2, 5
	JMP LBB0_113  // j	.LBB0_113
LBB0_72:
	WORD $0x00a00693  // li	a3, 10
	BLTU X16, X13, LBB0_74  // bltu	a6, a3, .LBB0_74
	WORD $0x00181813  // slli	a6, a6, 1
	MOV $·p590e8398564ef85b_Digits(SB), X13  // lui	a3, %hi(Digits)
	// addi	a3, a3, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x010686b3  // add	a3, a3, a6
	WORD $0xcc517057  // vsetivli	zero, 2, e8, mf8, ta, ma
	WORD $0x02068407  // vle8.v	v8, (a3)
	WORD $0x02058427  // vse8.v	v8, (a1)
	WORD $0x00460593  // addi	a1, a2, 4
	JMP LBB0_113  // j	.LBB0_113
LBB0_74:
	WORD $0x03086693  // ori	a3, a6, 48
	WORD $0x00360593  // addi	a1, a2, 3
	WORD $0x00d60123  // sb	a3, 2(a2)
	JMP LBB0_113  // j	.LBB0_113
LBB0_75:
	WORD $0x00000693  // li	a3, 0
	WORD $0x0db077d7  // vsetvli	a5, zero, e64, m8, ta, ma
	WORD $0x5208a457  // vid.v	v8
	WORD $0x02000793  // li	a5, 32
	WORD $0x2a87c857  // vor.vx	v16, v8, a5
	WORD $0x03000793  // li	a5, 48
	WORD $0x0c1074d7  // vsetvli	s1, zero, e8, m2, ta, ma
	WORD $0x5e07cc57  // vmv.v.x	v24, a5
	WORD $0x03f60793  // addi	a5, a2, 63
	WORD $0xfc07f793  // andi	a5, a5, -64
LBB0_76:
	WORD $0x00d40733  // add	a4, s0, a3
	WORD $0x0db074d7  // vsetvli	s1, zero, e64, m8, ta, ma
	WORD $0x5208a457  // vid.v	v8
	WORD $0x8286c457  // vsaddu.vx	v8, v8, a3
	WORD $0x6a864057  // vmsltu.vx	v0, v8, a2
	WORD $0x8306c457  // vsaddu.vx	v8, v16, a3
	WORD $0x6a864d57  // vmsltu.vx	v26, v8, a2
	WORD $0xcc647057  // vsetivli	zero, 8, e8, mf4, ta, ma
	WORD $0x3ba23057  // vslideup.vi	v0, v26, 4
	WORD $0x04068693  // addi	a3, a3, 64
	WORD $0x0c1074d7  // vsetvli	s1, zero, e8, m2, ta, ma
	WORD $0x00070c27  // vse8.v	v24, (a4), v0.t
	BNE X15, X13, LBB0_76  // bne	a5, a3, .LBB0_76
	JMP LBB0_113  // j	.LBB0_113
LBB0_77:
	WORD $0x009895b7  // lui	a1, 2441
	WORD $0x6805859b  // addiw	a1, a1, 1664
	WORD $0x00b2b5b3  // sltu	a1, t0, a1
	WORD $0x00800713  // li	a4, 8
	WORD $0x40b70733  // sub	a4, a4, a1
LBB0_78:
	WORD $0x00670733  // add	a4, a4, t1
LBB0_79:
	WORD $0x02029593  // slli	a1, t0, 32
	WORD $0xd1b71637  // lui	a2, 858993
	WORD $0xffffe7b7  // lui	a5, 1048574
	WORD $0x75960613  // addi	a2, a2, 1881
	WORD $0x02061613  // slli	a2, a2, 32
	WORD $0x02c5b5b3  // mulhu	a1, a1, a2
	WORD $0x51eb8637  // lui	a2, 335544
	WORD $0x8f078793  // addi	a5, a5, -1808
	WORD $0x51f60613  // addi	a2, a2, 1311
	WORD $0x02061613  // slli	a2, a2, 32
	WORD $0x02d5d593  // srli	a1, a1, 45
	WORD $0x02f587b3  // mul	a5, a1, a5
	WORD $0x005786b3  // add	a3, a5, t0
	WORD $0x02069793  // slli	a5, a3, 32
	WORD $0x02c7b633  // mulhu	a2, a5, a2
	WORD $0x06400793  // li	a5, 100
	WORD $0x02565613  // srli	a2, a2, 37
	WORD $0x02f607b3  // mul	a5, a2, a5
	WORD $0x00161613  // slli	a2, a2, 1
	WORD $0x40f686bb  // subw	a3, a3, a5
	WORD $0x01160633  // add	a2, a2, a7
	WORD $0x0016969b  // slliw	a3, a3, 1
	WORD $0x011686b3  // add	a3, a3, a7
	WORD $0xcc517057  // vsetivli	zero, 2, e8, mf8, ta, ma
	WORD $0x02068407  // vle8.v	v8, (a3)
	WORD $0x02060487  // vle8.v	v9, (a2)
	WORD $0x00070813  // mv	a6, a4
	WORD $0xffc70713  // addi	a4, a4, -4
	WORD $0xcc527057  // vsetivli	zero, 4, e8, mf8, ta, ma
	WORD $0x3a8134d7  // vslideup.vi	v9, v8, 2
	WORD $0x020704a7  // vse8.v	v9, (a4)
	WORD $0x00058293  // mv	t0, a1
LBB0_80:
	WORD $0x06400593  // li	a1, 100
	BLTU X5, X11, LBB0_83  // bltu	t0, a1, .LBB0_83
LBB0_81:
	WORD $0xffe70713  // addi	a4, a4, -2
	WORD $0x51eb85b7  // lui	a1, 335544
	WORD $0x06400393  // li	t2, 100
	WORD $0x51f58593  // addi	a1, a1, 1311
	WORD $0x02059593  // slli	a1, a1, 32
	WORD $0x27000613  // li	a2, 624
	WORD $0xcc517057  // vsetivli	zero, 2, e8, mf8, ta, ma
LBB0_82:
	WORD $0x00028793  // mv	a5, t0
	WORD $0x02029693  // slli	a3, t0, 32
	WORD $0x02b6b6b3  // mulhu	a3, a3, a1
	WORD $0x0256d293  // srli	t0, a3, 37
	WORD $0x027286b3  // mul	a3, t0, t2
	WORD $0x40d786bb  // subw	a3, a5, a3
	WORD $0x0016969b  // slliw	a3, a3, 1
	WORD $0x011686b3  // add	a3, a3, a7
	WORD $0x02068407  // vle8.v	v8, (a3)
	WORD $0x0047d69b  // srliw	a3, a5, 4
	WORD $0x02070427  // vse8.v	v8, (a4)
	WORD $0xffe70713  // addi	a4, a4, -2
	BLTU X12, X13, LBB0_82  // bltu	a2, a3, .LBB0_82
LBB0_83:
	WORD $0x00a00593  // li	a1, 10
	BLTU X5, X11, LBB0_85  // bltu	t0, a1, .LBB0_85
	WORD $0x0012959b  // slliw	a1, t0, 1
	WORD $0x011585b3  // add	a1, a1, a7
	WORD $0xcc517057  // vsetivli	zero, 2, e8, mf8, ta, ma
	WORD $0x02058407  // vle8.v	v8, (a1)
	WORD $0x02030427  // vse8.v	v8, (t1)
	JMP LBB0_86  // j	.LBB0_86
LBB0_85:
	WORD $0x0302e593  // ori	a1, t0, 48
	WORD $0x00b30023  // sb	a1, 0(t1)
LBB0_86:
	WORD $0x40a8053b  // subw	a0, a6, a0
	JMP LBB0_114  // j	.LBB0_114
LBB0_87:
	WORD $0x007e0733  // add	a4, t3, t2
	WORD $0xfff74713  // not	a4, a4
	WORD $0x02071713  // slli	a4, a4, 32
	WORD $0x02075713  // srli	a4, a4, 32
	WORD $0x00a282b3  // add	t0, t0, a0
	WORD $0x00570733  // add	a4, a4, t0
	WORD $0x00370713  // addi	a4, a4, 3
LBB0_88:
	WORD $0x00168313  // addi	t1, a3, 1
	WORD $0x00b68023  // sb	a1, 0(a3)
	WORD $0x00030693  // mv	a3, t1
	BNE X6, X14, LBB0_88  // bne	t1, a4, .LBB0_88
LBB0_89:
	WORD $0x004fd693  // srli	a3, t6, 4
	WORD $0x27100713  // li	a4, 625
	WORD $0x01c305b3  // add	a1, t1, t3
	BLTU X13, X14, LBB0_92  // bltu	a3, a4, .LBB0_92
	WORD $0x68db96b7  // lui	a3, 429497
	WORD $0xffffe7b7  // lui	a5, 1048574
	WORD $0xbad6869b  // addiw	a3, a3, -1107
	WORD $0x02df8733  // mul	a4, t6, a3
	WORD $0x02c75413  // srli	s0, a4, 44
	WORD $0x8f078693  // addi	a3, a5, -1808
	WORD $0x02d406b3  // mul	a3, s0, a3
	WORD $0x01f6863b  // addw	a2, a3, t6
	WORD $0xffc58593  // addi	a1, a1, -4
	BEQZ X12, LBB0_93  // beqz	a2, .LBB0_93
	WORD $0x00000893  // li	a7, 0
	WORD $0x51eb86b7  // lui	a3, 335544
	WORD $0x02061793  // slli	a5, a2, 32
	WORD $0x51f68693  // addi	a3, a3, 1311
	WORD $0x02069693  // slli	a3, a3, 32
	WORD $0x02d7b6b3  // mulhu	a3, a5, a3
	WORD $0x06400793  // li	a5, 100
	WORD $0x0256d693  // srli	a3, a3, 37
	WORD $0x02f687b3  // mul	a5, a3, a5
	WORD $0x40f6063b  // subw	a2, a2, a5
	MOV $·p590e8398564ef85b_Digits(SB), X15  // lui	a5, %hi(Digits)
	// addi	a5, a5, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x00169693  // slli	a3, a3, 1
	WORD $0x00f686b3  // add	a3, a3, a5
	WORD $0x0016161b  // slliw	a2, a2, 1
	WORD $0x00f60633  // add	a2, a2, a5
	WORD $0xcc517057  // vsetivli	zero, 2, e8, mf8, ta, ma
	WORD $0x02060407  // vle8.v	v8, (a2)
	WORD $0x02068487  // vle8.v	v9, (a3)
	WORD $0xcc527057  // vsetivli	zero, 4, e8, mf8, ta, ma
	WORD $0x3a8134d7  // vslideup.vi	v9, v8, 2
	WORD $0x020584a7  // vse8.v	v9, (a1)
	JMP LBB0_94  // j	.LBB0_94
LBB0_92:
	WORD $0x00000893  // li	a7, 0
	WORD $0x000f8413  // mv	s0, t6
	JMP LBB0_94  // j	.LBB0_94
LBB0_93:
	WORD $0xffc00893  // li	a7, -4
LBB0_94:
	WORD $0x06400293  // li	t0, 100
	BLTU X8, X5, LBB0_97  // bltu	s0, t0, .LBB0_97
	WORD $0xffe58613  // addi	a2, a1, -2
	WORD $0x51eb85b7  // lui	a1, 335544
	MOV $·p590e8398564ef85b_Digits(SB), X29  // lui	t4, %hi(Digits)
	// addi	t4, t4, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x51f58593  // addi	a1, a1, 1311
	WORD $0x02059593  // slli	a1, a1, 32
	WORD $0x27000793  // li	a5, 624
	WORD $0xcc517057  // vsetivli	zero, 2, e8, mf8, ta, ma
LBB0_96:
	WORD $0x02041693  // slli	a3, s0, 32
	WORD $0x02b6b6b3  // mulhu	a3, a3, a1
	WORD $0x0256d693  // srli	a3, a3, 37
	WORD $0x025684b3  // mul	s1, a3, t0
	WORD $0x4094073b  // subw	a4, s0, s1
	WORD $0x0017171b  // slliw	a4, a4, 1
	WORD $0x01d70733  // add	a4, a4, t4
	WORD $0x02070407  // vle8.v	v8, (a4)
	WORD $0x0044571b  // srliw	a4, s0, 4
	WORD $0x02060427  // vse8.v	v8, (a2)
	WORD $0xffe60613  // addi	a2, a2, -2
	WORD $0x00068413  // mv	s0, a3
	BLTU X15, X14, LBB0_96  // bltu	a5, a4, .LBB0_96
	JMP LBB0_98  // j	.LBB0_98
LBB0_97:
	WORD $0x00040693  // mv	a3, s0
LBB0_98:
	WORD $0x00a00593  // li	a1, 10
	BLTU X13, X11, LBB0_100  // bltu	a3, a1, .LBB0_100
	WORD $0x0016959b  // slliw	a1, a3, 1
	MOV $·p590e8398564ef85b_Digits(SB), X12  // lui	a2, %hi(Digits)
	// addi	a2, a2, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x00c585b3  // add	a1, a1, a2
	WORD $0xcc517057  // vsetivli	zero, 2, e8, mf8, ta, ma
	WORD $0x02058407  // vle8.v	v8, (a1)
	WORD $0x02030427  // vse8.v	v8, (t1)
	JMP LBB0_101  // j	.LBB0_101
LBB0_100:
	WORD $0x0306e593  // ori	a1, a3, 48
	WORD $0x00b30023  // sb	a1, 0(t1)
LBB0_101:
	WORD $0x00188593  // addi	a1, a7, 1
	WORD $0x01c888b3  // add	a7, a7, t3
	WORD $0x40758633  // sub	a2, a1, t2
	WORD $0x006888b3  // add	a7, a7, t1
	WORD $0x00be0e33  // add	t3, t3, a1
	WORD $0xfc188693  // addi	a3, a7, -63
	WORD $0x03000593  // li	a1, 48
LBB0_102:
	WORD $0x03e6c703  // lbu	a4, 62(a3)
	WORD $0xfff6061b  // addiw	a2, a2, -1
	WORD $0xfff68693  // addi	a3, a3, -1
	WORD $0xfffe0e1b  // addiw	t3, t3, -1
	BEQ X14, X11, LBB0_102  // beq	a4, a1, .LBB0_102
	WORD $0x04068713  // addi	a4, a3, 64
	BLEZ X16, LBB0_112  // blez	a6, .LBB0_112
	BGE X16, X28, LBB0_109  // bge	a6, t3, .LBB0_109
	BLEZ X12, LBB0_108  // blez	a2, .LBB0_108
	WORD $0x00000593  // li	a1, 0
	WORD $0x03f60713  // addi	a4, a2, 63
	MOV $·p590e8398564ef85b_LCPI0_0(SB), X15  // lui	a5, %hi(.LCPI0_0)
	// addi	a5, a5, %lo(.LCPI0_0) (skipped, covered by MOV address load)
	WORD $0x02878887  // vl1r.v	v17, (a5)
	MOV $·p590e8398564ef85b_LCPI0_1(SB), X15  // lui	a5, %hi(.LCPI0_1)
	// addi	a5, a5, %lo(.LCPI0_1) (skipped, covered by MOV address load)
	WORD $0x0067571b  // srliw	a4, a4, 6
	WORD $0x02878807  // vl1r.v	v16, (a5)
	WORD $0x00671713  // slli	a4, a4, 6
	WORD $0x0db077d7  // vsetvli	a5, zero, e64, m8, ta, ma
	WORD $0x4b11ac57  // vsext.vf8	v24, v17
	WORD $0x0c1077d7  // vsetvli	a5, zero, e8, m2, ta, ma
	WORD $0x5e003957  // vmv.v.i	v18, 0
	WORD $0x00068793  // mv	a5, a3
LBB0_107:
	WORD $0x0db074d7  // vsetvli	s1, zero, e64, m8, ta, ma
	WORD $0x5208a457  // vid.v	v8
	WORD $0x8285c457  // vsaddu.vx	v8, v8, a1
	WORD $0x6a864057  // vmsltu.vx	v0, v8, a2
	WORD $0x8385c457  // vsaddu.vx	v8, v24, a1
	WORD $0x6a8648d7  // vmsltu.vx	v17, v8, a2
	WORD $0xcc647057  // vsetivli	zero, 8, e8, mf4, ta, ma
	WORD $0x3b123057  // vslideup.vi	v0, v17, 4
	WORD $0x0c1074d7  // vsetvli	s1, zero, e8, m2, ta, ma
	WORD $0x5d20b457  // vmerge.vim	v8, v18, 1, v0
	WORD $0x0c0074d7  // vsetvli	s1, zero, e8, m1, ta, ma
	WORD $0x328805d7  // vrgather.vv	v11, v8, v16
	WORD $0x32980557  // vrgather.vv	v10, v9, v16
	WORD $0x0c1074d7  // vsetvli	s1, zero, e8, m2, ta, ma
	WORD $0x66a03057  // vmsne.vi	v0, v10, 0
	WORD $0x00078407  // vle8.v	v8, (a5), v0.t
	WORD $0x00178493  // addi	s1, a5, 1
	WORD $0x04058593  // addi	a1, a1, 64
	WORD $0x00048427  // vse8.v	v8, (s1), v0.t
	WORD $0xfc078793  // addi	a5, a5, -64
	BNE X14, X11, LBB0_107  // bne	a4, a1, .LBB0_107
LBB0_108:
	WORD $0x00680833  // add	a6, a6, t1
	WORD $0x02e00593  // li	a1, 46
	WORD $0x00b80023  // sb	a1, 0(a6)
	WORD $0x04168593  // addi	a1, a3, 65
	JMP LBB0_113  // j	.LBB0_113
LBB0_109:
	WORD $0x40c0063b  // negw	a2, a2
	BLEZ X12, LBB0_112  // blez	a2, .LBB0_112
	WORD $0x00000693  // li	a3, 0
	WORD $0x03000793  // li	a5, 48
LBB0_111:
	WORD $0x00170593  // addi	a1, a4, 1
	WORD $0x0016869b  // addiw	a3, a3, 1
	WORD $0x00f70023  // sb	a5, 0(a4)
	WORD $0x00058713  // mv	a4, a1
	BLT X13, X12, LBB0_111  // blt	a3, a2, .LBB0_111
	JMP LBB0_113  // j	.LBB0_113
LBB0_112:
	WORD $0x00070593  // mv	a1, a4
LBB0_113:
	WORD $0x40a5853b  // subw	a0, a1, a0
LBB0_114:
	WORD $0x00813403  // ld	s0, 8(sp)
	WORD $0x00013483  // ld	s1, 0(sp)
	WORD $0x01010113  // addi	sp, sp, 16
	RET  // ret
LBB0_115:
	WORD $0x0042d59b  // srliw	a1, t0, 4
	WORD $0x2715b613  // sltiu	a2, a1, 625
	WORD $0x00564713  // xori	a4, a2, 5
	WORD $0x27100613  // li	a2, 625
	WORD $0x00670733  // add	a4, a4, t1
	BGEU X11, X12, LBB0_79  // bgeu	a1, a2, .LBB0_79
	WORD $0x00070813  // mv	a6, a4
	JMP LBB0_81  // j	.LBB0_81
LBB0_117:
	WORD $0x00000513  // li	a0, 0
	RET  // ret
LBB0_118:
	WORD $0xf6b00813  // li	a6, -149
	WORD $0x00070613  // mv	a2, a4
	JMP LBB0_6  // j	.LBB0_6
Lfunc_end0:


TEXT ·__f32toa(SB), NOSPLIT, $0-24
	NO_LOCAL_POINTERS

_entry___f32toa:
	MOV 16(g), X17      // g.stack.hi
	ADD $-80, SP, X16
	BLTU X16, X17, _stack_grow___f32toa

___f32toa:
	MOV out+0(FP), X10
	MOVD val+8(FP), F10
	CALL ·__f32toa_riscv64_entry__(SB)
	MOV X10, ret+16(FP)
	RET

_stack_grow___f32toa:
	MOV X1, X5
	CALL runtime·morestack_noctxt(SB)
	JMP _entry___f32toa

// Data section
GLOBL ·p590e8398564ef85b_LCPI0_0(SB), RODATA, $32
DATA ·p590e8398564ef85b_LCPI0_0+0(SB)/8, $0x2726252423222120
DATA ·p590e8398564ef85b_LCPI0_0+8(SB)/8, $0x2f2e2d2c2b2a2928
DATA ·p590e8398564ef85b_LCPI0_0+16(SB)/8, $0x3736353433323130
DATA ·p590e8398564ef85b_LCPI0_0+24(SB)/8, $0x3f3e3d3c3b3a3938
GLOBL ·p590e8398564ef85b_LCPI0_1(SB), RODATA, $32
DATA ·p590e8398564ef85b_LCPI0_1+0(SB)/8, $0x18191a1b1c1d1e1f
DATA ·p590e8398564ef85b_LCPI0_1+8(SB)/8, $0x1011121314151617
DATA ·p590e8398564ef85b_LCPI0_1+16(SB)/8, $0x08090a0b0c0d0e0f
DATA ·p590e8398564ef85b_LCPI0_1+24(SB)/8, $0x0001020304050607
GLOBL ·p590e8398564ef85b_Digits(SB), RODATA, $200
DATA ·p590e8398564ef85b_Digits+0(SB)/8, $0x3330323031303030
DATA ·p590e8398564ef85b_Digits+8(SB)/8, $0x3730363035303430
DATA ·p590e8398564ef85b_Digits+16(SB)/8, $0x3131303139303830
DATA ·p590e8398564ef85b_Digits+24(SB)/8, $0x3531343133313231
DATA ·p590e8398564ef85b_Digits+32(SB)/8, $0x3931383137313631
DATA ·p590e8398564ef85b_Digits+40(SB)/8, $0x3332323231323032
DATA ·p590e8398564ef85b_Digits+48(SB)/8, $0x3732363235323432
DATA ·p590e8398564ef85b_Digits+56(SB)/8, $0x3133303339323832
DATA ·p590e8398564ef85b_Digits+64(SB)/8, $0x3533343333333233
DATA ·p590e8398564ef85b_Digits+72(SB)/8, $0x3933383337333633
DATA ·p590e8398564ef85b_Digits+80(SB)/8, $0x3334323431343034
DATA ·p590e8398564ef85b_Digits+88(SB)/8, $0x3734363435343434
DATA ·p590e8398564ef85b_Digits+96(SB)/8, $0x3135303539343834
DATA ·p590e8398564ef85b_Digits+104(SB)/8, $0x3535343533353235
DATA ·p590e8398564ef85b_Digits+112(SB)/8, $0x3935383537353635
DATA ·p590e8398564ef85b_Digits+120(SB)/8, $0x3336323631363036
DATA ·p590e8398564ef85b_Digits+128(SB)/8, $0x3736363635363436
DATA ·p590e8398564ef85b_Digits+136(SB)/8, $0x3137303739363836
DATA ·p590e8398564ef85b_Digits+144(SB)/8, $0x3537343733373237
DATA ·p590e8398564ef85b_Digits+152(SB)/8, $0x3937383737373637
DATA ·p590e8398564ef85b_Digits+160(SB)/8, $0x3338323831383038
DATA ·p590e8398564ef85b_Digits+168(SB)/8, $0x3738363835383438
DATA ·p590e8398564ef85b_Digits+176(SB)/8, $0x3139303939383838
DATA ·p590e8398564ef85b_Digits+184(SB)/8, $0x3539343933393239
DATA ·p590e8398564ef85b_Digits+192(SB)/8, $0x3939383937393639
GLOBL ·p590e8398564ef85b_pow10_ceil_sig_f32_g(SB), RODATA, $616
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+0(SB)/8, $0x81ceb32c4b43fcf5
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+8(SB)/8, $0xa2425ff75e14fc32
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+16(SB)/8, $0xcad2f7f5359a3b3f
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+24(SB)/8, $0xfd87b5f28300ca0e
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+32(SB)/8, $0x9e74d1b791e07e49
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+40(SB)/8, $0xc612062576589ddb
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+48(SB)/8, $0xf79687aed3eec552
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+56(SB)/8, $0x9abe14cd44753b53
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+64(SB)/8, $0xc16d9a0095928a28
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+72(SB)/8, $0xf1c90080baf72cb2
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+80(SB)/8, $0x971da05074da7bef
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+88(SB)/8, $0xbce5086492111aeb
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+96(SB)/8, $0xec1e4a7db69561a6
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+104(SB)/8, $0x9392ee8e921d5d08
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+112(SB)/8, $0xb877aa3236a4b44a
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+120(SB)/8, $0xe69594bec44de15c
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+128(SB)/8, $0x901d7cf73ab0acda
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+136(SB)/8, $0xb424dc35095cd810
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+144(SB)/8, $0xe12e13424bb40e14
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+152(SB)/8, $0x8cbccc096f5088cc
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+160(SB)/8, $0xafebff0bcb24aaff
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+168(SB)/8, $0xdbe6fecebdedd5bf
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+176(SB)/8, $0x89705f4136b4a598
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+184(SB)/8, $0xabcc77118461cefd
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+192(SB)/8, $0xd6bf94d5e57a42bd
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+200(SB)/8, $0x8637bd05af6c69b6
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+208(SB)/8, $0xa7c5ac471b478424
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+216(SB)/8, $0xd1b71758e219652c
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+224(SB)/8, $0x83126e978d4fdf3c
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+232(SB)/8, $0xa3d70a3d70a3d70b
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+240(SB)/8, $0xcccccccccccccccd
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+248(SB)/8, $0x8000000000000000
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+256(SB)/8, $0xa000000000000000
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+264(SB)/8, $0xc800000000000000
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+272(SB)/8, $0xfa00000000000000
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+280(SB)/8, $0x9c40000000000000
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+288(SB)/8, $0xc350000000000000
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+296(SB)/8, $0xf424000000000000
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+304(SB)/8, $0x9896800000000000
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+312(SB)/8, $0xbebc200000000000
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+320(SB)/8, $0xee6b280000000000
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+328(SB)/8, $0x9502f90000000000
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+336(SB)/8, $0xba43b74000000000
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+344(SB)/8, $0xe8d4a51000000000
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+352(SB)/8, $0x9184e72a00000000
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+360(SB)/8, $0xb5e620f480000000
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+368(SB)/8, $0xe35fa931a0000000
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+376(SB)/8, $0x8e1bc9bf04000000
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+384(SB)/8, $0xb1a2bc2ec5000000
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+392(SB)/8, $0xde0b6b3a76400000
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+400(SB)/8, $0x8ac7230489e80000
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+408(SB)/8, $0xad78ebc5ac620000
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+416(SB)/8, $0xd8d726b7177a8000
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+424(SB)/8, $0x878678326eac9000
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+432(SB)/8, $0xa968163f0a57b400
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+440(SB)/8, $0xd3c21bcecceda100
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+448(SB)/8, $0x84595161401484a0
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+456(SB)/8, $0xa56fa5b99019a5c8
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+464(SB)/8, $0xcecb8f27f4200f3a
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+472(SB)/8, $0x813f3978f8940985
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+480(SB)/8, $0xa18f07d736b90be6
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+488(SB)/8, $0xc9f2c9cd04674edf
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+496(SB)/8, $0xfc6f7c4045812297
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+504(SB)/8, $0x9dc5ada82b70b59e
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+512(SB)/8, $0xc5371912364ce306
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+520(SB)/8, $0xf684df56c3e01bc7
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+528(SB)/8, $0x9a130b963a6c115d
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+536(SB)/8, $0xc097ce7bc90715b4
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+544(SB)/8, $0xf0bdc21abb48db21
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+552(SB)/8, $0x96769950b50d88f5
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+560(SB)/8, $0xbc143fa4e250eb32
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+568(SB)/8, $0xeb194f8e1ae525fe
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+576(SB)/8, $0x92efd1b8d0cf37bf
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+584(SB)/8, $0xb7abc627050305ae
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+592(SB)/8, $0xe596b7b0c643c71a
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+600(SB)/8, $0x8f7e32ce7bea5c70
DATA ·p590e8398564ef85b_pow10_ceil_sig_f32_g+608(SB)/8, $0xb35dbf821ae4f38c
