// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package rvv

//go:nosplit
//go:noescape
//goland:noinspection ALL
func __get_by_path_entry__() uintptr

var (
    _subr__get_by_path uintptr = __get_by_path_entry__() + 0
)

const (
    _stack__get_by_path = 400
)

var (
    _ = _subr__get_by_path
)

const (
    _ = _stack__get_by_path
)
