// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

#include "go_asm.h"
#include "funcdata.h"
#include "textflag.h"

TEXT ·__i64toa_entry__(SB), NOSPLIT, $0-8
	MOV $·__i64toa_riscv64_entry__(SB), A0
	MOV A0, ret+0(FP)
	RET

TEXT ·__i64toa_riscv64_entry__(SB), NOSPLIT, $0
	NO_LOCAL_POINTERS
i64toa:
	WORD $0x00150613  // addi	a2, a0, 1
	BLTZ X11, LBB0_11  // bltz	a1, .LBB0_11
	WORD $0x0045d693  // srli	a3, a1, 4
	WORD $0x27000713  // li	a4, 624
	BLTU X14, X13, LBB0_14  // bltu	a4, a3, .LBB0_14
	WORD $0x03059613  // slli	a2, a1, 48
	WORD $0x000016b7  // lui	a3, 1
	WORD $0x06400713  // li	a4, 100
	WORD $0x03265613  // srli	a2, a2, 50
	WORD $0x47b6869b  // addiw	a3, a3, 1147
	WORD $0x02d60633  // mul	a2, a2, a3
	WORD $0x01165793  // srli	a5, a2, 17
	WORD $0x01065613  // srli	a2, a2, 16
	WORD $0x7fe67693  // andi	a3, a2, 2046
	WORD $0x02e78633  // mul	a2, a5, a4
	WORD $0x40c58633  // sub	a2, a1, a2
	WORD $0x3e800793  // li	a5, 1000
	WORD $0x00161613  // slli	a2, a2, 1
	BLTU X11, X15, LBB0_4  // bltu	a1, a5, .LBB0_4
	MOV $·pf9f0f641d845caf_Digits(SB), X11  // lui	a1, %hi(Digits)
	// addi	a1, a1, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x00d585b3  // add	a1, a1, a3
	WORD $0x0005c583  // lbu	a1, 0(a1)
	WORD $0x00b50023  // sb	a1, 0(a0)
	WORD $0x00100593  // li	a1, 1
	JMP LBB0_6  // j	.LBB0_6
LBB0_4:
	BLTU X11, X14, LBB0_10  // bltu	a1, a4, .LBB0_10
	WORD $0x00000593  // li	a1, 0
LBB0_6:
	WORD $0x0016e693  // ori	a3, a3, 1
	MOV $·pf9f0f641d845caf_Digits(SB), X14  // lui	a4, %hi(Digits)
	// addi	a4, a4, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x00e686b3  // add	a3, a3, a4
	WORD $0x0006c703  // lbu	a4, 0(a3)
	WORD $0x00158693  // addi	a3, a1, 1
	WORD $0x00a585b3  // add	a1, a1, a0
	WORD $0x00e58023  // sb	a4, 0(a1)
LBB0_7:
	WORD $0x03061593  // slli	a1, a2, 48
	WORD $0x0305d593  // srli	a1, a1, 48
	MOV $·pf9f0f641d845caf_Digits(SB), X14  // lui	a4, %hi(Digits)
	// addi	a4, a4, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x00e585b3  // add	a1, a1, a4
	WORD $0x0005c583  // lbu	a1, 0(a1)
	WORD $0x00168713  // addi	a4, a3, 1
	WORD $0x00a686b3  // add	a3, a3, a0
	WORD $0x00b68023  // sb	a1, 0(a3)
LBB0_8:
	WORD $0x00166593  // ori	a1, a2, 1
	WORD $0x03059593  // slli	a1, a1, 48
	WORD $0x0305d593  // srli	a1, a1, 48
	MOV $·pf9f0f641d845caf_Digits(SB), X12  // lui	a2, %hi(Digits)
	// addi	a2, a2, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x00c585b3  // add	a1, a1, a2
	WORD $0x0005c603  // lbu	a2, 0(a1)
	WORD $0x00170593  // addi	a1, a4, 1
	WORD $0x00e50533  // add	a0, a0, a4
	WORD $0x00c50023  // sb	a2, 0(a0)
LBB0_9:
	WORD $0x00058513  // mv	a0, a1
	RET  // ret
LBB0_10:
	WORD $0x00000693  // li	a3, 0
	WORD $0x00a00793  // li	a5, 10
	WORD $0x00000713  // li	a4, 0
	BGEU X11, X15, LBB0_7  // bgeu	a1, a5, .LBB0_7
	JMP LBB0_8  // j	.LBB0_8
LBB0_11:
	WORD $0x02d00693  // li	a3, 45
	WORD $0x40b005b3  // neg	a1, a1
	WORD $0x0045d713  // srli	a4, a1, 4
	WORD $0x27000793  // li	a5, 624
	WORD $0x00d50023  // sb	a3, 0(a0)
	BLTU X15, X14, LBB0_30  // bltu	a5, a4, .LBB0_30
	WORD $0x03059513  // slli	a0, a1, 48
	WORD $0x000016b7  // lui	a3, 1
	WORD $0x06400713  // li	a4, 100
	WORD $0x03255513  // srli	a0, a0, 50
	WORD $0x47b6869b  // addiw	a3, a3, 1147
	WORD $0x02d50533  // mul	a0, a0, a3
	WORD $0x01155793  // srli	a5, a0, 17
	WORD $0x01055513  // srli	a0, a0, 16
	WORD $0x7fe57693  // andi	a3, a0, 2046
	WORD $0x02e78533  // mul	a0, a5, a4
	WORD $0x40a58533  // sub	a0, a1, a0
	WORD $0x3e800793  // li	a5, 1000
	WORD $0x00151513  // slli	a0, a0, 1
	BLTU X11, X15, LBB0_17  // bltu	a1, a5, .LBB0_17
	MOV $·pf9f0f641d845caf_Digits(SB), X11  // lui	a1, %hi(Digits)
	// addi	a1, a1, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x00d585b3  // add	a1, a1, a3
	WORD $0x0005c583  // lbu	a1, 0(a1)
	WORD $0x00b60023  // sb	a1, 0(a2)
	WORD $0x00100593  // li	a1, 1
	JMP LBB0_19  // j	.LBB0_19
LBB0_14:
	WORD $0x05f5e6b7  // lui	a3, 24414
	WORD $0x0ff6871b  // addiw	a4, a3, 255
	BLTU X14, X11, LBB0_33  // bltu	a4, a1, .LBB0_33
	WORD $0x02059613  // slli	a2, a1, 32
	WORD $0xd1b716b7  // lui	a3, 858993
	WORD $0x431be737  // lui	a4, 274878
	WORD $0x051ec7b7  // lui	a5, 20972
	WORD $0x75968693  // addi	a3, a3, 1881
	WORD $0xe8370713  // addi	a4, a4, -381
	WORD $0x02069693  // slli	a3, a3, 32
	WORD $0x02071713  // slli	a4, a4, 32
	WORD $0x02d636b3  // mulhu	a3, a2, a3
	WORD $0x02e63733  // mulhu	a4, a2, a4
	WORD $0x02f6d613  // srli	a2, a3, 47
	WORD $0x03261613  // slli	a2, a2, 50
	WORD $0x02f63633  // mulhu	a2, a2, a5
	WORD $0x06400793  // li	a5, 100
	WORD $0x01165613  // srli	a2, a2, 17
	WORD $0x02f607b3  // mul	a5, a2, a5
	WORD $0x00989637  // lui	a2, 2441
	WORD $0x02d6d813  // srli	a6, a3, 45
	WORD $0x03175713  // srli	a4, a4, 49
	WORD $0xffe77713  // andi	a4, a4, -2
	WORD $0x40f806b3  // sub	a3, a6, a5
	WORD $0x6806061b  // addiw	a2, a2, 1664
	WORD $0x00169693  // slli	a3, a3, 1
	BLTU X11, X12, LBB0_23  // bltu	a1, a2, .LBB0_23
	MOV $·pf9f0f641d845caf_Digits(SB), X12  // lui	a2, %hi(Digits)
	// addi	a2, a2, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x00e60633  // add	a2, a2, a4
	WORD $0x00064603  // lbu	a2, 0(a2)
	WORD $0x00c50023  // sb	a2, 0(a0)
	WORD $0x00100793  // li	a5, 1
	JMP LBB0_25  // j	.LBB0_25
LBB0_17:
	BLTU X11, X14, LBB0_28  // bltu	a1, a4, .LBB0_28
	WORD $0x00000593  // li	a1, 0
LBB0_19:
	WORD $0x0016e693  // ori	a3, a3, 1
	MOV $·pf9f0f641d845caf_Digits(SB), X14  // lui	a4, %hi(Digits)
	// addi	a4, a4, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x00e686b3  // add	a3, a3, a4
	WORD $0x0006c703  // lbu	a4, 0(a3)
	WORD $0x00158693  // addi	a3, a1, 1
	WORD $0x00c585b3  // add	a1, a1, a2
	WORD $0x00e58023  // sb	a4, 0(a1)
LBB0_20:
	WORD $0x03051593  // slli	a1, a0, 48
	WORD $0x0305d593  // srli	a1, a1, 48
	MOV $·pf9f0f641d845caf_Digits(SB), X14  // lui	a4, %hi(Digits)
	// addi	a4, a4, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x00e585b3  // add	a1, a1, a4
	WORD $0x0005c583  // lbu	a1, 0(a1)
	WORD $0x00168713  // addi	a4, a3, 1
	WORD $0x00c686b3  // add	a3, a3, a2
	WORD $0x00b68023  // sb	a1, 0(a3)
LBB0_21:
	WORD $0x00156513  // ori	a0, a0, 1
	WORD $0x03051513  // slli	a0, a0, 48
	WORD $0x03055513  // srli	a0, a0, 48
	MOV $·pf9f0f641d845caf_Digits(SB), X11  // lui	a1, %hi(Digits)
	// addi	a1, a1, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x00b50533  // add	a0, a0, a1
	WORD $0x00054503  // lbu	a0, 0(a0)
	WORD $0x00170593  // addi	a1, a4, 1
	WORD $0x00e60633  // add	a2, a2, a4
	WORD $0x00a60023  // sb	a0, 0(a2)
LBB0_22:
	WORD $0x00158593  // addi	a1, a1, 1
	JMP LBB0_9  // j	.LBB0_9
LBB0_23:
	WORD $0x000f4637  // lui	a2, 244
	WORD $0x2406061b  // addiw	a2, a2, 576
	BLTU X11, X12, LBB0_29  // bltu	a1, a2, .LBB0_29
	WORD $0x00000793  // li	a5, 0
LBB0_25:
	WORD $0x00176613  // ori	a2, a4, 1
	MOV $·pf9f0f641d845caf_Digits(SB), X14  // lui	a4, %hi(Digits)
	// addi	a4, a4, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x00e60633  // add	a2, a2, a4
	WORD $0x00064603  // lbu	a2, 0(a2)
	WORD $0x00178713  // addi	a4, a5, 1
	WORD $0x00a787b3  // add	a5, a5, a0
	WORD $0x00c78023  // sb	a2, 0(a5)
LBB0_26:
	WORD $0x03069613  // slli	a2, a3, 48
	WORD $0x03065613  // srli	a2, a2, 48
	MOV $·pf9f0f641d845caf_Digits(SB), X15  // lui	a5, %hi(Digits)
	// addi	a5, a5, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x00f60633  // add	a2, a2, a5
	WORD $0x00064603  // lbu	a2, 0(a2)
	WORD $0x00170313  // addi	t1, a4, 1
	WORD $0x00a70733  // add	a4, a4, a0
	WORD $0x00c70023  // sb	a2, 0(a4)
LBB0_27:
	WORD $0x00002637  // lui	a2, 2
	WORD $0x000012b7  // lui	t0, 1
	WORD $0x06400893  // li	a7, 100
	WORD $0x0016e693  // ori	a3, a3, 1
	WORD $0x71060613  // addi	a2, a2, 1808
	WORD $0x02c80633  // mul	a2, a6, a2
	MOV $·pf9f0f641d845caf_Digits(SB), X14  // lui	a4, %hi(Digits)
	// addi	a4, a4, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x47b2879b  // addiw	a5, t0, 1147
	WORD $0x03069693  // slli	a3, a3, 48
	WORD $0x0306d693  // srli	a3, a3, 48
	WORD $0x40c585bb  // subw	a1, a1, a2
	WORD $0x00e686b3  // add	a3, a3, a4
	WORD $0x03059613  // slli	a2, a1, 48
	WORD $0x0006c683  // lbu	a3, 0(a3)
	WORD $0x03265613  // srli	a2, a2, 50
	WORD $0x02f60633  // mul	a2, a2, a5
	WORD $0x01165793  // srli	a5, a2, 17
	WORD $0x031787b3  // mul	a5, a5, a7
	WORD $0x00650533  // add	a0, a0, t1
	WORD $0x01065613  // srli	a2, a2, 16
	WORD $0x00d50023  // sb	a3, 0(a0)
	WORD $0x7fe67613  // andi	a2, a2, 2046
	WORD $0x40f585bb  // subw	a1, a1, a5
	WORD $0x00e60633  // add	a2, a2, a4
	WORD $0xcc517057  // vsetivli	zero, 2, e8, mf8, ta, ma
	WORD $0x02060407  // vle8.v	v8, (a2)
	WORD $0x03159593  // slli	a1, a1, 49
	WORD $0x0305d593  // srli	a1, a1, 48
	WORD $0x00e585b3  // add	a1, a1, a4
	WORD $0x02058487  // vle8.v	v9, (a1)
	WORD $0x00150513  // addi	a0, a0, 1
	WORD $0x00530593  // addi	a1, t1, 5
	WORD $0xcc527057  // vsetivli	zero, 4, e8, mf8, ta, ma
	WORD $0x3a913457  // vslideup.vi	v8, v9, 2
	WORD $0x02050427  // vse8.v	v8, (a0)
	JMP LBB0_9  // j	.LBB0_9
LBB0_28:
	WORD $0x00000693  // li	a3, 0
	WORD $0x00a00793  // li	a5, 10
	WORD $0x00000713  // li	a4, 0
	BGEU X11, X15, LBB0_20  // bgeu	a1, a5, .LBB0_20
	JMP LBB0_21  // j	.LBB0_21
LBB0_29:
	WORD $0x00000713  // li	a4, 0
	WORD $0x00018637  // lui	a2, 24
	WORD $0x6a06061b  // addiw	a2, a2, 1696
	WORD $0x00000313  // li	t1, 0
	BGEU X11, X12, LBB0_26  // bgeu	a1, a2, .LBB0_26
	JMP LBB0_27  // j	.LBB0_27
LBB0_30:
	WORD $0x05f5e6b7  // lui	a3, 24414
	WORD $0x0ff6869b  // addiw	a3, a3, 255
	BLTU X13, X11, LBB0_57  // bltu	a3, a1, .LBB0_57
	WORD $0x02059513  // slli	a0, a1, 32
	WORD $0xd1b716b7  // lui	a3, 858993
	WORD $0x431be737  // lui	a4, 274878
	WORD $0x051ec7b7  // lui	a5, 20972
	WORD $0x75968693  // addi	a3, a3, 1881
	WORD $0xe8370713  // addi	a4, a4, -381
	WORD $0x02069693  // slli	a3, a3, 32
	WORD $0x02071713  // slli	a4, a4, 32
	WORD $0x02d536b3  // mulhu	a3, a0, a3
	WORD $0x02e53733  // mulhu	a4, a0, a4
	WORD $0x02f6d513  // srli	a0, a3, 47
	WORD $0x03251513  // slli	a0, a0, 50
	WORD $0x02f53533  // mulhu	a0, a0, a5
	WORD $0x06400793  // li	a5, 100
	WORD $0x01155513  // srli	a0, a0, 17
	WORD $0x02f507b3  // mul	a5, a0, a5
	WORD $0x00989537  // lui	a0, 2441
	WORD $0x02d6d813  // srli	a6, a3, 45
	WORD $0x03175713  // srli	a4, a4, 49
	WORD $0xffe77713  // andi	a4, a4, -2
	WORD $0x40f806b3  // sub	a3, a6, a5
	WORD $0x6805051b  // addiw	a0, a0, 1664
	WORD $0x00169693  // slli	a3, a3, 1
	BLTU X11, X10, LBB0_51  // bltu	a1, a0, .LBB0_51
	MOV $·pf9f0f641d845caf_Digits(SB), X10  // lui	a0, %hi(Digits)
	// addi	a0, a0, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x00e50533  // add	a0, a0, a4
	WORD $0x00054503  // lbu	a0, 0(a0)
	WORD $0x00a60023  // sb	a0, 0(a2)
	WORD $0x00100793  // li	a5, 1
	JMP LBB0_53  // j	.LBB0_53
LBB0_33:
	MOV $·pf9f0f641d845caf_LCPI0_0(SB), X14  // lui	a4, %hi(.LCPI0_0)
	MOV (X14), X14  // ld	a4, %lo(.LCPI0_0)(a4)
	WORD $0x10068293  // addi	t0, a3, 256
	BLTU X14, X11, LBB0_75  // bltu	a4, a1, .LBB0_75
	WORD $0x00000613  // li	a2, 0
	MOV $·pf9f0f641d845caf_LCPI0_4(SB), X15  // lui	a5, %hi(.LCPI0_4)
	WORD $0xfff00813  // li	a6, -1
	WORD $0x000d26b7  // lui	a3, 210
	WORD $0x02085713  // srli	a4, a6, 32
	WORD $0xcd827057  // vsetivli	zero, 4, e64, m1, ta, ma
	WORD $0x5e074457  // vmv.v.x	v8, a4
	WORD $0x02d00713  // li	a4, 45
	MOV (X15), X15  // ld	a5, %lo(.LCPI0_4)(a5)
	WORD $0xb716869b  // addiw	a3, a3, -1167
	WORD $0x00c69693  // slli	a3, a3, 12
	WORD $0x75968693  // addi	a3, a3, 1881
	WORD $0x02f5b7b3  // mulhu	a5, a1, a5
	WORD $0x01a7d793  // srli	a5, a5, 26
	WORD $0x0d707057  // vsetvli	zero, zero, e32, mf2, ta, ma
	WORD $0x5e07c4d7  // vmv.v.x	v9, a5
	WORD $0x3e9064d7  // vslide1down.vx	v9, v9, zero
	WORD $0x3e9064d7  // vslide1down.vx	v9, v9, zero
	WORD $0x3e9064d7  // vslide1down.vx	v9, v9, zero
	WORD $0x26940457  // vand.vv	v8, v9, v8
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x9686e457  // vmul.vx	v8, v8, a3
	MOV $·pf9f0f641d845caf_LCPI0_5(SB), X13  // lui	a3, %hi(.LCPI0_5)
	MOV (X13), X13  // ld	a3, %lo(.LCPI0_5)(a3)
	WORD $0xa2874557  // vsrl.vx	v10, v8, a4
	WORD $0x42006457  // vmv.s.x	v8, zero
	WORD $0x5e0505d7  // vmv.v.v	v11, v10
	WORD $0x09707057  // vsetvli	zero, zero, e32, mf2, tu, ma
	WORD $0x3a80b5d7  // vslideup.vi	v11, v8, 1
	WORD $0x0d807057  // vsetvli	zero, zero, e64, m1, ta, ma
	WORD $0x5e06c457  // vmv.v.x	v8, a3
	WORD $0x025786b3  // mul	a3, a5, t0
	WORD $0x40d588b3  // sub	a7, a1, a3
	WORD $0x000026b7  // lui	a3, 2
	WORD $0x7106869b  // addiw	a3, a3, 1808
	WORD $0x96b6e5d7  // vmul.vx	v11, v11, a3
	WORD $0x0000b6b7  // lui	a3, 11
	WORD $0x7ff68693  // addi	a3, a3, 2047
	WORD $0xcd727057  // vsetivli	zero, 4, e32, mf2, ta, ma
	WORD $0x0a9584d7  // vsub.vv	v9, v9, v11
	WORD $0xc8f17057  // vsetivli	zero, 2, e16, mf2, tu, ma
	WORD $0x3a90b557  // vslideup.vi	v10, v9, 1
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x96a134d7  // vsll.vi	v9, v10, 2
	WORD $0xcce27057  // vsetivli	zero, 4, e16, mf4, ta, ma
	WORD $0xc294a5d7  // vwaddu.vv	v11, v9, v9
	WORD $0xf29865d7  // vwmaccu.vx	v11, a6, v9
	WORD $0xcd717057  // vsetivli	zero, 2, e32, mf2, ta, ma
	WORD $0xc2b5a557  // vwaddu.vv	v10, v11, v11
	WORD $0xf2b86557  // vwmaccu.vx	v10, a6, v11
	WORD $0x00800713  // li	a4, 8
LBB0_35:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3ea645d7  // vslidedown.vx	v11, v10, a2
	WORD $0x42b027d7  // vmv.x.s	a5, v11
	WORD $0x3e8645d7  // vslidedown.vx	v11, v8, a2
	WORD $0x42b025d7  // vmv.x.s	a1, v11
	WORD $0x03079793  // slli	a5, a5, 48
	WORD $0x00d5f5b3  // and	a1, a1, a3
	WORD $0x0307d793  // srli	a5, a5, 48
	WORD $0x02b785b3  // mul	a1, a5, a1
	WORD $0x0105d593  // srli	a1, a1, 16
	WORD $0x4205e5d7  // vmv.s.x	v11, a1
	WORD $0x00160593  // addi	a1, a2, 1
	WORD $0x08f5f057  // vsetvli	zero, a1, e16, mf2, tu, ma
	WORD $0x3ab644d7  // vslideup.vx	v9, v11, a2
	WORD $0x00058613  // mv	a2, a1
	BNE X11, X14, LBB0_35  // bne	a1, a4, .LBB0_35
	WORD $0x00000613  // li	a2, 0
	WORD $0xc00015b7  // lui	a1, 786433
	WORD $0x0000b6b7  // lui	a3, 11
	WORD $0x00659593  // slli	a1, a1, 6
	WORD $0x88068693  // addi	a3, a3, -1920
	WORD $0x00158593  // addi	a1, a1, 1
	WORD $0x01b59593  // slli	a1, a1, 27
	WORD $0x08058593  // addi	a1, a1, 128
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x5e05c557  // vmv.v.x	v10, a1
	WORD $0x00800713  // li	a4, 8
LBB0_37:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3e9645d7  // vslidedown.vx	v11, v9, a2
	WORD $0x42b025d7  // vmv.x.s	a1, v11
	WORD $0x3ea645d7  // vslidedown.vx	v11, v10, a2
	WORD $0x42b027d7  // vmv.x.s	a5, v11
	WORD $0x03059593  // slli	a1, a1, 48
	WORD $0x00d7f7b3  // and	a5, a5, a3
	WORD $0x0305d593  // srli	a1, a1, 48
	WORD $0x02f585b3  // mul	a1, a1, a5
	WORD $0x0105d593  // srli	a1, a1, 16
	WORD $0x4205e5d7  // vmv.s.x	v11, a1
	WORD $0x00160593  // addi	a1, a2, 1
	WORD $0x08f5f057  // vsetvli	zero, a1, e16, mf2, tu, ma
	WORD $0x3ab64457  // vslideup.vx	v8, v11, a2
	WORD $0x00058613  // mv	a2, a1
	BNE X11, X14, LBB0_37  // bne	a1, a4, .LBB0_37
	WORD $0x00000613  // li	a2, 0
	WORD $0x00a00693  // li	a3, 10
	WORD $0x00800713  // li	a4, 8
LBB0_39:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3e864557  // vslidedown.vx	v10, v8, a2
	WORD $0x42a025d7  // vmv.x.s	a1, v10
	WORD $0x02d585b3  // mul	a1, a1, a3
	WORD $0x4205e557  // vmv.s.x	v10, a1
	WORD $0x00160593  // addi	a1, a2, 1
	WORD $0x08f5f057  // vsetvli	zero, a1, e16, mf2, tu, ma
	WORD $0x3aa644d7  // vslideup.vx	v9, v10, a2
	WORD $0x00058613  // mv	a2, a1
	BNE X11, X14, LBB0_39  // bne	a1, a4, .LBB0_39
	WORD $0x00000613  // li	a2, 0
	WORD $0xcd727057  // vsetivli	zero, 4, e32, mf2, ta, ma
	WORD $0x5e08c557  // vmv.v.x	v10, a7
	WORD $0xfff00593  // li	a1, -1
	WORD $0x0205d693  // srli	a3, a1, 32
	WORD $0x0d807057  // vsetvli	zero, zero, e64, m1, ta, ma
	WORD $0x5e06c5d7  // vmv.v.x	v11, a3
	WORD $0x000d26b7  // lui	a3, 210
	WORD $0x0d707057  // vsetvli	zero, zero, e32, mf2, ta, ma
	WORD $0x3ea06557  // vslide1down.vx	v10, v10, zero
	WORD $0xb716869b  // addiw	a3, a3, -1167
	WORD $0x3ea06557  // vslide1down.vx	v10, v10, zero
	WORD $0x00c69693  // slli	a3, a3, 12
	WORD $0x3ea06557  // vslide1down.vx	v10, v10, zero
	WORD $0x75968693  // addi	a3, a3, 1881
	WORD $0x26a585d7  // vand.vv	v11, v10, v11
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x96b6e5d7  // vmul.vx	v11, v11, a3
	WORD $0x02d00693  // li	a3, 45
	WORD $0xa2b6c657  // vsrl.vx	v12, v11, a3
	MOV $·pf9f0f641d845caf_LCPI0_5(SB), X13  // lui	a3, %hi(.LCPI0_5)
	MOV (X13), X13  // ld	a3, %lo(.LCPI0_5)(a3)
	WORD $0x969834d7  // vsll.vi	v9, v9, 16
	WORD $0x420065d7  // vmv.s.x	v11, zero
	WORD $0x5e0606d7  // vmv.v.v	v13, v12
	WORD $0x09707057  // vsetvli	zero, zero, e32, mf2, tu, ma
	WORD $0x3ab0b6d7  // vslideup.vi	v13, v11, 1
	WORD $0x0d807057  // vsetvli	zero, zero, e64, m1, ta, ma
	WORD $0x5e06c5d7  // vmv.v.x	v11, a3
	WORD $0x000026b7  // lui	a3, 2
	WORD $0x7106869b  // addiw	a3, a3, 1808
	WORD $0x96d6e6d7  // vmul.vx	v13, v13, a3
	WORD $0x0000b6b7  // lui	a3, 11
	WORD $0x7ff68693  // addi	a3, a3, 2047
	WORD $0xcd727057  // vsetivli	zero, 4, e32, mf2, ta, ma
	WORD $0x0aa68557  // vsub.vv	v10, v10, v13
	WORD $0xc8f17057  // vsetivli	zero, 2, e16, mf2, tu, ma
	WORD $0x3aa0b657  // vslideup.vi	v12, v10, 1
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x96c13557  // vsll.vi	v10, v12, 2
	WORD $0xcce27057  // vsetivli	zero, 4, e16, mf4, ta, ma
	WORD $0xc2a526d7  // vwaddu.vv	v13, v10, v10
	WORD $0xf2a5e6d7  // vwmaccu.vx	v13, a1, v10
	WORD $0xcd717057  // vsetivli	zero, 2, e32, mf2, ta, ma
	WORD $0xc2d6a657  // vwaddu.vv	v12, v13, v13
	WORD $0xf2d5e657  // vwmaccu.vx	v12, a1, v13
	WORD $0x00800593  // li	a1, 8
LBB0_41:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3ec646d7  // vslidedown.vx	v13, v12, a2
	WORD $0x42d02757  // vmv.x.s	a4, v13
	WORD $0x3eb646d7  // vslidedown.vx	v13, v11, a2
	WORD $0x42d027d7  // vmv.x.s	a5, v13
	WORD $0x03071713  // slli	a4, a4, 48
	WORD $0x00d7f7b3  // and	a5, a5, a3
	WORD $0x03075713  // srli	a4, a4, 48
	WORD $0x02f70733  // mul	a4, a4, a5
	WORD $0x01075713  // srli	a4, a4, 16
	WORD $0x420766d7  // vmv.s.x	v13, a4
	WORD $0x00160713  // addi	a4, a2, 1
	WORD $0x08f77057  // vsetvli	zero, a4, e16, mf2, tu, ma
	WORD $0x3ad64557  // vslideup.vx	v10, v13, a2
	WORD $0x00070613  // mv	a2, a4
	BNE X14, X11, LBB0_41  // bne	a4, a1, .LBB0_41
	WORD $0x00000593  // li	a1, 0
	WORD $0xc0001637  // lui	a2, 786433
	WORD $0x0000b6b7  // lui	a3, 11
	WORD $0x00661713  // slli	a4, a2, 6
	WORD $0x88068613  // addi	a2, a3, -1920
	WORD $0x00170713  // addi	a4, a4, 1
	WORD $0x01b71713  // slli	a4, a4, 27
	WORD $0x08070693  // addi	a3, a4, 128
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x5e06c657  // vmv.v.x	v12, a3
	WORD $0x00800693  // li	a3, 8
LBB0_43:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3ea5c6d7  // vslidedown.vx	v13, v10, a1
	WORD $0x42d02757  // vmv.x.s	a4, v13
	WORD $0x3ec5c6d7  // vslidedown.vx	v13, v12, a1
	WORD $0x42d027d7  // vmv.x.s	a5, v13
	WORD $0x03071713  // slli	a4, a4, 48
	WORD $0x00c7f7b3  // and	a5, a5, a2
	WORD $0x03075713  // srli	a4, a4, 48
	WORD $0x02f70733  // mul	a4, a4, a5
	WORD $0x01075713  // srli	a4, a4, 16
	WORD $0x420766d7  // vmv.s.x	v13, a4
	WORD $0x00158713  // addi	a4, a1, 1
	WORD $0x08f77057  // vsetvli	zero, a4, e16, mf2, tu, ma
	WORD $0x3ad5c5d7  // vslideup.vx	v11, v13, a1
	WORD $0x00070593  // mv	a1, a4
	BNE X14, X13, LBB0_43  // bne	a4, a3, .LBB0_43
	WORD $0x00000593  // li	a1, 0
	WORD $0x00a00613  // li	a2, 10
	WORD $0x00800693  // li	a3, 8
LBB0_45:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3eb5c657  // vslidedown.vx	v12, v11, a1
	WORD $0x42c02757  // vmv.x.s	a4, v12
	WORD $0x02c70733  // mul	a4, a4, a2
	WORD $0x42076657  // vmv.s.x	v12, a4
	WORD $0x00158713  // addi	a4, a1, 1
	WORD $0x08f77057  // vsetvli	zero, a4, e16, mf2, tu, ma
	WORD $0x3ac5c557  // vslideup.vx	v10, v12, a1
	WORD $0x00070593  // mv	a1, a4
	BNE X14, X13, LBB0_45  // bne	a4, a3, .LBB0_45
	WORD $0x00000613  // li	a2, 0
	WORD $0xccf47057  // vsetivli	zero, 8, e16, mf2, ta, ma
	WORD $0x0a848457  // vsub.vv	v8, v8, v9
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x96a834d7  // vsll.vi	v9, v10, 16
	WORD $0x00f00593  // li	a1, 15
	WORD $0xfff00693  // li	a3, -1
	WORD $0xccf47057  // vsetivli	zero, 8, e16, mf2, ta, ma
	WORD $0x0ab484d7  // vsub.vv	v9, v11, v9
	WORD $0xcc887057  // vsetivli	zero, 16, e16, m1, ta, ma
	WORD $0x3a943457  // vslideup.vi	v8, v9, 8
	WORD $0x1e804457  // vmax.vx	v8, v8, zero
	WORD $0x0c707057  // vsetvli	zero, zero, e8, mf2, ta, ma
	WORD $0xba803457  // vnclipu.wi	v8, v8, 0
	WORD $0x00f00713  // li	a4, 15
LBB0_47:
	WORD $0xcc70f057  // vsetivli	zero, 1, e8, mf2, ta, ma
	WORD $0x3e8744d7  // vslidedown.vx	v9, v8, a4
	WORD $0xfff70713  // addi	a4, a4, -1
	WORD $0x429027d7  // vmv.x.s	a5, v9
	WORD $0x0ff7f793  // andi	a5, a5, 255
	WORD $0x0017b793  // seqz	a5, a5
	WORD $0x00b797bb  // sllw	a5, a5, a1
	WORD $0x00f66633  // or	a2, a2, a5
	WORD $0xfff58593  // addi	a1, a1, -1
	BNE X14, X13, LBB0_47  // bne	a4, a3, .LBB0_47
	WORD $0x00000593  // li	a1, 0
	WORD $0xfff64613  // not	a2, a2
	WORD $0x000086b7  // lui	a3, 8
	WORD $0x077cb737  // lui	a4, 30667
	WORD $0x00d66633  // or	a2, a2, a3
	WORD $0x40c006bb  // negw	a3, a2
	WORD $0x00d67633  // and	a2, a2, a3
	MOV $·pf9f0f641d845caf_LCPI0_6(SB), X13  // lui	a3, %hi(.LCPI0_6)
	// addi	a3, a3, %lo(.LCPI0_6) (skipped, covered by MOV address load)
	WORD $0x53170713  // addi	a4, a4, 1329
	WORD $0x02e60633  // mul	a2, a2, a4
	WORD $0x01b6561b  // srliw	a2, a2, 27
	WORD $0x00d60633  // add	a2, a2, a3
	WORD $0x00064603  // lbu	a2, 0(a2)
	WORD $0x00461693  // slli	a3, a2, 4
	MOV $·pf9f0f641d845caf_VecShiftShuffles(SB), X14  // lui	a4, %hi(VecShiftShuffles)
	// addi	a4, a4, %lo(VecShiftShuffles) (skipped, covered by MOV address load)
	WORD $0x00e686b3  // add	a3, a3, a4
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x02068487  // vle8.v	v9, (a3)
	WORD $0x01000693  // li	a3, 16
LBB0_49:
	WORD $0xcc70f057  // vsetivli	zero, 1, e8, mf2, ta, ma
	WORD $0x3e95c5d7  // vslidedown.vx	v11, v9, a1
	WORD $0x42b02757  // vmv.x.s	a4, v11
	WORD $0x00f77793  // andi	a5, a4, 15
	WORD $0x00072713  // slti	a4, a4, 0
	WORD $0x3e87c5d7  // vslidedown.vx	v11, v8, a5
	WORD $0xfff70713  // addi	a4, a4, -1
	WORD $0x42b027d7  // vmv.x.s	a5, v11
	WORD $0x03078793  // addi	a5, a5, 48
	WORD $0x00f77733  // and	a4, a4, a5
	WORD $0x420765d7  // vmv.s.x	v11, a4
	WORD $0x00158713  // addi	a4, a1, 1
	WORD $0x08777057  // vsetvli	zero, a4, e8, mf2, tu, ma
	WORD $0x3ab5c557  // vslideup.vx	v10, v11, a1
	WORD $0x00070593  // mv	a1, a4
	BNE X14, X13, LBB0_49  // bne	a4, a3, .LBB0_49
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x02050527  // vse8.v	v10, (a0)
	WORD $0x01000593  // li	a1, 16
	WORD $0x40c585b3  // sub	a1, a1, a2
	JMP LBB0_9  // j	.LBB0_9
LBB0_51:
	WORD $0x000f4537  // lui	a0, 244
	WORD $0x2405051b  // addiw	a0, a0, 576
	BLTU X11, X10, LBB0_56  // bltu	a1, a0, .LBB0_56
	WORD $0x00000793  // li	a5, 0
LBB0_53:
	WORD $0x00176513  // ori	a0, a4, 1
	MOV $·pf9f0f641d845caf_Digits(SB), X14  // lui	a4, %hi(Digits)
	// addi	a4, a4, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x00e50533  // add	a0, a0, a4
	WORD $0x00054503  // lbu	a0, 0(a0)
	WORD $0x00178713  // addi	a4, a5, 1
	WORD $0x00c787b3  // add	a5, a5, a2
	WORD $0x00a78023  // sb	a0, 0(a5)
LBB0_54:
	WORD $0x03069513  // slli	a0, a3, 48
	WORD $0x03055513  // srli	a0, a0, 48
	MOV $·pf9f0f641d845caf_Digits(SB), X15  // lui	a5, %hi(Digits)
	// addi	a5, a5, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x00f50533  // add	a0, a0, a5
	WORD $0x00054503  // lbu	a0, 0(a0)
	WORD $0x00170313  // addi	t1, a4, 1
	WORD $0x00c70733  // add	a4, a4, a2
	WORD $0x00a70023  // sb	a0, 0(a4)
LBB0_55:
	WORD $0x00002537  // lui	a0, 2
	WORD $0x000012b7  // lui	t0, 1
	WORD $0x06400893  // li	a7, 100
	WORD $0x0016e693  // ori	a3, a3, 1
	WORD $0x71050513  // addi	a0, a0, 1808
	WORD $0x02a80533  // mul	a0, a6, a0
	MOV $·pf9f0f641d845caf_Digits(SB), X14  // lui	a4, %hi(Digits)
	// addi	a4, a4, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x47b2879b  // addiw	a5, t0, 1147
	WORD $0x03069693  // slli	a3, a3, 48
	WORD $0x0306d693  // srli	a3, a3, 48
	WORD $0x40a585bb  // subw	a1, a1, a0
	WORD $0x00e686b3  // add	a3, a3, a4
	WORD $0x03059513  // slli	a0, a1, 48
	WORD $0x0006c683  // lbu	a3, 0(a3)
	WORD $0x03255513  // srli	a0, a0, 50
	WORD $0x02f50533  // mul	a0, a0, a5
	WORD $0x01155793  // srli	a5, a0, 17
	WORD $0x031787b3  // mul	a5, a5, a7
	WORD $0x00660633  // add	a2, a2, t1
	WORD $0x01055513  // srli	a0, a0, 16
	WORD $0x00d60023  // sb	a3, 0(a2)
	WORD $0x7fe57513  // andi	a0, a0, 2046
	WORD $0x40f585bb  // subw	a1, a1, a5
	WORD $0x00e50533  // add	a0, a0, a4
	WORD $0xcc517057  // vsetivli	zero, 2, e8, mf8, ta, ma
	WORD $0x02050407  // vle8.v	v8, (a0)
	WORD $0x03159593  // slli	a1, a1, 49
	WORD $0x0305d593  // srli	a1, a1, 48
	WORD $0x00e585b3  // add	a1, a1, a4
	WORD $0x02058487  // vle8.v	v9, (a1)
	WORD $0x00160613  // addi	a2, a2, 1
	WORD $0x00530593  // addi	a1, t1, 5
	WORD $0xcc527057  // vsetivli	zero, 4, e8, mf8, ta, ma
	WORD $0x3a913457  // vslideup.vi	v8, v9, 2
	WORD $0x02060427  // vse8.v	v8, (a2)
	JMP LBB0_22  // j	.LBB0_22
LBB0_56:
	WORD $0x00000713  // li	a4, 0
	WORD $0x00018537  // lui	a0, 24
	WORD $0x6a05051b  // addiw	a0, a0, 1696
	WORD $0x00000313  // li	t1, 0
	BGEU X11, X10, LBB0_54  // bgeu	a1, a0, .LBB0_54
	JMP LBB0_55  // j	.LBB0_55
LBB0_57:
	MOV $·pf9f0f641d845caf_LCPI0_0(SB), X13  // lui	a3, %hi(.LCPI0_0)
	MOV (X13), X13  // ld	a3, %lo(.LCPI0_0)(a3)
	BLTU X13, X11, LBB0_93  // bltu	a3, a1, .LBB0_93
	WORD $0x00000513  // li	a0, 0
	MOV $·pf9f0f641d845caf_LCPI0_4(SB), X14  // lui	a4, %hi(.LCPI0_4)
	WORD $0xfff00813  // li	a6, -1
	WORD $0x000d27b7  // lui	a5, 210
	WORD $0x02085693  // srli	a3, a6, 32
	WORD $0xcd827057  // vsetivli	zero, 4, e64, m1, ta, ma
	WORD $0x5e06c457  // vmv.v.x	v8, a3
	WORD $0x02d00693  // li	a3, 45
	MOV (X14), X14  // ld	a4, %lo(.LCPI0_4)(a4)
	WORD $0xb717879b  // addiw	a5, a5, -1167
	WORD $0x00c79793  // slli	a5, a5, 12
	WORD $0x75978793  // addi	a5, a5, 1881
	WORD $0x02e5b733  // mulhu	a4, a1, a4
	WORD $0x01a75713  // srli	a4, a4, 26
	WORD $0x0d707057  // vsetvli	zero, zero, e32, mf2, ta, ma
	WORD $0x5e0744d7  // vmv.v.x	v9, a4
	WORD $0x3e9064d7  // vslide1down.vx	v9, v9, zero
	WORD $0x3e9064d7  // vslide1down.vx	v9, v9, zero
	WORD $0x3e9064d7  // vslide1down.vx	v9, v9, zero
	WORD $0x26940457  // vand.vv	v8, v9, v8
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x9687e457  // vmul.vx	v8, v8, a5
	MOV $·pf9f0f641d845caf_LCPI0_5(SB), X15  // lui	a5, %hi(.LCPI0_5)
	MOV (X15), X15  // ld	a5, %lo(.LCPI0_5)(a5)
	WORD $0xa286c557  // vsrl.vx	v10, v8, a3
	WORD $0x42006457  // vmv.s.x	v8, zero
	WORD $0x5e0505d7  // vmv.v.v	v11, v10
	WORD $0x09707057  // vsetvli	zero, zero, e32, mf2, tu, ma
	WORD $0x3a80b5d7  // vslideup.vi	v11, v8, 1
	WORD $0x0d807057  // vsetvli	zero, zero, e64, m1, ta, ma
	WORD $0x5e07c457  // vmv.v.x	v8, a5
	WORD $0x05f5e6b7  // lui	a3, 24414
	WORD $0x10068693  // addi	a3, a3, 256
	WORD $0x02d706b3  // mul	a3, a4, a3
	WORD $0x40d588b3  // sub	a7, a1, a3
	WORD $0x000026b7  // lui	a3, 2
	WORD $0x7106869b  // addiw	a3, a3, 1808
	WORD $0x96b6e5d7  // vmul.vx	v11, v11, a3
	WORD $0x0000b6b7  // lui	a3, 11
	WORD $0x7ff68713  // addi	a4, a3, 2047
	WORD $0xcd727057  // vsetivli	zero, 4, e32, mf2, ta, ma
	WORD $0x0a9584d7  // vsub.vv	v9, v9, v11
	WORD $0xc8f17057  // vsetivli	zero, 2, e16, mf2, tu, ma
	WORD $0x3a90b557  // vslideup.vi	v10, v9, 1
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x96a134d7  // vsll.vi	v9, v10, 2
	WORD $0xcce27057  // vsetivli	zero, 4, e16, mf4, ta, ma
	WORD $0xc294a5d7  // vwaddu.vv	v11, v9, v9
	WORD $0xf29865d7  // vwmaccu.vx	v11, a6, v9
	WORD $0xcd717057  // vsetivli	zero, 2, e32, mf2, ta, ma
	WORD $0xc2b5a557  // vwaddu.vv	v10, v11, v11
	WORD $0xf2b86557  // vwmaccu.vx	v10, a6, v11
	WORD $0x00800693  // li	a3, 8
LBB0_59:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3ea545d7  // vslidedown.vx	v11, v10, a0
	WORD $0x42b027d7  // vmv.x.s	a5, v11
	WORD $0x3e8545d7  // vslidedown.vx	v11, v8, a0
	WORD $0x42b025d7  // vmv.x.s	a1, v11
	WORD $0x03079793  // slli	a5, a5, 48
	WORD $0x00e5f5b3  // and	a1, a1, a4
	WORD $0x0307d793  // srli	a5, a5, 48
	WORD $0x02b785b3  // mul	a1, a5, a1
	WORD $0x0105d593  // srli	a1, a1, 16
	WORD $0x4205e5d7  // vmv.s.x	v11, a1
	WORD $0x00150593  // addi	a1, a0, 1
	WORD $0x08f5f057  // vsetvli	zero, a1, e16, mf2, tu, ma
	WORD $0x3ab544d7  // vslideup.vx	v9, v11, a0
	WORD $0x00058513  // mv	a0, a1
	BNE X11, X13, LBB0_59  // bne	a1, a3, .LBB0_59
	WORD $0x00000513  // li	a0, 0
	WORD $0xc00015b7  // lui	a1, 786433
	WORD $0x0000b6b7  // lui	a3, 11
	WORD $0x00659593  // slli	a1, a1, 6
	WORD $0x88068693  // addi	a3, a3, -1920
	WORD $0x00158593  // addi	a1, a1, 1
	WORD $0x01b59593  // slli	a1, a1, 27
	WORD $0x08058593  // addi	a1, a1, 128
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x5e05c557  // vmv.v.x	v10, a1
	WORD $0x00800713  // li	a4, 8
LBB0_61:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3e9545d7  // vslidedown.vx	v11, v9, a0
	WORD $0x42b025d7  // vmv.x.s	a1, v11
	WORD $0x3ea545d7  // vslidedown.vx	v11, v10, a0
	WORD $0x42b027d7  // vmv.x.s	a5, v11
	WORD $0x03059593  // slli	a1, a1, 48
	WORD $0x00d7f7b3  // and	a5, a5, a3
	WORD $0x0305d593  // srli	a1, a1, 48
	WORD $0x02f585b3  // mul	a1, a1, a5
	WORD $0x0105d593  // srli	a1, a1, 16
	WORD $0x4205e5d7  // vmv.s.x	v11, a1
	WORD $0x00150593  // addi	a1, a0, 1
	WORD $0x08f5f057  // vsetvli	zero, a1, e16, mf2, tu, ma
	WORD $0x3ab54457  // vslideup.vx	v8, v11, a0
	WORD $0x00058513  // mv	a0, a1
	BNE X11, X14, LBB0_61  // bne	a1, a4, .LBB0_61
	WORD $0x00000513  // li	a0, 0
	WORD $0x00a00693  // li	a3, 10
	WORD $0x00800713  // li	a4, 8
LBB0_63:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3e854557  // vslidedown.vx	v10, v8, a0
	WORD $0x42a025d7  // vmv.x.s	a1, v10
	WORD $0x02d585b3  // mul	a1, a1, a3
	WORD $0x4205e557  // vmv.s.x	v10, a1
	WORD $0x00150593  // addi	a1, a0, 1
	WORD $0x08f5f057  // vsetvli	zero, a1, e16, mf2, tu, ma
	WORD $0x3aa544d7  // vslideup.vx	v9, v10, a0
	WORD $0x00058513  // mv	a0, a1
	BNE X11, X14, LBB0_63  // bne	a1, a4, .LBB0_63
	WORD $0x00000513  // li	a0, 0
	WORD $0xcd727057  // vsetivli	zero, 4, e32, mf2, ta, ma
	WORD $0x5e08c557  // vmv.v.x	v10, a7
	WORD $0xfff00593  // li	a1, -1
	WORD $0x0205d693  // srli	a3, a1, 32
	WORD $0x0d807057  // vsetvli	zero, zero, e64, m1, ta, ma
	WORD $0x5e06c5d7  // vmv.v.x	v11, a3
	WORD $0x000d26b7  // lui	a3, 210
	WORD $0x0d707057  // vsetvli	zero, zero, e32, mf2, ta, ma
	WORD $0x3ea06557  // vslide1down.vx	v10, v10, zero
	WORD $0xb716869b  // addiw	a3, a3, -1167
	WORD $0x3ea06557  // vslide1down.vx	v10, v10, zero
	WORD $0x00c69693  // slli	a3, a3, 12
	WORD $0x3ea06557  // vslide1down.vx	v10, v10, zero
	WORD $0x75968693  // addi	a3, a3, 1881
	WORD $0x26a585d7  // vand.vv	v11, v10, v11
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x96b6e5d7  // vmul.vx	v11, v11, a3
	WORD $0x02d00693  // li	a3, 45
	WORD $0xa2b6c657  // vsrl.vx	v12, v11, a3
	MOV $·pf9f0f641d845caf_LCPI0_5(SB), X13  // lui	a3, %hi(.LCPI0_5)
	MOV (X13), X13  // ld	a3, %lo(.LCPI0_5)(a3)
	WORD $0x969834d7  // vsll.vi	v9, v9, 16
	WORD $0x420065d7  // vmv.s.x	v11, zero
	WORD $0x5e0606d7  // vmv.v.v	v13, v12
	WORD $0x09707057  // vsetvli	zero, zero, e32, mf2, tu, ma
	WORD $0x3ab0b6d7  // vslideup.vi	v13, v11, 1
	WORD $0x0d807057  // vsetvli	zero, zero, e64, m1, ta, ma
	WORD $0x5e06c5d7  // vmv.v.x	v11, a3
	WORD $0x000026b7  // lui	a3, 2
	WORD $0x7106869b  // addiw	a3, a3, 1808
	WORD $0x96d6e6d7  // vmul.vx	v13, v13, a3
	WORD $0x0000b6b7  // lui	a3, 11
	WORD $0x7ff68693  // addi	a3, a3, 2047
	WORD $0xcd727057  // vsetivli	zero, 4, e32, mf2, ta, ma
	WORD $0x0aa68557  // vsub.vv	v10, v10, v13
	WORD $0xc8f17057  // vsetivli	zero, 2, e16, mf2, tu, ma
	WORD $0x3aa0b657  // vslideup.vi	v12, v10, 1
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x96c13557  // vsll.vi	v10, v12, 2
	WORD $0xcce27057  // vsetivli	zero, 4, e16, mf4, ta, ma
	WORD $0xc2a526d7  // vwaddu.vv	v13, v10, v10
	WORD $0xf2a5e6d7  // vwmaccu.vx	v13, a1, v10
	WORD $0xcd717057  // vsetivli	zero, 2, e32, mf2, ta, ma
	WORD $0xc2d6a657  // vwaddu.vv	v12, v13, v13
	WORD $0xf2d5e657  // vwmaccu.vx	v12, a1, v13
	WORD $0x00800593  // li	a1, 8
LBB0_65:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3ec546d7  // vslidedown.vx	v13, v12, a0
	WORD $0x42d02757  // vmv.x.s	a4, v13
	WORD $0x3eb546d7  // vslidedown.vx	v13, v11, a0
	WORD $0x42d027d7  // vmv.x.s	a5, v13
	WORD $0x03071713  // slli	a4, a4, 48
	WORD $0x00d7f7b3  // and	a5, a5, a3
	WORD $0x03075713  // srli	a4, a4, 48
	WORD $0x02f70733  // mul	a4, a4, a5
	WORD $0x01075713  // srli	a4, a4, 16
	WORD $0x420766d7  // vmv.s.x	v13, a4
	WORD $0x00150713  // addi	a4, a0, 1
	WORD $0x08f77057  // vsetvli	zero, a4, e16, mf2, tu, ma
	WORD $0x3ad54557  // vslideup.vx	v10, v13, a0
	WORD $0x00070513  // mv	a0, a4
	BNE X14, X11, LBB0_65  // bne	a4, a1, .LBB0_65
	WORD $0x00000513  // li	a0, 0
	WORD $0xc00015b7  // lui	a1, 786433
	WORD $0x0000b6b7  // lui	a3, 11
	WORD $0x00659713  // slli	a4, a1, 6
	WORD $0x88068593  // addi	a1, a3, -1920
	WORD $0x00170713  // addi	a4, a4, 1
	WORD $0x01b71713  // slli	a4, a4, 27
	WORD $0x08070693  // addi	a3, a4, 128
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x5e06c657  // vmv.v.x	v12, a3
	WORD $0x00800693  // li	a3, 8
LBB0_67:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3ea546d7  // vslidedown.vx	v13, v10, a0
	WORD $0x42d02757  // vmv.x.s	a4, v13
	WORD $0x3ec546d7  // vslidedown.vx	v13, v12, a0
	WORD $0x42d027d7  // vmv.x.s	a5, v13
	WORD $0x03071713  // slli	a4, a4, 48
	WORD $0x00b7f7b3  // and	a5, a5, a1
	WORD $0x03075713  // srli	a4, a4, 48
	WORD $0x02f70733  // mul	a4, a4, a5
	WORD $0x01075713  // srli	a4, a4, 16
	WORD $0x420766d7  // vmv.s.x	v13, a4
	WORD $0x00150713  // addi	a4, a0, 1
	WORD $0x08f77057  // vsetvli	zero, a4, e16, mf2, tu, ma
	WORD $0x3ad545d7  // vslideup.vx	v11, v13, a0
	WORD $0x00070513  // mv	a0, a4
	BNE X14, X13, LBB0_67  // bne	a4, a3, .LBB0_67
	WORD $0x00000513  // li	a0, 0
	WORD $0x00a00593  // li	a1, 10
	WORD $0x00800693  // li	a3, 8
LBB0_69:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3eb54657  // vslidedown.vx	v12, v11, a0
	WORD $0x42c02757  // vmv.x.s	a4, v12
	WORD $0x02b70733  // mul	a4, a4, a1
	WORD $0x42076657  // vmv.s.x	v12, a4
	WORD $0x00150713  // addi	a4, a0, 1
	WORD $0x08f77057  // vsetvli	zero, a4, e16, mf2, tu, ma
	WORD $0x3ac54557  // vslideup.vx	v10, v12, a0
	WORD $0x00070513  // mv	a0, a4
	BNE X14, X13, LBB0_69  // bne	a4, a3, .LBB0_69
	WORD $0x00000593  // li	a1, 0
	WORD $0xccf47057  // vsetivli	zero, 8, e16, mf2, ta, ma
	WORD $0x0a848457  // vsub.vv	v8, v8, v9
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x96a834d7  // vsll.vi	v9, v10, 16
	WORD $0x00f00513  // li	a0, 15
	WORD $0xfff00693  // li	a3, -1
	WORD $0xccf47057  // vsetivli	zero, 8, e16, mf2, ta, ma
	WORD $0x0ab484d7  // vsub.vv	v9, v11, v9
	WORD $0xcc887057  // vsetivli	zero, 16, e16, m1, ta, ma
	WORD $0x3a943457  // vslideup.vi	v8, v9, 8
	WORD $0x1e804457  // vmax.vx	v8, v8, zero
	WORD $0x0c707057  // vsetvli	zero, zero, e8, mf2, ta, ma
	WORD $0xba803457  // vnclipu.wi	v8, v8, 0
	WORD $0x00f00713  // li	a4, 15
LBB0_71:
	WORD $0xcc70f057  // vsetivli	zero, 1, e8, mf2, ta, ma
	WORD $0x3e8744d7  // vslidedown.vx	v9, v8, a4
	WORD $0xfff70713  // addi	a4, a4, -1
	WORD $0x429027d7  // vmv.x.s	a5, v9
	WORD $0x0ff7f793  // andi	a5, a5, 255
	WORD $0x0017b793  // seqz	a5, a5
	WORD $0x00a797bb  // sllw	a5, a5, a0
	WORD $0x00f5e5b3  // or	a1, a1, a5
	WORD $0xfff50513  // addi	a0, a0, -1
	BNE X14, X13, LBB0_71  // bne	a4, a3, .LBB0_71
	WORD $0x00000513  // li	a0, 0
	WORD $0xfff5c593  // not	a1, a1
	WORD $0x000086b7  // lui	a3, 8
	WORD $0x077cb737  // lui	a4, 30667
	WORD $0x00d5e5b3  // or	a1, a1, a3
	WORD $0x40b006bb  // negw	a3, a1
	WORD $0x00d5f5b3  // and	a1, a1, a3
	MOV $·pf9f0f641d845caf_LCPI0_6(SB), X13  // lui	a3, %hi(.LCPI0_6)
	// addi	a3, a3, %lo(.LCPI0_6) (skipped, covered by MOV address load)
	WORD $0x53170713  // addi	a4, a4, 1329
	WORD $0x02e585b3  // mul	a1, a1, a4
	WORD $0x01b5d59b  // srliw	a1, a1, 27
	WORD $0x00d585b3  // add	a1, a1, a3
	WORD $0x0005c583  // lbu	a1, 0(a1)
	WORD $0x00459693  // slli	a3, a1, 4
	MOV $·pf9f0f641d845caf_VecShiftShuffles(SB), X14  // lui	a4, %hi(VecShiftShuffles)
	// addi	a4, a4, %lo(VecShiftShuffles) (skipped, covered by MOV address load)
	WORD $0x00e686b3  // add	a3, a3, a4
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x02068487  // vle8.v	v9, (a3)
	WORD $0x01000693  // li	a3, 16
LBB0_73:
	WORD $0xcc70f057  // vsetivli	zero, 1, e8, mf2, ta, ma
	WORD $0x3e9545d7  // vslidedown.vx	v11, v9, a0
	WORD $0x42b02757  // vmv.x.s	a4, v11
	WORD $0x00f77793  // andi	a5, a4, 15
	WORD $0x00072713  // slti	a4, a4, 0
	WORD $0x3e87c5d7  // vslidedown.vx	v11, v8, a5
	WORD $0xfff70713  // addi	a4, a4, -1
	WORD $0x42b027d7  // vmv.x.s	a5, v11
	WORD $0x03078793  // addi	a5, a5, 48
	WORD $0x00f77733  // and	a4, a4, a5
	WORD $0x420765d7  // vmv.s.x	v11, a4
	WORD $0x00150713  // addi	a4, a0, 1
	WORD $0x08777057  // vsetvli	zero, a4, e8, mf2, tu, ma
	WORD $0x3ab54557  // vslideup.vx	v10, v11, a0
	WORD $0x00070513  // mv	a0, a4
	BNE X14, X13, LBB0_73  // bne	a4, a3, .LBB0_73
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x02060527  // vse8.v	v10, (a2)
	WORD $0x01000513  // li	a0, 16
	WORD $0x40b505b3  // sub	a1, a0, a1
	JMP LBB0_22  // j	.LBB0_22
LBB0_75:
	MOV $·pf9f0f641d845caf_LCPI0_1(SB), X13  // lui	a3, %hi(.LCPI0_1)
	MOV (X13), X13  // ld	a3, %lo(.LCPI0_1)(a3)
	MOV $·pf9f0f641d845caf_LCPI0_2(SB), X14  // lui	a4, %hi(.LCPI0_2)
	MOV (X14), X15  // ld	a5, %lo(.LCPI0_2)(a4)
	WORD $0x02d5b733  // mulhu	a4, a1, a3
	WORD $0x03375713  // srli	a4, a4, 51
	BLTU X15, X11, LBB0_77  // bltu	a5, a1, .LBB0_77
	WORD $0x03076613  // ori	a2, a4, 48
	WORD $0x00c50023  // sb	a2, 0(a0)
	WORD $0x00100813  // li	a6, 1
	JMP LBB0_80  // j	.LBB0_80
LBB0_77:
	MOV $·pf9f0f641d845caf_LCPI0_3(SB), X13  // lui	a3, %hi(.LCPI0_3)
	MOV (X13), X13  // ld	a3, %lo(.LCPI0_3)(a3)
	BLTU X13, X11, LBB0_79  // bltu	a3, a1, .LBB0_79
	WORD $0x00171613  // slli	a2, a4, 1
	MOV $·pf9f0f641d845caf_Digits(SB), X13  // lui	a3, %hi(Digits)
	// addi	a3, a3, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x00d60633  // add	a2, a2, a3
	WORD $0xcc517057  // vsetivli	zero, 2, e8, mf8, ta, ma
	WORD $0x02060407  // vle8.v	v8, (a2)
	WORD $0x02050427  // vse8.v	v8, (a0)
	WORD $0x00200813  // li	a6, 2
	JMP LBB0_80  // j	.LBB0_80
LBB0_79:
	WORD $0x51f00693  // li	a3, 1311
	WORD $0x06400793  // li	a5, 100
	WORD $0x02d706b3  // mul	a3, a4, a3
	WORD $0x0116d693  // srli	a3, a3, 17
	WORD $0x02f687b3  // mul	a5, a3, a5
	WORD $0x0306e693  // ori	a3, a3, 48
	WORD $0x00d50023  // sb	a3, 0(a0)
	MOV $·pf9f0f641d845caf_Digits(SB), X13  // lui	a3, %hi(Digits)
	// addi	a3, a3, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x40f707bb  // subw	a5, a4, a5
	WORD $0x03179793  // slli	a5, a5, 49
	WORD $0x0307d793  // srli	a5, a5, 48
	WORD $0x00f686b3  // add	a3, a3, a5
	WORD $0xcc517057  // vsetivli	zero, 2, e8, mf8, ta, ma
	WORD $0x02068407  // vle8.v	v8, (a3)
	WORD $0x02060427  // vse8.v	v8, (a2)
	WORD $0x00300813  // li	a6, 3
LBB0_80:
	WORD $0x00000793  // li	a5, 0
	WORD $0x023876b7  // lui	a3, 9095
	WORD $0xfff00313  // li	t1, -1
	WORD $0x02035613  // srli	a2, t1, 32
	WORD $0xcd827057  // vsetivli	zero, 4, e64, m1, ta, ma
	WORD $0x5e064457  // vmv.v.x	v8, a2
	MOV $·pf9f0f641d845caf_LCPI0_4(SB), X12  // lui	a2, %hi(.LCPI0_4)
	WORD $0xf276869b  // addiw	a3, a3, -217
	WORD $0x00c69693  // slli	a3, a3, 12
	WORD $0xfc168693  // addi	a3, a3, -63
	WORD $0x01069693  // slli	a3, a3, 16
	WORD $0x02d706b3  // mul	a3, a4, a3
	WORD $0x000d2737  // lui	a4, 210
	WORD $0x40d588b3  // sub	a7, a1, a3
	WORD $0x02d00593  // li	a1, 45
	MOV (X12), X12  // ld	a2, %lo(.LCPI0_4)(a2)
	WORD $0xb717069b  // addiw	a3, a4, -1167
	WORD $0x00c69693  // slli	a3, a3, 12
	WORD $0x75968693  // addi	a3, a3, 1881
	WORD $0x02c8b733  // mulhu	a4, a7, a2
	WORD $0x01a75393  // srli	t2, a4, 26
	WORD $0x0d707057  // vsetvli	zero, zero, e32, mf2, ta, ma
	WORD $0x5e03c4d7  // vmv.v.x	v9, t2
	WORD $0x3e9064d7  // vslide1down.vx	v9, v9, zero
	WORD $0x3e9064d7  // vslide1down.vx	v9, v9, zero
	WORD $0x3e9064d7  // vslide1down.vx	v9, v9, zero
	WORD $0x26940457  // vand.vv	v8, v9, v8
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x9686e457  // vmul.vx	v8, v8, a3
	MOV $·pf9f0f641d845caf_LCPI0_5(SB), X12  // lui	a2, %hi(.LCPI0_5)
	MOV (X12), X12  // ld	a2, %lo(.LCPI0_5)(a2)
	WORD $0xa285c557  // vsrl.vx	v10, v8, a1
	WORD $0x42006457  // vmv.s.x	v8, zero
	WORD $0x5e0505d7  // vmv.v.v	v11, v10
	WORD $0x09707057  // vsetvli	zero, zero, e32, mf2, tu, ma
	WORD $0x3a80b5d7  // vslideup.vi	v11, v8, 1
	WORD $0x0d807057  // vsetvli	zero, zero, e64, m1, ta, ma
	WORD $0x5e064457  // vmv.v.x	v8, a2
	WORD $0x000025b7  // lui	a1, 2
	WORD $0x7105859b  // addiw	a1, a1, 1808
	WORD $0x96b5e5d7  // vmul.vx	v11, v11, a1
	WORD $0x0000b5b7  // lui	a1, 11
	WORD $0x7ff58593  // addi	a1, a1, 2047
	WORD $0xcd727057  // vsetivli	zero, 4, e32, mf2, ta, ma
	WORD $0x0a9584d7  // vsub.vv	v9, v9, v11
	WORD $0xc8f17057  // vsetivli	zero, 2, e16, mf2, tu, ma
	WORD $0x3a90b557  // vslideup.vi	v10, v9, 1
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x96a134d7  // vsll.vi	v9, v10, 2
	WORD $0xcce27057  // vsetivli	zero, 4, e16, mf4, ta, ma
	WORD $0xc294a5d7  // vwaddu.vv	v11, v9, v9
	WORD $0xf29365d7  // vwmaccu.vx	v11, t1, v9
	WORD $0xcd717057  // vsetivli	zero, 2, e32, mf2, ta, ma
	WORD $0xc2b5a557  // vwaddu.vv	v10, v11, v11
	WORD $0xf2b36557  // vwmaccu.vx	v10, t1, v11
	WORD $0x00800613  // li	a2, 8
LBB0_81:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3ea7c5d7  // vslidedown.vx	v11, v10, a5
	WORD $0x42b026d7  // vmv.x.s	a3, v11
	WORD $0x3e87c5d7  // vslidedown.vx	v11, v8, a5
	WORD $0x42b02757  // vmv.x.s	a4, v11
	WORD $0x03069693  // slli	a3, a3, 48
	WORD $0x00b77733  // and	a4, a4, a1
	WORD $0x0306d693  // srli	a3, a3, 48
	WORD $0x02e686b3  // mul	a3, a3, a4
	WORD $0x0106d693  // srli	a3, a3, 16
	WORD $0x4206e5d7  // vmv.s.x	v11, a3
	WORD $0x00178693  // addi	a3, a5, 1
	WORD $0x08f6f057  // vsetvli	zero, a3, e16, mf2, tu, ma
	WORD $0x3ab7c4d7  // vslideup.vx	v9, v11, a5
	WORD $0x00068793  // mv	a5, a3
	BNE X13, X12, LBB0_81  // bne	a3, a2, .LBB0_81
	WORD $0x00000613  // li	a2, 0
	WORD $0xc00015b7  // lui	a1, 786433
	WORD $0x0000b6b7  // lui	a3, 11
	WORD $0x00659713  // slli	a4, a1, 6
	WORD $0x88068593  // addi	a1, a3, -1920
	WORD $0x00170713  // addi	a4, a4, 1
	WORD $0x01b71713  // slli	a4, a4, 27
	WORD $0x08070693  // addi	a3, a4, 128
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x5e06c557  // vmv.v.x	v10, a3
	WORD $0x00800793  // li	a5, 8
LBB0_83:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3e9645d7  // vslidedown.vx	v11, v9, a2
	WORD $0x42b026d7  // vmv.x.s	a3, v11
	WORD $0x3ea645d7  // vslidedown.vx	v11, v10, a2
	WORD $0x42b02757  // vmv.x.s	a4, v11
	WORD $0x03069693  // slli	a3, a3, 48
	WORD $0x00b77733  // and	a4, a4, a1
	WORD $0x0306d693  // srli	a3, a3, 48
	WORD $0x02e686b3  // mul	a3, a3, a4
	WORD $0x0106d693  // srli	a3, a3, 16
	WORD $0x4206e5d7  // vmv.s.x	v11, a3
	WORD $0x00160693  // addi	a3, a2, 1
	WORD $0x08f6f057  // vsetvli	zero, a3, e16, mf2, tu, ma
	WORD $0x3ab64457  // vslideup.vx	v8, v11, a2
	WORD $0x00068613  // mv	a2, a3
	BNE X13, X15, LBB0_83  // bne	a3, a5, .LBB0_83
	WORD $0x00000593  // li	a1, 0
	WORD $0x00a00613  // li	a2, 10
	WORD $0x00800793  // li	a5, 8
LBB0_85:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3e85c557  // vslidedown.vx	v10, v8, a1
	WORD $0x42a026d7  // vmv.x.s	a3, v10
	WORD $0x02c686b3  // mul	a3, a3, a2
	WORD $0x4206e557  // vmv.s.x	v10, a3
	WORD $0x00158693  // addi	a3, a1, 1
	WORD $0x08f6f057  // vsetvli	zero, a3, e16, mf2, tu, ma
	WORD $0x3aa5c4d7  // vslideup.vx	v9, v10, a1
	WORD $0x00068593  // mv	a1, a3
	BNE X13, X15, LBB0_85  // bne	a3, a5, .LBB0_85
	WORD $0x00000793  // li	a5, 0
	WORD $0x025385b3  // mul	a1, t2, t0
	WORD $0x40b8863b  // subw	a2, a7, a1
	WORD $0xfff00593  // li	a1, -1
	WORD $0xcd727057  // vsetivli	zero, 4, e32, mf2, ta, ma
	WORD $0x5e064557  // vmv.v.x	v10, a2
	WORD $0x0205d613  // srli	a2, a1, 32
	WORD $0x0d807057  // vsetvli	zero, zero, e64, m1, ta, ma
	WORD $0x5e0645d7  // vmv.v.x	v11, a2
	WORD $0x000d2637  // lui	a2, 210
	WORD $0xb716061b  // addiw	a2, a2, -1167
	WORD $0x00c61613  // slli	a2, a2, 12
	WORD $0x0d707057  // vsetvli	zero, zero, e32, mf2, ta, ma
	WORD $0x3ea06557  // vslide1down.vx	v10, v10, zero
	WORD $0x75960613  // addi	a2, a2, 1881
	WORD $0x3ea06557  // vslide1down.vx	v10, v10, zero
	WORD $0x3ea06557  // vslide1down.vx	v10, v10, zero
	WORD $0x26a585d7  // vand.vv	v11, v10, v11
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x96b665d7  // vmul.vx	v11, v11, a2
	WORD $0x02d00613  // li	a2, 45
	WORD $0xa2b64657  // vsrl.vx	v12, v11, a2
	MOV $·pf9f0f641d845caf_LCPI0_5(SB), X12  // lui	a2, %hi(.LCPI0_5)
	MOV (X12), X12  // ld	a2, %lo(.LCPI0_5)(a2)
	WORD $0x969834d7  // vsll.vi	v9, v9, 16
	WORD $0x420065d7  // vmv.s.x	v11, zero
	WORD $0x5e0606d7  // vmv.v.v	v13, v12
	WORD $0x09707057  // vsetvli	zero, zero, e32, mf2, tu, ma
	WORD $0x3ab0b6d7  // vslideup.vi	v13, v11, 1
	WORD $0x0d807057  // vsetvli	zero, zero, e64, m1, ta, ma
	WORD $0x5e0645d7  // vmv.v.x	v11, a2
	WORD $0x00002637  // lui	a2, 2
	WORD $0x7106061b  // addiw	a2, a2, 1808
	WORD $0x96d666d7  // vmul.vx	v13, v13, a2
	WORD $0x0000b637  // lui	a2, 11
	WORD $0x7ff60613  // addi	a2, a2, 2047
	WORD $0xcd727057  // vsetivli	zero, 4, e32, mf2, ta, ma
	WORD $0x0aa68557  // vsub.vv	v10, v10, v13
	WORD $0xc8f17057  // vsetivli	zero, 2, e16, mf2, tu, ma
	WORD $0x3aa0b657  // vslideup.vi	v12, v10, 1
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x96c13557  // vsll.vi	v10, v12, 2
	WORD $0xcce27057  // vsetivli	zero, 4, e16, mf4, ta, ma
	WORD $0xc2a526d7  // vwaddu.vv	v13, v10, v10
	WORD $0xf2a5e6d7  // vwmaccu.vx	v13, a1, v10
	WORD $0xcd717057  // vsetivli	zero, 2, e32, mf2, ta, ma
	WORD $0xc2d6a657  // vwaddu.vv	v12, v13, v13
	WORD $0xf2d5e657  // vwmaccu.vx	v12, a1, v13
	WORD $0x00800593  // li	a1, 8
LBB0_87:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3ec7c6d7  // vslidedown.vx	v13, v12, a5
	WORD $0x42d026d7  // vmv.x.s	a3, v13
	WORD $0x3eb7c6d7  // vslidedown.vx	v13, v11, a5
	WORD $0x42d02757  // vmv.x.s	a4, v13
	WORD $0x03069693  // slli	a3, a3, 48
	WORD $0x00c77733  // and	a4, a4, a2
	WORD $0x0306d693  // srli	a3, a3, 48
	WORD $0x02e686b3  // mul	a3, a3, a4
	WORD $0x0106d693  // srli	a3, a3, 16
	WORD $0x4206e6d7  // vmv.s.x	v13, a3
	WORD $0x00178693  // addi	a3, a5, 1
	WORD $0x08f6f057  // vsetvli	zero, a3, e16, mf2, tu, ma
	WORD $0x3ad7c557  // vslideup.vx	v10, v13, a5
	WORD $0x00068793  // mv	a5, a3
	BNE X13, X11, LBB0_87  // bne	a3, a1, .LBB0_87
	WORD $0x00000593  // li	a1, 0
	WORD $0xc0001637  // lui	a2, 786433
	WORD $0x0000b6b7  // lui	a3, 11
	WORD $0x00661713  // slli	a4, a2, 6
	WORD $0x88068613  // addi	a2, a3, -1920
	WORD $0x00170713  // addi	a4, a4, 1
	WORD $0x01b71713  // slli	a4, a4, 27
	WORD $0x08070693  // addi	a3, a4, 128
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x5e06c657  // vmv.v.x	v12, a3
	WORD $0x00800693  // li	a3, 8
LBB0_89:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3ea5c6d7  // vslidedown.vx	v13, v10, a1
	WORD $0x42d02757  // vmv.x.s	a4, v13
	WORD $0x3ec5c6d7  // vslidedown.vx	v13, v12, a1
	WORD $0x42d027d7  // vmv.x.s	a5, v13
	WORD $0x03071713  // slli	a4, a4, 48
	WORD $0x00c7f7b3  // and	a5, a5, a2
	WORD $0x03075713  // srli	a4, a4, 48
	WORD $0x02f70733  // mul	a4, a4, a5
	WORD $0x01075713  // srli	a4, a4, 16
	WORD $0x420766d7  // vmv.s.x	v13, a4
	WORD $0x00158713  // addi	a4, a1, 1
	WORD $0x08f77057  // vsetvli	zero, a4, e16, mf2, tu, ma
	WORD $0x3ad5c5d7  // vslideup.vx	v11, v13, a1
	WORD $0x00070593  // mv	a1, a4
	BNE X14, X13, LBB0_89  // bne	a4, a3, .LBB0_89
	WORD $0x00000593  // li	a1, 0
	WORD $0x00a00613  // li	a2, 10
	WORD $0x00800693  // li	a3, 8
LBB0_91:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3eb5c657  // vslidedown.vx	v12, v11, a1
	WORD $0x42c02757  // vmv.x.s	a4, v12
	WORD $0x02c70733  // mul	a4, a4, a2
	WORD $0x42076657  // vmv.s.x	v12, a4
	WORD $0x00158713  // addi	a4, a1, 1
	WORD $0x08f77057  // vsetvli	zero, a4, e16, mf2, tu, ma
	WORD $0x3ac5c557  // vslideup.vx	v10, v12, a1
	WORD $0x00070593  // mv	a1, a4
	BNE X14, X13, LBB0_91  // bne	a4, a3, .LBB0_91
	WORD $0xccf47057  // vsetivli	zero, 8, e16, mf2, ta, ma
	WORD $0x0a848457  // vsub.vv	v8, v8, v9
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x96a834d7  // vsll.vi	v9, v10, 16
	WORD $0x03000593  // li	a1, 48
	WORD $0x01050533  // add	a0, a0, a6
	WORD $0xccf47057  // vsetivli	zero, 8, e16, mf2, ta, ma
	WORD $0x0ab484d7  // vsub.vv	v9, v11, v9
	WORD $0xcc887057  // vsetivli	zero, 16, e16, m1, ta, ma
	WORD $0x3a943457  // vslideup.vi	v8, v9, 8
	WORD $0x1e804457  // vmax.vx	v8, v8, zero
	WORD $0x0c707057  // vsetvli	zero, zero, e8, mf2, ta, ma
	WORD $0xba803457  // vnclipu.wi	v8, v8, 0
	WORD $0x0285c457  // vadd.vx	v8, v8, a1
	WORD $0x02050427  // vse8.v	v8, (a0)
	WORD $0x01080593  // addi	a1, a6, 16
	JMP LBB0_9  // j	.LBB0_9
LBB0_93:
	MOV $·pf9f0f641d845caf_LCPI0_1(SB), X13  // lui	a3, %hi(.LCPI0_1)
	MOV (X13), X13  // ld	a3, %lo(.LCPI0_1)(a3)
	MOV $·pf9f0f641d845caf_LCPI0_2(SB), X14  // lui	a4, %hi(.LCPI0_2)
	MOV (X14), X14  // ld	a4, %lo(.LCPI0_2)(a4)
	WORD $0x02d5b6b3  // mulhu	a3, a1, a3
	WORD $0x0336d693  // srli	a3, a3, 51
	BLTU X14, X11, LBB0_95  // bltu	a4, a1, .LBB0_95
	WORD $0x0306e513  // ori	a0, a3, 48
	WORD $0x00a60023  // sb	a0, 0(a2)
	WORD $0x00100813  // li	a6, 1
	JMP LBB0_98  // j	.LBB0_98
LBB0_95:
	MOV $·pf9f0f641d845caf_LCPI0_3(SB), X14  // lui	a4, %hi(.LCPI0_3)
	MOV (X14), X14  // ld	a4, %lo(.LCPI0_3)(a4)
	BLTU X14, X11, LBB0_97  // bltu	a4, a1, .LBB0_97
	WORD $0x00169513  // slli	a0, a3, 1
	MOV $·pf9f0f641d845caf_Digits(SB), X14  // lui	a4, %hi(Digits)
	// addi	a4, a4, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x00e50533  // add	a0, a0, a4
	WORD $0xcc517057  // vsetivli	zero, 2, e8, mf8, ta, ma
	WORD $0x02050407  // vle8.v	v8, (a0)
	WORD $0x02060427  // vse8.v	v8, (a2)
	WORD $0x00200813  // li	a6, 2
	JMP LBB0_98  // j	.LBB0_98
LBB0_97:
	WORD $0x51f00713  // li	a4, 1311
	WORD $0x02e68733  // mul	a4, a3, a4
	WORD $0x01175713  // srli	a4, a4, 17
	WORD $0x03076793  // ori	a5, a4, 48
	WORD $0x00f500a3  // sb	a5, 1(a0)
	WORD $0x06400513  // li	a0, 100
	MOV $·pf9f0f641d845caf_Digits(SB), X15  // lui	a5, %hi(Digits)
	// addi	a5, a5, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x02a70533  // mul	a0, a4, a0
	WORD $0x40a6853b  // subw	a0, a3, a0
	WORD $0x03151513  // slli	a0, a0, 49
	WORD $0x03055513  // srli	a0, a0, 48
	WORD $0x00f50533  // add	a0, a0, a5
	WORD $0xcc517057  // vsetivli	zero, 2, e8, mf8, ta, ma
	WORD $0x02050407  // vle8.v	v8, (a0)
	WORD $0x00160513  // addi	a0, a2, 1
	WORD $0x02050427  // vse8.v	v8, (a0)
	WORD $0x00300813  // li	a6, 3
LBB0_98:
	WORD $0x00000713  // li	a4, 0
	WORD $0x02387537  // lui	a0, 9095
	WORD $0xfff00893  // li	a7, -1
	WORD $0x0208d793  // srli	a5, a7, 32
	WORD $0xcd827057  // vsetivli	zero, 4, e64, m1, ta, ma
	WORD $0x5e07c457  // vmv.v.x	v8, a5
	MOV $·pf9f0f641d845caf_LCPI0_4(SB), X15  // lui	a5, %hi(.LCPI0_4)
	WORD $0xf275051b  // addiw	a0, a0, -217
	WORD $0x00c51513  // slli	a0, a0, 12
	WORD $0xfc150513  // addi	a0, a0, -63
	WORD $0x01051513  // slli	a0, a0, 16
	WORD $0x02a68533  // mul	a0, a3, a0
	WORD $0x000d26b7  // lui	a3, 210
	WORD $0x40a582b3  // sub	t0, a1, a0
	WORD $0x02d00513  // li	a0, 45
	MOV (X15), X15  // ld	a5, %lo(.LCPI0_4)(a5)
	WORD $0xb716869b  // addiw	a3, a3, -1167
	WORD $0x00c69693  // slli	a3, a3, 12
	WORD $0x75968593  // addi	a1, a3, 1881
	WORD $0x02f2b6b3  // mulhu	a3, t0, a5
	WORD $0x01a6d313  // srli	t1, a3, 26
	WORD $0x0d707057  // vsetvli	zero, zero, e32, mf2, ta, ma
	WORD $0x5e0344d7  // vmv.v.x	v9, t1
	WORD $0x3e9064d7  // vslide1down.vx	v9, v9, zero
	WORD $0x3e9064d7  // vslide1down.vx	v9, v9, zero
	WORD $0x3e9064d7  // vslide1down.vx	v9, v9, zero
	WORD $0x26940457  // vand.vv	v8, v9, v8
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x9685e457  // vmul.vx	v8, v8, a1
	MOV $·pf9f0f641d845caf_LCPI0_5(SB), X11  // lui	a1, %hi(.LCPI0_5)
	MOV (X11), X11  // ld	a1, %lo(.LCPI0_5)(a1)
	WORD $0xa2854557  // vsrl.vx	v10, v8, a0
	WORD $0x42006457  // vmv.s.x	v8, zero
	WORD $0x5e0505d7  // vmv.v.v	v11, v10
	WORD $0x09707057  // vsetvli	zero, zero, e32, mf2, tu, ma
	WORD $0x3a80b5d7  // vslideup.vi	v11, v8, 1
	WORD $0x0d807057  // vsetvli	zero, zero, e64, m1, ta, ma
	WORD $0x5e05c457  // vmv.v.x	v8, a1
	WORD $0x00002537  // lui	a0, 2
	WORD $0x7105051b  // addiw	a0, a0, 1808
	WORD $0x96b565d7  // vmul.vx	v11, v11, a0
	WORD $0x0000b537  // lui	a0, 11
	WORD $0x7ff50513  // addi	a0, a0, 2047
	WORD $0xcd727057  // vsetivli	zero, 4, e32, mf2, ta, ma
	WORD $0x0a9584d7  // vsub.vv	v9, v9, v11
	WORD $0xc8f17057  // vsetivli	zero, 2, e16, mf2, tu, ma
	WORD $0x3a90b557  // vslideup.vi	v10, v9, 1
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x96a134d7  // vsll.vi	v9, v10, 2
	WORD $0xcce27057  // vsetivli	zero, 4, e16, mf4, ta, ma
	WORD $0xc294a5d7  // vwaddu.vv	v11, v9, v9
	WORD $0xf298e5d7  // vwmaccu.vx	v11, a7, v9
	WORD $0xcd717057  // vsetivli	zero, 2, e32, mf2, ta, ma
	WORD $0xc2b5a557  // vwaddu.vv	v10, v11, v11
	WORD $0xf2b8e557  // vwmaccu.vx	v10, a7, v11
	WORD $0x00800793  // li	a5, 8
LBB0_99:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3ea745d7  // vslidedown.vx	v11, v10, a4
	WORD $0x42b025d7  // vmv.x.s	a1, v11
	WORD $0x3e8745d7  // vslidedown.vx	v11, v8, a4
	WORD $0x42b026d7  // vmv.x.s	a3, v11
	WORD $0x03059593  // slli	a1, a1, 48
	WORD $0x00a6f6b3  // and	a3, a3, a0
	WORD $0x0305d593  // srli	a1, a1, 48
	WORD $0x02d585b3  // mul	a1, a1, a3
	WORD $0x0105d593  // srli	a1, a1, 16
	WORD $0x4205e5d7  // vmv.s.x	v11, a1
	WORD $0x00170593  // addi	a1, a4, 1
	WORD $0x08f5f057  // vsetvli	zero, a1, e16, mf2, tu, ma
	WORD $0x3ab744d7  // vslideup.vx	v9, v11, a4
	WORD $0x00058713  // mv	a4, a1
	BNE X11, X15, LBB0_99  // bne	a1, a5, .LBB0_99
	WORD $0x00000713  // li	a4, 0
	WORD $0xc0001537  // lui	a0, 786433
	WORD $0x0000b5b7  // lui	a1, 11
	WORD $0x00651693  // slli	a3, a0, 6
	WORD $0x88058513  // addi	a0, a1, -1920
	WORD $0x00168693  // addi	a3, a3, 1
	WORD $0x01b69693  // slli	a3, a3, 27
	WORD $0x08068593  // addi	a1, a3, 128
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x5e05c557  // vmv.v.x	v10, a1
	WORD $0x00800793  // li	a5, 8
LBB0_101:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3e9745d7  // vslidedown.vx	v11, v9, a4
	WORD $0x42b025d7  // vmv.x.s	a1, v11
	WORD $0x3ea745d7  // vslidedown.vx	v11, v10, a4
	WORD $0x42b026d7  // vmv.x.s	a3, v11
	WORD $0x03059593  // slli	a1, a1, 48
	WORD $0x00a6f6b3  // and	a3, a3, a0
	WORD $0x0305d593  // srli	a1, a1, 48
	WORD $0x02d585b3  // mul	a1, a1, a3
	WORD $0x0105d593  // srli	a1, a1, 16
	WORD $0x4205e5d7  // vmv.s.x	v11, a1
	WORD $0x00170593  // addi	a1, a4, 1
	WORD $0x08f5f057  // vsetvli	zero, a1, e16, mf2, tu, ma
	WORD $0x3ab74457  // vslideup.vx	v8, v11, a4
	WORD $0x00058713  // mv	a4, a1
	BNE X11, X15, LBB0_101  // bne	a1, a5, .LBB0_101
	WORD $0x00000513  // li	a0, 0
	WORD $0x00a00713  // li	a4, 10
	WORD $0x00800793  // li	a5, 8
LBB0_103:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3e854557  // vslidedown.vx	v10, v8, a0
	WORD $0x42a025d7  // vmv.x.s	a1, v10
	WORD $0x02e585b3  // mul	a1, a1, a4
	WORD $0x4205e557  // vmv.s.x	v10, a1
	WORD $0x00150593  // addi	a1, a0, 1
	WORD $0x08f5f057  // vsetvli	zero, a1, e16, mf2, tu, ma
	WORD $0x3aa544d7  // vslideup.vx	v9, v10, a0
	WORD $0x00058513  // mv	a0, a1
	BNE X11, X15, LBB0_103  // bne	a1, a5, .LBB0_103
	WORD $0x00000713  // li	a4, 0
	WORD $0x05f5e537  // lui	a0, 24414
	WORD $0xfff00793  // li	a5, -1
	WORD $0x10050513  // addi	a0, a0, 256
	WORD $0x02a30533  // mul	a0, t1, a0
	WORD $0x0207d593  // srli	a1, a5, 32
	WORD $0xcd827057  // vsetivli	zero, 4, e64, m1, ta, ma
	WORD $0x5e05c557  // vmv.v.x	v10, a1
	WORD $0x40a2853b  // subw	a0, t0, a0
	WORD $0x0d707057  // vsetvli	zero, zero, e32, mf2, ta, ma
	WORD $0x5e0545d7  // vmv.v.x	v11, a0
	WORD $0x000d2537  // lui	a0, 210
	WORD $0xb715051b  // addiw	a0, a0, -1167
	WORD $0x00c51513  // slli	a0, a0, 12
	WORD $0x75950513  // addi	a0, a0, 1881
	WORD $0x3eb065d7  // vslide1down.vx	v11, v11, zero
	WORD $0x3eb065d7  // vslide1down.vx	v11, v11, zero
	WORD $0x3eb06657  // vslide1down.vx	v12, v11, zero
	WORD $0x26c50557  // vand.vv	v10, v12, v10
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x96a56557  // vmul.vx	v10, v10, a0
	WORD $0x02d00513  // li	a0, 45
	WORD $0xa2a54557  // vsrl.vx	v10, v10, a0
	MOV $·pf9f0f641d845caf_LCPI0_5(SB), X10  // lui	a0, %hi(.LCPI0_5)
	MOV (X10), X10  // ld	a0, %lo(.LCPI0_5)(a0)
	WORD $0x969834d7  // vsll.vi	v9, v9, 16
	WORD $0x420065d7  // vmv.s.x	v11, zero
	WORD $0x5e0506d7  // vmv.v.v	v13, v10
	WORD $0x09707057  // vsetvli	zero, zero, e32, mf2, tu, ma
	WORD $0x3ab0b6d7  // vslideup.vi	v13, v11, 1
	WORD $0x0d807057  // vsetvli	zero, zero, e64, m1, ta, ma
	WORD $0x5e0545d7  // vmv.v.x	v11, a0
	WORD $0x00002537  // lui	a0, 2
	WORD $0x7105051b  // addiw	a0, a0, 1808
	WORD $0x96d566d7  // vmul.vx	v13, v13, a0
	WORD $0x0000b537  // lui	a0, 11
	WORD $0x7ff50513  // addi	a0, a0, 2047
	WORD $0xcd727057  // vsetivli	zero, 4, e32, mf2, ta, ma
	WORD $0x0ac68657  // vsub.vv	v12, v12, v13
	WORD $0xc8f17057  // vsetivli	zero, 2, e16, mf2, tu, ma
	WORD $0x3ac0b557  // vslideup.vi	v10, v12, 1
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x96a13557  // vsll.vi	v10, v10, 2
	WORD $0xcce27057  // vsetivli	zero, 4, e16, mf4, ta, ma
	WORD $0xc2a526d7  // vwaddu.vv	v13, v10, v10
	WORD $0xf2a7e6d7  // vwmaccu.vx	v13, a5, v10
	WORD $0xcd717057  // vsetivli	zero, 2, e32, mf2, ta, ma
	WORD $0xc2d6a657  // vwaddu.vv	v12, v13, v13
	WORD $0xf2d7e657  // vwmaccu.vx	v12, a5, v13
	WORD $0x00800593  // li	a1, 8
LBB0_105:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3ec746d7  // vslidedown.vx	v13, v12, a4
	WORD $0x42d026d7  // vmv.x.s	a3, v13
	WORD $0x3eb746d7  // vslidedown.vx	v13, v11, a4
	WORD $0x42d027d7  // vmv.x.s	a5, v13
	WORD $0x03069693  // slli	a3, a3, 48
	WORD $0x00a7f7b3  // and	a5, a5, a0
	WORD $0x0306d693  // srli	a3, a3, 48
	WORD $0x02f686b3  // mul	a3, a3, a5
	WORD $0x0106d693  // srli	a3, a3, 16
	WORD $0x4206e6d7  // vmv.s.x	v13, a3
	WORD $0x00170693  // addi	a3, a4, 1
	WORD $0x08f6f057  // vsetvli	zero, a3, e16, mf2, tu, ma
	WORD $0x3ad74557  // vslideup.vx	v10, v13, a4
	WORD $0x00068713  // mv	a4, a3
	BNE X13, X11, LBB0_105  // bne	a3, a1, .LBB0_105
	WORD $0x00000593  // li	a1, 0
	WORD $0xc0001537  // lui	a0, 786433
	WORD $0x0000b6b7  // lui	a3, 11
	WORD $0x00651713  // slli	a4, a0, 6
	WORD $0x88068513  // addi	a0, a3, -1920
	WORD $0x00170713  // addi	a4, a4, 1
	WORD $0x01b71713  // slli	a4, a4, 27
	WORD $0x08070693  // addi	a3, a4, 128
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x5e06c657  // vmv.v.x	v12, a3
	WORD $0x00800693  // li	a3, 8
LBB0_107:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3ea5c6d7  // vslidedown.vx	v13, v10, a1
	WORD $0x42d02757  // vmv.x.s	a4, v13
	WORD $0x3ec5c6d7  // vslidedown.vx	v13, v12, a1
	WORD $0x42d027d7  // vmv.x.s	a5, v13
	WORD $0x03071713  // slli	a4, a4, 48
	WORD $0x00a7f7b3  // and	a5, a5, a0
	WORD $0x03075713  // srli	a4, a4, 48
	WORD $0x02f70733  // mul	a4, a4, a5
	WORD $0x01075713  // srli	a4, a4, 16
	WORD $0x420766d7  // vmv.s.x	v13, a4
	WORD $0x00158713  // addi	a4, a1, 1
	WORD $0x08f77057  // vsetvli	zero, a4, e16, mf2, tu, ma
	WORD $0x3ad5c5d7  // vslideup.vx	v11, v13, a1
	WORD $0x00070593  // mv	a1, a4
	BNE X14, X13, LBB0_107  // bne	a4, a3, .LBB0_107
	WORD $0x00000513  // li	a0, 0
	WORD $0x00a00593  // li	a1, 10
	WORD $0x00800693  // li	a3, 8
LBB0_109:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3eb54657  // vslidedown.vx	v12, v11, a0
	WORD $0x42c02757  // vmv.x.s	a4, v12
	WORD $0x02b70733  // mul	a4, a4, a1
	WORD $0x42076657  // vmv.s.x	v12, a4
	WORD $0x00150713  // addi	a4, a0, 1
	WORD $0x08f77057  // vsetvli	zero, a4, e16, mf2, tu, ma
	WORD $0x3ac54557  // vslideup.vx	v10, v12, a0
	WORD $0x00070513  // mv	a0, a4
	BNE X14, X13, LBB0_109  // bne	a4, a3, .LBB0_109
	WORD $0xccf47057  // vsetivli	zero, 8, e16, mf2, ta, ma
	WORD $0x0a848457  // vsub.vv	v8, v8, v9
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x96a834d7  // vsll.vi	v9, v10, 16
	WORD $0x03000513  // li	a0, 48
	WORD $0x01060633  // add	a2, a2, a6
	WORD $0xccf47057  // vsetivli	zero, 8, e16, mf2, ta, ma
	WORD $0x0ab484d7  // vsub.vv	v9, v11, v9
	WORD $0xcc887057  // vsetivli	zero, 16, e16, m1, ta, ma
	WORD $0x3a943457  // vslideup.vi	v8, v9, 8
	WORD $0x1e804457  // vmax.vx	v8, v8, zero
	WORD $0x0c707057  // vsetvli	zero, zero, e8, mf2, ta, ma
	WORD $0xba803457  // vnclipu.wi	v8, v8, 0
	WORD $0x02854457  // vadd.vx	v8, v8, a0
	WORD $0x02060427  // vse8.v	v8, (a2)
	WORD $0x01080593  // addi	a1, a6, 16
	JMP LBB0_22  // j	.LBB0_22
Lfunc_end0:


TEXT ·__i64toa(SB), NOSPLIT, $0-24
	NO_LOCAL_POINTERS

_entry___i64toa:
	MOV 16(g), X31      // g.stack.hi
	ADD $-64, SP, X30
	BLTU X30, X31, _stack_grow___i64toa

___i64toa:
	MOV out+0(FP), X10
	MOV val+8(FP), X11
	CALL ·__i64toa_riscv64_entry__(SB)
	MOV X10, ret+16(FP)
	RET

_stack_grow___i64toa:
	MOV X1, X3      // Save return address (RA)
	CALL runtime·morestack_noctxt(SB)
	JMP _entry___i64toa

// Data section
GLOBL ·pf9f0f641d845caf_LCPI0_0(SB), RODATA, $8
DATA ·pf9f0f641d845caf_LCPI0_0+0(SB)/8, $0x002386f26fc0ffff
GLOBL ·pf9f0f641d845caf_LCPI0_1(SB), RODATA, $8
DATA ·pf9f0f641d845caf_LCPI0_1+0(SB)/8, $0x39a5652fb1137857
GLOBL ·pf9f0f641d845caf_LCPI0_2(SB), RODATA, $8
DATA ·pf9f0f641d845caf_LCPI0_2+0(SB)/8, $0x016345785d89ffff
GLOBL ·pf9f0f641d845caf_LCPI0_3(SB), RODATA, $8
DATA ·pf9f0f641d845caf_LCPI0_3+0(SB)/8, $0x0de0b6b3a763ffff
GLOBL ·pf9f0f641d845caf_LCPI0_4(SB), RODATA, $8
DATA ·pf9f0f641d845caf_LCPI0_4+0(SB)/8, $0xabcc77118461cefd
GLOBL ·pf9f0f641d845caf_LCPI0_5(SB), RODATA, $8
DATA ·pf9f0f641d845caf_LCPI0_5+0(SB)/8, $0x80003334147b20c5
GLOBL ·pf9f0f641d845caf_LCPI0_6(SB), RODATA, $32
DATA ·pf9f0f641d845caf_LCPI0_6+0(SB)/8, $0x03180e1d021c0100
DATA ·pf9f0f641d845caf_LCPI0_6+8(SB)/8, $0x080411190f14161e
DATA ·pf9f0f641d845caf_LCPI0_6+16(SB)/8, $0x07101315170d1b1f
DATA ·pf9f0f641d845caf_LCPI0_6+24(SB)/8, $0x090a050b06120c1a
GLOBL ·pf9f0f641d845caf_Digits(SB), RODATA, $200
DATA ·pf9f0f641d845caf_Digits+0(SB)/8, $0x3330323031303030
DATA ·pf9f0f641d845caf_Digits+8(SB)/8, $0x3730363035303430
DATA ·pf9f0f641d845caf_Digits+16(SB)/8, $0x3131303139303830
DATA ·pf9f0f641d845caf_Digits+24(SB)/8, $0x3531343133313231
DATA ·pf9f0f641d845caf_Digits+32(SB)/8, $0x3931383137313631
DATA ·pf9f0f641d845caf_Digits+40(SB)/8, $0x3332323231323032
DATA ·pf9f0f641d845caf_Digits+48(SB)/8, $0x3732363235323432
DATA ·pf9f0f641d845caf_Digits+56(SB)/8, $0x3133303339323832
DATA ·pf9f0f641d845caf_Digits+64(SB)/8, $0x3533343333333233
DATA ·pf9f0f641d845caf_Digits+72(SB)/8, $0x3933383337333633
DATA ·pf9f0f641d845caf_Digits+80(SB)/8, $0x3334323431343034
DATA ·pf9f0f641d845caf_Digits+88(SB)/8, $0x3734363435343434
DATA ·pf9f0f641d845caf_Digits+96(SB)/8, $0x3135303539343834
DATA ·pf9f0f641d845caf_Digits+104(SB)/8, $0x3535343533353235
DATA ·pf9f0f641d845caf_Digits+112(SB)/8, $0x3935383537353635
DATA ·pf9f0f641d845caf_Digits+120(SB)/8, $0x3336323631363036
DATA ·pf9f0f641d845caf_Digits+128(SB)/8, $0x3736363635363436
DATA ·pf9f0f641d845caf_Digits+136(SB)/8, $0x3137303739363836
DATA ·pf9f0f641d845caf_Digits+144(SB)/8, $0x3537343733373237
DATA ·pf9f0f641d845caf_Digits+152(SB)/8, $0x3937383737373637
DATA ·pf9f0f641d845caf_Digits+160(SB)/8, $0x3338323831383038
DATA ·pf9f0f641d845caf_Digits+168(SB)/8, $0x3738363835383438
DATA ·pf9f0f641d845caf_Digits+176(SB)/8, $0x3139303939383838
DATA ·pf9f0f641d845caf_Digits+184(SB)/8, $0x3539343933393239
DATA ·pf9f0f641d845caf_Digits+192(SB)/8, $0x3939383937393639
GLOBL ·pf9f0f641d845caf_VecShiftShuffles(SB), RODATA, $144
DATA ·pf9f0f641d845caf_VecShiftShuffles+0(SB)/8, $0x0706050403020100
DATA ·pf9f0f641d845caf_VecShiftShuffles+8(SB)/8, $0x0f0e0d0c0b0a0908
DATA ·pf9f0f641d845caf_VecShiftShuffles+16(SB)/8, $0x0807060504030201
DATA ·pf9f0f641d845caf_VecShiftShuffles+24(SB)/8, $0xff0f0e0d0c0b0a09
DATA ·pf9f0f641d845caf_VecShiftShuffles+32(SB)/8, $0x0908070605040302
DATA ·pf9f0f641d845caf_VecShiftShuffles+40(SB)/8, $0xffff0f0e0d0c0b0a
DATA ·pf9f0f641d845caf_VecShiftShuffles+48(SB)/8, $0x0a09080706050403
DATA ·pf9f0f641d845caf_VecShiftShuffles+56(SB)/8, $0xffffff0f0e0d0c0b
DATA ·pf9f0f641d845caf_VecShiftShuffles+64(SB)/8, $0x0b0a090807060504
DATA ·pf9f0f641d845caf_VecShiftShuffles+72(SB)/8, $0xffffffff0f0e0d0c
DATA ·pf9f0f641d845caf_VecShiftShuffles+80(SB)/8, $0x0c0b0a0908070605
DATA ·pf9f0f641d845caf_VecShiftShuffles+88(SB)/8, $0xffffffffff0f0e0d
DATA ·pf9f0f641d845caf_VecShiftShuffles+96(SB)/8, $0x0d0c0b0a09080706
DATA ·pf9f0f641d845caf_VecShiftShuffles+104(SB)/8, $0xffffffffffff0f0e
DATA ·pf9f0f641d845caf_VecShiftShuffles+112(SB)/8, $0x0e0d0c0b0a090807
DATA ·pf9f0f641d845caf_VecShiftShuffles+120(SB)/8, $0xffffffffffffff0f
DATA ·pf9f0f641d845caf_VecShiftShuffles+128(SB)/8, $0x0f0e0d0c0b0a0908
DATA ·pf9f0f641d845caf_VecShiftShuffles+136(SB)/8, $0xffffffffffffffff
