// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

#include "go_asm.h"
#include "funcdata.h"
#include "textflag.h"

TEXT ·__lookup_small_key_entry__(SB), $0-8
	MOV $·__lookup_small_key_riscv64_entry__(SB), A0
	MOV A0, ret+0(FP)
	RET

TEXT ·__lookup_small_key_riscv64_entry__(SB), $48
	NO_LOCAL_POINTERS
lookup_small_key:
	WORD $0xfc010113  // addi	sp, sp, -64
	WORD $0x02813c23  // sd	s0, 56(sp)
	WORD $0x02913823  // sd	s1, 48(sp)
	WORD $0x03213423  // sd	s2, 40(sp)
	WORD $0x00853683  // ld	a3, 8(a0)
	WORD $0x0005b803  // ld	a6, 0(a1)
	WORD $0x0ff6f293  // andi	t0, a3, 255
	WORD $0x00229593  // slli	a1, t0, 2
	WORD $0x005806b3  // add	a3, a6, t0
	WORD $0x00d585b3  // add	a1, a1, a3
	WORD $0x00053f03  // ld	t5, 0(a0)
	WORD $0x0005c383  // lbu	t2, 0(a1)
	WORD $0x0015e883  // lwu	a7, 1(a1)
	WORD $0xcd827057  // vsetivli	zero, 4, e64, m1, ta, ma
	WORD $0x5e003457  // vmv.v.i	v8, 0
	WORD $0x00010513  // mv	a0, sp
	WORD $0x02850427  // vs1r.v	v8, (a0)
	BEQZ X7, LBB0_41  // beqz	t2, .LBB0_41
	WORD $0x0a588513  // addi	a0, a7, 165
	WORD $0x00900593  // li	a1, 9
	WORD $0x02051513  // slli	a0, a0, 32
	WORD $0x02055513  // srli	a0, a0, 32
	WORD $0x00a80933  // add	s2, a6, a0
	WORD $0x00128313  // addi	t1, t0, 1
	BGEU X5, X11, LBB0_9  // bgeu	t0, a1, .LBB0_9
	WORD $0x00000593  // li	a1, 0
LBB0_3:
	WORD $0x00000693  // li	a3, 0
	WORD $0x00800713  // li	a4, 8
	WORD $0x000f0793  // mv	a5, t5
	WORD $0x00090513  // mv	a0, s2
LBB0_4:
	WORD $0x00054403  // lbu	s0, 0(a0)
	WORD $0x0007c483  // lbu	s1, 0(a5)
	BNE X8, X9, LBB0_7  // bne	s0, s1, .LBB0_7
	WORD $0x0016869b  // addiw	a3, a3, 1
	WORD $0x00150513  // addi	a0, a0, 1
	WORD $0xfff70713  // addi	a4, a4, -1
	WORD $0x00178793  // addi	a5, a5, 1
	BNEZ X14, LBB0_4  // bnez	a4, .LBB0_4
	WORD $0x00800693  // li	a3, 8
LBB0_7:
	BGEU X13, X5, LBB0_33  // bgeu	a3, t0, .LBB0_33
	WORD $0x0015859b  // addiw	a1, a1, 1
	WORD $0x00690933  // add	s2, s2, t1
	BNE X11, X7, LBB0_3  // bne	a1, t2, .LBB0_3
	JMP LBB0_16  // j	.LBB0_16
LBB0_9:
	WORD $0x00000f93  // li	t6, 0
	WORD $0x00010e37  // lui	t3, 16
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x020f0407  // vle8.v	v8, (t5)
	WORD $0x010f0513  // addi	a0, t5, 16
	WORD $0x02050487  // vle8.v	v9, (a0)
	WORD $0xfffe0e13  // addi	t3, t3, -1
	WORD $0xfff00713  // li	a4, -1
	WORD $0x00571eb3  // sll	t4, a4, t0
LBB0_10:
	WORD $0x00000693  // li	a3, 0
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x02090587  // vle8.v	v11, (s2)
	WORD $0x01090513  // addi	a0, s2, 16
	WORD $0x02050507  // vle8.v	v10, (a0)
	WORD $0x00f00793  // li	a5, 15
	WORD $0x00f00593  // li	a1, 15
LBB0_11:
	WORD $0xcc70f057  // vsetivli	zero, 1, e8, mf2, ta, ma
	WORD $0x3eb5c657  // vslidedown.vx	v12, v11, a1
	WORD $0x42c02557  // vmv.x.s	a0, v12
	WORD $0x3e85c657  // vslidedown.vx	v12, v8, a1
	WORD $0xfff58593  // addi	a1, a1, -1
	WORD $0x42c02457  // vmv.x.s	s0, v12
	WORD $0x0ff57513  // andi	a0, a0, 255
	WORD $0x0ff47413  // andi	s0, s0, 255
	WORD $0x00854533  // xor	a0, a0, s0
	WORD $0x00153513  // seqz	a0, a0
	WORD $0x00f5153b  // sllw	a0, a0, a5
	WORD $0x00a6e6b3  // or	a3, a3, a0
	WORD $0xfff78793  // addi	a5, a5, -1
	BNE X11, X14, LBB0_11  // bne	a1, a4, .LBB0_11
	WORD $0x00000793  // li	a5, 0
	WORD $0x00f00593  // li	a1, 15
	WORD $0x00f00413  // li	s0, 15
LBB0_13:
	WORD $0x3ea445d7  // vslidedown.vx	v11, v10, s0
	WORD $0x42b02557  // vmv.x.s	a0, v11
	WORD $0x3e9445d7  // vslidedown.vx	v11, v9, s0
	WORD $0xfff40413  // addi	s0, s0, -1
	WORD $0x42b024d7  // vmv.x.s	s1, v11
	WORD $0x0ff57513  // andi	a0, a0, 255
	WORD $0x0ff4f493  // andi	s1, s1, 255
	WORD $0x00954533  // xor	a0, a0, s1
	WORD $0x00153513  // seqz	a0, a0
	WORD $0x00b5153b  // sllw	a0, a0, a1
	WORD $0x00a7e7b3  // or	a5, a5, a0
	WORD $0xfff58593  // addi	a1, a1, -1
	BNE X8, X14, LBB0_13  // bne	s0, a4, .LBB0_13
	WORD $0x01c6f533  // and	a0, a3, t3
	WORD $0x01079793  // slli	a5, a5, 16
	WORD $0x01d56533  // or	a0, a0, t4
	WORD $0x00f56533  // or	a0, a0, a5
	WORD $0x0005051b  // sext.w	a0, a0
	BEQ X10, X14, LBB0_33  // beq	a0, a4, .LBB0_33
	WORD $0x001f8f9b  // addiw	t6, t6, 1
	WORD $0x00690933  // add	s2, s2, t1
	BNE X31, X7, LBB0_10  // bne	t6, t2, .LBB0_10
LBB0_16:
	WORD $0xfff00513  // li	a0, -1
	BEQ X12, X10, LBB0_44  // beq	a2, a0, .LBB0_44
	WORD $0x00000593  // li	a1, 0
	WORD $0x01180833  // add	a6, a6, a7
	WORD $0x04000693  // li	a3, 64
	WORD $0x0c007757  // vsetvli	a4, zero, e8, m1, ta, ma
	WORD $0x4206e4d7  // vmv.s.x	v9, a3
	WORD $0x01000693  // li	a3, 16
LBB0_18:
	WORD $0x00158713  // addi	a4, a1, 1
	WORD $0x08777057  // vsetvli	zero, a4, e8, mf2, tu, ma
	WORD $0x3a95c457  // vslideup.vx	v8, v9, a1
	WORD $0x00070593  // mv	a1, a4
	BNE X14, X13, LBB0_18  // bne	a4, a3, .LBB0_18
	WORD $0x00000593  // li	a1, 0
	WORD $0x05b00693  // li	a3, 91
	WORD $0x0c707757  // vsetvli	a4, zero, e8, mf2, ta, ma
	WORD $0x4206e557  // vmv.s.x	v10, a3
	WORD $0x01000693  // li	a3, 16
LBB0_20:
	WORD $0x00158713  // addi	a4, a1, 1
	WORD $0x08777057  // vsetvli	zero, a4, e8, mf2, tu, ma
	WORD $0x3aa5c4d7  // vslideup.vx	v9, v10, a1
	WORD $0x00070593  // mv	a1, a4
	BNE X14, X13, LBB0_20  // bne	a4, a3, .LBB0_20
	WORD $0x00000593  // li	a1, 0
	WORD $0x02000693  // li	a3, 32
	WORD $0x0c707757  // vsetvli	a4, zero, e8, mf2, ta, ma
	WORD $0x4206e5d7  // vmv.s.x	v11, a3
	WORD $0x01000693  // li	a3, 16
LBB0_22:
	WORD $0x00158713  // addi	a4, a1, 1
	WORD $0x08777057  // vsetvli	zero, a4, e8, mf2, tu, ma
	WORD $0x3ab5c557  // vslideup.vx	v10, v11, a1
	WORD $0x00070593  // mv	a1, a4
	BNE X14, X13, LBB0_22  // bne	a4, a3, .LBB0_22
	WORD $0x00010593  // mv	a1, sp
	WORD $0x02010693  // addi	a3, sp, 32
LBB0_24:
	WORD $0xc4787057  // vsetivli	zero, 16, e8, mf2, ta, mu
	WORD $0x020f0587  // vle8.v	v11, (t5)
	WORD $0x6e858657  // vmslt.vv	v12, v8, v11
	WORD $0x6eb486d7  // vmslt.vv	v13, v11, v9
	WORD $0x66c6a057  // vmand.mm	v0, v12, v13
	WORD $0x00b505d7  // vadd.vv	v11, v11, v10, v0.t
	WORD $0x020585a7  // vse8.v	v11, (a1)
	WORD $0x01058593  // addi	a1, a1, 16
	WORD $0x010f0f13  // addi	t5, t5, 16
	BNE X11, X13, LBB0_24  // bne	a1, a3, .LBB0_24
	WORD $0x00900593  // li	a1, 9
	WORD $0x00c80e33  // add	t3, a6, a2
	BGEU X5, X11, LBB0_34  // bgeu	t0, a1, .LBB0_34
	WORD $0x00000593  // li	a1, 0
	WORD $0x0013b613  // seqz	a2, t2
	WORD $0x00c3883b  // addw	a6, t2, a2
LBB0_27:
	WORD $0x00000713  // li	a4, 0
	WORD $0x00010793  // mv	a5, sp
	WORD $0x00800413  // li	s0, 8
	WORD $0x000e0613  // mv	a2, t3
LBB0_28:
	WORD $0x00064683  // lbu	a3, 0(a2)
	WORD $0x0007c483  // lbu	s1, 0(a5)
	BNE X13, X9, LBB0_31  // bne	a3, s1, .LBB0_31
	WORD $0x0017071b  // addiw	a4, a4, 1
	WORD $0x00160613  // addi	a2, a2, 1
	WORD $0xfff40413  // addi	s0, s0, -1
	WORD $0x00178793  // addi	a5, a5, 1
	BNEZ X8, LBB0_28  // bnez	s0, .LBB0_28
	WORD $0x00800713  // li	a4, 8
LBB0_31:
	BGEU X14, X5, LBB0_42  // bgeu	a4, t0, .LBB0_42
	WORD $0x0015859b  // addiw	a1, a1, 1
	WORD $0x006e0e33  // add	t3, t3, t1
	BNE X11, X16, LBB0_27  // bne	a1, a6, .LBB0_27
	JMP LBB0_44  // j	.LBB0_44
LBB0_33:
	WORD $0x012282b3  // add	t0, t0, s2
	JMP LBB0_43  // j	.LBB0_43
LBB0_34:
	WORD $0x00000513  // li	a0, 0
	WORD $0x00010837  // lui	a6, 16
	WORD $0x00010593  // mv	a1, sp
	WORD $0x01010613  // addi	a2, sp, 16
	WORD $0xfff80813  // addi	a6, a6, -1
	WORD $0x02058407  // vle8.v	v8, (a1)
	WORD $0x02060487  // vle8.v	v9, (a2)
	WORD $0xfff00693  // li	a3, -1
	WORD $0x0013b593  // seqz	a1, t2
	WORD $0x00b388bb  // addw	a7, t2, a1
	WORD $0x005693b3  // sll	t2, a3, t0
LBB0_35:
	WORD $0x00000593  // li	a1, 0
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x020e0587  // vle8.v	v11, (t3)
	WORD $0x010e0613  // addi	a2, t3, 16
	WORD $0x02060507  // vle8.v	v10, (a2)
	WORD $0x00f00713  // li	a4, 15
	WORD $0x00f00793  // li	a5, 15
LBB0_36:
	WORD $0xcc70f057  // vsetivli	zero, 1, e8, mf2, ta, ma
	WORD $0x3eb7c657  // vslidedown.vx	v12, v11, a5
	WORD $0x42c02657  // vmv.x.s	a2, v12
	WORD $0x3e87c657  // vslidedown.vx	v12, v8, a5
	WORD $0xfff78793  // addi	a5, a5, -1
	WORD $0x42c024d7  // vmv.x.s	s1, v12
	WORD $0x0ff67613  // andi	a2, a2, 255
	WORD $0x0ff4f493  // andi	s1, s1, 255
	WORD $0x00964633  // xor	a2, a2, s1
	WORD $0x00163613  // seqz	a2, a2
	WORD $0x00e6163b  // sllw	a2, a2, a4
	WORD $0x00c5e5b3  // or	a1, a1, a2
	WORD $0xfff70713  // addi	a4, a4, -1
	BNE X15, X13, LBB0_36  // bne	a5, a3, .LBB0_36
	WORD $0x00000713  // li	a4, 0
	WORD $0x00f00793  // li	a5, 15
	WORD $0x00f00413  // li	s0, 15
LBB0_38:
	WORD $0x3ea445d7  // vslidedown.vx	v11, v10, s0
	WORD $0x42b02657  // vmv.x.s	a2, v11
	WORD $0x3e9445d7  // vslidedown.vx	v11, v9, s0
	WORD $0xfff40413  // addi	s0, s0, -1
	WORD $0x42b024d7  // vmv.x.s	s1, v11
	WORD $0x0ff67613  // andi	a2, a2, 255
	WORD $0x0ff4f493  // andi	s1, s1, 255
	WORD $0x00964633  // xor	a2, a2, s1
	WORD $0x00163613  // seqz	a2, a2
	WORD $0x00f6163b  // sllw	a2, a2, a5
	WORD $0x00c76733  // or	a4, a4, a2
	WORD $0xfff78793  // addi	a5, a5, -1
	BNE X8, X13, LBB0_38  // bne	s0, a3, .LBB0_38
	WORD $0x0105f5b3  // and	a1, a1, a6
	WORD $0x01071713  // slli	a4, a4, 16
	WORD $0x0075e5b3  // or	a1, a1, t2
	WORD $0x00e5e5b3  // or	a1, a1, a4
	WORD $0x0005859b  // sext.w	a1, a1
	BEQ X11, X13, LBB0_42  // beq	a1, a3, .LBB0_42
	WORD $0x0015051b  // addiw	a0, a0, 1
	WORD $0x006e0e33  // add	t3, t3, t1
	BNE X10, X17, LBB0_35  // bne	a0, a7, .LBB0_35
LBB0_41:
	WORD $0xfff00513  // li	a0, -1
	JMP LBB0_44  // j	.LBB0_44
LBB0_42:
	WORD $0x01c282b3  // add	t0, t0, t3
LBB0_43:
	WORD $0x0002c503  // lbu	a0, 0(t0)
LBB0_44:
	WORD $0x03813403  // ld	s0, 56(sp)
	WORD $0x03013483  // ld	s1, 48(sp)
	WORD $0x02813903  // ld	s2, 40(sp)
	WORD $0x04010113  // addi	sp, sp, 64
	RET  // ret
Lfunc_end0:


TEXT ·__lookup_small_key(SB), $0-32
	NO_LOCAL_POINTERS
___lookup_small_key:
	MOV key+0(FP), X10
	MOV table+8(FP), X11
	MOV lowerOff+16(FP), X12
	CALL ·__lookup_small_key_riscv64_entry__(SB)
	MOV X10, ret+24(FP)
	RET
