// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

#include "go_asm.h"
#include "funcdata.h"
#include "textflag.h"

TEXT ·__lspace_entry__(SB), $0-8
	MOV $·__lspace_riscv64_entry__(SB), A0
	MOV A0, ret+0(FP)
	RET

TEXT ·__lspace_riscv64_entry__(SB), $0
	NO_LOCAL_POINTERS
lspace:
	WORD $0x00c506b3  // add	a3, a0, a2
	BEQ X11, X12, LBB0_6  // beq	a1, a2, .LBB0_6
	WORD $0x00b50833  // add	a6, a0, a1
	WORD $0x40b007b3  // neg	a5, a1
	WORD $0x40c005b3  // neg	a1, a2
	WORD $0x02000893  // li	a7, 32
	WORD $0x00800637  // lui	a2, 2048
	WORD $0x0136061b  // addiw	a2, a2, 19
	WORD $0x00961713  // slli	a4, a2, 9
LBB0_2:
	WORD $0x0006c603  // lbu	a2, 0(a3)
	BLTU X17, X12, LBB0_7  // bltu	a7, a2, .LBB0_7
	WORD $0x00c75633  // srl	a2, a4, a2
	WORD $0x00167613  // andi	a2, a2, 1
	BEQZ X12, LBB0_7  // beqz	a2, .LBB0_7
	WORD $0xfff58593  // addi	a1, a1, -1
	WORD $0x00168693  // addi	a3, a3, 1
	BNE X15, X11, LBB0_2  // bne	a5, a1, .LBB0_2
	WORD $0x00080693  // mv	a3, a6
LBB0_6:
	WORD $0x40a68533  // sub	a0, a3, a0
	RET  // ret
LBB0_7:
	WORD $0x40b00533  // neg	a0, a1
	RET  // ret
Lfunc_end0:


TEXT ·__lspace(SB), $0-32
	NO_LOCAL_POINTERS
___lspace:
	MOV sp+0(FP), X10
	MOV nb+8(FP), X11
	MOV off+16(FP), X12
	CALL ·__lspace_riscv64_entry__(SB)
	MOV X10, ret+24(FP)
	RET
