// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package rvv

//go:nosplit
//go:noescape
//goland:noinspection ALL
func __quote_entry__() uintptr

var (
    _subr__quote uintptr = __quote_entry__() + 0
)

const (
    _stack__quote = 144
)

var (
    _ = _subr__quote
)

const (
    _ = _stack__quote
)
