// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package rvv

//go:nosplit
//go:noescape
//goland:noinspection ALL
func __skip_number_entry__() uintptr

var (
    _subr__skip_number uintptr = __skip_number_entry__() + 0
)

const (
    _stack__skip_number = 80
)

var (
    _ = _subr__skip_number
)

const (
    _ = _stack__skip_number
)
