// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package rvv

//go:nosplit
//go:noescape
//goland:noinspection ALL
func __skip_array_entry__() uintptr

var (
    _subr__skip_array uintptr = __skip_array_entry__() + 0
)

const (
    _stack__skip_array = 448
)

var (
    _ = _subr__skip_array
)

const (
    _ = _stack__skip_array
)
