// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

#include "go_asm.h"
#include "funcdata.h"
#include "textflag.h"

TEXT ·__skip_one_fast_entry__(SB), $0-8
	MOV $·__skip_one_fast_riscv64_entry__(SB), A0
	MOV A0, ret+0(FP)
	RET

TEXT ·__skip_one_fast_riscv64_entry__(SB), $272
	NO_LOCAL_POINTERS
skip_one_fast:
	WORD $0xee010113  // addi	sp, sp, -288
	WORD $0x10113c23  // sd	ra, 280(sp)
	WORD $0x10813823  // sd	s0, 272(sp)
	WORD $0x10913423  // sd	s1, 264(sp)
	WORD $0x11213023  // sd	s2, 256(sp)
	WORD $0x0f313c23  // sd	s3, 248(sp)
	WORD $0x0f413823  // sd	s4, 240(sp)
	WORD $0x0f513423  // sd	s5, 232(sp)
	WORD $0x0f613023  // sd	s6, 224(sp)
	WORD $0x0d713c23  // sd	s7, 216(sp)
	WORD $0x0d813823  // sd	s8, 208(sp)
	WORD $0x0d913423  // sd	s9, 200(sp)
	WORD $0x0da13023  // sd	s10, 192(sp)
	WORD $0x0bb13c23  // sd	s11, 184(sp)
	WORD $0x00058913  // mv	s2, a1
	WORD $0x0005b603  // ld	a2, 0(a1)
	WORD $0x00853803  // ld	a6, 8(a0)
	WORD $0x00053e83  // ld	t4, 0(a0)
	BGEU X12, X16, LBB0_5  // bgeu	a2, a6, .LBB0_5
	WORD $0x00ce86b3  // add	a3, t4, a2
	WORD $0x0006c703  // lbu	a4, 0(a3)
	WORD $0x00d00693  // li	a3, 13
	BEQ X14, X13, LBB0_5  // beq	a4, a3, .LBB0_5
	WORD $0x02000693  // li	a3, 32
	BEQ X14, X13, LBB0_5  // beq	a4, a3, .LBB0_5
	WORD $0xff570713  // addi	a4, a4, -11
	WORD $0xffe00693  // li	a3, -2
	BGEU X14, X13, LBB0_5  // bgeu	a4, a3, .LBB0_5
	WORD $0x00060993  // mv	s3, a2
	JMP LBB0_25  // j	.LBB0_25
LBB0_5:
	WORD $0x00160993  // addi	s3, a2, 1
	BGEU X19, X16, LBB0_9  // bgeu	s3, a6, .LBB0_9
	WORD $0x013e86b3  // add	a3, t4, s3
	WORD $0x0006c703  // lbu	a4, 0(a3)
	WORD $0x00d00693  // li	a3, 13
	BEQ X14, X13, LBB0_9  // beq	a4, a3, .LBB0_9
	WORD $0x02000693  // li	a3, 32
	BEQ X14, X13, LBB0_9  // beq	a4, a3, .LBB0_9
	WORD $0xff570713  // addi	a4, a4, -11
	WORD $0xffe00693  // li	a3, -2
	BLTU X14, X13, LBB0_25  // bltu	a4, a3, .LBB0_25
LBB0_9:
	WORD $0x00260993  // addi	s3, a2, 2
	BGEU X19, X16, LBB0_13  // bgeu	s3, a6, .LBB0_13
	WORD $0x013e86b3  // add	a3, t4, s3
	WORD $0x0006c703  // lbu	a4, 0(a3)
	WORD $0x00d00693  // li	a3, 13
	BEQ X14, X13, LBB0_13  // beq	a4, a3, .LBB0_13
	WORD $0x02000693  // li	a3, 32
	BEQ X14, X13, LBB0_13  // beq	a4, a3, .LBB0_13
	WORD $0xff570713  // addi	a4, a4, -11
	WORD $0xffe00693  // li	a3, -2
	BLTU X14, X13, LBB0_25  // bltu	a4, a3, .LBB0_25
LBB0_13:
	WORD $0x00360993  // addi	s3, a2, 3
	BGEU X19, X16, LBB0_17  // bgeu	s3, a6, .LBB0_17
	WORD $0x013e86b3  // add	a3, t4, s3
	WORD $0x0006c703  // lbu	a4, 0(a3)
	WORD $0x00d00693  // li	a3, 13
	BEQ X14, X13, LBB0_17  // beq	a4, a3, .LBB0_17
	WORD $0x02000693  // li	a3, 32
	BEQ X14, X13, LBB0_17  // beq	a4, a3, .LBB0_17
	WORD $0xff570713  // addi	a4, a4, -11
	WORD $0xffe00693  // li	a3, -2
	BLTU X14, X13, LBB0_25  // bltu	a4, a3, .LBB0_25
LBB0_17:
	WORD $0x00460713  // addi	a4, a2, 4
	BGEU X14, X16, LBB0_22  // bgeu	a4, a6, .LBB0_22
	WORD $0x01d70733  // add	a4, a4, t4
	WORD $0x410007b3  // neg	a5, a6
	WORD $0xffc00693  // li	a3, -4
	WORD $0x02000493  // li	s1, 32
	WORD $0x40c68633  // sub	a2, a3, a2
	WORD $0x008006b7  // lui	a3, 2048
	WORD $0x0136869b  // addiw	a3, a3, 19
	WORD $0x00969413  // slli	s0, a3, 9
LBB0_19:
	WORD $0x00074683  // lbu	a3, 0(a4)
	BLTU X9, X13, LBB0_24  // bltu	s1, a3, .LBB0_24
	WORD $0x00d456b3  // srl	a3, s0, a3
	WORD $0x0016f693  // andi	a3, a3, 1
	BEQZ X13, LBB0_24  // beqz	a3, .LBB0_24
	WORD $0xfff60613  // addi	a2, a2, -1
	WORD $0x00170713  // addi	a4, a4, 1
	BNE X15, X12, LBB0_19  // bne	a5, a2, .LBB0_19
	JMP LBB0_23  // j	.LBB0_23
LBB0_22:
	WORD $0x00e93023  // sd	a4, 0(s2)
LBB0_23:
	WORD $0xfff00393  // li	t2, -1
	JMP LBB0_301  // j	.LBB0_301
LBB0_24:
	WORD $0x40c009b3  // neg	s3, a2
	WORD $0xfff00393  // li	t2, -1
	BLTU X19, X16, LBB0_25  // bltu	s3, a6, .LBB0_25
	JMP LBB0_301  // j	.LBB0_301
LBB0_25:
	WORD $0x00198713  // addi	a4, s3, 1
	WORD $0x00e93023  // sd	a4, 0(s2)
	WORD $0x013e88b3  // add	a7, t4, s3
	WORD $0x0008c603  // lbu	a2, 0(a7)
	WORD $0x05a00693  // li	a3, 90
	WORD $0xfff00393  // li	t2, -1
	BLT X13, X12, LBB0_53  // blt	a3, a2, .LBB0_53
	WORD $0x02f00693  // li	a3, 47
	BGE X13, X12, LBB0_155  // bge	a3, a2, .LBB0_155
	WORD $0xfd060613  // addi	a2, a2, -48
	WORD $0x00a00693  // li	a3, 10
	BLTU X12, X13, LBB0_28  // bltu	a2, a3, .LBB0_28
	JMP LBB0_291  // j	.LBB0_291
LBB0_28:
	WORD $0x00853503  // ld	a0, 8(a0)
	WORD $0x40e50333  // sub	t1, a0, a4
	WORD $0x01000493  // li	s1, 16
	WORD $0x00ee82b3  // add	t0, t4, a4
	BLTU X6, X9, LBB0_40  // bltu	t1, s1, .LBB0_40
	WORD $0x00298393  // addi	t2, s3, 2
	WORD $0x07d00513  // li	a0, 125
	WORD $0x05d00593  // li	a1, 93
	WORD $0x02c00613  // li	a2, 44
	WORD $0x0c0076d7  // vsetvli	a3, zero, e8, m1, ta, ma
	WORD $0x42056457  // vmv.s.x	v8, a0
	WORD $0xfff00413  // li	s0, -1
	WORD $0x4205e4d7  // vmv.s.x	v9, a1
	WORD $0x42066557  // vmv.s.x	v10, a2
	WORD $0x00f00813  // li	a6, 15
	WORD $0x00098793  // mv	a5, s3
LBB0_30:
	WORD $0x00000513  // li	a0, 0
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x02028587  // vle8.v	v11, (t0)
LBB0_31:
	WORD $0x00150593  // addi	a1, a0, 1
	WORD $0x0875f057  // vsetvli	zero, a1, e8, mf2, tu, ma
	WORD $0x3a854657  // vslideup.vx	v12, v8, a0
	WORD $0x00058513  // mv	a0, a1
	BNE X11, X9, LBB0_31  // bne	a1, s1, .LBB0_31
	WORD $0x00000513  // li	a0, 0
LBB0_33:
	WORD $0x00150593  // addi	a1, a0, 1
	WORD $0x0875f057  // vsetvli	zero, a1, e8, mf2, tu, ma
	WORD $0x3a9546d7  // vslideup.vx	v13, v9, a0
	WORD $0x00058513  // mv	a0, a1
	BNE X11, X9, LBB0_33  // bne	a1, s1, .LBB0_33
	WORD $0x00000513  // li	a0, 0
LBB0_35:
	WORD $0x00150593  // addi	a1, a0, 1
	WORD $0x0875f057  // vsetvli	zero, a1, e8, mf2, tu, ma
	WORD $0x3aa54757  // vslideup.vx	v14, v10, a0
	WORD $0x00058513  // mv	a0, a1
	BNE X11, X9, LBB0_35  // bne	a1, s1, .LBB0_35
	WORD $0x00000693  // li	a3, 0
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62b60657  // vmseq.vv	v12, v11, v12
	WORD $0x62b686d7  // vmseq.vv	v13, v11, v13
	WORD $0x62b705d7  // vmseq.vv	v11, v11, v14
	WORD $0x00f00513  // li	a0, 15
	WORD $0x6ad62657  // vmor.mm	v12, v13, v12
	WORD $0x6ac5a5d7  // vmor.mm	v11, v12, v11
	WORD $0x0c807057  // vsetvli	zero, zero, e16, m1, ta, ma
	WORD $0x42b02657  // vmv.x.s	a2, v11
	WORD $0x00f00713  // li	a4, 15
LBB0_37:
	WORD $0x00e655b3  // srl	a1, a2, a4
	WORD $0xfff70713  // addi	a4, a4, -1
	WORD $0x0015f593  // andi	a1, a1, 1
	WORD $0x00a595bb  // sllw	a1, a1, a0
	WORD $0x00b6e6b3  // or	a3, a3, a1
	WORD $0xfff50513  // addi	a0, a0, -1
	BNE X14, X8, LBB0_37  // bne	a4, s0, .LBB0_37
	BNEZ X13, LBB0_48  // bnez	a3, .LBB0_48
	WORD $0x01028293  // addi	t0, t0, 16
	WORD $0xff030313  // addi	t1, t1, -16
	WORD $0x01038393  // addi	t2, t2, 16
	WORD $0x01078793  // addi	a5, a5, 16
	WORD $0x01088893  // addi	a7, a7, 16
	BLTU X16, X6, LBB0_30  // bltu	a6, t1, .LBB0_30
LBB0_40:
	BNEZ X6, LBB0_41  // bnez	t1, .LBB0_41
	JMP LBB0_304  // j	.LBB0_304
LBB0_41:
	WORD $0x00628833  // add	a6, t0, t1
	WORD $0x41d28733  // sub	a4, t0, t4
	WORD $0x02c00793  // li	a5, 44
	WORD $0x07d00493  // li	s1, 125
	WORD $0x05d00413  // li	s0, 93
	WORD $0x01001537  // lui	a0, 4097
	WORD $0x00b51513  // slli	a0, a0, 11
	WORD $0x01350513  // addi	a0, a0, 19
	WORD $0x00951693  // slli	a3, a0, 9
LBB0_42:
	WORD $0x0002c503  // lbu	a0, 0(t0)
	BLTU X15, X10, LBB0_44  // bltu	a5, a0, .LBB0_44
	WORD $0x00a6d5b3  // srl	a1, a3, a0
	WORD $0x0015f593  // andi	a1, a1, 1
	BEQZ X11, LBB0_44  // beqz	a1, .LBB0_44
	JMP LBB0_302  // j	.LBB0_302
LBB0_44:
	BNE X10, X9, LBB0_45  // bne	a0, s1, .LBB0_45
	JMP LBB0_302  // j	.LBB0_302
LBB0_45:
	BNE X10, X8, LBB0_46  // bne	a0, s0, .LBB0_46
	JMP LBB0_302  // j	.LBB0_302
LBB0_46:
	WORD $0x00128293  // addi	t0, t0, 1
	WORD $0xfff30313  // addi	t1, t1, -1
	WORD $0x00170713  // addi	a4, a4, 1
	BNEZ X6, LBB0_42  // bnez	t1, .LBB0_42
	WORD $0x00098393  // mv	t2, s3
	WORD $0x00080293  // mv	t0, a6
	JMP LBB0_305  // j	.LBB0_305
LBB0_48:
	WORD $0x40d0053b  // negw	a0, a3
	WORD $0x00d57533  // and	a0, a0, a3
	WORD $0x077cb5b7  // lui	a1, 30667
	WORD $0x53158593  // addi	a1, a1, 1329
	WORD $0x02b50533  // mul	a0, a0, a1
	WORD $0x01b5551b  // srliw	a0, a0, 27
	MOV $·p7c48db41412b1d2_LCPI0_0(SB), X11  // lui	a1, %hi(.LCPI0_0)
	// addi	a1, a1, %lo(.LCPI0_0) (skipped, covered by MOV address load)
	WORD $0x00b50533  // add	a0, a0, a1
	WORD $0x00054503  // lbu	a0, 0(a0)
	WORD $0x41d285b3  // sub	a1, t0, t4
	WORD $0x00a585b3  // add	a1, a1, a0
	WORD $0x00b93023  // sd	a1, 0(s2)
	BGTZ X11, LBB0_49  // bgtz	a1, .LBB0_49
	JMP LBB0_300  // j	.LBB0_300
LBB0_49:
	WORD $0x00750733  // add	a4, a0, t2
	WORD $0x00a787b3  // add	a5, a5, a0
	WORD $0x00a888b3  // add	a7, a7, a0
	WORD $0x02000513  // li	a0, 32
	WORD $0x008005b7  // lui	a1, 2048
	WORD $0x0135859b  // addiw	a1, a1, 19
	WORD $0x00959613  // slli	a2, a1, 9
	WORD $0x00100693  // li	a3, 1
LBB0_50:
	WORD $0x0008c483  // lbu	s1, 0(a7)
	BGEU X10, X9, LBB0_51  // bgeu	a0, s1, .LBB0_51
	JMP LBB0_300  // j	.LBB0_300
LBB0_51:
	WORD $0x009655b3  // srl	a1, a2, s1
	WORD $0x0015f593  // andi	a1, a1, 1
	BNEZ X11, LBB0_52  // bnez	a1, .LBB0_52
	JMP LBB0_300  // j	.LBB0_300
LBB0_52:
	WORD $0x00f93023  // sd	a5, 0(s2)
	WORD $0xfff70713  // addi	a4, a4, -1
	WORD $0xfff78793  // addi	a5, a5, -1
	WORD $0xfff88893  // addi	a7, a7, -1
	BLT X13, X14, LBB0_50  // blt	a3, a4, .LBB0_50
	JMP LBB0_300  // j	.LBB0_300
LBB0_53:
	WORD $0x06d00693  // li	a3, 109
	BGE X13, X12, LBB0_158  // bge	a3, a2, .LBB0_158
	WORD $0x06e00693  // li	a3, 110
	BEQ X12, X13, LBB0_161  // beq	a2, a3, .LBB0_161
	WORD $0x07400693  // li	a3, 116
	BEQ X12, X13, LBB0_161  // beq	a2, a3, .LBB0_161
	WORD $0x07b00693  // li	a3, 123
	BEQ X12, X13, LBB0_57  // beq	a2, a3, .LBB0_57
	JMP LBB0_291  // j	.LBB0_291
LBB0_57:
	WORD $0x01313c23  // sd	s3, 24(sp)
	WORD $0x03213423  // sd	s2, 40(sp)
	WORD $0x00000d13  // li	s10, 0
	WORD $0x00000393  // li	t2, 0
	WORD $0x00000313  // li	t1, 0
	WORD $0x04013c23  // sd	zero, 88(sp)
	MOV $·p7c48db41412b1d2_LCPI0_3(SB), X17  // lui	a7, %hi(.LCPI0_3)
	MOV $·p7c48db41412b1d2_LCPI0_4(SB), X28  // lui	t3, %hi(.LCPI0_4)
	MOV $·p7c48db41412b1d2_LCPI0_5(SB), X31  // lui	t6, %hi(.LCPI0_5)
	MOV $·p7c48db41412b1d2_LCPI0_6(SB), X19  // lui	s3, %hi(.LCPI0_6)
	MOV $·p7c48db41412b1d2_LCPI0_7(SB), X20  // lui	s4, %hi(.LCPI0_7)
	MOV $·p7c48db41412b1d2_LCPI0_8(SB), X23  // lui	s7, %hi(.LCPI0_8)
	WORD $0x02a13023  // sd	a0, 32(sp)
	WORD $0x00853503  // ld	a0, 8(a0)
	WORD $0x00ee8eb3  // add	t4, t4, a4
	WORD $0x02200593  // li	a1, 34
	WORD $0x01000293  // li	t0, 16
	WORD $0xfff00f13  // li	t5, -1
	WORD $0x05c00613  // li	a2, 92
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x5e0fb457  // vmv.v.i	v8, -1
	WORD $0x00ff0ab7  // lui	s5, 4080
	WORD $0x00010c37  // lui	s8, 16
	MOV $·p7c48db41412b1d2_LCPI0_9(SB), X9  // lui	s1, %hi(.LCPI0_9)
	MOV $·p7c48db41412b1d2_LCPI0_10(SB), X8  // lui	s0, %hi(.LCPI0_10)
	WORD $0x5e00b057  // vmv.v.i	v0, 1
	WORD $0x4206e4d7  // vmv.s.x	v9, a3
	WORD $0x07d00693  // li	a3, 125
	MOV $·p7c48db41412b1d2_LCPI0_11(SB), X15  // lui	a5, %hi(.LCPI0_11)
	WORD $0xcd827057  // vsetivli	zero, 4, e64, m1, ta, ma
	WORD $0x5e003557  // vmv.v.i	v10, 0
	WORD $0x00001837  // lui	a6, 1
	WORD $0x4205e5d7  // vmv.s.x	v11, a1
	WORD $0x42066657  // vmv.s.x	v12, a2
	WORD $0x4206e6d7  // vmv.s.x	v13, a3
	MOV (X17), X11  // ld	a1, %lo(.LCPI0_3)(a7)
	WORD $0x00b13823  // sd	a1, 16(sp)
	MOV (X28), X18  // ld	s2, %lo(.LCPI0_4)(t3)
	MOV (X31), X22  // ld	s6, %lo(.LCPI0_5)(t6)
	MOV (X19), X1  // ld	ra, %lo(.LCPI0_6)(s3)
	MOV (X20), g  // ld	s11, %lo(.LCPI0_7)(s4)
	MOV (X23), X17  // ld	a7, %lo(.LCPI0_8)(s7)
	WORD $0xf00c0e1b  // addiw	t3, s8, -256
	MOV (X9), X24  // ld	s8, %lo(.LCPI0_9)(s1)
	MOV (X8), X25  // ld	s9, %lo(.LCPI0_10)(s0)
	MOV (X15), X11  // ld	a1, %lo(.LCPI0_11)(a5)
	WORD $0x02b13823  // sd	a1, 48(sp)
	WORD $0xfc18059b  // addiw	a1, a6, -63
	WORD $0x00b13423  // sd	a1, 8(sp)
	WORD $0x40e505b3  // sub	a1, a0, a4
	WORD $0x03c13c23  // sd	t3, 56(sp)
LBB0_58:
	WORD $0x04000513  // li	a0, 64
	WORD $0x06b13023  // sd	a1, 96(sp)
	WORD $0x05a13823  // sd	s10, 80(sp)
	BLT X11, X10, LBB0_138  // blt	a1, a0, .LBB0_138
LBB0_59:
	WORD $0x00000693  // li	a3, 0
	WORD $0x020e8513  // addi	a0, t4, 32
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x02050787  // vle8.v	v15, (a0)
	WORD $0x010e8593  // addi	a1, t4, 16
	WORD $0x020e8887  // vle8.v	v17, (t4)
	WORD $0x030e8513  // addi	a0, t4, 48
	WORD $0x04b13023  // sd	a1, 64(sp)
	WORD $0x02058807  // vle8.v	v16, (a1)
	WORD $0x02050707  // vle8.v	v14, (a0)
LBB0_60:
	WORD $0x00168513  // addi	a0, a3, 1
	WORD $0x08757057  // vsetvli	zero, a0, e8, mf2, tu, ma
	WORD $0x3ab6c957  // vslideup.vx	v18, v11, a3
	WORD $0x00050693  // mv	a3, a0
	BNE X10, X5, LBB0_60  // bne	a0, t0, .LBB0_60
	WORD $0x00000e93  // li	t4, 0
	WORD $0x00f00693  // li	a3, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x63190957  // vmseq.vv	v18, v17, v18
	WORD $0x0c807057  // vsetvli	zero, zero, e16, m1, ta, ma
	WORD $0x43202657  // vmv.x.s	a2, v18
	WORD $0x00f00713  // li	a4, 15
LBB0_62:
	WORD $0x00e65533  // srl	a0, a2, a4
	WORD $0xfff70713  // addi	a4, a4, -1
	WORD $0x00157513  // andi	a0, a0, 1
	WORD $0x00d5153b  // sllw	a0, a0, a3
	WORD $0x01d56eb3  // or	t4, a0, t4
	WORD $0xfff68693  // addi	a3, a3, -1
	BNE X14, X30, LBB0_62  // bne	a4, t5, .LBB0_62
	WORD $0x00000613  // li	a2, 0
LBB0_64:
	WORD $0x00160513  // addi	a0, a2, 1
	WORD $0x08757057  // vsetvli	zero, a0, e8, mf2, tu, ma
	WORD $0x3ab64957  // vslideup.vx	v18, v11, a2
	WORD $0x00050613  // mv	a2, a0
	BNE X10, X5, LBB0_64  // bne	a0, t0, .LBB0_64
	WORD $0x00000693  // li	a3, 0
	WORD $0x00f00713  // li	a4, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x63090957  // vmseq.vv	v18, v16, v18
	WORD $0x00f00613  // li	a2, 15
LBB0_66:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x43202557  // vmv.x.s	a0, v18
	WORD $0x00c55533  // srl	a0, a0, a2
	WORD $0xfff60613  // addi	a2, a2, -1
	WORD $0x00157513  // andi	a0, a0, 1
	WORD $0x00e5153b  // sllw	a0, a0, a4
	WORD $0x00a6e6b3  // or	a3, a3, a0
	WORD $0xfff70713  // addi	a4, a4, -1
	BNE X12, X30, LBB0_66  // bne	a2, t5, .LBB0_66
	WORD $0x00000613  // li	a2, 0
LBB0_68:
	WORD $0x00160513  // addi	a0, a2, 1
	WORD $0x08757057  // vsetvli	zero, a0, e8, mf2, tu, ma
	WORD $0x3ab64957  // vslideup.vx	v18, v11, a2
	WORD $0x00050613  // mv	a2, a0
	BNE X10, X5, LBB0_68  // bne	a0, t0, .LBB0_68
	WORD $0x00000713  // li	a4, 0
	WORD $0x00f00493  // li	s1, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62f90957  // vmseq.vv	v18, v15, v18
	WORD $0x00f00613  // li	a2, 15
LBB0_70:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x43202557  // vmv.x.s	a0, v18
	WORD $0x00c55533  // srl	a0, a0, a2
	WORD $0xfff60613  // addi	a2, a2, -1
	WORD $0x00157513  // andi	a0, a0, 1
	WORD $0x0095153b  // sllw	a0, a0, s1
	WORD $0x00a76733  // or	a4, a4, a0
	WORD $0xfff48493  // addi	s1, s1, -1
	BNE X12, X30, LBB0_70  // bne	a2, t5, .LBB0_70
	WORD $0x00000613  // li	a2, 0
LBB0_72:
	WORD $0x00160513  // addi	a0, a2, 1
	WORD $0x08757057  // vsetvli	zero, a0, e8, mf2, tu, ma
	WORD $0x3ab64957  // vslideup.vx	v18, v11, a2
	WORD $0x00050613  // mv	a2, a0
	BNE X10, X5, LBB0_72  // bne	a0, t0, .LBB0_72
	WORD $0x00000493  // li	s1, 0
	WORD $0x00f00413  // li	s0, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62e90957  // vmseq.vv	v18, v14, v18
	WORD $0x00f00613  // li	a2, 15
LBB0_74:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x43202557  // vmv.x.s	a0, v18
	WORD $0x00c55533  // srl	a0, a0, a2
	WORD $0xfff60613  // addi	a2, a2, -1
	WORD $0x00157513  // andi	a0, a0, 1
	WORD $0x0085153b  // sllw	a0, a0, s0
	WORD $0x00a4e4b3  // or	s1, s1, a0
	WORD $0xfff40413  // addi	s0, s0, -1
	BNE X12, X30, LBB0_74  // bne	a2, t5, .LBB0_74
	WORD $0x00000793  // li	a5, 0
	WORD $0x02071713  // slli	a4, a4, 32
	WORD $0x03069613  // slli	a2, a3, 48
	WORD $0x02065613  // srli	a2, a2, 32
LBB0_76:
	WORD $0x00178513  // addi	a0, a5, 1
	WORD $0x08757057  // vsetvli	zero, a0, e8, mf2, tu, ma
	WORD $0x3ac7c957  // vslideup.vx	v18, v12, a5
	WORD $0x00050793  // mv	a5, a0
	BNE X10, X5, LBB0_76  // bne	a0, t0, .LBB0_76
	WORD $0x00000693  // li	a3, 0
	WORD $0x03049493  // slli	s1, s1, 48
	WORD $0x00e484b3  // add	s1, s1, a4
	WORD $0x00f00713  // li	a4, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x63190957  // vmseq.vv	v18, v17, v18
	WORD $0x00c4efb3  // or	t6, s1, a2
	WORD $0x00f00613  // li	a2, 15
LBB0_78:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x43202557  // vmv.x.s	a0, v18
	WORD $0x00c55533  // srl	a0, a0, a2
	WORD $0xfff60613  // addi	a2, a2, -1
	WORD $0x00157513  // andi	a0, a0, 1
	WORD $0x00e5153b  // sllw	a0, a0, a4
	WORD $0x00a6e6b3  // or	a3, a3, a0
	WORD $0xfff70713  // addi	a4, a4, -1
	BNE X12, X30, LBB0_78  // bne	a2, t5, .LBB0_78
	WORD $0x00000613  // li	a2, 0
LBB0_80:
	WORD $0x00160513  // addi	a0, a2, 1
	WORD $0x08757057  // vsetvli	zero, a0, e8, mf2, tu, ma
	WORD $0x3ac64957  // vslideup.vx	v18, v12, a2
	WORD $0x00050613  // mv	a2, a0
	BNE X10, X5, LBB0_80  // bne	a0, t0, .LBB0_80
	WORD $0x00000413  // li	s0, 0
	WORD $0x00f00713  // li	a4, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x63090957  // vmseq.vv	v18, v16, v18
	WORD $0x00f00613  // li	a2, 15
LBB0_82:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x43202557  // vmv.x.s	a0, v18
	WORD $0x00c55533  // srl	a0, a0, a2
	WORD $0xfff60613  // addi	a2, a2, -1
	WORD $0x00157513  // andi	a0, a0, 1
	WORD $0x00e5153b  // sllw	a0, a0, a4
	WORD $0x00a46433  // or	s0, s0, a0
	WORD $0xfff70713  // addi	a4, a4, -1
	BNE X12, X30, LBB0_82  // bne	a2, t5, .LBB0_82
	WORD $0x00000613  // li	a2, 0
LBB0_84:
	WORD $0x00160513  // addi	a0, a2, 1
	WORD $0x08757057  // vsetvli	zero, a0, e8, mf2, tu, ma
	WORD $0x3ac64957  // vslideup.vx	v18, v12, a2
	WORD $0x00050613  // mv	a2, a0
	BNE X10, X5, LBB0_84  // bne	a0, t0, .LBB0_84
	WORD $0x00000713  // li	a4, 0
	WORD $0x00f00493  // li	s1, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62f90957  // vmseq.vv	v18, v15, v18
	WORD $0x00f00613  // li	a2, 15
LBB0_86:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x43202557  // vmv.x.s	a0, v18
	WORD $0x00c55533  // srl	a0, a0, a2
	WORD $0xfff60613  // addi	a2, a2, -1
	WORD $0x00157513  // andi	a0, a0, 1
	WORD $0x0095153b  // sllw	a0, a0, s1
	WORD $0x00a76733  // or	a4, a4, a0
	WORD $0xfff48493  // addi	s1, s1, -1
	BNE X12, X30, LBB0_86  // bne	a2, t5, .LBB0_86
	WORD $0x00000613  // li	a2, 0
LBB0_88:
	WORD $0x00160513  // addi	a0, a2, 1
	WORD $0x08757057  // vsetvli	zero, a0, e8, mf2, tu, ma
	WORD $0x3ac64957  // vslideup.vx	v18, v12, a2
	WORD $0x00050613  // mv	a2, a0
	BNE X10, X5, LBB0_88  // bne	a0, t0, .LBB0_88
	WORD $0x00000493  // li	s1, 0
	WORD $0x00f00993  // li	s3, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62e90957  // vmseq.vv	v18, v14, v18
	WORD $0x00f00613  // li	a2, 15
LBB0_90:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x43202557  // vmv.x.s	a0, v18
	WORD $0x00c55533  // srl	a0, a0, a2
	WORD $0xfff60613  // addi	a2, a2, -1
	WORD $0x00157513  // andi	a0, a0, 1
	WORD $0x0135153b  // sllw	a0, a0, s3
	WORD $0x00a4e4b3  // or	s1, s1, a0
	WORD $0xfff98993  // addi	s3, s3, -1
	BNE X12, X30, LBB0_90  // bne	a2, t5, .LBB0_90
	WORD $0x03049493  // slli	s1, s1, 48
	WORD $0x02071713  // slli	a4, a4, 32
	WORD $0x03041413  // slli	s0, s0, 48
	WORD $0x00970733  // add	a4, a4, s1
	WORD $0x02045413  // srli	s0, s0, 32
	WORD $0x00876733  // or	a4, a4, s0
	WORD $0x00e686b3  // add	a3, a3, a4
	WORD $0x0076e533  // or	a0, a3, t2
	BNEZ X10, LBB0_93  // bnez	a0, .LBB0_93
	WORD $0x00000593  // li	a1, 0
	WORD $0x00000693  // li	a3, 0
	JMP LBB0_94  // j	.LBB0_94
LBB0_93:
	WORD $0xfff3c513  // not	a0, t2
	WORD $0x01013583  // ld	a1, 16(sp)
	WORD $0x00d5f5b3  // and	a1, a1, a3
	WORD $0x00d57533  // and	a0, a0, a3
	WORD $0x00151613  // slli	a2, a0, 1
	WORD $0x00766633  // or	a2, a2, t2
	WORD $0xfff64693  // not	a3, a2
	WORD $0x00d5f5b3  // and	a1, a1, a3
	WORD $0x00b50533  // add	a0, a0, a1
	WORD $0x00b535b3  // sltu	a1, a0, a1
	WORD $0x00151513  // slli	a0, a0, 1
	WORD $0x016546b3  // xor	a3, a0, s6
	WORD $0x00c6f6b3  // and	a3, a3, a2
LBB0_94:
	WORD $0x04613423  // sd	t1, 72(sp)
	WORD $0x00000613  // li	a2, 0
	WORD $0x01fe8eb3  // add	t4, t4, t6
	WORD $0xfff6c513  // not	a0, a3
	WORD $0x00aef6b3  // and	a3, t4, a0
LBB0_95:
	WORD $0x00160513  // addi	a0, a2, 1
	WORD $0x08757057  // vsetvli	zero, a0, e8, mf2, tu, ma
	WORD $0x3a864957  // vslideup.vx	v18, v8, a2
	WORD $0x00050613  // mv	a2, a0
	BNE X10, X5, LBB0_95  // bne	a0, t0, .LBB0_95
	WORD $0x06b13423  // sd	a1, 104(sp)
	WORD $0x00000413  // li	s0, 0
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x332039d7  // vrgather.vi	v19, v18, 0
	WORD $0x5e098957  // vmv.v.v	v18, v19
	WORD $0x09807057  // vsetvli	zero, zero, e64, m1, tu, ma
	WORD $0x4206e957  // vmv.s.x	v18, a3
	WORD $0x00100713  // li	a4, 1
LBB0_97:
	WORD $0xcd80f057  // vsetivli	zero, 1, e64, m1, ta, ma
	WORD $0x3f244a57  // vslidedown.vx	v20, v18, s0
	WORD $0x43402557  // vmv.x.s	a0, v20
	WORD $0x0185559b  // srliw	a1, a0, 24
	WORD $0x01557633  // and	a2, a0, s5
	WORD $0x03851793  // slli	a5, a0, 56
	WORD $0x01c574b3  // and	s1, a0, t3
	WORD $0x02059593  // slli	a1, a1, 32
	WORD $0x01861613  // slli	a2, a2, 24
	WORD $0x00c5e5b3  // or	a1, a1, a2
	WORD $0x02855613  // srli	a2, a0, 40
	WORD $0x02849493  // slli	s1, s1, 40
	WORD $0x0097e7b3  // or	a5, a5, s1
	WORD $0x03855493  // srli	s1, a0, 56
	WORD $0x01c67633  // and	a2, a2, t3
	WORD $0x00966633  // or	a2, a2, s1
	WORD $0x00f5e5b3  // or	a1, a1, a5
	WORD $0x01855793  // srli	a5, a0, 24
	WORD $0x00855513  // srli	a0, a0, 8
	WORD $0x0157f7b3  // and	a5, a5, s5
	WORD $0x0185551b  // srliw	a0, a0, 24
	WORD $0x01851513  // slli	a0, a0, 24
	WORD $0x00f56533  // or	a0, a0, a5
	WORD $0x00140793  // addi	a5, s0, 1
	WORD $0x00177493  // andi	s1, a4, 1
	WORD $0x00c56533  // or	a0, a0, a2
	WORD $0x00b56533  // or	a0, a0, a1
	WORD $0x00455593  // srli	a1, a0, 4
	WORD $0x01857533  // and	a0, a0, s8
	WORD $0x0185f5b3  // and	a1, a1, s8
	WORD $0x00451513  // slli	a0, a0, 4
	WORD $0x00b56533  // or	a0, a0, a1
	WORD $0x00255593  // srli	a1, a0, 2
	WORD $0x01957533  // and	a0, a0, s9
	WORD $0x0195f5b3  // and	a1, a1, s9
	WORD $0x00251513  // slli	a0, a0, 2
	WORD $0x00b56533  // or	a0, a0, a1
	WORD $0x00155593  // srli	a1, a0, 1
	WORD $0x01657533  // and	a0, a0, s6
	WORD $0x0165f5b3  // and	a1, a1, s6
	WORD $0x00151513  // slli	a0, a0, 1
	WORD $0x00b56533  // or	a0, a0, a1
	WORD $0x42056a57  // vmv.s.x	v20, a0
	WORD $0x0987f057  // vsetvli	zero, a5, e64, m1, tu, ma
	WORD $0x3b444957  // vslideup.vx	v18, v20, s0
	WORD $0x00100413  // li	s0, 1
	WORD $0x00000713  // li	a4, 0
	BNEZ X9, LBB0_97  // bnez	s1, .LBB0_97
	WORD $0x00000e93  // li	t4, 0
	WORD $0xc5817057  // vsetivli	zero, 2, e64, m1, ta, mu
	WORD $0x3b26ea57  // vslide1up.vx	v20, v18, a3
	WORD $0x3130b957  // vrgather.vi	v18, v19, 1, v0.t
	WORD $0x00100813  // li	a6, 1
LBB0_99:
	WORD $0xcd80f057  // vsetivli	zero, 1, e64, m1, ta, ma
	WORD $0x3f4ecad7  // vslidedown.vx	v21, v20, t4
	WORD $0x43502557  // vmv.x.s	a0, v21
	WORD $0x3f2ecad7  // vslidedown.vx	v21, v18, t4
	WORD $0x435025d7  // vmv.x.s	a1, v21
	WORD $0x01157633  // and	a2, a0, a7
	WORD $0x01b57733  // and	a4, a0, s11
	WORD $0x001577b3  // and	a5, a0, ra
	WORD $0x01257533  // and	a0, a0, s2
	WORD $0x0115f4b3  // and	s1, a1, a7
	WORD $0x01b5f6b3  // and	a3, a1, s11
	WORD $0x0015f433  // and	s0, a1, ra
	WORD $0x0125f5b3  // and	a1, a1, s2
	WORD $0x02960fb3  // mul	t6, a2, s1
	WORD $0x02b709b3  // mul	s3, a4, a1
	WORD $0x02878a33  // mul	s4, a5, s0
	WORD $0x02d50e33  // mul	t3, a0, a3
	WORD $0x02d60d33  // mul	s10, a2, a3
	WORD $0x02970333  // mul	t1, a4, s1
	WORD $0x02b783b3  // mul	t2, a5, a1
	WORD $0x02850bb3  // mul	s7, a0, s0
	WORD $0x02860ab3  // mul	s5, a2, s0
	WORD $0x02870433  // mul	s0, a4, s0
	WORD $0x02d70733  // mul	a4, a4, a3
	WORD $0x02d786b3  // mul	a3, a5, a3
	WORD $0x029787b3  // mul	a5, a5, s1
	WORD $0x02b60633  // mul	a2, a2, a1
	WORD $0x02b505b3  // mul	a1, a0, a1
	WORD $0x02950533  // mul	a0, a0, s1
	WORD $0x013fcfb3  // xor	t6, t6, s3
	WORD $0x01ca4e33  // xor	t3, s4, t3
	WORD $0x006d4333  // xor	t1, s10, t1
	WORD $0x0173c4b3  // xor	s1, t2, s7
	WORD $0x001e8393  // addi	t2, t4, 1
	WORD $0x00187993  // andi	s3, a6, 1
	WORD $0x00eac733  // xor	a4, s5, a4
	WORD $0x00f5c5b3  // xor	a1, a1, a5
	WORD $0x00864633  // xor	a2, a2, s0
	WORD $0x00d54533  // xor	a0, a0, a3
	WORD $0x01cfc6b3  // xor	a3, t6, t3
	WORD $0x009347b3  // xor	a5, t1, s1
	WORD $0x00e5c5b3  // xor	a1, a1, a4
	WORD $0x00c54533  // xor	a0, a0, a2
	WORD $0x0116f633  // and	a2, a3, a7
	WORD $0x01b7f6b3  // and	a3, a5, s11
	WORD $0x0015f5b3  // and	a1, a1, ra
	WORD $0x01257533  // and	a0, a0, s2
	WORD $0x00d66633  // or	a2, a2, a3
	WORD $0x00b56533  // or	a0, a0, a1
	WORD $0x00c56533  // or	a0, a0, a2
	WORD $0x42056ad7  // vmv.s.x	v21, a0
	WORD $0x0983f057  // vsetvli	zero, t2, e64, m1, tu, ma
	WORD $0x3b5ec9d7  // vslideup.vx	v19, v21, t4
	WORD $0x00100e93  // li	t4, 1
	WORD $0x00000813  // li	a6, 0
	BNEZ X19, LBB0_99  // bnez	s3, .LBB0_99
	WORD $0x00000613  // li	a2, 0
	WORD $0x43302557  // vmv.x.s	a0, v19
	WORD $0x05013583  // ld	a1, 80(sp)
	WORD $0x00b54833  // xor	a6, a0, a1
LBB0_101:
	WORD $0x00160513  // addi	a0, a2, 1
	WORD $0x08757057  // vsetvli	zero, a0, e8, mf2, tu, ma
	WORD $0x3a964957  // vslideup.vx	v18, v9, a2
	WORD $0x00050613  // mv	a2, a0
	BNE X10, X5, LBB0_101  // bne	a0, t0, .LBB0_101
	WORD $0x00000413  // li	s0, 0
	WORD $0x00f00693  // li	a3, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x63190957  // vmseq.vv	v18, v17, v18
	WORD $0x00f00613  // li	a2, 15
	WORD $0x04813303  // ld	t1, 72(sp)
LBB0_103:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x43202557  // vmv.x.s	a0, v18
	WORD $0x00c55533  // srl	a0, a0, a2
	WORD $0xfff60613  // addi	a2, a2, -1
	WORD $0x00157513  // andi	a0, a0, 1
	WORD $0x00d5153b  // sllw	a0, a0, a3
	WORD $0x00a46433  // or	s0, s0, a0
	WORD $0xfff68693  // addi	a3, a3, -1
	BNE X12, X30, LBB0_103  // bne	a2, t5, .LBB0_103
	WORD $0x00000613  // li	a2, 0
LBB0_105:
	WORD $0x00160513  // addi	a0, a2, 1
	WORD $0x08757057  // vsetvli	zero, a0, e8, mf2, tu, ma
	WORD $0x3a964957  // vslideup.vx	v18, v9, a2
	WORD $0x00050613  // mv	a2, a0
	BNE X10, X5, LBB0_105  // bne	a0, t0, .LBB0_105
	WORD $0x00000693  // li	a3, 0
	WORD $0x00f00713  // li	a4, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x63090957  // vmseq.vv	v18, v16, v18
	WORD $0x00f00613  // li	a2, 15
	WORD $0x06813383  // ld	t2, 104(sp)
	WORD $0x00ff0ab7  // lui	s5, 4080
	WORD $0x03813e03  // ld	t3, 56(sp)
LBB0_107:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x43202557  // vmv.x.s	a0, v18
	WORD $0x00c55533  // srl	a0, a0, a2
	WORD $0xfff60613  // addi	a2, a2, -1
	WORD $0x00157513  // andi	a0, a0, 1
	WORD $0x00e5153b  // sllw	a0, a0, a4
	WORD $0x00a6e6b3  // or	a3, a3, a0
	WORD $0xfff70713  // addi	a4, a4, -1
	BNE X12, X30, LBB0_107  // bne	a2, t5, .LBB0_107
	WORD $0x00000613  // li	a2, 0
LBB0_109:
	WORD $0x00160513  // addi	a0, a2, 1
	WORD $0x08757057  // vsetvli	zero, a0, e8, mf2, tu, ma
	WORD $0x3a964957  // vslideup.vx	v18, v9, a2
	WORD $0x00050613  // mv	a2, a0
	BNE X10, X5, LBB0_109  // bne	a0, t0, .LBB0_109
	WORD $0x00000713  // li	a4, 0
	WORD $0x00f00493  // li	s1, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62f90957  // vmseq.vv	v18, v15, v18
	WORD $0x00f00613  // li	a2, 15
LBB0_111:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x43202557  // vmv.x.s	a0, v18
	WORD $0x00c55533  // srl	a0, a0, a2
	WORD $0xfff60613  // addi	a2, a2, -1
	WORD $0x00157513  // andi	a0, a0, 1
	WORD $0x0095153b  // sllw	a0, a0, s1
	WORD $0x00a76733  // or	a4, a4, a0
	WORD $0xfff48493  // addi	s1, s1, -1
	BNE X12, X30, LBB0_111  // bne	a2, t5, .LBB0_111
	WORD $0x00000613  // li	a2, 0
LBB0_113:
	WORD $0x00160513  // addi	a0, a2, 1
	WORD $0x08757057  // vsetvli	zero, a0, e8, mf2, tu, ma
	WORD $0x3a964957  // vslideup.vx	v18, v9, a2
	WORD $0x00050613  // mv	a2, a0
	BNE X10, X5, LBB0_113  // bne	a0, t0, .LBB0_113
	WORD $0x00000493  // li	s1, 0
	WORD $0x00f00613  // li	a2, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62e90957  // vmseq.vv	v18, v14, v18
	WORD $0x00f00793  // li	a5, 15
LBB0_115:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x43202557  // vmv.x.s	a0, v18
	WORD $0x00f55533  // srl	a0, a0, a5
	WORD $0xfff78793  // addi	a5, a5, -1
	WORD $0x00157513  // andi	a0, a0, 1
	WORD $0x00c5153b  // sllw	a0, a0, a2
	WORD $0x00a4e4b3  // or	s1, s1, a0
	WORD $0xfff60613  // addi	a2, a2, -1
	BNE X15, X30, LBB0_115  // bne	a5, t5, .LBB0_115
	WORD $0x00000793  // li	a5, 0
	WORD $0x02071713  // slli	a4, a4, 32
	WORD $0x03069613  // slli	a2, a3, 48
	WORD $0x02065613  // srli	a2, a2, 32
	WORD $0xfff84e93  // not	t4, a6
LBB0_117:
	WORD $0x00178513  // addi	a0, a5, 1
	WORD $0x08757057  // vsetvli	zero, a0, e8, mf2, tu, ma
	WORD $0x3ad7c957  // vslideup.vx	v18, v13, a5
	WORD $0x00050793  // mv	a5, a0
	BNE X10, X5, LBB0_117  // bne	a0, t0, .LBB0_117
	WORD $0x00000693  // li	a3, 0
	WORD $0x03049493  // slli	s1, s1, 48
	WORD $0x00970733  // add	a4, a4, s1
	WORD $0x00e66633  // or	a2, a2, a4
	WORD $0x00f00713  // li	a4, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x631908d7  // vmseq.vv	v17, v17, v18
	WORD $0x00860fb3  // add	t6, a2, s0
	WORD $0x00f00613  // li	a2, 15
LBB0_119:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x43102557  // vmv.x.s	a0, v17
	WORD $0x00c55533  // srl	a0, a0, a2
	WORD $0xfff60613  // addi	a2, a2, -1
	WORD $0x00157513  // andi	a0, a0, 1
	WORD $0x00e5153b  // sllw	a0, a0, a4
	WORD $0x00a6e6b3  // or	a3, a3, a0
	WORD $0xfff70713  // addi	a4, a4, -1
	BNE X12, X30, LBB0_119  // bne	a2, t5, .LBB0_119
	WORD $0x00000613  // li	a2, 0
	WORD $0x43f85d13  // srai	s10, a6, 63
LBB0_121:
	WORD $0x00160513  // addi	a0, a2, 1
	WORD $0x08757057  // vsetvli	zero, a0, e8, mf2, tu, ma
	WORD $0x3ad648d7  // vslideup.vx	v17, v13, a2
	WORD $0x00050613  // mv	a2, a0
	BNE X10, X5, LBB0_121  // bne	a0, t0, .LBB0_121
	WORD $0x00000413  // li	s0, 0
	WORD $0x00f00613  // li	a2, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x63088857  // vmseq.vv	v16, v16, v17
	WORD $0x00f00713  // li	a4, 15
LBB0_123:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x43002557  // vmv.x.s	a0, v16
	WORD $0x00e55533  // srl	a0, a0, a4
	WORD $0xfff70713  // addi	a4, a4, -1
	WORD $0x00157513  // andi	a0, a0, 1
	WORD $0x00c5153b  // sllw	a0, a0, a2
	WORD $0x00a46433  // or	s0, s0, a0
	WORD $0xfff60613  // addi	a2, a2, -1
	BNE X14, X30, LBB0_123  // bne	a4, t5, .LBB0_123
	WORD $0x00000613  // li	a2, 0
LBB0_125:
	WORD $0x00160513  // addi	a0, a2, 1
	WORD $0x08757057  // vsetvli	zero, a0, e8, mf2, tu, ma
	WORD $0x3ad64857  // vslideup.vx	v16, v13, a2
	WORD $0x00050613  // mv	a2, a0
	BNE X10, X5, LBB0_125  // bne	a0, t0, .LBB0_125
	WORD $0x00000713  // li	a4, 0
	WORD $0x00f00613  // li	a2, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62f807d7  // vmseq.vv	v15, v15, v16
	WORD $0x00f00793  // li	a5, 15
LBB0_127:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x42f02557  // vmv.x.s	a0, v15
	WORD $0x00f55533  // srl	a0, a0, a5
	WORD $0xfff78793  // addi	a5, a5, -1
	WORD $0x00157513  // andi	a0, a0, 1
	WORD $0x00c5153b  // sllw	a0, a0, a2
	WORD $0x00a76733  // or	a4, a4, a0
	WORD $0xfff60613  // addi	a2, a2, -1
	BNE X15, X30, LBB0_127  // bne	a5, t5, .LBB0_127
	WORD $0x00000613  // li	a2, 0
LBB0_129:
	WORD $0x00160513  // addi	a0, a2, 1
	WORD $0x08757057  // vsetvli	zero, a0, e8, mf2, tu, ma
	WORD $0x3ad647d7  // vslideup.vx	v15, v13, a2
	WORD $0x00050613  // mv	a2, a0
	BNE X10, X5, LBB0_129  // bne	a0, t0, .LBB0_129
	WORD $0x00000493  // li	s1, 0
	WORD $0x00f00613  // li	a2, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62e78757  // vmseq.vv	v14, v14, v15
	WORD $0x00f00793  // li	a5, 15
LBB0_131:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x42e02557  // vmv.x.s	a0, v14
	WORD $0x00f55533  // srl	a0, a0, a5
	WORD $0xfff78793  // addi	a5, a5, -1
	WORD $0x00157513  // andi	a0, a0, 1
	WORD $0x00c5153b  // sllw	a0, a0, a2
	WORD $0x00a4e4b3  // or	s1, s1, a0
	WORD $0xfff60613  // addi	a2, a2, -1
	BNE X15, X30, LBB0_131  // bne	a5, t5, .LBB0_131
	WORD $0x03049493  // slli	s1, s1, 48
	WORD $0x02071713  // slli	a4, a4, 32
	WORD $0x03041413  // slli	s0, s0, 48
	WORD $0x00970733  // add	a4, a4, s1
	WORD $0x02045413  // srli	s0, s0, 32
	WORD $0x00876733  // or	a4, a4, s0
	WORD $0x00e686b3  // add	a3, a3, a4
	WORD $0x01d6f733  // and	a4, a3, t4
	WORD $0x01dff6b3  // and	a3, t6, t4
	BEQZ X14, LBB0_136  // beqz	a4, .LBB0_136
	WORD $0x05813783  // ld	a5, 88(sp)
	WORD $0x03013483  // ld	s1, 48(sp)
LBB0_134:
	WORD $0xfff70613  // addi	a2, a4, -1
	WORD $0x00d67533  // and	a0, a2, a3
	WORD $0x00155593  // srli	a1, a0, 1
	WORD $0x0165f5b3  // and	a1, a1, s6
	WORD $0x40b50533  // sub	a0, a0, a1
	WORD $0x019575b3  // and	a1, a0, s9
	WORD $0x00255513  // srli	a0, a0, 2
	WORD $0x01957533  // and	a0, a0, s9
	WORD $0x00b50533  // add	a0, a0, a1
	WORD $0x00455593  // srli	a1, a0, 4
	WORD $0x00b50533  // add	a0, a0, a1
	WORD $0x01857533  // and	a0, a0, s8
	WORD $0x02950533  // mul	a0, a0, s1
	WORD $0x03855513  // srli	a0, a0, 56
	WORD $0x00650533  // add	a0, a0, t1
	BGEU X15, X10, LBB0_292  // bgeu	a5, a0, .LBB0_292
	WORD $0x00c77733  // and	a4, a4, a2
	WORD $0x00178793  // addi	a5, a5, 1
	BNEZ X14, LBB0_134  // bnez	a4, .LBB0_134
	JMP LBB0_137  // j	.LBB0_137
LBB0_136:
	WORD $0x05813783  // ld	a5, 88(sp)
	WORD $0x03013483  // ld	s1, 48(sp)
LBB0_137:
	WORD $0x04f13c23  // sd	a5, 88(sp)
	WORD $0x0016d513  // srli	a0, a3, 1
	WORD $0x04013583  // ld	a1, 64(sp)
	WORD $0x03058e93  // addi	t4, a1, 48
	WORD $0x01657533  // and	a0, a0, s6
	WORD $0x40a686b3  // sub	a3, a3, a0
	WORD $0x0196f533  // and	a0, a3, s9
	WORD $0x0026d693  // srli	a3, a3, 2
	WORD $0x0196f5b3  // and	a1, a3, s9
	WORD $0x00b50533  // add	a0, a0, a1
	WORD $0x00455593  // srli	a1, a0, 4
	WORD $0x00b50533  // add	a0, a0, a1
	WORD $0x01857533  // and	a0, a0, s8
	WORD $0x02950533  // mul	a0, a0, s1
	WORD $0x03855513  // srli	a0, a0, 56
	WORD $0x00a30333  // add	t1, t1, a0
	WORD $0x06013583  // ld	a1, 96(sp)
	WORD $0xfc058593  // addi	a1, a1, -64
	JMP LBB0_58  // j	.LBB0_58
LBB0_138:
	WORD $0x06713423  // sd	t2, 104(sp)
	BLEZ X11, LBB0_306  // blez	a1, .LBB0_306
	WORD $0x00030993  // mv	s3, t1
	WORD $0x09010513  // addi	a0, sp, 144
	WORD $0x02850527  // vs1r.v	v10, (a0)
	WORD $0x034e9513  // slli	a0, t4, 52
	WORD $0x03455513  // srli	a0, a0, 52
	WORD $0x07010593  // addi	a1, sp, 112
	WORD $0x02858527  // vs1r.v	v10, (a1)
	WORD $0x00813583  // ld	a1, 8(sp)
	BLTU X10, X11, LBB0_154  // bltu	a0, a1, .LBB0_154
	WORD $0x07010693  // addi	a3, sp, 112
	WORD $0x02000513  // li	a0, 32
	WORD $0x06013583  // ld	a1, 96(sp)
	BLTU X11, X10, LBB0_142  // bltu	a1, a0, .LBB0_142
	WORD $0x000ec303  // lbu	t1, 0(t4)
	WORD $0x001ece03  // lbu	t3, 1(t4)
	WORD $0x002ec383  // lbu	t2, 2(t4)
	WORD $0x003ecf83  // lbu	t6, 3(t4)
	WORD $0x004eca83  // lbu	s5, 4(t4)
	WORD $0x005ec803  // lbu	a6, 5(t4)
	WORD $0x006ec503  // lbu	a0, 6(t4)
	WORD $0x04a13023  // sd	a0, 64(sp)
	WORD $0x007eca03  // lbu	s4, 7(t4)
	WORD $0x008ec483  // lbu	s1, 8(t4)
	WORD $0x009ec503  // lbu	a0, 9(t4)
	WORD $0x00aecd03  // lbu	s10, 10(t4)
	WORD $0x00bec703  // lbu	a4, 11(t4)
	WORD $0x00cec403  // lbu	s0, 12(t4)
	WORD $0x00dec683  // lbu	a3, 13(t4)
	WORD $0x00eec583  // lbu	a1, 14(t4)
	WORD $0x00b13023  // sd	a1, 0(sp)
	WORD $0x00fecb83  // lbu	s7, 15(t4)
	WORD $0x010ec583  // lbu	a1, 16(t4)
	WORD $0x011ec603  // lbu	a2, 17(t4)
	WORD $0x008e1e13  // slli	t3, t3, 8
	WORD $0x006e67b3  // or	a5, t3, t1
	WORD $0x04f13423  // sd	a5, 72(sp)
	WORD $0x012ec303  // lbu	t1, 18(t4)
	WORD $0x01039393  // slli	t2, t2, 16
	WORD $0x018f9f93  // slli	t6, t6, 24
	WORD $0x007fefb3  // or	t6, t6, t2
	WORD $0x013ec383  // lbu	t2, 19(t4)
	WORD $0x00881793  // slli	a5, a6, 8
	WORD $0x0157ee33  // or	t3, a5, s5
	WORD $0x014ec783  // lbu	a5, 20(t4)
	WORD $0x04013803  // ld	a6, 64(sp)
	WORD $0x01081813  // slli	a6, a6, 16
	WORD $0x018a1a13  // slli	s4, s4, 24
	WORD $0x010a6833  // or	a6, s4, a6
	WORD $0x015eca03  // lbu	s4, 21(t4)
	WORD $0x00851513  // slli	a0, a0, 8
	WORD $0x00956533  // or	a0, a0, s1
	WORD $0x016ec483  // lbu	s1, 22(t4)
	WORD $0x010d1d13  // slli	s10, s10, 16
	WORD $0x01871713  // slli	a4, a4, 24
	WORD $0x01a76d33  // or	s10, a4, s10
	WORD $0x017ec703  // lbu	a4, 23(t4)
	WORD $0x00869693  // slli	a3, a3, 8
	WORD $0x0086e6b3  // or	a3, a3, s0
	WORD $0x018ec403  // lbu	s0, 24(t4)
	WORD $0x00013a83  // ld	s5, 0(sp)
	WORD $0x010a9a93  // slli	s5, s5, 16
	WORD $0x018b9b93  // slli	s7, s7, 24
	WORD $0x015beab3  // or	s5, s7, s5
	WORD $0x019ecb83  // lbu	s7, 25(t4)
	WORD $0x00861613  // slli	a2, a2, 8
	WORD $0x00c5e5b3  // or	a1, a1, a2
	WORD $0x01aec603  // lbu	a2, 26(t4)
	WORD $0x01031313  // slli	t1, t1, 16
	WORD $0x01839393  // slli	t2, t2, 24
	WORD $0x0063e333  // or	t1, t2, t1
	WORD $0x01bec383  // lbu	t2, 27(t4)
	WORD $0x008a1a13  // slli	s4, s4, 8
	WORD $0x00fa6a33  // or	s4, s4, a5
	WORD $0x01cec783  // lbu	a5, 28(t4)
	WORD $0x01049493  // slli	s1, s1, 16
	WORD $0x01871713  // slli	a4, a4, 24
	WORD $0x00976733  // or	a4, a4, s1
	WORD $0x01dec483  // lbu	s1, 29(t4)
	WORD $0x008b9b93  // slli	s7, s7, 8
	WORD $0x008bebb3  // or	s7, s7, s0
	WORD $0x01eec403  // lbu	s0, 30(t4)
	WORD $0x01061613  // slli	a2, a2, 16
	WORD $0x01839393  // slli	t2, t2, 24
	WORD $0x00c3e3b3  // or	t2, t2, a2
	WORD $0x01fec603  // lbu	a2, 31(t4)
	WORD $0x00849493  // slli	s1, s1, 8
	WORD $0x0097e7b3  // or	a5, a5, s1
	WORD $0x01041413  // slli	s0, s0, 16
	WORD $0x01861613  // slli	a2, a2, 24
	WORD $0x00866633  // or	a2, a2, s0
	WORD $0x04813403  // ld	s0, 72(sp)
	WORD $0x008fe4b3  // or	s1, t6, s0
	WORD $0x01c86433  // or	s0, a6, t3
	WORD $0x00ad6533  // or	a0, s10, a0
	WORD $0x00dae6b3  // or	a3, s5, a3
	WORD $0x00b365b3  // or	a1, t1, a1
	WORD $0x01476733  // or	a4, a4, s4
	WORD $0x0173e833  // or	a6, t2, s7
	WORD $0x00f66633  // or	a2, a2, a5
	WORD $0x02041413  // slli	s0, s0, 32
	WORD $0x00946433  // or	s0, s0, s1
	WORD $0x02069693  // slli	a3, a3, 32
	WORD $0x00d56533  // or	a0, a0, a3
	WORD $0x02071713  // slli	a4, a4, 32
	WORD $0x00e5e5b3  // or	a1, a1, a4
	WORD $0x020e8e93  // addi	t4, t4, 32
	WORD $0x02061613  // slli	a2, a2, 32
	WORD $0x01066633  // or	a2, a2, a6
	WORD $0x06a13c23  // sd	a0, 120(sp)
	WORD $0x06813823  // sd	s0, 112(sp)
	WORD $0x08c13423  // sd	a2, 136(sp)
	WORD $0x08b13023  // sd	a1, 128(sp)
	WORD $0x06013403  // ld	s0, 96(sp)
	WORD $0xfe040413  // addi	s0, s0, -32
	WORD $0x09010693  // addi	a3, sp, 144
	JMP LBB0_143  // j	.LBB0_143
LBB0_142:
	WORD $0x06013403  // ld	s0, 96(sp)
LBB0_143:
	BLTU X8, X5, LBB0_145  // bltu	s0, t0, .LBB0_145
	WORD $0x000ec503  // lbu	a0, 0(t4)
	WORD $0x04a13423  // sd	a0, 72(sp)
	WORD $0x001ec303  // lbu	t1, 1(t4)
	WORD $0x002ec383  // lbu	t2, 2(t4)
	WORD $0x003ece03  // lbu	t3, 3(t4)
	WORD $0x004ecf83  // lbu	t6, 4(t4)
	WORD $0x005ec803  // lbu	a6, 5(t4)
	WORD $0x006eca03  // lbu	s4, 6(t4)
	WORD $0x007eca83  // lbu	s5, 7(t4)
	WORD $0x008ecb83  // lbu	s7, 8(t4)
	WORD $0x009ecd03  // lbu	s10, 9(t4)
	WORD $0x00aec783  // lbu	a5, 10(t4)
	WORD $0x00bec483  // lbu	s1, 11(t4)
	WORD $0x00cec503  // lbu	a0, 12(t4)
	WORD $0x00fec583  // lbu	a1, 15(t4)
	WORD $0x00eec603  // lbu	a2, 14(t4)
	WORD $0x00dec703  // lbu	a4, 13(t4)
	WORD $0x010e8e93  // addi	t4, t4, 16
	WORD $0x00b687a3  // sb	a1, 15(a3)
	WORD $0x00c68723  // sb	a2, 14(a3)
	WORD $0x00e686a3  // sb	a4, 13(a3)
	WORD $0x00a68623  // sb	a0, 12(a3)
	WORD $0x009685a3  // sb	s1, 11(a3)
	WORD $0x00f68523  // sb	a5, 10(a3)
	WORD $0x01a684a3  // sb	s10, 9(a3)
	WORD $0x01768423  // sb	s7, 8(a3)
	WORD $0x015683a3  // sb	s5, 7(a3)
	WORD $0x01468323  // sb	s4, 6(a3)
	WORD $0x010682a3  // sb	a6, 5(a3)
	WORD $0x01f68223  // sb	t6, 4(a3)
	WORD $0x01c681a3  // sb	t3, 3(a3)
	WORD $0x00768123  // sb	t2, 2(a3)
	WORD $0x006680a3  // sb	t1, 1(a3)
	WORD $0x04813503  // ld	a0, 72(sp)
	WORD $0x00a68023  // sb	a0, 0(a3)
	WORD $0x01068693  // addi	a3, a3, 16
	WORD $0xff040413  // addi	s0, s0, -16
LBB0_145:
	WORD $0x00800513  // li	a0, 8
	BLTU X8, X10, LBB0_147  // bltu	s0, a0, .LBB0_147
	WORD $0x000eb503  // ld	a0, 0(t4)
	WORD $0x008e8e93  // addi	t4, t4, 8
	WORD $0x00a6b023  // sd	a0, 0(a3)
	WORD $0x00868693  // addi	a3, a3, 8
	WORD $0xff840413  // addi	s0, s0, -8
LBB0_147:
	WORD $0x00400513  // li	a0, 4
	BLTU X8, X10, LBB0_149  // bltu	s0, a0, .LBB0_149
	WORD $0x000ea503  // lw	a0, 0(t4)
	WORD $0x004e8e93  // addi	t4, t4, 4
	WORD $0x00a6a023  // sw	a0, 0(a3)
	WORD $0x00468693  // addi	a3, a3, 4
	WORD $0xffc40413  // addi	s0, s0, -4
LBB0_149:
	WORD $0x00200513  // li	a0, 2
	BLTU X8, X10, LBB0_151  // bltu	s0, a0, .LBB0_151
	WORD $0x000e9503  // lh	a0, 0(t4)
	WORD $0x002e8613  // addi	a2, t4, 2
	WORD $0x00a69023  // sh	a0, 0(a3)
	WORD $0x00268693  // addi	a3, a3, 2
	WORD $0xffe40413  // addi	s0, s0, -2
	JMP LBB0_152  // j	.LBB0_152
LBB0_151:
	WORD $0x000e8613  // mv	a2, t4
LBB0_152:
	WORD $0x07010e93  // addi	t4, sp, 112
	BEQZ X8, LBB0_154  // beqz	s0, .LBB0_154
	WORD $0x00064503  // lbu	a0, 0(a2)
	WORD $0x00a68023  // sb	a0, 0(a3)
LBB0_154:
	WORD $0x00098313  // mv	t1, s3
	WORD $0x06813383  // ld	t2, 104(sp)
	WORD $0x00ff0ab7  // lui	s5, 4080
	WORD $0x03813e03  // ld	t3, 56(sp)
	JMP LBB0_59  // j	.LBB0_59
LBB0_155:
	BEQZ X12, LBB0_301  // beqz	a2, .LBB0_301
	WORD $0x02200693  // li	a3, 34
	BEQ X12, X13, LBB0_162  // beq	a2, a3, .LBB0_162
	WORD $0x02d00693  // li	a3, 45
	BEQ X12, X13, LBB0_28  // beq	a2, a3, .LBB0_28
	JMP LBB0_291  // j	.LBB0_291
LBB0_158:
	WORD $0x05b00693  // li	a3, 91
	BEQ X12, X13, LBB0_193  // beq	a2, a3, .LBB0_193
	WORD $0x06600693  // li	a3, 102
	BNE X12, X13, LBB0_291  // bne	a2, a3, .LBB0_291
	WORD $0x00853583  // ld	a1, 8(a0)
	WORD $0x00598513  // addi	a0, s3, 5
	BGEU X11, X10, LBB0_299  // bgeu	a1, a0, .LBB0_299
	JMP LBB0_301  // j	.LBB0_301
LBB0_161:
	WORD $0x00853583  // ld	a1, 8(a0)
	WORD $0x00498513  // addi	a0, s3, 4
	BGEU X11, X10, LBB0_299  // bgeu	a1, a0, .LBB0_299
	JMP LBB0_301  // j	.LBB0_301
LBB0_162:
	WORD $0x00853403  // ld	s0, 8(a0)
	WORD $0x40e40433  // sub	s0, s0, a4
	WORD $0x02000513  // li	a0, 32
	WORD $0x00ee87b3  // add	a5, t4, a4
	BLT X8, X10, LBB0_186  // blt	s0, a0, .LBB0_186
	WORD $0x00000313  // li	t1, 0
	WORD $0x02200593  // li	a1, 34
	WORD $0x01000513  // li	a0, 16
	WORD $0xfff00713  // li	a4, -1
	WORD $0x05c00613  // li	a2, 92
	WORD $0xaaaab6b7  // lui	a3, 699051
	WORD $0x0c0074d7  // vsetvli	s1, zero, e8, m1, ta, ma
	WORD $0x4205e457  // vmv.s.x	v8, a1
	WORD $0x555555b7  // lui	a1, 349525
	WORD $0x420664d7  // vmv.s.x	v9, a2
	WORD $0xaaa6881b  // addiw	a6, a3, -1366
	WORD $0x5555829b  // addiw	t0, a1, 1365
	WORD $0x03f00893  // li	a7, 63
LBB0_164:
	WORD $0x00000613  // li	a2, 0
	WORD $0x00078e13  // mv	t3, a5
	WORD $0x01078f93  // addi	t6, a5, 16
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x02078587  // vle8.v	v11, (a5)
	WORD $0x020f8507  // vle8.v	v10, (t6)
	WORD $0x00040f13  // mv	t5, s0
LBB0_165:
	WORD $0x00160593  // addi	a1, a2, 1
	WORD $0x0875f057  // vsetvli	zero, a1, e8, mf2, tu, ma
	WORD $0x3a864657  // vslideup.vx	v12, v8, a2
	WORD $0x00058613  // mv	a2, a1
	BNE X11, X10, LBB0_165  // bne	a1, a0, .LBB0_165
	WORD $0x00000413  // li	s0, 0
	WORD $0x00f00613  // li	a2, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62b60657  // vmseq.vv	v12, v11, v12
	WORD $0x0c807057  // vsetvli	zero, zero, e16, m1, ta, ma
	WORD $0x42c026d7  // vmv.x.s	a3, v12
	WORD $0x00f00793  // li	a5, 15
LBB0_167:
	WORD $0x00f6d5b3  // srl	a1, a3, a5
	WORD $0xfff78793  // addi	a5, a5, -1
	WORD $0x0015f593  // andi	a1, a1, 1
	WORD $0x00c595bb  // sllw	a1, a1, a2
	WORD $0x00b46433  // or	s0, s0, a1
	WORD $0xfff60613  // addi	a2, a2, -1
	BNE X15, X14, LBB0_167  // bne	a5, a4, .LBB0_167
	WORD $0x00000613  // li	a2, 0
LBB0_169:
	WORD $0x00160593  // addi	a1, a2, 1
	WORD $0x0875f057  // vsetvli	zero, a1, e8, mf2, tu, ma
	WORD $0x3a864657  // vslideup.vx	v12, v8, a2
	WORD $0x00058613  // mv	a2, a1
	BNE X11, X10, LBB0_169  // bne	a1, a0, .LBB0_169
	WORD $0x00000613  // li	a2, 0
	WORD $0x00f00693  // li	a3, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62a60657  // vmseq.vv	v12, v10, v12
	WORD $0x0c807057  // vsetvli	zero, zero, e16, m1, ta, ma
	WORD $0x42c024d7  // vmv.x.s	s1, v12
	WORD $0x00f00793  // li	a5, 15
LBB0_171:
	WORD $0x00f4d5b3  // srl	a1, s1, a5
	WORD $0xfff78793  // addi	a5, a5, -1
	WORD $0x0015f593  // andi	a1, a1, 1
	WORD $0x00d595bb  // sllw	a1, a1, a3
	WORD $0x00b66633  // or	a2, a2, a1
	WORD $0xfff68693  // addi	a3, a3, -1
	BNE X15, X14, LBB0_171  // bne	a5, a4, .LBB0_171
	WORD $0x00000693  // li	a3, 0
	WORD $0x01061613  // slli	a2, a2, 16
	WORD $0x00c40433  // add	s0, s0, a2
LBB0_173:
	WORD $0x00168593  // addi	a1, a3, 1
	WORD $0x0875f057  // vsetvli	zero, a1, e8, mf2, tu, ma
	WORD $0x3a96c657  // vslideup.vx	v12, v9, a3
	WORD $0x00058693  // mv	a3, a1
	BNE X11, X10, LBB0_173  // bne	a1, a0, .LBB0_173
	WORD $0x00000613  // li	a2, 0
	WORD $0x00f00693  // li	a3, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62b605d7  // vmseq.vv	v11, v11, v12
	WORD $0x00f00493  // li	s1, 15
LBB0_175:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x42b025d7  // vmv.x.s	a1, v11
	WORD $0x0095d5b3  // srl	a1, a1, s1
	WORD $0xfff48493  // addi	s1, s1, -1
	WORD $0x0015f593  // andi	a1, a1, 1
	WORD $0x00d595bb  // sllw	a1, a1, a3
	WORD $0x00b66633  // or	a2, a2, a1
	WORD $0xfff68693  // addi	a3, a3, -1
	BNE X9, X14, LBB0_175  // bne	s1, a4, .LBB0_175
	WORD $0x00000693  // li	a3, 0
LBB0_177:
	WORD $0x00168593  // addi	a1, a3, 1
	WORD $0x0875f057  // vsetvli	zero, a1, e8, mf2, tu, ma
	WORD $0x3a96c5d7  // vslideup.vx	v11, v9, a3
	WORD $0x00058693  // mv	a3, a1
	BNE X11, X10, LBB0_177  // bne	a1, a0, .LBB0_177
	WORD $0x00000693  // li	a3, 0
	WORD $0x00f00493  // li	s1, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62a58557  // vmseq.vv	v10, v10, v11
	WORD $0x00f00793  // li	a5, 15
LBB0_179:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x42a025d7  // vmv.x.s	a1, v10
	WORD $0x00f5d5b3  // srl	a1, a1, a5
	WORD $0xfff78793  // addi	a5, a5, -1
	WORD $0x0015f593  // andi	a1, a1, 1
	WORD $0x009595bb  // sllw	a1, a1, s1
	WORD $0x00b6e6b3  // or	a3, a3, a1
	WORD $0xfff48493  // addi	s1, s1, -1
	BNE X15, X14, LBB0_179  // bne	a5, a4, .LBB0_179
	WORD $0x02041413  // slli	s0, s0, 32
	WORD $0x01069693  // slli	a3, a3, 16
	WORD $0x00c686bb  // addw	a3, a3, a2
	WORD $0x02045613  // srli	a2, s0, 32
	BNEZ X13, LBB0_182  // bnez	a3, .LBB0_182
	BEQZ X6, LBB0_183  // beqz	t1, .LBB0_183
LBB0_182:
	WORD $0xfff34593  // not	a1, t1
	WORD $0x0106f7b3  // and	a5, a3, a6
	WORD $0x00d5f5b3  // and	a1, a1, a3
	WORD $0x02159693  // slli	a3, a1, 33
	WORD $0x0206d693  // srli	a3, a3, 32
	WORD $0x0066e6b3  // or	a3, a3, t1
	WORD $0xfff6c493  // not	s1, a3
	WORD $0x0097f7b3  // and	a5, a5, s1
	WORD $0x00b784bb  // addw	s1, a5, a1
	WORD $0x0007841b  // sext.w	s0, a5
	WORD $0x00f585b3  // add	a1, a1, a5
	WORD $0x0084b333  // sltu	t1, s1, s0
	WORD $0x00159593  // slli	a1, a1, 1
	WORD $0x0055c5b3  // xor	a1, a1, t0
	WORD $0x00d5f5b3  // and	a1, a1, a3
	WORD $0xfff5c593  // not	a1, a1
	WORD $0x00b67633  // and	a2, a2, a1
LBB0_183:
	BNEZ X12, LBB0_297  // bnez	a2, .LBB0_297
	WORD $0x010f8793  // addi	a5, t6, 16
	WORD $0xfe0f0413  // addi	s0, t5, -32
	BLT X17, X30, LBB0_164  // blt	a7, t5, .LBB0_164
	BNEZ X6, LBB0_307  // bnez	t1, .LBB0_307
LBB0_186:
	BLEZ X8, LBB0_301  // blez	s0, .LBB0_301
LBB0_187:
	WORD $0x05c00513  // li	a0, 92
	WORD $0x02200613  // li	a2, 34
	WORD $0xfff00393  // li	t2, -1
LBB0_188:
	WORD $0x0007c683  // lbu	a3, 0(a5)
	BEQ X13, X10, LBB0_191  // beq	a3, a0, .LBB0_191
	BEQ X13, X12, LBB0_303  // beq	a3, a2, .LBB0_303
	WORD $0xfff00693  // li	a3, -1
	WORD $0x00100713  // li	a4, 1
	JMP LBB0_192  // j	.LBB0_192
LBB0_191:
	WORD $0xffe00693  // li	a3, -2
	WORD $0x00200713  // li	a4, 2
LBB0_192:
	WORD $0x00e787b3  // add	a5, a5, a4
	WORD $0x00d40433  // add	s0, s0, a3
	BGTZ X8, LBB0_188  // bgtz	s0, .LBB0_188
	JMP LBB0_301  // j	.LBB0_301
LBB0_193:
	WORD $0x01313c23  // sd	s3, 24(sp)
	WORD $0x03213423  // sd	s2, 40(sp)
	WORD $0x00000a93  // li	s5, 0
	WORD $0x00000593  // li	a1, 0
	WORD $0x00000313  // li	t1, 0
	WORD $0x06013023  // sd	zero, 96(sp)
	MOV $·p7c48db41412b1d2_LCPI0_3(SB), X17  // lui	a7, %hi(.LCPI0_3)
	MOV $·p7c48db41412b1d2_LCPI0_4(SB), X18  // lui	s2, %hi(.LCPI0_4)
	MOV $·p7c48db41412b1d2_LCPI0_5(SB), X31  // lui	t6, %hi(.LCPI0_5)
	MOV $·p7c48db41412b1d2_LCPI0_6(SB), X19  // lui	s3, %hi(.LCPI0_6)
	MOV $·p7c48db41412b1d2_LCPI0_7(SB), X23  // lui	s7, %hi(.LCPI0_7)
	MOV $·p7c48db41412b1d2_LCPI0_8(SB), X24  // lui	s8, %hi(.LCPI0_8)
	WORD $0x02a13023  // sd	a0, 32(sp)
	WORD $0x00853483  // ld	s1, 8(a0)
	WORD $0x00ee8eb3  // add	t4, t4, a4
	WORD $0x02200413  // li	s0, 34
	WORD $0x01000293  // li	t0, 16
	WORD $0xfff00f13  // li	t5, -1
	WORD $0x05c00613  // li	a2, 92
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x5e0fb457  // vmv.v.i	v8, -1
	WORD $0x00ff03b7  // lui	t2, 4080
	WORD $0x00010cb7  // lui	s9, 16
	MOV $·p7c48db41412b1d2_LCPI0_9(SB), X26  // lui	s10, %hi(.LCPI0_9)
	MOV $·p7c48db41412b1d2_LCPI0_10(SB), X15  // lui	a5, %hi(.LCPI0_10)
	WORD $0x5e00b057  // vmv.v.i	v0, 1
	WORD $0x4206e4d7  // vmv.s.x	v9, a3
	WORD $0x05d00693  // li	a3, 93
	MOV $·p7c48db41412b1d2_LCPI0_11(SB), X16  // lui	a6, %hi(.LCPI0_11)
	WORD $0xcd827057  // vsetivli	zero, 4, e64, m1, ta, ma
	WORD $0x5e003557  // vmv.v.i	v10, 0
	WORD $0x00001e37  // lui	t3, 1
	WORD $0x420465d7  // vmv.s.x	v11, s0
	WORD $0x42066657  // vmv.s.x	v12, a2
	WORD $0x4206e6d7  // vmv.s.x	v13, a3
	MOV (X17), X10  // ld	a0, %lo(.LCPI0_3)(a7)
	WORD $0x00a13823  // sd	a0, 16(sp)
	MOV (X18), X18  // ld	s2, %lo(.LCPI0_4)(s2)
	MOV (X31), X22  // ld	s6, %lo(.LCPI0_5)(t6)
	MOV (X19), X1  // ld	ra, %lo(.LCPI0_6)(s3)
	MOV (X23), g  // ld	s11, %lo(.LCPI0_7)(s7)
	MOV (X24), X17  // ld	a7, %lo(.LCPI0_8)(s8)
	WORD $0xf00c8a1b  // addiw	s4, s9, -256
	MOV (X26), X24  // ld	s8, %lo(.LCPI0_9)(s10)
	MOV (X15), X25  // ld	s9, %lo(.LCPI0_10)(a5)
	MOV (X16), X10  // ld	a0, %lo(.LCPI0_11)(a6)
	WORD $0x02a13823  // sd	a0, 48(sp)
	WORD $0xfc1e051b  // addiw	a0, t3, -63
	WORD $0x00a13423  // sd	a0, 8(sp)
	WORD $0x40e484b3  // sub	s1, s1, a4
	WORD $0x03413c23  // sd	s4, 56(sp)
LBB0_194:
	WORD $0x04000513  // li	a0, 64
	WORD $0x06913423  // sd	s1, 104(sp)
	WORD $0x05513c23  // sd	s5, 88(sp)
	BLT X9, X10, LBB0_274  // blt	s1, a0, .LBB0_274
LBB0_195:
	WORD $0x00000693  // li	a3, 0
	WORD $0x020e8613  // addi	a2, t4, 32
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x02060787  // vle8.v	v15, (a2)
	WORD $0x010e8513  // addi	a0, t4, 16
	WORD $0x020e8887  // vle8.v	v17, (t4)
	WORD $0x030e8613  // addi	a2, t4, 48
	WORD $0x04a13023  // sd	a0, 64(sp)
	WORD $0x02050807  // vle8.v	v16, (a0)
	WORD $0x02060707  // vle8.v	v14, (a2)
LBB0_196:
	WORD $0x00168613  // addi	a2, a3, 1
	WORD $0x08767057  // vsetvli	zero, a2, e8, mf2, tu, ma
	WORD $0x3ab6c957  // vslideup.vx	v18, v11, a3
	WORD $0x00060693  // mv	a3, a2
	BNE X12, X5, LBB0_196  // bne	a2, t0, .LBB0_196
	WORD $0x00000e93  // li	t4, 0
	WORD $0x00f00693  // li	a3, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x63190957  // vmseq.vv	v18, v17, v18
	WORD $0x0c807057  // vsetvli	zero, zero, e16, m1, ta, ma
	WORD $0x43202657  // vmv.x.s	a2, v18
	WORD $0x00f00713  // li	a4, 15
LBB0_198:
	WORD $0x00e657b3  // srl	a5, a2, a4
	WORD $0xfff70713  // addi	a4, a4, -1
	WORD $0x0017f793  // andi	a5, a5, 1
	WORD $0x00d797bb  // sllw	a5, a5, a3
	WORD $0x01d7eeb3  // or	t4, a5, t4
	WORD $0xfff68693  // addi	a3, a3, -1
	BNE X14, X30, LBB0_198  // bne	a4, t5, .LBB0_198
	WORD $0x00000613  // li	a2, 0
LBB0_200:
	WORD $0x00160693  // addi	a3, a2, 1
	WORD $0x0876f057  // vsetvli	zero, a3, e8, mf2, tu, ma
	WORD $0x3ab64957  // vslideup.vx	v18, v11, a2
	WORD $0x00068613  // mv	a2, a3
	BNE X13, X5, LBB0_200  // bne	a3, t0, .LBB0_200
	WORD $0x00000693  // li	a3, 0
	WORD $0x00f00713  // li	a4, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x63090957  // vmseq.vv	v18, v16, v18
	WORD $0x00f00613  // li	a2, 15
LBB0_202:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x432027d7  // vmv.x.s	a5, v18
	WORD $0x00c7d7b3  // srl	a5, a5, a2
	WORD $0xfff60613  // addi	a2, a2, -1
	WORD $0x0017f793  // andi	a5, a5, 1
	WORD $0x00e797bb  // sllw	a5, a5, a4
	WORD $0x00f6e6b3  // or	a3, a3, a5
	WORD $0xfff70713  // addi	a4, a4, -1
	BNE X12, X30, LBB0_202  // bne	a2, t5, .LBB0_202
	WORD $0x00000613  // li	a2, 0
LBB0_204:
	WORD $0x00160713  // addi	a4, a2, 1
	WORD $0x08777057  // vsetvli	zero, a4, e8, mf2, tu, ma
	WORD $0x3ab64957  // vslideup.vx	v18, v11, a2
	WORD $0x00070613  // mv	a2, a4
	BNE X14, X5, LBB0_204  // bne	a4, t0, .LBB0_204
	WORD $0x00000713  // li	a4, 0
	WORD $0x00f00493  // li	s1, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62f90957  // vmseq.vv	v18, v15, v18
	WORD $0x00f00613  // li	a2, 15
LBB0_206:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x432027d7  // vmv.x.s	a5, v18
	WORD $0x00c7d7b3  // srl	a5, a5, a2
	WORD $0xfff60613  // addi	a2, a2, -1
	WORD $0x0017f793  // andi	a5, a5, 1
	WORD $0x009797bb  // sllw	a5, a5, s1
	WORD $0x00f76733  // or	a4, a4, a5
	WORD $0xfff48493  // addi	s1, s1, -1
	BNE X12, X30, LBB0_206  // bne	a2, t5, .LBB0_206
	WORD $0x00000613  // li	a2, 0
LBB0_208:
	WORD $0x00160793  // addi	a5, a2, 1
	WORD $0x0877f057  // vsetvli	zero, a5, e8, mf2, tu, ma
	WORD $0x3ab64957  // vslideup.vx	v18, v11, a2
	WORD $0x00078613  // mv	a2, a5
	BNE X15, X5, LBB0_208  // bne	a5, t0, .LBB0_208
	WORD $0x00000493  // li	s1, 0
	WORD $0x00f00413  // li	s0, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62e90957  // vmseq.vv	v18, v14, v18
	WORD $0x00f00613  // li	a2, 15
LBB0_210:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x432027d7  // vmv.x.s	a5, v18
	WORD $0x00c7d7b3  // srl	a5, a5, a2
	WORD $0xfff60613  // addi	a2, a2, -1
	WORD $0x0017f793  // andi	a5, a5, 1
	WORD $0x008797bb  // sllw	a5, a5, s0
	WORD $0x00f4e4b3  // or	s1, s1, a5
	WORD $0xfff40413  // addi	s0, s0, -1
	BNE X12, X30, LBB0_210  // bne	a2, t5, .LBB0_210
	WORD $0x00000793  // li	a5, 0
	WORD $0x02071713  // slli	a4, a4, 32
	WORD $0x03069613  // slli	a2, a3, 48
	WORD $0x02065613  // srli	a2, a2, 32
LBB0_212:
	WORD $0x00178693  // addi	a3, a5, 1
	WORD $0x0876f057  // vsetvli	zero, a3, e8, mf2, tu, ma
	WORD $0x3ac7c957  // vslideup.vx	v18, v12, a5
	WORD $0x00068793  // mv	a5, a3
	BNE X13, X5, LBB0_212  // bne	a3, t0, .LBB0_212
	WORD $0x00000693  // li	a3, 0
	WORD $0x03049493  // slli	s1, s1, 48
	WORD $0x00e484b3  // add	s1, s1, a4
	WORD $0x00f00713  // li	a4, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x63190957  // vmseq.vv	v18, v17, v18
	WORD $0x00c4efb3  // or	t6, s1, a2
	WORD $0x00f00613  // li	a2, 15
LBB0_214:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x432027d7  // vmv.x.s	a5, v18
	WORD $0x00c7d7b3  // srl	a5, a5, a2
	WORD $0xfff60613  // addi	a2, a2, -1
	WORD $0x0017f793  // andi	a5, a5, 1
	WORD $0x00e797bb  // sllw	a5, a5, a4
	WORD $0x00f6e6b3  // or	a3, a3, a5
	WORD $0xfff70713  // addi	a4, a4, -1
	BNE X12, X30, LBB0_214  // bne	a2, t5, .LBB0_214
	WORD $0x00000613  // li	a2, 0
LBB0_216:
	WORD $0x00160713  // addi	a4, a2, 1
	WORD $0x08777057  // vsetvli	zero, a4, e8, mf2, tu, ma
	WORD $0x3ac64957  // vslideup.vx	v18, v12, a2
	WORD $0x00070613  // mv	a2, a4
	BNE X14, X5, LBB0_216  // bne	a4, t0, .LBB0_216
	WORD $0x00000413  // li	s0, 0
	WORD $0x00f00713  // li	a4, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x63090957  // vmseq.vv	v18, v16, v18
	WORD $0x00f00613  // li	a2, 15
LBB0_218:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x432027d7  // vmv.x.s	a5, v18
	WORD $0x00c7d7b3  // srl	a5, a5, a2
	WORD $0xfff60613  // addi	a2, a2, -1
	WORD $0x0017f793  // andi	a5, a5, 1
	WORD $0x00e797bb  // sllw	a5, a5, a4
	WORD $0x00f46433  // or	s0, s0, a5
	WORD $0xfff70713  // addi	a4, a4, -1
	BNE X12, X30, LBB0_218  // bne	a2, t5, .LBB0_218
	WORD $0x00000613  // li	a2, 0
LBB0_220:
	WORD $0x00160713  // addi	a4, a2, 1
	WORD $0x08777057  // vsetvli	zero, a4, e8, mf2, tu, ma
	WORD $0x3ac64957  // vslideup.vx	v18, v12, a2
	WORD $0x00070613  // mv	a2, a4
	BNE X14, X5, LBB0_220  // bne	a4, t0, .LBB0_220
	WORD $0x00000713  // li	a4, 0
	WORD $0x00f00493  // li	s1, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62f90957  // vmseq.vv	v18, v15, v18
	WORD $0x00f00613  // li	a2, 15
LBB0_222:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x432027d7  // vmv.x.s	a5, v18
	WORD $0x00c7d7b3  // srl	a5, a5, a2
	WORD $0xfff60613  // addi	a2, a2, -1
	WORD $0x0017f793  // andi	a5, a5, 1
	WORD $0x009797bb  // sllw	a5, a5, s1
	WORD $0x00f76733  // or	a4, a4, a5
	WORD $0xfff48493  // addi	s1, s1, -1
	BNE X12, X30, LBB0_222  // bne	a2, t5, .LBB0_222
	WORD $0x00000613  // li	a2, 0
LBB0_224:
	WORD $0x00160793  // addi	a5, a2, 1
	WORD $0x0877f057  // vsetvli	zero, a5, e8, mf2, tu, ma
	WORD $0x3ac64957  // vslideup.vx	v18, v12, a2
	WORD $0x00078613  // mv	a2, a5
	BNE X15, X5, LBB0_224  // bne	a5, t0, .LBB0_224
	WORD $0x00000493  // li	s1, 0
	WORD $0x00f00993  // li	s3, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62e90957  // vmseq.vv	v18, v14, v18
	WORD $0x00f00613  // li	a2, 15
LBB0_226:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x432027d7  // vmv.x.s	a5, v18
	WORD $0x00c7d7b3  // srl	a5, a5, a2
	WORD $0xfff60613  // addi	a2, a2, -1
	WORD $0x0017f793  // andi	a5, a5, 1
	WORD $0x013797bb  // sllw	a5, a5, s3
	WORD $0x00f4e4b3  // or	s1, s1, a5
	WORD $0xfff98993  // addi	s3, s3, -1
	BNE X12, X30, LBB0_226  // bne	a2, t5, .LBB0_226
	WORD $0x03049493  // slli	s1, s1, 48
	WORD $0x02071713  // slli	a4, a4, 32
	WORD $0x03041413  // slli	s0, s0, 48
	WORD $0x00970733  // add	a4, a4, s1
	WORD $0x02045413  // srli	s0, s0, 32
	WORD $0x00876733  // or	a4, a4, s0
	WORD $0x00e686b3  // add	a3, a3, a4
	WORD $0x00b6e633  // or	a2, a3, a1
	BNEZ X12, LBB0_229  // bnez	a2, .LBB0_229
	WORD $0x00000513  // li	a0, 0
	WORD $0x00000693  // li	a3, 0
	JMP LBB0_230  // j	.LBB0_230
LBB0_229:
	WORD $0xfff5c613  // not	a2, a1
	WORD $0x01013703  // ld	a4, 16(sp)
	WORD $0x00d77733  // and	a4, a4, a3
	WORD $0x00d67633  // and	a2, a2, a3
	WORD $0x00161693  // slli	a3, a2, 1
	WORD $0x00b6e6b3  // or	a3, a3, a1
	WORD $0xfff6c793  // not	a5, a3
	WORD $0x00f77733  // and	a4, a4, a5
	WORD $0x00e60633  // add	a2, a2, a4
	WORD $0x00e63533  // sltu	a0, a2, a4
	WORD $0x00161613  // slli	a2, a2, 1
	WORD $0x01664633  // xor	a2, a2, s6
	WORD $0x00c6f6b3  // and	a3, a3, a2
LBB0_230:
	WORD $0x04613823  // sd	t1, 80(sp)
	WORD $0x00000613  // li	a2, 0
	WORD $0x01fe8eb3  // add	t4, t4, t6
	WORD $0xfff6c693  // not	a3, a3
	WORD $0x00def833  // and	a6, t4, a3
LBB0_231:
	WORD $0x00160713  // addi	a4, a2, 1
	WORD $0x08777057  // vsetvli	zero, a4, e8, mf2, tu, ma
	WORD $0x3a864957  // vslideup.vx	v18, v8, a2
	WORD $0x00070613  // mv	a2, a4
	BNE X14, X5, LBB0_231  // bne	a4, t0, .LBB0_231
	WORD $0x04a13423  // sd	a0, 72(sp)
	WORD $0x00000413  // li	s0, 0
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x332039d7  // vrgather.vi	v19, v18, 0
	WORD $0x5e098957  // vmv.v.v	v18, v19
	WORD $0x09807057  // vsetvli	zero, zero, e64, m1, tu, ma
	WORD $0x42086957  // vmv.s.x	v18, a6
	WORD $0x00100e93  // li	t4, 1
LBB0_233:
	WORD $0xcd80f057  // vsetivli	zero, 1, e64, m1, ta, ma
	WORD $0x3f244a57  // vslidedown.vx	v20, v18, s0
	WORD $0x43402657  // vmv.x.s	a2, v20
	WORD $0x0186579b  // srliw	a5, a2, 24
	WORD $0x007674b3  // and	s1, a2, t2
	WORD $0x03861693  // slli	a3, a2, 56
	WORD $0x01467733  // and	a4, a2, s4
	WORD $0x02079793  // slli	a5, a5, 32
	WORD $0x01849493  // slli	s1, s1, 24
	WORD $0x0097e7b3  // or	a5, a5, s1
	WORD $0x02865493  // srli	s1, a2, 40
	WORD $0x02871713  // slli	a4, a4, 40
	WORD $0x00e6e6b3  // or	a3, a3, a4
	WORD $0x03865713  // srli	a4, a2, 56
	WORD $0x0144f4b3  // and	s1, s1, s4
	WORD $0x00976733  // or	a4, a4, s1
	WORD $0x00f6e6b3  // or	a3, a3, a5
	WORD $0x01865793  // srli	a5, a2, 24
	WORD $0x00865613  // srli	a2, a2, 8
	WORD $0x0077f7b3  // and	a5, a5, t2
	WORD $0x0186561b  // srliw	a2, a2, 24
	WORD $0x01861613  // slli	a2, a2, 24
	WORD $0x00f66633  // or	a2, a2, a5
	WORD $0x00140793  // addi	a5, s0, 1
	WORD $0x001ef493  // andi	s1, t4, 1
	WORD $0x00e66633  // or	a2, a2, a4
	WORD $0x00d66633  // or	a2, a2, a3
	WORD $0x00465693  // srli	a3, a2, 4
	WORD $0x01867633  // and	a2, a2, s8
	WORD $0x0186f6b3  // and	a3, a3, s8
	WORD $0x00461613  // slli	a2, a2, 4
	WORD $0x00d66633  // or	a2, a2, a3
	WORD $0x00265693  // srli	a3, a2, 2
	WORD $0x01967633  // and	a2, a2, s9
	WORD $0x0196f6b3  // and	a3, a3, s9
	WORD $0x00261613  // slli	a2, a2, 2
	WORD $0x00d66633  // or	a2, a2, a3
	WORD $0x00165693  // srli	a3, a2, 1
	WORD $0x01667633  // and	a2, a2, s6
	WORD $0x0166f6b3  // and	a3, a3, s6
	WORD $0x00161613  // slli	a2, a2, 1
	WORD $0x00d66633  // or	a2, a2, a3
	WORD $0x42066a57  // vmv.s.x	v20, a2
	WORD $0x0987f057  // vsetvli	zero, a5, e64, m1, tu, ma
	WORD $0x3b444957  // vslideup.vx	v18, v20, s0
	WORD $0x00100413  // li	s0, 1
	WORD $0x00000e93  // li	t4, 0
	BNEZ X9, LBB0_233  // bnez	s1, .LBB0_233
	WORD $0x00000e93  // li	t4, 0
	WORD $0xc5817057  // vsetivli	zero, 2, e64, m1, ta, mu
	WORD $0x3b286a57  // vslide1up.vx	v20, v18, a6
	WORD $0x3130b957  // vrgather.vi	v18, v19, 1, v0.t
	WORD $0x00100813  // li	a6, 1
LBB0_235:
	WORD $0xcd80f057  // vsetivli	zero, 1, e64, m1, ta, ma
	WORD $0x3f4ecad7  // vslidedown.vx	v21, v20, t4
	WORD $0x43502657  // vmv.x.s	a2, v21
	WORD $0x3f2ecad7  // vslidedown.vx	v21, v18, t4
	WORD $0x43502757  // vmv.x.s	a4, v21
	WORD $0x01167fb3  // and	t6, a2, a7
	WORD $0x01b674b3  // and	s1, a2, s11
	WORD $0x001676b3  // and	a3, a2, ra
	WORD $0x012679b3  // and	s3, a2, s2
	WORD $0x01177433  // and	s0, a4, a7
	WORD $0x01b777b3  // and	a5, a4, s11
	WORD $0x00177633  // and	a2, a4, ra
	WORD $0x01277733  // and	a4, a4, s2
	WORD $0x028f8e33  // mul	t3, t6, s0
	WORD $0x02e48d33  // mul	s10, s1, a4
	WORD $0x02c68333  // mul	t1, a3, a2
	WORD $0x02f983b3  // mul	t2, s3, a5
	WORD $0x02ff8533  // mul	a0, t6, a5
	WORD $0x02848a33  // mul	s4, s1, s0
	WORD $0x02e685b3  // mul	a1, a3, a4
	WORD $0x02c98bb3  // mul	s7, s3, a2
	WORD $0x02cf8ab3  // mul	s5, t6, a2
	WORD $0x02c48633  // mul	a2, s1, a2
	WORD $0x02f484b3  // mul	s1, s1, a5
	WORD $0x02f687b3  // mul	a5, a3, a5
	WORD $0x028686b3  // mul	a3, a3, s0
	WORD $0x02ef8fb3  // mul	t6, t6, a4
	WORD $0x02e98733  // mul	a4, s3, a4
	WORD $0x028989b3  // mul	s3, s3, s0
	WORD $0x01ae4e33  // xor	t3, t3, s10
	WORD $0x00734433  // xor	s0, t1, t2
	WORD $0x01454333  // xor	t1, a0, s4
	WORD $0x0175c5b3  // xor	a1, a1, s7
	WORD $0x001e8513  // addi	a0, t4, 1
	WORD $0x00187393  // andi	t2, a6, 1
	WORD $0x009ac4b3  // xor	s1, s5, s1
	WORD $0x00e6c6b3  // xor	a3, a3, a4
	WORD $0x00cfc633  // xor	a2, t6, a2
	WORD $0x0137c733  // xor	a4, a5, s3
	WORD $0x008e47b3  // xor	a5, t3, s0
	WORD $0x00b345b3  // xor	a1, t1, a1
	WORD $0x0096c6b3  // xor	a3, a3, s1
	WORD $0x00e64633  // xor	a2, a2, a4
	WORD $0x0117f733  // and	a4, a5, a7
	WORD $0x01b5f5b3  // and	a1, a1, s11
	WORD $0x0016f6b3  // and	a3, a3, ra
	WORD $0x01267633  // and	a2, a2, s2
	WORD $0x00e5e5b3  // or	a1, a1, a4
	WORD $0x00d66633  // or	a2, a2, a3
	WORD $0x00c5e5b3  // or	a1, a1, a2
	WORD $0x4205ead7  // vmv.s.x	v21, a1
	WORD $0x09857057  // vsetvli	zero, a0, e64, m1, tu, ma
	WORD $0x3b5ec9d7  // vslideup.vx	v19, v21, t4
	WORD $0x00100e93  // li	t4, 1
	WORD $0x00000813  // li	a6, 0
	BNEZ X7, LBB0_235  // bnez	t2, .LBB0_235
	WORD $0x00000613  // li	a2, 0
	WORD $0x43302557  // vmv.x.s	a0, v19
	WORD $0x05813583  // ld	a1, 88(sp)
	WORD $0x00b54833  // xor	a6, a0, a1
LBB0_237:
	WORD $0x00160513  // addi	a0, a2, 1
	WORD $0x08757057  // vsetvli	zero, a0, e8, mf2, tu, ma
	WORD $0x3a964957  // vslideup.vx	v18, v9, a2
	WORD $0x00050613  // mv	a2, a0
	BNE X10, X5, LBB0_237  // bne	a0, t0, .LBB0_237
	WORD $0x00000413  // li	s0, 0
	WORD $0x00f00693  // li	a3, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x63190957  // vmseq.vv	v18, v17, v18
	WORD $0x00f00613  // li	a2, 15
	WORD $0x05013303  // ld	t1, 80(sp)
LBB0_239:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x43202557  // vmv.x.s	a0, v18
	WORD $0x00c55533  // srl	a0, a0, a2
	WORD $0xfff60613  // addi	a2, a2, -1
	WORD $0x00157513  // andi	a0, a0, 1
	WORD $0x00d5153b  // sllw	a0, a0, a3
	WORD $0x00a46433  // or	s0, s0, a0
	WORD $0xfff68693  // addi	a3, a3, -1
	BNE X12, X30, LBB0_239  // bne	a2, t5, .LBB0_239
	WORD $0x00000613  // li	a2, 0
LBB0_241:
	WORD $0x00160513  // addi	a0, a2, 1
	WORD $0x08757057  // vsetvli	zero, a0, e8, mf2, tu, ma
	WORD $0x3a964957  // vslideup.vx	v18, v9, a2
	WORD $0x00050613  // mv	a2, a0
	BNE X10, X5, LBB0_241  // bne	a0, t0, .LBB0_241
	WORD $0x00000693  // li	a3, 0
	WORD $0x00f00713  // li	a4, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x63090957  // vmseq.vv	v18, v16, v18
	WORD $0x00f00613  // li	a2, 15
	WORD $0x00ff03b7  // lui	t2, 4080
	WORD $0x03813a03  // ld	s4, 56(sp)
LBB0_243:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x43202557  // vmv.x.s	a0, v18
	WORD $0x00c55533  // srl	a0, a0, a2
	WORD $0xfff60613  // addi	a2, a2, -1
	WORD $0x00157513  // andi	a0, a0, 1
	WORD $0x00e5153b  // sllw	a0, a0, a4
	WORD $0x00a6e6b3  // or	a3, a3, a0
	WORD $0xfff70713  // addi	a4, a4, -1
	BNE X12, X30, LBB0_243  // bne	a2, t5, .LBB0_243
	WORD $0x00000613  // li	a2, 0
LBB0_245:
	WORD $0x00160513  // addi	a0, a2, 1
	WORD $0x08757057  // vsetvli	zero, a0, e8, mf2, tu, ma
	WORD $0x3a964957  // vslideup.vx	v18, v9, a2
	WORD $0x00050613  // mv	a2, a0
	BNE X10, X5, LBB0_245  // bne	a0, t0, .LBB0_245
	WORD $0x00000713  // li	a4, 0
	WORD $0x00f00493  // li	s1, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62f90957  // vmseq.vv	v18, v15, v18
	WORD $0x00f00613  // li	a2, 15
LBB0_247:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x43202557  // vmv.x.s	a0, v18
	WORD $0x00c55533  // srl	a0, a0, a2
	WORD $0xfff60613  // addi	a2, a2, -1
	WORD $0x00157513  // andi	a0, a0, 1
	WORD $0x0095153b  // sllw	a0, a0, s1
	WORD $0x00a76733  // or	a4, a4, a0
	WORD $0xfff48493  // addi	s1, s1, -1
	BNE X12, X30, LBB0_247  // bne	a2, t5, .LBB0_247
	WORD $0x00000613  // li	a2, 0
LBB0_249:
	WORD $0x00160513  // addi	a0, a2, 1
	WORD $0x08757057  // vsetvli	zero, a0, e8, mf2, tu, ma
	WORD $0x3a964957  // vslideup.vx	v18, v9, a2
	WORD $0x00050613  // mv	a2, a0
	BNE X10, X5, LBB0_249  // bne	a0, t0, .LBB0_249
	WORD $0x00000493  // li	s1, 0
	WORD $0x00f00613  // li	a2, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62e90957  // vmseq.vv	v18, v14, v18
	WORD $0x00f00793  // li	a5, 15
LBB0_251:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x43202557  // vmv.x.s	a0, v18
	WORD $0x00f55533  // srl	a0, a0, a5
	WORD $0xfff78793  // addi	a5, a5, -1
	WORD $0x00157513  // andi	a0, a0, 1
	WORD $0x00c5153b  // sllw	a0, a0, a2
	WORD $0x00a4e4b3  // or	s1, s1, a0
	WORD $0xfff60613  // addi	a2, a2, -1
	BNE X15, X30, LBB0_251  // bne	a5, t5, .LBB0_251
	WORD $0x00000793  // li	a5, 0
	WORD $0x02071713  // slli	a4, a4, 32
	WORD $0x03069613  // slli	a2, a3, 48
	WORD $0x02065613  // srli	a2, a2, 32
	WORD $0xfff84e93  // not	t4, a6
LBB0_253:
	WORD $0x00178513  // addi	a0, a5, 1
	WORD $0x08757057  // vsetvli	zero, a0, e8, mf2, tu, ma
	WORD $0x3ad7c957  // vslideup.vx	v18, v13, a5
	WORD $0x00050793  // mv	a5, a0
	BNE X10, X5, LBB0_253  // bne	a0, t0, .LBB0_253
	WORD $0x00000693  // li	a3, 0
	WORD $0x03049493  // slli	s1, s1, 48
	WORD $0x00970733  // add	a4, a4, s1
	WORD $0x00e66633  // or	a2, a2, a4
	WORD $0x00f00713  // li	a4, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x631908d7  // vmseq.vv	v17, v17, v18
	WORD $0x00860fb3  // add	t6, a2, s0
	WORD $0x00f00613  // li	a2, 15
LBB0_255:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x43102557  // vmv.x.s	a0, v17
	WORD $0x00c55533  // srl	a0, a0, a2
	WORD $0xfff60613  // addi	a2, a2, -1
	WORD $0x00157513  // andi	a0, a0, 1
	WORD $0x00e5153b  // sllw	a0, a0, a4
	WORD $0x00a6e6b3  // or	a3, a3, a0
	WORD $0xfff70713  // addi	a4, a4, -1
	BNE X12, X30, LBB0_255  // bne	a2, t5, .LBB0_255
	WORD $0x00000613  // li	a2, 0
	WORD $0x43f85a93  // srai	s5, a6, 63
LBB0_257:
	WORD $0x00160513  // addi	a0, a2, 1
	WORD $0x08757057  // vsetvli	zero, a0, e8, mf2, tu, ma
	WORD $0x3ad648d7  // vslideup.vx	v17, v13, a2
	WORD $0x00050613  // mv	a2, a0
	BNE X10, X5, LBB0_257  // bne	a0, t0, .LBB0_257
	WORD $0x00000413  // li	s0, 0
	WORD $0x00f00613  // li	a2, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x63088857  // vmseq.vv	v16, v16, v17
	WORD $0x00f00713  // li	a4, 15
LBB0_259:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x43002557  // vmv.x.s	a0, v16
	WORD $0x00e55533  // srl	a0, a0, a4
	WORD $0xfff70713  // addi	a4, a4, -1
	WORD $0x00157513  // andi	a0, a0, 1
	WORD $0x00c5153b  // sllw	a0, a0, a2
	WORD $0x00a46433  // or	s0, s0, a0
	WORD $0xfff60613  // addi	a2, a2, -1
	BNE X14, X30, LBB0_259  // bne	a4, t5, .LBB0_259
	WORD $0x00000613  // li	a2, 0
LBB0_261:
	WORD $0x00160513  // addi	a0, a2, 1
	WORD $0x08757057  // vsetvli	zero, a0, e8, mf2, tu, ma
	WORD $0x3ad64857  // vslideup.vx	v16, v13, a2
	WORD $0x00050613  // mv	a2, a0
	BNE X10, X5, LBB0_261  // bne	a0, t0, .LBB0_261
	WORD $0x00000713  // li	a4, 0
	WORD $0x00f00613  // li	a2, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62f807d7  // vmseq.vv	v15, v15, v16
	WORD $0x00f00793  // li	a5, 15
LBB0_263:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x42f02557  // vmv.x.s	a0, v15
	WORD $0x00f55533  // srl	a0, a0, a5
	WORD $0xfff78793  // addi	a5, a5, -1
	WORD $0x00157513  // andi	a0, a0, 1
	WORD $0x00c5153b  // sllw	a0, a0, a2
	WORD $0x00a76733  // or	a4, a4, a0
	WORD $0xfff60613  // addi	a2, a2, -1
	BNE X15, X30, LBB0_263  // bne	a5, t5, .LBB0_263
	WORD $0x00000613  // li	a2, 0
LBB0_265:
	WORD $0x00160513  // addi	a0, a2, 1
	WORD $0x08757057  // vsetvli	zero, a0, e8, mf2, tu, ma
	WORD $0x3ad647d7  // vslideup.vx	v15, v13, a2
	WORD $0x00050613  // mv	a2, a0
	BNE X10, X5, LBB0_265  // bne	a0, t0, .LBB0_265
	WORD $0x00000493  // li	s1, 0
	WORD $0x00f00613  // li	a2, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62e78757  // vmseq.vv	v14, v14, v15
	WORD $0x00f00793  // li	a5, 15
LBB0_267:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x42e02557  // vmv.x.s	a0, v14
	WORD $0x00f55533  // srl	a0, a0, a5
	WORD $0xfff78793  // addi	a5, a5, -1
	WORD $0x00157513  // andi	a0, a0, 1
	WORD $0x00c5153b  // sllw	a0, a0, a2
	WORD $0x00a4e4b3  // or	s1, s1, a0
	WORD $0xfff60613  // addi	a2, a2, -1
	BNE X15, X30, LBB0_267  // bne	a5, t5, .LBB0_267
	WORD $0x03049493  // slli	s1, s1, 48
	WORD $0x02071713  // slli	a4, a4, 32
	WORD $0x03041413  // slli	s0, s0, 48
	WORD $0x00970733  // add	a4, a4, s1
	WORD $0x02045413  // srli	s0, s0, 32
	WORD $0x00876733  // or	a4, a4, s0
	WORD $0x00e686b3  // add	a3, a3, a4
	WORD $0x01d6f733  // and	a4, a3, t4
	WORD $0x01dff6b3  // and	a3, t6, t4
	BEQZ X14, LBB0_272  // beqz	a4, .LBB0_272
	WORD $0x06013783  // ld	a5, 96(sp)
	WORD $0x03013483  // ld	s1, 48(sp)
LBB0_270:
	WORD $0xfff70613  // addi	a2, a4, -1
	WORD $0x00d67533  // and	a0, a2, a3
	WORD $0x00155593  // srli	a1, a0, 1
	WORD $0x0165f5b3  // and	a1, a1, s6
	WORD $0x40b50533  // sub	a0, a0, a1
	WORD $0x019575b3  // and	a1, a0, s9
	WORD $0x00255513  // srli	a0, a0, 2
	WORD $0x01957533  // and	a0, a0, s9
	WORD $0x00b50533  // add	a0, a0, a1
	WORD $0x00455593  // srli	a1, a0, 4
	WORD $0x00b50533  // add	a0, a0, a1
	WORD $0x01857533  // and	a0, a0, s8
	WORD $0x02950533  // mul	a0, a0, s1
	WORD $0x03855513  // srli	a0, a0, 56
	WORD $0x00650533  // add	a0, a0, t1
	BGEU X15, X10, LBB0_293  // bgeu	a5, a0, .LBB0_293
	WORD $0x00c77733  // and	a4, a4, a2
	WORD $0x00178793  // addi	a5, a5, 1
	BNEZ X14, LBB0_270  // bnez	a4, .LBB0_270
	JMP LBB0_273  // j	.LBB0_273
LBB0_272:
	WORD $0x06013783  // ld	a5, 96(sp)
	WORD $0x03013483  // ld	s1, 48(sp)
LBB0_273:
	WORD $0x06f13023  // sd	a5, 96(sp)
	WORD $0x0016d513  // srli	a0, a3, 1
	WORD $0x04013583  // ld	a1, 64(sp)
	WORD $0x03058e93  // addi	t4, a1, 48
	WORD $0x01657533  // and	a0, a0, s6
	WORD $0x40a686b3  // sub	a3, a3, a0
	WORD $0x0196f533  // and	a0, a3, s9
	WORD $0x0026d693  // srli	a3, a3, 2
	WORD $0x0196f5b3  // and	a1, a3, s9
	WORD $0x00b50533  // add	a0, a0, a1
	WORD $0x00455593  // srli	a1, a0, 4
	WORD $0x00b50533  // add	a0, a0, a1
	WORD $0x01857533  // and	a0, a0, s8
	WORD $0x02950533  // mul	a0, a0, s1
	WORD $0x03855513  // srli	a0, a0, 56
	WORD $0x00a30333  // add	t1, t1, a0
	WORD $0x06813483  // ld	s1, 104(sp)
	WORD $0xfc048493  // addi	s1, s1, -64
	WORD $0x04813583  // ld	a1, 72(sp)
	JMP LBB0_194  // j	.LBB0_194
LBB0_274:
	WORD $0x04b13423  // sd	a1, 72(sp)
	BLEZ X9, LBB0_306  // blez	s1, .LBB0_306
	WORD $0x00030993  // mv	s3, t1
	WORD $0x09010513  // addi	a0, sp, 144
	WORD $0x02850527  // vs1r.v	v10, (a0)
	WORD $0x034e9513  // slli	a0, t4, 52
	WORD $0x03455513  // srli	a0, a0, 52
	WORD $0x07010593  // addi	a1, sp, 112
	WORD $0x02858527  // vs1r.v	v10, (a1)
	WORD $0x00813583  // ld	a1, 8(sp)
	BLTU X10, X11, LBB0_290  // bltu	a0, a1, .LBB0_290
	WORD $0x07010693  // addi	a3, sp, 112
	WORD $0x02000513  // li	a0, 32
	WORD $0x06813583  // ld	a1, 104(sp)
	BLTU X11, X10, LBB0_278  // bltu	a1, a0, .LBB0_278
	WORD $0x000ec303  // lbu	t1, 0(t4)
	WORD $0x001ece03  // lbu	t3, 1(t4)
	WORD $0x002ec383  // lbu	t2, 2(t4)
	WORD $0x003ecf83  // lbu	t6, 3(t4)
	WORD $0x004eca83  // lbu	s5, 4(t4)
	WORD $0x005ec803  // lbu	a6, 5(t4)
	WORD $0x006ec503  // lbu	a0, 6(t4)
	WORD $0x04a13023  // sd	a0, 64(sp)
	WORD $0x007eca03  // lbu	s4, 7(t4)
	WORD $0x008ec483  // lbu	s1, 8(t4)
	WORD $0x009ec503  // lbu	a0, 9(t4)
	WORD $0x00aecd03  // lbu	s10, 10(t4)
	WORD $0x00bec703  // lbu	a4, 11(t4)
	WORD $0x00cec403  // lbu	s0, 12(t4)
	WORD $0x00dec683  // lbu	a3, 13(t4)
	WORD $0x00eec583  // lbu	a1, 14(t4)
	WORD $0x00b13023  // sd	a1, 0(sp)
	WORD $0x00fecb83  // lbu	s7, 15(t4)
	WORD $0x010ec583  // lbu	a1, 16(t4)
	WORD $0x011ec603  // lbu	a2, 17(t4)
	WORD $0x008e1e13  // slli	t3, t3, 8
	WORD $0x006e67b3  // or	a5, t3, t1
	WORD $0x04f13823  // sd	a5, 80(sp)
	WORD $0x012ec303  // lbu	t1, 18(t4)
	WORD $0x01039393  // slli	t2, t2, 16
	WORD $0x018f9f93  // slli	t6, t6, 24
	WORD $0x007fefb3  // or	t6, t6, t2
	WORD $0x013ec383  // lbu	t2, 19(t4)
	WORD $0x00881793  // slli	a5, a6, 8
	WORD $0x0157ee33  // or	t3, a5, s5
	WORD $0x014ec783  // lbu	a5, 20(t4)
	WORD $0x04013803  // ld	a6, 64(sp)
	WORD $0x01081813  // slli	a6, a6, 16
	WORD $0x018a1a13  // slli	s4, s4, 24
	WORD $0x010a6833  // or	a6, s4, a6
	WORD $0x015eca03  // lbu	s4, 21(t4)
	WORD $0x00851513  // slli	a0, a0, 8
	WORD $0x00956533  // or	a0, a0, s1
	WORD $0x016ec483  // lbu	s1, 22(t4)
	WORD $0x010d1d13  // slli	s10, s10, 16
	WORD $0x01871713  // slli	a4, a4, 24
	WORD $0x01a76d33  // or	s10, a4, s10
	WORD $0x017ec703  // lbu	a4, 23(t4)
	WORD $0x00869693  // slli	a3, a3, 8
	WORD $0x0086e6b3  // or	a3, a3, s0
	WORD $0x018ec403  // lbu	s0, 24(t4)
	WORD $0x00013a83  // ld	s5, 0(sp)
	WORD $0x010a9a93  // slli	s5, s5, 16
	WORD $0x018b9b93  // slli	s7, s7, 24
	WORD $0x015beab3  // or	s5, s7, s5
	WORD $0x019ecb83  // lbu	s7, 25(t4)
	WORD $0x00861613  // slli	a2, a2, 8
	WORD $0x00c5e5b3  // or	a1, a1, a2
	WORD $0x01aec603  // lbu	a2, 26(t4)
	WORD $0x01031313  // slli	t1, t1, 16
	WORD $0x01839393  // slli	t2, t2, 24
	WORD $0x0063e333  // or	t1, t2, t1
	WORD $0x01bec383  // lbu	t2, 27(t4)
	WORD $0x008a1a13  // slli	s4, s4, 8
	WORD $0x00fa6a33  // or	s4, s4, a5
	WORD $0x01cec783  // lbu	a5, 28(t4)
	WORD $0x01049493  // slli	s1, s1, 16
	WORD $0x01871713  // slli	a4, a4, 24
	WORD $0x00976733  // or	a4, a4, s1
	WORD $0x01dec483  // lbu	s1, 29(t4)
	WORD $0x008b9b93  // slli	s7, s7, 8
	WORD $0x008bebb3  // or	s7, s7, s0
	WORD $0x01eec403  // lbu	s0, 30(t4)
	WORD $0x01061613  // slli	a2, a2, 16
	WORD $0x01839393  // slli	t2, t2, 24
	WORD $0x00c3e3b3  // or	t2, t2, a2
	WORD $0x01fec603  // lbu	a2, 31(t4)
	WORD $0x00849493  // slli	s1, s1, 8
	WORD $0x0097e7b3  // or	a5, a5, s1
	WORD $0x01041413  // slli	s0, s0, 16
	WORD $0x01861613  // slli	a2, a2, 24
	WORD $0x00866633  // or	a2, a2, s0
	WORD $0x05013403  // ld	s0, 80(sp)
	WORD $0x008fe4b3  // or	s1, t6, s0
	WORD $0x01c86433  // or	s0, a6, t3
	WORD $0x00ad6533  // or	a0, s10, a0
	WORD $0x00dae6b3  // or	a3, s5, a3
	WORD $0x00b365b3  // or	a1, t1, a1
	WORD $0x01476733  // or	a4, a4, s4
	WORD $0x0173e833  // or	a6, t2, s7
	WORD $0x00f66633  // or	a2, a2, a5
	WORD $0x02041413  // slli	s0, s0, 32
	WORD $0x00946433  // or	s0, s0, s1
	WORD $0x02069693  // slli	a3, a3, 32
	WORD $0x00d56533  // or	a0, a0, a3
	WORD $0x02071713  // slli	a4, a4, 32
	WORD $0x00e5e5b3  // or	a1, a1, a4
	WORD $0x020e8e93  // addi	t4, t4, 32
	WORD $0x02061613  // slli	a2, a2, 32
	WORD $0x01066633  // or	a2, a2, a6
	WORD $0x06a13c23  // sd	a0, 120(sp)
	WORD $0x06813823  // sd	s0, 112(sp)
	WORD $0x08c13423  // sd	a2, 136(sp)
	WORD $0x08b13023  // sd	a1, 128(sp)
	WORD $0x06813403  // ld	s0, 104(sp)
	WORD $0xfe040413  // addi	s0, s0, -32
	WORD $0x09010693  // addi	a3, sp, 144
	JMP LBB0_279  // j	.LBB0_279
LBB0_278:
	WORD $0x06813403  // ld	s0, 104(sp)
LBB0_279:
	BLTU X8, X5, LBB0_281  // bltu	s0, t0, .LBB0_281
	WORD $0x000ec503  // lbu	a0, 0(t4)
	WORD $0x04a13823  // sd	a0, 80(sp)
	WORD $0x001ec303  // lbu	t1, 1(t4)
	WORD $0x002ec383  // lbu	t2, 2(t4)
	WORD $0x003ece03  // lbu	t3, 3(t4)
	WORD $0x004ecf83  // lbu	t6, 4(t4)
	WORD $0x005ec803  // lbu	a6, 5(t4)
	WORD $0x006eca03  // lbu	s4, 6(t4)
	WORD $0x007eca83  // lbu	s5, 7(t4)
	WORD $0x008ecb83  // lbu	s7, 8(t4)
	WORD $0x009ecd03  // lbu	s10, 9(t4)
	WORD $0x00aec783  // lbu	a5, 10(t4)
	WORD $0x00bec483  // lbu	s1, 11(t4)
	WORD $0x00cec503  // lbu	a0, 12(t4)
	WORD $0x00fec583  // lbu	a1, 15(t4)
	WORD $0x00eec603  // lbu	a2, 14(t4)
	WORD $0x00dec703  // lbu	a4, 13(t4)
	WORD $0x010e8e93  // addi	t4, t4, 16
	WORD $0x00b687a3  // sb	a1, 15(a3)
	WORD $0x00c68723  // sb	a2, 14(a3)
	WORD $0x00e686a3  // sb	a4, 13(a3)
	WORD $0x00a68623  // sb	a0, 12(a3)
	WORD $0x009685a3  // sb	s1, 11(a3)
	WORD $0x00f68523  // sb	a5, 10(a3)
	WORD $0x01a684a3  // sb	s10, 9(a3)
	WORD $0x01768423  // sb	s7, 8(a3)
	WORD $0x015683a3  // sb	s5, 7(a3)
	WORD $0x01468323  // sb	s4, 6(a3)
	WORD $0x010682a3  // sb	a6, 5(a3)
	WORD $0x01f68223  // sb	t6, 4(a3)
	WORD $0x01c681a3  // sb	t3, 3(a3)
	WORD $0x00768123  // sb	t2, 2(a3)
	WORD $0x006680a3  // sb	t1, 1(a3)
	WORD $0x05013503  // ld	a0, 80(sp)
	WORD $0x00a68023  // sb	a0, 0(a3)
	WORD $0x01068693  // addi	a3, a3, 16
	WORD $0xff040413  // addi	s0, s0, -16
LBB0_281:
	WORD $0x00800513  // li	a0, 8
	BLTU X8, X10, LBB0_283  // bltu	s0, a0, .LBB0_283
	WORD $0x000eb503  // ld	a0, 0(t4)
	WORD $0x008e8e93  // addi	t4, t4, 8
	WORD $0x00a6b023  // sd	a0, 0(a3)
	WORD $0x00868693  // addi	a3, a3, 8
	WORD $0xff840413  // addi	s0, s0, -8
LBB0_283:
	WORD $0x00400513  // li	a0, 4
	BLTU X8, X10, LBB0_285  // bltu	s0, a0, .LBB0_285
	WORD $0x000ea503  // lw	a0, 0(t4)
	WORD $0x004e8e93  // addi	t4, t4, 4
	WORD $0x00a6a023  // sw	a0, 0(a3)
	WORD $0x00468693  // addi	a3, a3, 4
	WORD $0xffc40413  // addi	s0, s0, -4
LBB0_285:
	WORD $0x00200513  // li	a0, 2
	BLTU X8, X10, LBB0_287  // bltu	s0, a0, .LBB0_287
	WORD $0x000e9503  // lh	a0, 0(t4)
	WORD $0x002e8613  // addi	a2, t4, 2
	WORD $0x00a69023  // sh	a0, 0(a3)
	WORD $0x00268693  // addi	a3, a3, 2
	WORD $0xffe40413  // addi	s0, s0, -2
	JMP LBB0_288  // j	.LBB0_288
LBB0_287:
	WORD $0x000e8613  // mv	a2, t4
LBB0_288:
	WORD $0x07010e93  // addi	t4, sp, 112
	BEQZ X8, LBB0_290  // beqz	s0, .LBB0_290
	WORD $0x00064503  // lbu	a0, 0(a2)
	WORD $0x00a68023  // sb	a0, 0(a3)
LBB0_290:
	WORD $0x00098313  // mv	t1, s3
	WORD $0x04813583  // ld	a1, 72(sp)
	WORD $0x00ff03b7  // lui	t2, 4080
	WORD $0x03813a03  // ld	s4, 56(sp)
	JMP LBB0_195  // j	.LBB0_195
LBB0_291:
	WORD $0x01393023  // sd	s3, 0(s2)
	WORD $0xffe00393  // li	t2, -2
	JMP LBB0_301  // j	.LBB0_301
LBB0_292:
	MOV $·p7c48db41412b1d2_LCPI0_1(SB), X10  // lui	a0, %hi(.LCPI0_1)
	MOV (X10), X10  // ld	a0, %lo(.LCPI0_1)(a0)
	WORD $0x40e005b3  // neg	a1, a4
	WORD $0x00e5f5b3  // and	a1, a1, a4
	WORD $0x02013683  // ld	a3, 32(sp)
	WORD $0x0086b603  // ld	a2, 8(a3)
	WORD $0x02a58533  // mul	a0, a1, a0
	WORD $0x03a55513  // srli	a0, a0, 58
	MOV $·p7c48db41412b1d2_LCPI0_2(SB), X11  // lui	a1, %hi(.LCPI0_2)
	// addi	a1, a1, %lo(.LCPI0_2) (skipped, covered by MOV address load)
	WORD $0x00b50533  // add	a0, a0, a1
	WORD $0x00054503  // lbu	a0, 0(a0)
	WORD $0x06013583  // ld	a1, 96(sp)
	JMP LBB0_294  // j	.LBB0_294
LBB0_293:
	MOV $·p7c48db41412b1d2_LCPI0_1(SB), X10  // lui	a0, %hi(.LCPI0_1)
	MOV (X10), X10  // ld	a0, %lo(.LCPI0_1)(a0)
	WORD $0x40e005b3  // neg	a1, a4
	WORD $0x00e5f5b3  // and	a1, a1, a4
	WORD $0x02013683  // ld	a3, 32(sp)
	WORD $0x0086b603  // ld	a2, 8(a3)
	WORD $0x02a58533  // mul	a0, a1, a0
	WORD $0x03a55513  // srli	a0, a0, 58
	MOV $·p7c48db41412b1d2_LCPI0_2(SB), X11  // lui	a1, %hi(.LCPI0_2)
	// addi	a1, a1, %lo(.LCPI0_2) (skipped, covered by MOV address load)
	WORD $0x00b50533  // add	a0, a0, a1
	WORD $0x00054503  // lbu	a0, 0(a0)
	WORD $0x06813583  // ld	a1, 104(sp)
LBB0_294:
	WORD $0x40c585b3  // sub	a1, a1, a2
	WORD $0x40b50533  // sub	a0, a0, a1
	WORD $0x00150613  // addi	a2, a0, 1
	WORD $0x02813583  // ld	a1, 40(sp)
	WORD $0x00c5b023  // sd	a2, 0(a1)
	WORD $0x0086b683  // ld	a3, 8(a3)
	WORD $0x00c6b533  // sltu	a0, a3, a2
	BLTU X12, X13, LBB0_296  // bltu	a2, a3, .LBB0_296
	WORD $0x00068613  // mv	a2, a3
LBB0_296:
	WORD $0x00c5b023  // sd	a2, 0(a1)
	WORD $0x40a00533  // neg	a0, a0
	WORD $0x01813583  // ld	a1, 24(sp)
	WORD $0x00b563b3  // or	t2, a0, a1
	JMP LBB0_301  // j	.LBB0_301
LBB0_297:
	MOV $·p7c48db41412b1d2_LCPI0_1(SB), X10  // lui	a0, %hi(.LCPI0_1)
	MOV (X10), X10  // ld	a0, %lo(.LCPI0_1)(a0)
	WORD $0x40c005b3  // neg	a1, a2
	WORD $0x00c5f5b3  // and	a1, a1, a2
	WORD $0x02a58533  // mul	a0, a1, a0
	WORD $0x03a55513  // srli	a0, a0, 58
	MOV $·p7c48db41412b1d2_LCPI0_2(SB), X11  // lui	a1, %hi(.LCPI0_2)
	// addi	a1, a1, %lo(.LCPI0_2) (skipped, covered by MOV address load)
	WORD $0x00b50533  // add	a0, a0, a1
	WORD $0x00054503  // lbu	a0, 0(a0)
	WORD $0x41de05b3  // sub	a1, t3, t4
	WORD $0x00b50533  // add	a0, a0, a1
LBB0_298:
	WORD $0x00150513  // addi	a0, a0, 1
LBB0_299:
	WORD $0x00a93023  // sd	a0, 0(s2)
LBB0_300:
	WORD $0x00098393  // mv	t2, s3
LBB0_301:
	WORD $0x00038513  // mv	a0, t2
	WORD $0x11813083  // ld	ra, 280(sp)
	WORD $0x11013403  // ld	s0, 272(sp)
	WORD $0x10813483  // ld	s1, 264(sp)
	WORD $0x10013903  // ld	s2, 256(sp)
	WORD $0x0f813983  // ld	s3, 248(sp)
	WORD $0x0f013a03  // ld	s4, 240(sp)
	WORD $0x0e813a83  // ld	s5, 232(sp)
	WORD $0x0e013b03  // ld	s6, 224(sp)
	WORD $0x0d813b83  // ld	s7, 216(sp)
	WORD $0x0d013c03  // ld	s8, 208(sp)
	WORD $0x0c813c83  // ld	s9, 200(sp)
	WORD $0x0c013d03  // ld	s10, 192(sp)
	WORD $0x0b813d83  // ld	s11, 184(sp)
	WORD $0x12010113  // addi	sp, sp, 288
	RET  // ret
LBB0_302:
	WORD $0x00e93023  // sd	a4, 0(s2)
	JMP LBB0_300  // j	.LBB0_300
LBB0_303:
	WORD $0x41d78533  // sub	a0, a5, t4
	JMP LBB0_298  // j	.LBB0_298
LBB0_304:
	WORD $0x00098393  // mv	t2, s3
LBB0_305:
	WORD $0x41d28533  // sub	a0, t0, t4
	WORD $0x00a93023  // sd	a0, 0(s2)
	JMP LBB0_301  // j	.LBB0_301
LBB0_306:
	WORD $0x02013503  // ld	a0, 32(sp)
	WORD $0x00853503  // ld	a0, 8(a0)
	WORD $0x02813583  // ld	a1, 40(sp)
	WORD $0x00a5b023  // sd	a0, 0(a1)
	JMP LBB0_23  // j	.LBB0_23
LBB0_307:
	BNEZ X8, LBB0_308  // bnez	s0, .LBB0_308
	JMP LBB0_23  // j	.LBB0_23
LBB0_308:
	WORD $0x021e0793  // addi	a5, t3, 33
	WORD $0xfdff0413  // addi	s0, t5, -33
	BGTZ X8, LBB0_187  // bgtz	s0, .LBB0_187
	JMP LBB0_301  // j	.LBB0_301
Lfunc_end0:


TEXT ·__skip_one_fast(SB), $0-24
	NO_LOCAL_POINTERS
___skip_one_fast:
	MOV s+0(FP), X10
	MOV p+8(FP), X11
	CALL ·__skip_one_fast_riscv64_entry__(SB)
	MOV X10, ret+16(FP)
	RET

// Data section
GLOBL ·p7c48db41412b1d2_LCPI0_0(SB), RODATA, $32
DATA ·p7c48db41412b1d2_LCPI0_0+0(SB)/8, $0x03180e1d021c0100
DATA ·p7c48db41412b1d2_LCPI0_0+8(SB)/8, $0x080411190f14161e
DATA ·p7c48db41412b1d2_LCPI0_0+16(SB)/8, $0x07101315170d1b1f
DATA ·p7c48db41412b1d2_LCPI0_0+24(SB)/8, $0x090a050b06120c1a
GLOBL ·p7c48db41412b1d2_LCPI0_1(SB), RODATA, $8
DATA ·p7c48db41412b1d2_LCPI0_1+0(SB)/8, $0x0218a392cd3d5dbf
GLOBL ·p7c48db41412b1d2_LCPI0_3(SB), RODATA, $8
DATA ·p7c48db41412b1d2_LCPI0_3+0(SB)/8, $0xaaaaaaaaaaaaaaaa
GLOBL ·p7c48db41412b1d2_LCPI0_4(SB), RODATA, $8
DATA ·p7c48db41412b1d2_LCPI0_4+0(SB)/8, $0x8888888888888888
GLOBL ·p7c48db41412b1d2_LCPI0_5(SB), RODATA, $8
DATA ·p7c48db41412b1d2_LCPI0_5+0(SB)/8, $0x5555555555555555
GLOBL ·p7c48db41412b1d2_LCPI0_6(SB), RODATA, $8
DATA ·p7c48db41412b1d2_LCPI0_6+0(SB)/8, $0x4444444444444444
GLOBL ·p7c48db41412b1d2_LCPI0_7(SB), RODATA, $8
DATA ·p7c48db41412b1d2_LCPI0_7+0(SB)/8, $0x2222222222222222
GLOBL ·p7c48db41412b1d2_LCPI0_8(SB), RODATA, $8
DATA ·p7c48db41412b1d2_LCPI0_8+0(SB)/8, $0x1111111111111111
GLOBL ·p7c48db41412b1d2_LCPI0_9(SB), RODATA, $8
DATA ·p7c48db41412b1d2_LCPI0_9+0(SB)/8, $0x0f0f0f0f0f0f0f0f
GLOBL ·p7c48db41412b1d2_LCPI0_10(SB), RODATA, $8
DATA ·p7c48db41412b1d2_LCPI0_10+0(SB)/8, $0x3333333333333333
GLOBL ·p7c48db41412b1d2_LCPI0_11(SB), RODATA, $8
DATA ·p7c48db41412b1d2_LCPI0_11+0(SB)/8, $0x0101010101010101
GLOBL ·p7c48db41412b1d2_LCPI0_2(SB), RODATA, $83
DATA ·p7c48db41412b1d2_LCPI0_2+0(SB)/8, $0x30305c3030305c22
DATA ·p7c48db41412b1d2_LCPI0_2+8(SB)/8, $0x30305c3230305c31
DATA ·p7c48db41412b1d2_LCPI0_2+16(SB)/8, $0x5c725c3330305c37
DATA ·p7c48db41412b1d2_LCPI0_2+24(SB)/8, $0x30305c3332305c62
DATA ·p7c48db41412b1d2_LCPI0_2+32(SB)/8, $0x31305c3133305c34
DATA ·p7c48db41412b1d2_LCPI0_2+40(SB)/8, $0x5c745c3433305c36
DATA ·p7c48db41412b1d2_LCPI0_2+48(SB)/8, $0x305c283432305c22
DATA ·p7c48db41412b1d2_LCPI0_2+56(SB)/8, $0x305c3132305c3530
DATA ·p7c48db41412b1d2_LCPI0_2+64(SB)/8, $0x2e3731305c263233
DATA ·p7c48db41412b1d2_LCPI0_2+72(SB)/8, $0x5c6e5c303533305c
DATA ·p7c48db41412b1d2_LCPI0_2+80(SB)/8, $0x0000000000373330
GLOBL ·p7c48db41412b1d2_MASK_USE_NUMBER(SB), RODATA, $4
DATA ·p7c48db41412b1d2_MASK_USE_NUMBER+0(SB)/8, $0x0000000000000002
