// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package rvv

//go:nosplit
//go:noescape
//goland:noinspection ALL
func __skip_one_entry__() uintptr

var (
    _subr__skip_one uintptr = __skip_one_entry__() + 0
)

const (
    _stack__skip_one = 368
)

var (
    _ = _subr__skip_one
)

const (
    _ = _stack__skip_one
)
