// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package rvv

//go:nosplit
//go:noescape
//goland:noinspection ALL
func __skip_object_entry__() uintptr

var (
    _subr__skip_object uintptr = __skip_object_entry__() + 0
)

const (
    _stack__skip_object = 432
)

var (
    _ = _subr__skip_object
)

const (
    _ = _stack__skip_object
)
