// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

#include "go_asm.h"
#include "funcdata.h"
#include "textflag.h"

TEXT ·__skip_number_entry__(SB), NOSPLIT, $0-8
	MOV $·__skip_number_riscv64_entry__(SB), A0
	MOV A0, ret+0(FP)
	RET

TEXT ·__skip_number_riscv64_entry__(SB), NOSPLIT, $64
	NO_LOCAL_POINTERS
skip_number:
	WORD $0xfb010113  // addi	sp, sp, -80
	WORD $0x04813423  // sd	s0, 72(sp)
	WORD $0x04913023  // sd	s1, 64(sp)
	WORD $0x03213c23  // sd	s2, 56(sp)
	WORD $0x03313823  // sd	s3, 48(sp)
	WORD $0x03413423  // sd	s4, 40(sp)
	WORD $0x03513023  // sd	s5, 32(sp)
	WORD $0x01613c23  // sd	s6, 24(sp)
	WORD $0x01713823  // sd	s7, 16(sp)
	WORD $0x01813423  // sd	s8, 8(sp)
	WORD $0x01913023  // sd	s9, 0(sp)
	WORD $0x00053803  // ld	a6, 0(a0)
	WORD $0x0005b883  // ld	a7, 0(a1)
	WORD $0x01180333  // add	t1, a6, a7
	WORD $0x00853503  // ld	a0, 8(a0)
	WORD $0x00034603  // lbu	a2, 0(t1)
	WORD $0x41150533  // sub	a0, a0, a7
	WORD $0xfd360613  // addi	a2, a2, -45
	WORD $0x00163613  // seqz	a2, a2
	WORD $0x40c50bb3  // sub	s7, a0, a2
	WORD $0x00c30333  // add	t1, t1, a2
	BEQZ X23, LBB0_84  // beqz	s7, .LBB0_84
	WORD $0x00034603  // lbu	a2, 0(t1)
	WORD $0xfc660693  // addi	a3, a2, -58
	WORD $0xff600713  // li	a4, -10
	WORD $0xffe00513  // li	a0, -2
	BLTU X13, X14, LBB0_77  // bltu	a3, a4, .LBB0_77
	WORD $0x03000693  // li	a3, 48
	BNE X12, X13, LBB0_6  // bne	a2, a3, .LBB0_6
	WORD $0x00100c93  // li	s9, 1
	BEQ X23, X25, LBB0_72  // beq	s7, s9, .LBB0_72
	WORD $0x00134603  // lbu	a2, 1(t1)
	WORD $0xfd260613  // addi	a2, a2, -46
	WORD $0x03700693  // li	a3, 55
	BLTU X13, X12, LBB0_72  // bltu	a3, a2, .LBB0_72
	WORD $0x008006b7  // lui	a3, 2048
	WORD $0x0016869b  // addiw	a3, a3, 1
	WORD $0x03769793  // slli	a5, a3, 55
	WORD $0x00f686b3  // add	a3, a3, a5
	WORD $0x00c6d633  // srl	a2, a3, a2
	WORD $0x00167613  // andi	a2, a2, 1
	BEQZ X12, LBB0_72  // beqz	a2, .LBB0_72
LBB0_6:
	WORD $0x01000613  // li	a2, 16
	WORD $0xfff00293  // li	t0, -1
	BLTU X23, X12, LBB0_85  // bltu	s7, a2, .LBB0_85
	WORD $0x00000693  // li	a3, 0
	WORD $0x03a00713  // li	a4, 58
	WORD $0x0c0077d7  // vsetvli	a5, zero, e8, m1, ta, ma
	WORD $0x420764d7  // vmv.s.x	v9, a4
LBB0_8:
	WORD $0x00168713  // addi	a4, a3, 1
	WORD $0x08777057  // vsetvli	zero, a4, e8, mf2, tu, ma
	WORD $0x3a96c457  // vslideup.vx	v8, v9, a3
	WORD $0x00070693  // mv	a3, a4
	BNE X14, X12, LBB0_8  // bne	a4, a2, .LBB0_8
	WORD $0x00000613  // li	a2, 0
	WORD $0x02f00693  // li	a3, 47
	WORD $0x0c707757  // vsetvli	a4, zero, e8, mf2, ta, ma
	WORD $0x4206e557  // vmv.s.x	v10, a3
	WORD $0x01000693  // li	a3, 16
LBB0_10:
	WORD $0x00160713  // addi	a4, a2, 1
	WORD $0x08777057  // vsetvli	zero, a4, e8, mf2, tu, ma
	WORD $0x3aa644d7  // vslideup.vx	v9, v10, a2
	WORD $0x00070613  // mv	a2, a4
	BNE X14, X13, LBB0_10  // bne	a4, a3, .LBB0_10
	WORD $0x00000613  // li	a2, 0
	WORD $0x02e00693  // li	a3, 46
	WORD $0x0c707757  // vsetvli	a4, zero, e8, mf2, ta, ma
	WORD $0x4206e5d7  // vmv.s.x	v11, a3
	WORD $0x01000693  // li	a3, 16
LBB0_12:
	WORD $0x00160713  // addi	a4, a2, 1
	WORD $0x08777057  // vsetvli	zero, a4, e8, mf2, tu, ma
	WORD $0x3ab64557  // vslideup.vx	v10, v11, a2
	WORD $0x00070613  // mv	a2, a4
	BNE X14, X13, LBB0_12  // bne	a4, a3, .LBB0_12
	WORD $0x00000613  // li	a2, 0
	WORD $0x06500693  // li	a3, 101
	WORD $0x0c707757  // vsetvli	a4, zero, e8, mf2, ta, ma
	WORD $0x4206e657  // vmv.s.x	v12, a3
	WORD $0x01000693  // li	a3, 16
LBB0_14:
	WORD $0x00160713  // addi	a4, a2, 1
	WORD $0x08777057  // vsetvli	zero, a4, e8, mf2, tu, ma
	WORD $0x3ac645d7  // vslideup.vx	v11, v12, a2
	WORD $0x00070613  // mv	a2, a4
	BNE X14, X13, LBB0_14  // bne	a4, a3, .LBB0_14
	WORD $0x00000613  // li	a2, 0
	WORD $0x04500693  // li	a3, 69
	WORD $0x0c707757  // vsetvli	a4, zero, e8, mf2, ta, ma
	WORD $0x4206e6d7  // vmv.s.x	v13, a3
	WORD $0x01000693  // li	a3, 16
LBB0_16:
	WORD $0x00160713  // addi	a4, a2, 1
	WORD $0x08777057  // vsetvli	zero, a4, e8, mf2, tu, ma
	WORD $0x3ad64657  // vslideup.vx	v12, v13, a2
	WORD $0x00070613  // mv	a2, a4
	BNE X14, X13, LBB0_16  // bne	a4, a3, .LBB0_16
	WORD $0x00000613  // li	a2, 0
	WORD $0x02b00693  // li	a3, 43
	WORD $0x0c707757  // vsetvli	a4, zero, e8, mf2, ta, ma
	WORD $0x4206e757  // vmv.s.x	v14, a3
	WORD $0x01000693  // li	a3, 16
LBB0_18:
	WORD $0x00160713  // addi	a4, a2, 1
	WORD $0x08777057  // vsetvli	zero, a4, e8, mf2, tu, ma
	WORD $0x3ae646d7  // vslideup.vx	v13, v14, a2
	WORD $0x00070613  // mv	a2, a4
	BNE X14, X13, LBB0_18  // bne	a4, a3, .LBB0_18
	WORD $0x00000613  // li	a2, 0
	WORD $0x02d00693  // li	a3, 45
	WORD $0x0c707757  // vsetvli	a4, zero, e8, mf2, ta, ma
	WORD $0x4206e7d7  // vmv.s.x	v15, a3
	WORD $0x01000693  // li	a3, 16
LBB0_20:
	WORD $0x00160713  // addi	a4, a2, 1
	WORD $0x08777057  // vsetvli	zero, a4, e8, mf2, tu, ma
	WORD $0x3af64757  // vslideup.vx	v14, v15, a2
	WORD $0x00070613  // mv	a2, a4
	BNE X14, X13, LBB0_20  // bne	a4, a3, .LBB0_20
	WORD $0xfff00a93  // li	s5, -1
	WORD $0x077cb637  // lui	a2, 30667
	MOV $·p6c1dccc627f482e9_LCPI0_0(SB), X28  // lui	t3, %hi(.LCPI0_0)
	// addi	t3, t3, %lo(.LCPI0_0) (skipped, covered by MOV address load)
	WORD $0x01000f13  // li	t5, 16
	WORD $0x00f00f93  // li	t6, 15
	WORD $0xfff00993  // li	s3, -1
	WORD $0xfff00393  // li	t2, -1
	WORD $0x53160913  // addi	s2, a2, 1329
	WORD $0xfff00e93  // li	t4, -1
	WORD $0x00030c13  // mv	s8, t1
LBB0_22:
	WORD $0x00000b13  // li	s6, 0
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x020c0887  // vle8.v	v17, (s8)
	WORD $0x00f00613  // li	a2, 15
	WORD $0x6e9887d7  // vmslt.vv	v15, v9, v17
	WORD $0x6f140857  // vmslt.vv	v16, v17, v8
	WORD $0x63150957  // vmseq.vv	v18, v17, v10
	WORD $0x631689d7  // vmseq.vv	v19, v17, v13
	WORD $0x63170a57  // vmseq.vv	v20, v17, v14
	WORD $0x6707a7d7  // vmand.mm	v15, v16, v15
	WORD $0x63150ad7  // vmseq.vv	v21, v17, v10
	WORD $0x6b3a2857  // vmor.mm	v16, v19, v20
	WORD $0x0c807057  // vsetvli	zero, zero, e16, m1, ta, ma
	WORD $0x435026d7  // vmv.x.s	a3, v21
	WORD $0x6af927d7  // vmor.mm	v15, v15, v18
	WORD $0x6af827d7  // vmor.mm	v15, v15, v16
	WORD $0x00f00713  // li	a4, 15
LBB0_23:
	WORD $0x00e6d7b3  // srl	a5, a3, a4
	WORD $0xfff70713  // addi	a4, a4, -1
	WORD $0x0017f793  // andi	a5, a5, 1
	WORD $0x00c797bb  // sllw	a5, a5, a2
	WORD $0x0167eb33  // or	s6, a5, s6
	WORD $0xfff60613  // addi	a2, a2, -1
	BNE X14, X21, LBB0_23  // bne	a4, s5, .LBB0_23
	WORD $0x00000413  // li	s0, 0
	WORD $0x0c707057  // vsetvli	zero, zero, e8, mf2, ta, ma
	WORD $0x63158957  // vmseq.vv	v18, v17, v11
	WORD $0x631608d7  // vmseq.vv	v17, v17, v12
	WORD $0x00f00613  // li	a2, 15
	WORD $0x6b28a8d7  // vmor.mm	v17, v18, v17
	WORD $0x0c807057  // vsetvli	zero, zero, e16, m1, ta, ma
	WORD $0x431026d7  // vmv.x.s	a3, v17
	WORD $0x00f00713  // li	a4, 15
LBB0_25:
	WORD $0x00e6d7b3  // srl	a5, a3, a4
	WORD $0xfff70713  // addi	a4, a4, -1
	WORD $0x0017f793  // andi	a5, a5, 1
	WORD $0x00c797bb  // sllw	a5, a5, a2
	WORD $0x00f46433  // or	s0, s0, a5
	WORD $0xfff60613  // addi	a2, a2, -1
	BNE X14, X21, LBB0_25  // bne	a4, s5, .LBB0_25
	WORD $0x00000613  // li	a2, 0
	WORD $0x00f00693  // li	a3, 15
	WORD $0x43002a57  // vmv.x.s	s4, v16
	WORD $0x00f00713  // li	a4, 15
LBB0_27:
	WORD $0x00ea57b3  // srl	a5, s4, a4
	WORD $0xfff70713  // addi	a4, a4, -1
	WORD $0x0017f793  // andi	a5, a5, 1
	WORD $0x00d797bb  // sllw	a5, a5, a3
	WORD $0x00f66633  // or	a2, a2, a5
	WORD $0xfff68693  // addi	a3, a3, -1
	BNE X14, X21, LBB0_27  // bne	a4, s5, .LBB0_27
	WORD $0x00000793  // li	a5, 0
	WORD $0x6af8a7d7  // vmor.mm	v15, v15, v17
	WORD $0x00f00693  // li	a3, 15
	WORD $0x00f00713  // li	a4, 15
LBB0_29:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x42f024d7  // vmv.x.s	s1, v15
	WORD $0x00e4d4b3  // srl	s1, s1, a4
	WORD $0xfff70713  // addi	a4, a4, -1
	WORD $0x0014f493  // andi	s1, s1, 1
	WORD $0x00d494bb  // sllw	s1, s1, a3
	WORD $0x0097e7b3  // or	a5, a5, s1
	WORD $0xfff68693  // addi	a3, a3, -1
	BNE X14, X21, LBB0_29  // bne	a4, s5, .LBB0_29
	WORD $0xfff7c693  // not	a3, a5
	WORD $0x40d0073b  // negw	a4, a3
	WORD $0x00e6f6b3  // and	a3, a3, a4
	WORD $0x032686b3  // mul	a3, a3, s2
	WORD $0x01b6d69b  // srliw	a3, a3, 27
	WORD $0x01c686b3  // add	a3, a3, t3
	WORD $0x0006ca03  // lbu	s4, 0(a3)
	BEQ X20, X30, LBB0_32  // beq	s4, t5, .LBB0_32
	WORD $0x014a96bb  // sllw	a3, s5, s4
	WORD $0xfff6c693  // not	a3, a3
	WORD $0x00db7b33  // and	s6, s6, a3
	WORD $0x00d47433  // and	s0, s0, a3
	WORD $0x00d67633  // and	a2, a2, a3
LBB0_32:
	WORD $0xfffb069b  // addiw	a3, s6, -1
	WORD $0x0166f6b3  // and	a3, a3, s6
	BNEZ X13, LBB0_81  // bnez	a3, .LBB0_81
	WORD $0xfff4069b  // addiw	a3, s0, -1
	WORD $0x0086f6b3  // and	a3, a3, s0
	BNEZ X13, LBB0_81  // bnez	a3, .LBB0_81
	WORD $0xfff6069b  // addiw	a3, a2, -1
	WORD $0x00c6f6b3  // and	a3, a3, a2
	BNEZ X13, LBB0_81  // bnez	a3, .LBB0_81
	BEQZ X22, LBB0_38  // beqz	s6, .LBB0_38
	WORD $0x416006bb  // negw	a3, s6
	WORD $0x00db76b3  // and	a3, s6, a3
	WORD $0x032686b3  // mul	a3, a3, s2
	WORD $0x01b6d69b  // srliw	a3, a3, 27
	WORD $0x01c686b3  // add	a3, a3, t3
	WORD $0x0006c683  // lbu	a3, 0(a3)
	WORD $0x406c0733  // sub	a4, s8, t1
	WORD $0x00e686b3  // add	a3, a3, a4
	BNE X29, X21, LBB0_83  // bne	t4, s5, .LBB0_83
	WORD $0x00068e93  // mv	t4, a3
LBB0_38:
	BEQZ X8, LBB0_41  // beqz	s0, .LBB0_41
	WORD $0x408006bb  // negw	a3, s0
	WORD $0x0086f6b3  // and	a3, a3, s0
	WORD $0x032686b3  // mul	a3, a3, s2
	WORD $0x01b6d69b  // srliw	a3, a3, 27
	WORD $0x01c686b3  // add	a3, a3, t3
	WORD $0x0006c683  // lbu	a3, 0(a3)
	WORD $0x406c0733  // sub	a4, s8, t1
	WORD $0x00e686b3  // add	a3, a3, a4
	BNE X7, X21, LBB0_83  // bne	t2, s5, .LBB0_83
	WORD $0x00068393  // mv	t2, a3
LBB0_41:
	BEQZ X12, LBB0_44  // beqz	a2, .LBB0_44
	WORD $0x40c006bb  // negw	a3, a2
	WORD $0x00d67633  // and	a2, a2, a3
	WORD $0x03260633  // mul	a2, a2, s2
	WORD $0x01b6561b  // srliw	a2, a2, 27
	WORD $0x01c60633  // add	a2, a2, t3
	WORD $0x00064603  // lbu	a2, 0(a2)
	WORD $0x406c06b3  // sub	a3, s8, t1
	WORD $0x00d60633  // add	a2, a2, a3
	BNE X19, X21, LBB0_82  // bne	s3, s5, .LBB0_82
	WORD $0x00060993  // mv	s3, a2
LBB0_44:
	BNE X20, X30, LBB0_60  // bne	s4, t5, .LBB0_60
	WORD $0xff0b8b93  // addi	s7, s7, -16
	WORD $0x010c0c13  // addi	s8, s8, 16
	BLTU X31, X23, LBB0_22  // bltu	t6, s7, .LBB0_22
	BEQZ X23, LBB0_61  // beqz	s7, .LBB0_61
LBB0_47:
	WORD $0x017c0e33  // add	t3, s8, s7
	WORD $0xfffc4713  // not	a4, s8
	WORD $0x406c04b3  // sub	s1, s8, t1
	WORD $0x00a00b13  // li	s6, 10
	WORD $0x02d00a93  // li	s5, 45
	WORD $0x02b00f13  // li	t5, 43
	WORD $0x06500f93  // li	t6, 101
	WORD $0x04500913  // li	s2, 69
	WORD $0x00670cb3  // add	s9, a4, t1
	WORD $0x02e00a13  // li	s4, 46
	WORD $0x000e8793  // mv	a5, t4
	WORD $0x00038413  // mv	s0, t2
	WORD $0x00098613  // mv	a2, s3
LBB0_48:
	WORD $0x000c4683  // lbu	a3, 0(s8)
	WORD $0xfd068713  // addi	a4, a3, -48
	WORD $0x00060993  // mv	s3, a2
	WORD $0x00040393  // mv	t2, s0
	WORD $0x00078e93  // mv	t4, a5
	BGEU X14, X22, LBB0_51  // bgeu	a4, s6, .LBB0_51
	WORD $0x00098613  // mv	a2, s3
	WORD $0x00038413  // mv	s0, t2
	WORD $0x000e8793  // mv	a5, t4
LBB0_50:
	WORD $0xfffb8b93  // addi	s7, s7, -1
	WORD $0x001c0c13  // addi	s8, s8, 1
	WORD $0xfffc8c93  // addi	s9, s9, -1
	WORD $0x00148493  // addi	s1, s1, 1
	BNEZ X23, LBB0_48  // bnez	s7, .LBB0_48
	JMP LBB0_78  // j	.LBB0_78
LBB0_51:
	BGE X21, X13, LBB0_56  // bge	s5, a3, .LBB0_56
	BEQ X13, X31, LBB0_59  // beq	a3, t6, .LBB0_59
	BEQ X13, X18, LBB0_59  // beq	a3, s2, .LBB0_59
	BNE X13, X20, LBB0_61  // bne	a3, s4, .LBB0_61
	WORD $0x00098613  // mv	a2, s3
	WORD $0x00038413  // mv	s0, t2
	WORD $0x00048793  // mv	a5, s1
	BEQ X29, X5, LBB0_50  // beq	t4, t0, .LBB0_50
	JMP LBB0_71  // j	.LBB0_71
LBB0_56:
	BEQ X13, X30, LBB0_58  // beq	a3, t5, .LBB0_58
	BNE X13, X21, LBB0_61  // bne	a3, s5, .LBB0_61
LBB0_58:
	WORD $0x00048613  // mv	a2, s1
	WORD $0x00038413  // mv	s0, t2
	WORD $0x000e8793  // mv	a5, t4
	BEQ X19, X5, LBB0_50  // beq	s3, t0, .LBB0_50
	JMP LBB0_71  // j	.LBB0_71
LBB0_59:
	WORD $0x00098613  // mv	a2, s3
	WORD $0x00048413  // mv	s0, s1
	WORD $0x000e8793  // mv	a5, t4
	BEQ X7, X5, LBB0_50  // beq	t2, t0, .LBB0_50
	JMP LBB0_71  // j	.LBB0_71
LBB0_60:
	WORD $0x014c0c33  // add	s8, s8, s4
LBB0_61:
	WORD $0xfff00c93  // li	s9, -1
	BEQZ X29, LBB0_76  // beqz	t4, .LBB0_76
	BEQZ X19, LBB0_76  // beqz	s3, .LBB0_76
	BEQZ X7, LBB0_76  // beqz	t2, .LBB0_76
	WORD $0x406c0cb3  // sub	s9, s8, t1
	WORD $0xfffc8613  // addi	a2, s9, -1
	BEQ X29, X12, LBB0_70  // beq	t4, a2, .LBB0_70
	BEQ X19, X12, LBB0_70  // beq	s3, a2, .LBB0_70
	BEQ X7, X12, LBB0_70  // beq	t2, a2, .LBB0_70
	BLEZ X19, LBB0_73  // blez	s3, .LBB0_73
	WORD $0xfff98613  // addi	a2, s3, -1
	BEQ X7, X12, LBB0_73  // beq	t2, a2, .LBB0_73
	WORD $0xfff9cc93  // not	s9, s3
	JMP LBB0_76  // j	.LBB0_76
LBB0_70:
	WORD $0x41900cb3  // neg	s9, s9
LBB0_71:
	BLTZ X25, LBB0_76  // bltz	s9, .LBB0_76
LBB0_72:
	WORD $0x01930333  // add	t1, t1, s9
	WORD $0x00088513  // mv	a0, a7
	JMP LBB0_77  // j	.LBB0_77
LBB0_73:
	WORD $0x007ee633  // or	a2, t4, t2
	BLTZ X12, LBB0_79  // bltz	a2, .LBB0_79
	BLT X29, X7, LBB0_79  // blt	t4, t2, .LBB0_79
	WORD $0xfffecc93  // not	s9, t4
LBB0_76:
	WORD $0xfffcc613  // not	a2, s9
	WORD $0x00c30333  // add	t1, t1, a2
LBB0_77:
	WORD $0x41030633  // sub	a2, t1, a6
	WORD $0x00c5b023  // sd	a2, 0(a1)
	WORD $0x04813403  // ld	s0, 72(sp)
	WORD $0x04013483  // ld	s1, 64(sp)
	WORD $0x03813903  // ld	s2, 56(sp)
	WORD $0x03013983  // ld	s3, 48(sp)
	WORD $0x02813a03  // ld	s4, 40(sp)
	WORD $0x02013a83  // ld	s5, 32(sp)
	WORD $0x01813b03  // ld	s6, 24(sp)
	WORD $0x01013b83  // ld	s7, 16(sp)
	WORD $0x00813c03  // ld	s8, 8(sp)
	WORD $0x00013c83  // ld	s9, 0(sp)
	WORD $0x05010113  // addi	sp, sp, 80
	RET  // ret
LBB0_78:
	WORD $0x00060993  // mv	s3, a2
	WORD $0x00040393  // mv	t2, s0
	WORD $0x00078e93  // mv	t4, a5
	WORD $0x000e0c13  // mv	s8, t3
	JMP LBB0_61  // j	.LBB0_61
LBB0_79:
	WORD $0x00062613  // slti	a2, a2, 0
	WORD $0xfff38693  // addi	a3, t2, -1
	WORD $0x00164613  // xori	a2, a2, 1
	WORD $0x00dec6b3  // xor	a3, t4, a3
	WORD $0x0016b693  // seqz	a3, a3
	WORD $0x00d67633  // and	a2, a2, a3
	BEQZ X12, LBB0_71  // beqz	a2, .LBB0_71
	WORD $0xfff3cc93  // not	s9, t2
	JMP LBB0_71  // j	.LBB0_71
LBB0_81:
	WORD $0x40d0063b  // negw	a2, a3
	WORD $0x00d67633  // and	a2, a2, a3
	WORD $0x077cb6b7  // lui	a3, 30667
	WORD $0x53168693  // addi	a3, a3, 1329
	WORD $0x02d60633  // mul	a2, a2, a3
	WORD $0x01b6561b  // srliw	a2, a2, 27
	WORD $0x01c60633  // add	a2, a2, t3
	WORD $0x00064603  // lbu	a2, 0(a2)
	WORD $0x406c06b3  // sub	a3, s8, t1
	WORD $0x00d60633  // add	a2, a2, a3
LBB0_82:
	WORD $0xfff64c93  // not	s9, a2
	JMP LBB0_71  // j	.LBB0_71
LBB0_83:
	WORD $0xfff6cc93  // not	s9, a3
	JMP LBB0_71  // j	.LBB0_71
LBB0_84:
	WORD $0xfff00513  // li	a0, -1
	JMP LBB0_77  // j	.LBB0_77
LBB0_85:
	WORD $0x00030c13  // mv	s8, t1
	WORD $0xfff00e93  // li	t4, -1
	WORD $0xfff00393  // li	t2, -1
	WORD $0xfff00993  // li	s3, -1
	JMP LBB0_47  // j	.LBB0_47
Lfunc_end0:


TEXT ·__skip_number(SB), NOSPLIT, $0-24
	NO_LOCAL_POINTERS

_entry___skip_number:
	MOV 16(g), X31      // g.stack.hi
	ADD $-144, SP, X30
	BLTU X30, X31, _stack_grow___skip_number

___skip_number:
	MOV s+0(FP), X10
	MOV p+8(FP), X11
	CALL ·__skip_number_riscv64_entry__(SB)
	MOV X10, ret+16(FP)
	RET

_stack_grow___skip_number:
	MOV X1, X3      // Save return address (RA)
	CALL runtime·morestack_noctxt(SB)
	JMP _entry___skip_number

// Data section
GLOBL ·p6c1dccc627f482e9_LCPI0_0(SB), RODATA, $32
DATA ·p6c1dccc627f482e9_LCPI0_0+0(SB)/8, $0x03180e1d021c0100
DATA ·p6c1dccc627f482e9_LCPI0_0+8(SB)/8, $0x080411190f14161e
DATA ·p6c1dccc627f482e9_LCPI0_0+16(SB)/8, $0x07101315170d1b1f
DATA ·p6c1dccc627f482e9_LCPI0_0+24(SB)/8, $0x090a050b06120c1a
GLOBL ·p6c1dccc627f482e9_MASK_USE_NUMBER(SB), RODATA, $4
DATA ·p6c1dccc627f482e9_MASK_USE_NUMBER+0(SB)/8, $0x0000000000000002
