// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

#include "go_asm.h"
#include "funcdata.h"
#include "textflag.h"

TEXT ·__u64toa_entry__(SB), NOSPLIT, $0-8
	MOV $·__u64toa_riscv64_entry__(SB), A0
	MOV A0, ret+0(FP)
	RET

TEXT ·__u64toa_riscv64_entry__(SB), NOSPLIT, $0
	NO_LOCAL_POINTERS
u64toa:
	WORD $0x0045d613  // srli	a2, a1, 4
	WORD $0x27000693  // li	a3, 624
	BLTU X13, X12, LBB0_10  // bltu	a3, a2, .LBB0_10
	WORD $0x03059613  // slli	a2, a1, 48
	WORD $0x000016b7  // lui	a3, 1
	WORD $0x06400713  // li	a4, 100
	WORD $0x03265613  // srli	a2, a2, 50
	WORD $0x47b6869b  // addiw	a3, a3, 1147
	WORD $0x02d60633  // mul	a2, a2, a3
	WORD $0x01165793  // srli	a5, a2, 17
	WORD $0x01065613  // srli	a2, a2, 16
	WORD $0x7fe67693  // andi	a3, a2, 2046
	WORD $0x02e78633  // mul	a2, a5, a4
	WORD $0x40c58633  // sub	a2, a1, a2
	WORD $0x3e800793  // li	a5, 1000
	WORD $0x00161613  // slli	a2, a2, 1
	BLTU X11, X15, LBB0_3  // bltu	a1, a5, .LBB0_3
	MOV $·p3349f7c8cbc5d84a_Digits(SB), X11  // lui	a1, %hi(Digits)
	// addi	a1, a1, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x00d585b3  // add	a1, a1, a3
	WORD $0x0005c583  // lbu	a1, 0(a1)
	WORD $0x00b50023  // sb	a1, 0(a0)
	WORD $0x00100593  // li	a1, 1
	JMP LBB0_5  // j	.LBB0_5
LBB0_3:
	BLTU X11, X14, LBB0_9  // bltu	a1, a4, .LBB0_9
	WORD $0x00000593  // li	a1, 0
LBB0_5:
	WORD $0x0016e693  // ori	a3, a3, 1
	MOV $·p3349f7c8cbc5d84a_Digits(SB), X14  // lui	a4, %hi(Digits)
	// addi	a4, a4, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x00e686b3  // add	a3, a3, a4
	WORD $0x0006c703  // lbu	a4, 0(a3)
	WORD $0x00158693  // addi	a3, a1, 1
	WORD $0x00a585b3  // add	a1, a1, a0
	WORD $0x00e58023  // sb	a4, 0(a1)
LBB0_6:
	WORD $0x03061593  // slli	a1, a2, 48
	WORD $0x0305d593  // srli	a1, a1, 48
	MOV $·p3349f7c8cbc5d84a_Digits(SB), X14  // lui	a4, %hi(Digits)
	// addi	a4, a4, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x00e585b3  // add	a1, a1, a4
	WORD $0x0005c583  // lbu	a1, 0(a1)
	WORD $0x00168713  // addi	a4, a3, 1
	WORD $0x00a686b3  // add	a3, a3, a0
	WORD $0x00b68023  // sb	a1, 0(a3)
LBB0_7:
	WORD $0x00166593  // ori	a1, a2, 1
	WORD $0x03059593  // slli	a1, a1, 48
	WORD $0x0305d593  // srli	a1, a1, 48
	MOV $·p3349f7c8cbc5d84a_Digits(SB), X12  // lui	a2, %hi(Digits)
	// addi	a2, a2, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x00c585b3  // add	a1, a1, a2
	WORD $0x0005c603  // lbu	a2, 0(a1)
	WORD $0x00170593  // addi	a1, a4, 1
	WORD $0x00e50533  // add	a0, a0, a4
	WORD $0x00c50023  // sb	a2, 0(a0)
LBB0_8:
	WORD $0x00058513  // mv	a0, a1
	RET  // ret
LBB0_9:
	WORD $0x00000693  // li	a3, 0
	WORD $0x00a00793  // li	a5, 10
	WORD $0x00000713  // li	a4, 0
	BGEU X11, X15, LBB0_6  // bgeu	a1, a5, .LBB0_6
	JMP LBB0_7  // j	.LBB0_7
LBB0_10:
	WORD $0x05f5e637  // lui	a2, 24414
	WORD $0x0ff6069b  // addiw	a3, a2, 255
	BLTU X13, X11, LBB0_19  // bltu	a3, a1, .LBB0_19
	WORD $0x02059613  // slli	a2, a1, 32
	WORD $0xd1b716b7  // lui	a3, 858993
	WORD $0x431be737  // lui	a4, 274878
	WORD $0x051ec7b7  // lui	a5, 20972
	WORD $0x75968693  // addi	a3, a3, 1881
	WORD $0xe8370713  // addi	a4, a4, -381
	WORD $0x02069693  // slli	a3, a3, 32
	WORD $0x02071713  // slli	a4, a4, 32
	WORD $0x02d636b3  // mulhu	a3, a2, a3
	WORD $0x02e63733  // mulhu	a4, a2, a4
	WORD $0x02f6d613  // srli	a2, a3, 47
	WORD $0x03261613  // slli	a2, a2, 50
	WORD $0x02f63633  // mulhu	a2, a2, a5
	WORD $0x06400793  // li	a5, 100
	WORD $0x01165613  // srli	a2, a2, 17
	WORD $0x02f607b3  // mul	a5, a2, a5
	WORD $0x00989637  // lui	a2, 2441
	WORD $0x02d6d813  // srli	a6, a3, 45
	WORD $0x03175713  // srli	a4, a4, 49
	WORD $0xffe77713  // andi	a4, a4, -2
	WORD $0x40f806b3  // sub	a3, a6, a5
	WORD $0x6806061b  // addiw	a2, a2, 1664
	WORD $0x00169693  // slli	a3, a3, 1
	BLTU X11, X12, LBB0_13  // bltu	a1, a2, .LBB0_13
	MOV $·p3349f7c8cbc5d84a_Digits(SB), X12  // lui	a2, %hi(Digits)
	// addi	a2, a2, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x00e60633  // add	a2, a2, a4
	WORD $0x00064603  // lbu	a2, 0(a2)
	WORD $0x00c50023  // sb	a2, 0(a0)
	WORD $0x00100793  // li	a5, 1
	JMP LBB0_15  // j	.LBB0_15
LBB0_13:
	WORD $0x000f4637  // lui	a2, 244
	WORD $0x2406061b  // addiw	a2, a2, 576
	BLTU X11, X12, LBB0_18  // bltu	a1, a2, .LBB0_18
	WORD $0x00000793  // li	a5, 0
LBB0_15:
	WORD $0x00176613  // ori	a2, a4, 1
	MOV $·p3349f7c8cbc5d84a_Digits(SB), X14  // lui	a4, %hi(Digits)
	// addi	a4, a4, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x00e60633  // add	a2, a2, a4
	WORD $0x00064603  // lbu	a2, 0(a2)
	WORD $0x00178713  // addi	a4, a5, 1
	WORD $0x00a787b3  // add	a5, a5, a0
	WORD $0x00c78023  // sb	a2, 0(a5)
LBB0_16:
	WORD $0x03069613  // slli	a2, a3, 48
	WORD $0x03065613  // srli	a2, a2, 48
	MOV $·p3349f7c8cbc5d84a_Digits(SB), X15  // lui	a5, %hi(Digits)
	// addi	a5, a5, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x00f60633  // add	a2, a2, a5
	WORD $0x00064603  // lbu	a2, 0(a2)
	WORD $0x00170313  // addi	t1, a4, 1
	WORD $0x00a70733  // add	a4, a4, a0
	WORD $0x00c70023  // sb	a2, 0(a4)
LBB0_17:
	WORD $0x00002637  // lui	a2, 2
	WORD $0x000012b7  // lui	t0, 1
	WORD $0x06400893  // li	a7, 100
	WORD $0x0016e693  // ori	a3, a3, 1
	WORD $0x71060613  // addi	a2, a2, 1808
	WORD $0x02c80633  // mul	a2, a6, a2
	MOV $·p3349f7c8cbc5d84a_Digits(SB), X14  // lui	a4, %hi(Digits)
	// addi	a4, a4, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x47b2879b  // addiw	a5, t0, 1147
	WORD $0x03069693  // slli	a3, a3, 48
	WORD $0x0306d693  // srli	a3, a3, 48
	WORD $0x40c585bb  // subw	a1, a1, a2
	WORD $0x00e686b3  // add	a3, a3, a4
	WORD $0x03059613  // slli	a2, a1, 48
	WORD $0x0006c683  // lbu	a3, 0(a3)
	WORD $0x03265613  // srli	a2, a2, 50
	WORD $0x02f60633  // mul	a2, a2, a5
	WORD $0x01165793  // srli	a5, a2, 17
	WORD $0x031787b3  // mul	a5, a5, a7
	WORD $0x00650533  // add	a0, a0, t1
	WORD $0x01065613  // srli	a2, a2, 16
	WORD $0x00d50023  // sb	a3, 0(a0)
	WORD $0x7fe67613  // andi	a2, a2, 2046
	WORD $0x40f585bb  // subw	a1, a1, a5
	WORD $0x00e60633  // add	a2, a2, a4
	WORD $0xcc517057  // vsetivli	zero, 2, e8, mf8, ta, ma
	WORD $0x02060407  // vle8.v	v8, (a2)
	WORD $0x03159593  // slli	a1, a1, 49
	WORD $0x0305d593  // srli	a1, a1, 48
	WORD $0x00e585b3  // add	a1, a1, a4
	WORD $0x02058487  // vle8.v	v9, (a1)
	WORD $0x00150513  // addi	a0, a0, 1
	WORD $0x00530593  // addi	a1, t1, 5
	WORD $0xcc527057  // vsetivli	zero, 4, e8, mf8, ta, ma
	WORD $0x3a913457  // vslideup.vi	v8, v9, 2
	WORD $0x02050427  // vse8.v	v8, (a0)
	JMP LBB0_8  // j	.LBB0_8
LBB0_18:
	WORD $0x00000713  // li	a4, 0
	WORD $0x00018637  // lui	a2, 24
	WORD $0x6a06061b  // addiw	a2, a2, 1696
	WORD $0x00000313  // li	t1, 0
	BGEU X11, X12, LBB0_16  // bgeu	a1, a2, .LBB0_16
	JMP LBB0_17  // j	.LBB0_17
LBB0_19:
	MOV $·p3349f7c8cbc5d84a_LCPI0_0(SB), X13  // lui	a3, %hi(.LCPI0_0)
	MOV (X13), X14  // ld	a4, %lo(.LCPI0_0)(a3)
	WORD $0x10060293  // addi	t0, a2, 256
	BLTU X14, X11, LBB0_37  // bltu	a4, a1, .LBB0_37
	WORD $0x00000613  // li	a2, 0
	MOV $·p3349f7c8cbc5d84a_LCPI0_5(SB), X15  // lui	a5, %hi(.LCPI0_5)
	WORD $0xfff00813  // li	a6, -1
	WORD $0x000d26b7  // lui	a3, 210
	WORD $0x02085713  // srli	a4, a6, 32
	WORD $0xcd827057  // vsetivli	zero, 4, e64, m1, ta, ma
	WORD $0x5e074457  // vmv.v.x	v8, a4
	WORD $0x02d00713  // li	a4, 45
	MOV (X15), X15  // ld	a5, %lo(.LCPI0_5)(a5)
	WORD $0xb716869b  // addiw	a3, a3, -1167
	WORD $0x00c69693  // slli	a3, a3, 12
	WORD $0x75968693  // addi	a3, a3, 1881
	WORD $0x02f5b7b3  // mulhu	a5, a1, a5
	WORD $0x01a7d793  // srli	a5, a5, 26
	WORD $0x0d707057  // vsetvli	zero, zero, e32, mf2, ta, ma
	WORD $0x5e07c4d7  // vmv.v.x	v9, a5
	WORD $0x3e9064d7  // vslide1down.vx	v9, v9, zero
	WORD $0x3e9064d7  // vslide1down.vx	v9, v9, zero
	WORD $0x3e9064d7  // vslide1down.vx	v9, v9, zero
	WORD $0x26940457  // vand.vv	v8, v9, v8
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x9686e457  // vmul.vx	v8, v8, a3
	MOV $·p3349f7c8cbc5d84a_LCPI0_6(SB), X13  // lui	a3, %hi(.LCPI0_6)
	MOV (X13), X13  // ld	a3, %lo(.LCPI0_6)(a3)
	WORD $0xa2874557  // vsrl.vx	v10, v8, a4
	WORD $0x42006457  // vmv.s.x	v8, zero
	WORD $0x5e0505d7  // vmv.v.v	v11, v10
	WORD $0x09707057  // vsetvli	zero, zero, e32, mf2, tu, ma
	WORD $0x3a80b5d7  // vslideup.vi	v11, v8, 1
	WORD $0x0d807057  // vsetvli	zero, zero, e64, m1, ta, ma
	WORD $0x5e06c457  // vmv.v.x	v8, a3
	WORD $0x025786b3  // mul	a3, a5, t0
	WORD $0x40d588b3  // sub	a7, a1, a3
	WORD $0x000026b7  // lui	a3, 2
	WORD $0x7106869b  // addiw	a3, a3, 1808
	WORD $0x96b6e5d7  // vmul.vx	v11, v11, a3
	WORD $0x0000b6b7  // lui	a3, 11
	WORD $0x7ff68693  // addi	a3, a3, 2047
	WORD $0xcd727057  // vsetivli	zero, 4, e32, mf2, ta, ma
	WORD $0x0a9584d7  // vsub.vv	v9, v9, v11
	WORD $0xc8f17057  // vsetivli	zero, 2, e16, mf2, tu, ma
	WORD $0x3a90b557  // vslideup.vi	v10, v9, 1
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x96a134d7  // vsll.vi	v9, v10, 2
	WORD $0xcce27057  // vsetivli	zero, 4, e16, mf4, ta, ma
	WORD $0xc294a5d7  // vwaddu.vv	v11, v9, v9
	WORD $0xf29865d7  // vwmaccu.vx	v11, a6, v9
	WORD $0xcd717057  // vsetivli	zero, 2, e32, mf2, ta, ma
	WORD $0xc2b5a557  // vwaddu.vv	v10, v11, v11
	WORD $0xf2b86557  // vwmaccu.vx	v10, a6, v11
	WORD $0x00800713  // li	a4, 8
LBB0_21:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3ea645d7  // vslidedown.vx	v11, v10, a2
	WORD $0x42b027d7  // vmv.x.s	a5, v11
	WORD $0x3e8645d7  // vslidedown.vx	v11, v8, a2
	WORD $0x42b025d7  // vmv.x.s	a1, v11
	WORD $0x03079793  // slli	a5, a5, 48
	WORD $0x00d5f5b3  // and	a1, a1, a3
	WORD $0x0307d793  // srli	a5, a5, 48
	WORD $0x02b785b3  // mul	a1, a5, a1
	WORD $0x0105d593  // srli	a1, a1, 16
	WORD $0x4205e5d7  // vmv.s.x	v11, a1
	WORD $0x00160593  // addi	a1, a2, 1
	WORD $0x08f5f057  // vsetvli	zero, a1, e16, mf2, tu, ma
	WORD $0x3ab644d7  // vslideup.vx	v9, v11, a2
	WORD $0x00058613  // mv	a2, a1
	BNE X11, X14, LBB0_21  // bne	a1, a4, .LBB0_21
	WORD $0x00000613  // li	a2, 0
	WORD $0xc00015b7  // lui	a1, 786433
	WORD $0x0000b6b7  // lui	a3, 11
	WORD $0x00659593  // slli	a1, a1, 6
	WORD $0x88068693  // addi	a3, a3, -1920
	WORD $0x00158593  // addi	a1, a1, 1
	WORD $0x01b59593  // slli	a1, a1, 27
	WORD $0x08058593  // addi	a1, a1, 128
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x5e05c557  // vmv.v.x	v10, a1
	WORD $0x00800713  // li	a4, 8
LBB0_23:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3e9645d7  // vslidedown.vx	v11, v9, a2
	WORD $0x42b025d7  // vmv.x.s	a1, v11
	WORD $0x3ea645d7  // vslidedown.vx	v11, v10, a2
	WORD $0x42b027d7  // vmv.x.s	a5, v11
	WORD $0x03059593  // slli	a1, a1, 48
	WORD $0x00d7f7b3  // and	a5, a5, a3
	WORD $0x0305d593  // srli	a1, a1, 48
	WORD $0x02f585b3  // mul	a1, a1, a5
	WORD $0x0105d593  // srli	a1, a1, 16
	WORD $0x4205e5d7  // vmv.s.x	v11, a1
	WORD $0x00160593  // addi	a1, a2, 1
	WORD $0x08f5f057  // vsetvli	zero, a1, e16, mf2, tu, ma
	WORD $0x3ab64457  // vslideup.vx	v8, v11, a2
	WORD $0x00058613  // mv	a2, a1
	BNE X11, X14, LBB0_23  // bne	a1, a4, .LBB0_23
	WORD $0x00000613  // li	a2, 0
	WORD $0x00a00693  // li	a3, 10
	WORD $0x00800713  // li	a4, 8
LBB0_25:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3e864557  // vslidedown.vx	v10, v8, a2
	WORD $0x42a025d7  // vmv.x.s	a1, v10
	WORD $0x02d585b3  // mul	a1, a1, a3
	WORD $0x4205e557  // vmv.s.x	v10, a1
	WORD $0x00160593  // addi	a1, a2, 1
	WORD $0x08f5f057  // vsetvli	zero, a1, e16, mf2, tu, ma
	WORD $0x3aa644d7  // vslideup.vx	v9, v10, a2
	WORD $0x00058613  // mv	a2, a1
	BNE X11, X14, LBB0_25  // bne	a1, a4, .LBB0_25
	WORD $0x00000613  // li	a2, 0
	WORD $0xcd727057  // vsetivli	zero, 4, e32, mf2, ta, ma
	WORD $0x5e08c557  // vmv.v.x	v10, a7
	WORD $0xfff00593  // li	a1, -1
	WORD $0x0205d693  // srli	a3, a1, 32
	WORD $0x0d807057  // vsetvli	zero, zero, e64, m1, ta, ma
	WORD $0x5e06c5d7  // vmv.v.x	v11, a3
	WORD $0x000d26b7  // lui	a3, 210
	WORD $0x0d707057  // vsetvli	zero, zero, e32, mf2, ta, ma
	WORD $0x3ea06557  // vslide1down.vx	v10, v10, zero
	WORD $0xb716869b  // addiw	a3, a3, -1167
	WORD $0x3ea06557  // vslide1down.vx	v10, v10, zero
	WORD $0x00c69693  // slli	a3, a3, 12
	WORD $0x3ea06557  // vslide1down.vx	v10, v10, zero
	WORD $0x75968693  // addi	a3, a3, 1881
	WORD $0x26a585d7  // vand.vv	v11, v10, v11
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x96b6e5d7  // vmul.vx	v11, v11, a3
	WORD $0x02d00693  // li	a3, 45
	WORD $0xa2b6c657  // vsrl.vx	v12, v11, a3
	MOV $·p3349f7c8cbc5d84a_LCPI0_6(SB), X13  // lui	a3, %hi(.LCPI0_6)
	MOV (X13), X13  // ld	a3, %lo(.LCPI0_6)(a3)
	WORD $0x969834d7  // vsll.vi	v9, v9, 16
	WORD $0x420065d7  // vmv.s.x	v11, zero
	WORD $0x5e0606d7  // vmv.v.v	v13, v12
	WORD $0x09707057  // vsetvli	zero, zero, e32, mf2, tu, ma
	WORD $0x3ab0b6d7  // vslideup.vi	v13, v11, 1
	WORD $0x0d807057  // vsetvli	zero, zero, e64, m1, ta, ma
	WORD $0x5e06c5d7  // vmv.v.x	v11, a3
	WORD $0x000026b7  // lui	a3, 2
	WORD $0x7106869b  // addiw	a3, a3, 1808
	WORD $0x96d6e6d7  // vmul.vx	v13, v13, a3
	WORD $0x0000b6b7  // lui	a3, 11
	WORD $0x7ff68693  // addi	a3, a3, 2047
	WORD $0xcd727057  // vsetivli	zero, 4, e32, mf2, ta, ma
	WORD $0x0aa68557  // vsub.vv	v10, v10, v13
	WORD $0xc8f17057  // vsetivli	zero, 2, e16, mf2, tu, ma
	WORD $0x3aa0b657  // vslideup.vi	v12, v10, 1
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x96c13557  // vsll.vi	v10, v12, 2
	WORD $0xcce27057  // vsetivli	zero, 4, e16, mf4, ta, ma
	WORD $0xc2a526d7  // vwaddu.vv	v13, v10, v10
	WORD $0xf2a5e6d7  // vwmaccu.vx	v13, a1, v10
	WORD $0xcd717057  // vsetivli	zero, 2, e32, mf2, ta, ma
	WORD $0xc2d6a657  // vwaddu.vv	v12, v13, v13
	WORD $0xf2d5e657  // vwmaccu.vx	v12, a1, v13
	WORD $0x00800593  // li	a1, 8
LBB0_27:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3ec646d7  // vslidedown.vx	v13, v12, a2
	WORD $0x42d02757  // vmv.x.s	a4, v13
	WORD $0x3eb646d7  // vslidedown.vx	v13, v11, a2
	WORD $0x42d027d7  // vmv.x.s	a5, v13
	WORD $0x03071713  // slli	a4, a4, 48
	WORD $0x00d7f7b3  // and	a5, a5, a3
	WORD $0x03075713  // srli	a4, a4, 48
	WORD $0x02f70733  // mul	a4, a4, a5
	WORD $0x01075713  // srli	a4, a4, 16
	WORD $0x420766d7  // vmv.s.x	v13, a4
	WORD $0x00160713  // addi	a4, a2, 1
	WORD $0x08f77057  // vsetvli	zero, a4, e16, mf2, tu, ma
	WORD $0x3ad64557  // vslideup.vx	v10, v13, a2
	WORD $0x00070613  // mv	a2, a4
	BNE X14, X11, LBB0_27  // bne	a4, a1, .LBB0_27
	WORD $0x00000593  // li	a1, 0
	WORD $0xc0001637  // lui	a2, 786433
	WORD $0x0000b6b7  // lui	a3, 11
	WORD $0x00661713  // slli	a4, a2, 6
	WORD $0x88068613  // addi	a2, a3, -1920
	WORD $0x00170713  // addi	a4, a4, 1
	WORD $0x01b71713  // slli	a4, a4, 27
	WORD $0x08070693  // addi	a3, a4, 128
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x5e06c657  // vmv.v.x	v12, a3
	WORD $0x00800693  // li	a3, 8
LBB0_29:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3ea5c6d7  // vslidedown.vx	v13, v10, a1
	WORD $0x42d02757  // vmv.x.s	a4, v13
	WORD $0x3ec5c6d7  // vslidedown.vx	v13, v12, a1
	WORD $0x42d027d7  // vmv.x.s	a5, v13
	WORD $0x03071713  // slli	a4, a4, 48
	WORD $0x00c7f7b3  // and	a5, a5, a2
	WORD $0x03075713  // srli	a4, a4, 48
	WORD $0x02f70733  // mul	a4, a4, a5
	WORD $0x01075713  // srli	a4, a4, 16
	WORD $0x420766d7  // vmv.s.x	v13, a4
	WORD $0x00158713  // addi	a4, a1, 1
	WORD $0x08f77057  // vsetvli	zero, a4, e16, mf2, tu, ma
	WORD $0x3ad5c5d7  // vslideup.vx	v11, v13, a1
	WORD $0x00070593  // mv	a1, a4
	BNE X14, X13, LBB0_29  // bne	a4, a3, .LBB0_29
	WORD $0x00000593  // li	a1, 0
	WORD $0x00a00613  // li	a2, 10
	WORD $0x00800693  // li	a3, 8
LBB0_31:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3eb5c657  // vslidedown.vx	v12, v11, a1
	WORD $0x42c02757  // vmv.x.s	a4, v12
	WORD $0x02c70733  // mul	a4, a4, a2
	WORD $0x42076657  // vmv.s.x	v12, a4
	WORD $0x00158713  // addi	a4, a1, 1
	WORD $0x08f77057  // vsetvli	zero, a4, e16, mf2, tu, ma
	WORD $0x3ac5c557  // vslideup.vx	v10, v12, a1
	WORD $0x00070593  // mv	a1, a4
	BNE X14, X13, LBB0_31  // bne	a4, a3, .LBB0_31
	WORD $0x00000613  // li	a2, 0
	WORD $0xccf47057  // vsetivli	zero, 8, e16, mf2, ta, ma
	WORD $0x0a848457  // vsub.vv	v8, v8, v9
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x96a834d7  // vsll.vi	v9, v10, 16
	WORD $0x00f00593  // li	a1, 15
	WORD $0xfff00693  // li	a3, -1
	WORD $0xccf47057  // vsetivli	zero, 8, e16, mf2, ta, ma
	WORD $0x0ab484d7  // vsub.vv	v9, v11, v9
	WORD $0xcc887057  // vsetivli	zero, 16, e16, m1, ta, ma
	WORD $0x3a943457  // vslideup.vi	v8, v9, 8
	WORD $0x1e804457  // vmax.vx	v8, v8, zero
	WORD $0x0c707057  // vsetvli	zero, zero, e8, mf2, ta, ma
	WORD $0xba803457  // vnclipu.wi	v8, v8, 0
	WORD $0x00f00713  // li	a4, 15
LBB0_33:
	WORD $0xcc70f057  // vsetivli	zero, 1, e8, mf2, ta, ma
	WORD $0x3e8744d7  // vslidedown.vx	v9, v8, a4
	WORD $0xfff70713  // addi	a4, a4, -1
	WORD $0x429027d7  // vmv.x.s	a5, v9
	WORD $0x0ff7f793  // andi	a5, a5, 255
	WORD $0x0017b793  // seqz	a5, a5
	WORD $0x00b797bb  // sllw	a5, a5, a1
	WORD $0x00f66633  // or	a2, a2, a5
	WORD $0xfff58593  // addi	a1, a1, -1
	BNE X14, X13, LBB0_33  // bne	a4, a3, .LBB0_33
	WORD $0x00000593  // li	a1, 0
	WORD $0xfff64613  // not	a2, a2
	WORD $0x000086b7  // lui	a3, 8
	WORD $0x077cb737  // lui	a4, 30667
	WORD $0x00d66633  // or	a2, a2, a3
	WORD $0x40c006bb  // negw	a3, a2
	WORD $0x00d67633  // and	a2, a2, a3
	MOV $·p3349f7c8cbc5d84a_LCPI0_7(SB), X13  // lui	a3, %hi(.LCPI0_7)
	// addi	a3, a3, %lo(.LCPI0_7) (skipped, covered by MOV address load)
	WORD $0x53170713  // addi	a4, a4, 1329
	WORD $0x02e60633  // mul	a2, a2, a4
	WORD $0x01b6561b  // srliw	a2, a2, 27
	WORD $0x00d60633  // add	a2, a2, a3
	WORD $0x00064603  // lbu	a2, 0(a2)
	WORD $0x00461693  // slli	a3, a2, 4
	MOV $·p3349f7c8cbc5d84a_VecShiftShuffles(SB), X14  // lui	a4, %hi(VecShiftShuffles)
	// addi	a4, a4, %lo(VecShiftShuffles) (skipped, covered by MOV address load)
	WORD $0x00e686b3  // add	a3, a3, a4
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x02068487  // vle8.v	v9, (a3)
	WORD $0x01000693  // li	a3, 16
LBB0_35:
	WORD $0xcc70f057  // vsetivli	zero, 1, e8, mf2, ta, ma
	WORD $0x3e95c5d7  // vslidedown.vx	v11, v9, a1
	WORD $0x42b02757  // vmv.x.s	a4, v11
	WORD $0x00f77793  // andi	a5, a4, 15
	WORD $0x00072713  // slti	a4, a4, 0
	WORD $0x3e87c5d7  // vslidedown.vx	v11, v8, a5
	WORD $0xfff70713  // addi	a4, a4, -1
	WORD $0x42b027d7  // vmv.x.s	a5, v11
	WORD $0x03078793  // addi	a5, a5, 48
	WORD $0x00f77733  // and	a4, a4, a5
	WORD $0x420765d7  // vmv.s.x	v11, a4
	WORD $0x00158713  // addi	a4, a1, 1
	WORD $0x08777057  // vsetvli	zero, a4, e8, mf2, tu, ma
	WORD $0x3ab5c557  // vslideup.vx	v10, v11, a1
	WORD $0x00070593  // mv	a1, a4
	BNE X14, X13, LBB0_35  // bne	a4, a3, .LBB0_35
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x02050527  // vse8.v	v10, (a0)
	WORD $0x01000593  // li	a1, 16
	WORD $0x40c585b3  // sub	a1, a1, a2
	JMP LBB0_8  // j	.LBB0_8
LBB0_37:
	MOV $·p3349f7c8cbc5d84a_LCPI0_1(SB), X12  // lui	a2, %hi(.LCPI0_1)
	MOV (X12), X12  // ld	a2, %lo(.LCPI0_1)(a2)
	MOV $·p3349f7c8cbc5d84a_LCPI0_2(SB), X13  // lui	a3, %hi(.LCPI0_2)
	MOV (X13), X13  // ld	a3, %lo(.LCPI0_2)(a3)
	WORD $0x02c5b733  // mulhu	a4, a1, a2
	WORD $0x03375713  // srli	a4, a4, 51
	BLTU X13, X11, LBB0_39  // bltu	a3, a1, .LBB0_39
	WORD $0x03076613  // ori	a2, a4, 48
	WORD $0x00c50023  // sb	a2, 0(a0)
	WORD $0x00100813  // li	a6, 1
	JMP LBB0_44  // j	.LBB0_44
LBB0_39:
	MOV $·p3349f7c8cbc5d84a_LCPI0_3(SB), X12  // lui	a2, %hi(.LCPI0_3)
	MOV (X12), X12  // ld	a2, %lo(.LCPI0_3)(a2)
	BLTU X12, X11, LBB0_41  // bltu	a2, a1, .LBB0_41
	WORD $0x00171613  // slli	a2, a4, 1
	MOV $·p3349f7c8cbc5d84a_Digits(SB), X13  // lui	a3, %hi(Digits)
	// addi	a3, a3, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x00d60633  // add	a2, a2, a3
	WORD $0xcc517057  // vsetivli	zero, 2, e8, mf8, ta, ma
	WORD $0x02060407  // vle8.v	v8, (a2)
	WORD $0x02050427  // vse8.v	v8, (a0)
	WORD $0x00200813  // li	a6, 2
	JMP LBB0_44  // j	.LBB0_44
LBB0_41:
	MOV $·p3349f7c8cbc5d84a_LCPI0_4(SB), X12  // lui	a2, %hi(.LCPI0_4)
	MOV (X12), X13  // ld	a3, %lo(.LCPI0_4)(a2)
	WORD $0x51f00613  // li	a2, 1311
	WORD $0x02c70633  // mul	a2, a4, a2
	WORD $0x01165613  // srli	a2, a2, 17
	BLTU X13, X11, LBB0_43  // bltu	a3, a1, .LBB0_43
	WORD $0x03060693  // addi	a3, a2, 48
	WORD $0x00d50023  // sb	a3, 0(a0)
	WORD $0x06400693  // li	a3, 100
	WORD $0x02d60633  // mul	a2, a2, a3
	MOV $·p3349f7c8cbc5d84a_Digits(SB), X13  // lui	a3, %hi(Digits)
	// addi	a3, a3, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x40c7063b  // subw	a2, a4, a2
	WORD $0x03161613  // slli	a2, a2, 49
	WORD $0x03065613  // srli	a2, a2, 48
	WORD $0x00d60633  // add	a2, a2, a3
	WORD $0xcc517057  // vsetivli	zero, 2, e8, mf8, ta, ma
	WORD $0x02060407  // vle8.v	v8, (a2)
	WORD $0x00150613  // addi	a2, a0, 1
	WORD $0x02060427  // vse8.v	v8, (a2)
	WORD $0x00300813  // li	a6, 3
	JMP LBB0_44  // j	.LBB0_44
LBB0_43:
	WORD $0x00161693  // slli	a3, a2, 1
	WORD $0x06400793  // li	a5, 100
	WORD $0x02f60633  // mul	a2, a2, a5
	MOV $·p3349f7c8cbc5d84a_Digits(SB), X15  // lui	a5, %hi(Digits)
	// addi	a5, a5, %lo(Digits) (skipped, covered by MOV address load)
	WORD $0x00f686b3  // add	a3, a3, a5
	WORD $0xcc517057  // vsetivli	zero, 2, e8, mf8, ta, ma
	WORD $0x02068407  // vle8.v	v8, (a3)
	WORD $0x40c7063b  // subw	a2, a4, a2
	WORD $0x03161613  // slli	a2, a2, 49
	WORD $0x03065613  // srli	a2, a2, 48
	WORD $0x00f60633  // add	a2, a2, a5
	WORD $0x02060487  // vle8.v	v9, (a2)
	WORD $0xcc527057  // vsetivli	zero, 4, e8, mf8, ta, ma
	WORD $0x3a913457  // vslideup.vi	v8, v9, 2
	WORD $0x02050427  // vse8.v	v8, (a0)
	WORD $0x00400813  // li	a6, 4
LBB0_44:
	WORD $0x00000793  // li	a5, 0
	WORD $0x023876b7  // lui	a3, 9095
	WORD $0xfff00313  // li	t1, -1
	WORD $0x02035613  // srli	a2, t1, 32
	WORD $0xcd827057  // vsetivli	zero, 4, e64, m1, ta, ma
	WORD $0x5e064457  // vmv.v.x	v8, a2
	MOV $·p3349f7c8cbc5d84a_LCPI0_5(SB), X12  // lui	a2, %hi(.LCPI0_5)
	WORD $0xf276869b  // addiw	a3, a3, -217
	WORD $0x00c69693  // slli	a3, a3, 12
	WORD $0xfc168693  // addi	a3, a3, -63
	WORD $0x01069693  // slli	a3, a3, 16
	WORD $0x02d706b3  // mul	a3, a4, a3
	WORD $0x000d2737  // lui	a4, 210
	WORD $0x40d588b3  // sub	a7, a1, a3
	WORD $0x02d00593  // li	a1, 45
	MOV (X12), X12  // ld	a2, %lo(.LCPI0_5)(a2)
	WORD $0xb717069b  // addiw	a3, a4, -1167
	WORD $0x00c69693  // slli	a3, a3, 12
	WORD $0x75968693  // addi	a3, a3, 1881
	WORD $0x02c8b733  // mulhu	a4, a7, a2
	WORD $0x01a75393  // srli	t2, a4, 26
	WORD $0x0d707057  // vsetvli	zero, zero, e32, mf2, ta, ma
	WORD $0x5e03c4d7  // vmv.v.x	v9, t2
	WORD $0x3e9064d7  // vslide1down.vx	v9, v9, zero
	WORD $0x3e9064d7  // vslide1down.vx	v9, v9, zero
	WORD $0x3e9064d7  // vslide1down.vx	v9, v9, zero
	WORD $0x26940457  // vand.vv	v8, v9, v8
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x9686e457  // vmul.vx	v8, v8, a3
	MOV $·p3349f7c8cbc5d84a_LCPI0_6(SB), X12  // lui	a2, %hi(.LCPI0_6)
	MOV (X12), X12  // ld	a2, %lo(.LCPI0_6)(a2)
	WORD $0xa285c557  // vsrl.vx	v10, v8, a1
	WORD $0x42006457  // vmv.s.x	v8, zero
	WORD $0x5e0505d7  // vmv.v.v	v11, v10
	WORD $0x09707057  // vsetvli	zero, zero, e32, mf2, tu, ma
	WORD $0x3a80b5d7  // vslideup.vi	v11, v8, 1
	WORD $0x0d807057  // vsetvli	zero, zero, e64, m1, ta, ma
	WORD $0x5e064457  // vmv.v.x	v8, a2
	WORD $0x000025b7  // lui	a1, 2
	WORD $0x7105859b  // addiw	a1, a1, 1808
	WORD $0x96b5e5d7  // vmul.vx	v11, v11, a1
	WORD $0x0000b5b7  // lui	a1, 11
	WORD $0x7ff58593  // addi	a1, a1, 2047
	WORD $0xcd727057  // vsetivli	zero, 4, e32, mf2, ta, ma
	WORD $0x0a9584d7  // vsub.vv	v9, v9, v11
	WORD $0xc8f17057  // vsetivli	zero, 2, e16, mf2, tu, ma
	WORD $0x3a90b557  // vslideup.vi	v10, v9, 1
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x96a134d7  // vsll.vi	v9, v10, 2
	WORD $0xcce27057  // vsetivli	zero, 4, e16, mf4, ta, ma
	WORD $0xc294a5d7  // vwaddu.vv	v11, v9, v9
	WORD $0xf29365d7  // vwmaccu.vx	v11, t1, v9
	WORD $0xcd717057  // vsetivli	zero, 2, e32, mf2, ta, ma
	WORD $0xc2b5a557  // vwaddu.vv	v10, v11, v11
	WORD $0xf2b36557  // vwmaccu.vx	v10, t1, v11
	WORD $0x00800613  // li	a2, 8
LBB0_45:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3ea7c5d7  // vslidedown.vx	v11, v10, a5
	WORD $0x42b026d7  // vmv.x.s	a3, v11
	WORD $0x3e87c5d7  // vslidedown.vx	v11, v8, a5
	WORD $0x42b02757  // vmv.x.s	a4, v11
	WORD $0x03069693  // slli	a3, a3, 48
	WORD $0x00b77733  // and	a4, a4, a1
	WORD $0x0306d693  // srli	a3, a3, 48
	WORD $0x02e686b3  // mul	a3, a3, a4
	WORD $0x0106d693  // srli	a3, a3, 16
	WORD $0x4206e5d7  // vmv.s.x	v11, a3
	WORD $0x00178693  // addi	a3, a5, 1
	WORD $0x08f6f057  // vsetvli	zero, a3, e16, mf2, tu, ma
	WORD $0x3ab7c4d7  // vslideup.vx	v9, v11, a5
	WORD $0x00068793  // mv	a5, a3
	BNE X13, X12, LBB0_45  // bne	a3, a2, .LBB0_45
	WORD $0x00000613  // li	a2, 0
	WORD $0xc00015b7  // lui	a1, 786433
	WORD $0x0000b6b7  // lui	a3, 11
	WORD $0x00659713  // slli	a4, a1, 6
	WORD $0x88068593  // addi	a1, a3, -1920
	WORD $0x00170713  // addi	a4, a4, 1
	WORD $0x01b71713  // slli	a4, a4, 27
	WORD $0x08070693  // addi	a3, a4, 128
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x5e06c557  // vmv.v.x	v10, a3
	WORD $0x00800793  // li	a5, 8
LBB0_47:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3e9645d7  // vslidedown.vx	v11, v9, a2
	WORD $0x42b026d7  // vmv.x.s	a3, v11
	WORD $0x3ea645d7  // vslidedown.vx	v11, v10, a2
	WORD $0x42b02757  // vmv.x.s	a4, v11
	WORD $0x03069693  // slli	a3, a3, 48
	WORD $0x00b77733  // and	a4, a4, a1
	WORD $0x0306d693  // srli	a3, a3, 48
	WORD $0x02e686b3  // mul	a3, a3, a4
	WORD $0x0106d693  // srli	a3, a3, 16
	WORD $0x4206e5d7  // vmv.s.x	v11, a3
	WORD $0x00160693  // addi	a3, a2, 1
	WORD $0x08f6f057  // vsetvli	zero, a3, e16, mf2, tu, ma
	WORD $0x3ab64457  // vslideup.vx	v8, v11, a2
	WORD $0x00068613  // mv	a2, a3
	BNE X13, X15, LBB0_47  // bne	a3, a5, .LBB0_47
	WORD $0x00000593  // li	a1, 0
	WORD $0x00a00613  // li	a2, 10
	WORD $0x00800793  // li	a5, 8
LBB0_49:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3e85c557  // vslidedown.vx	v10, v8, a1
	WORD $0x42a026d7  // vmv.x.s	a3, v10
	WORD $0x02c686b3  // mul	a3, a3, a2
	WORD $0x4206e557  // vmv.s.x	v10, a3
	WORD $0x00158693  // addi	a3, a1, 1
	WORD $0x08f6f057  // vsetvli	zero, a3, e16, mf2, tu, ma
	WORD $0x3aa5c4d7  // vslideup.vx	v9, v10, a1
	WORD $0x00068593  // mv	a1, a3
	BNE X13, X15, LBB0_49  // bne	a3, a5, .LBB0_49
	WORD $0x00000793  // li	a5, 0
	WORD $0x025385b3  // mul	a1, t2, t0
	WORD $0x40b8863b  // subw	a2, a7, a1
	WORD $0xfff00593  // li	a1, -1
	WORD $0xcd727057  // vsetivli	zero, 4, e32, mf2, ta, ma
	WORD $0x5e064557  // vmv.v.x	v10, a2
	WORD $0x0205d613  // srli	a2, a1, 32
	WORD $0x0d807057  // vsetvli	zero, zero, e64, m1, ta, ma
	WORD $0x5e0645d7  // vmv.v.x	v11, a2
	WORD $0x000d2637  // lui	a2, 210
	WORD $0xb716061b  // addiw	a2, a2, -1167
	WORD $0x00c61613  // slli	a2, a2, 12
	WORD $0x0d707057  // vsetvli	zero, zero, e32, mf2, ta, ma
	WORD $0x3ea06557  // vslide1down.vx	v10, v10, zero
	WORD $0x75960613  // addi	a2, a2, 1881
	WORD $0x3ea06557  // vslide1down.vx	v10, v10, zero
	WORD $0x3ea06557  // vslide1down.vx	v10, v10, zero
	WORD $0x26a585d7  // vand.vv	v11, v10, v11
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x96b665d7  // vmul.vx	v11, v11, a2
	WORD $0x02d00613  // li	a2, 45
	WORD $0xa2b64657  // vsrl.vx	v12, v11, a2
	MOV $·p3349f7c8cbc5d84a_LCPI0_6(SB), X12  // lui	a2, %hi(.LCPI0_6)
	MOV (X12), X12  // ld	a2, %lo(.LCPI0_6)(a2)
	WORD $0x969834d7  // vsll.vi	v9, v9, 16
	WORD $0x420065d7  // vmv.s.x	v11, zero
	WORD $0x5e0606d7  // vmv.v.v	v13, v12
	WORD $0x09707057  // vsetvli	zero, zero, e32, mf2, tu, ma
	WORD $0x3ab0b6d7  // vslideup.vi	v13, v11, 1
	WORD $0x0d807057  // vsetvli	zero, zero, e64, m1, ta, ma
	WORD $0x5e0645d7  // vmv.v.x	v11, a2
	WORD $0x00002637  // lui	a2, 2
	WORD $0x7106061b  // addiw	a2, a2, 1808
	WORD $0x96d666d7  // vmul.vx	v13, v13, a2
	WORD $0x0000b637  // lui	a2, 11
	WORD $0x7ff60613  // addi	a2, a2, 2047
	WORD $0xcd727057  // vsetivli	zero, 4, e32, mf2, ta, ma
	WORD $0x0aa68557  // vsub.vv	v10, v10, v13
	WORD $0xc8f17057  // vsetivli	zero, 2, e16, mf2, tu, ma
	WORD $0x3aa0b657  // vslideup.vi	v12, v10, 1
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x96c13557  // vsll.vi	v10, v12, 2
	WORD $0xcce27057  // vsetivli	zero, 4, e16, mf4, ta, ma
	WORD $0xc2a526d7  // vwaddu.vv	v13, v10, v10
	WORD $0xf2a5e6d7  // vwmaccu.vx	v13, a1, v10
	WORD $0xcd717057  // vsetivli	zero, 2, e32, mf2, ta, ma
	WORD $0xc2d6a657  // vwaddu.vv	v12, v13, v13
	WORD $0xf2d5e657  // vwmaccu.vx	v12, a1, v13
	WORD $0x00800593  // li	a1, 8
LBB0_51:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3ec7c6d7  // vslidedown.vx	v13, v12, a5
	WORD $0x42d026d7  // vmv.x.s	a3, v13
	WORD $0x3eb7c6d7  // vslidedown.vx	v13, v11, a5
	WORD $0x42d02757  // vmv.x.s	a4, v13
	WORD $0x03069693  // slli	a3, a3, 48
	WORD $0x00c77733  // and	a4, a4, a2
	WORD $0x0306d693  // srli	a3, a3, 48
	WORD $0x02e686b3  // mul	a3, a3, a4
	WORD $0x0106d693  // srli	a3, a3, 16
	WORD $0x4206e6d7  // vmv.s.x	v13, a3
	WORD $0x00178693  // addi	a3, a5, 1
	WORD $0x08f6f057  // vsetvli	zero, a3, e16, mf2, tu, ma
	WORD $0x3ad7c557  // vslideup.vx	v10, v13, a5
	WORD $0x00068793  // mv	a5, a3
	BNE X13, X11, LBB0_51  // bne	a3, a1, .LBB0_51
	WORD $0x00000593  // li	a1, 0
	WORD $0xc0001637  // lui	a2, 786433
	WORD $0x0000b6b7  // lui	a3, 11
	WORD $0x00661713  // slli	a4, a2, 6
	WORD $0x88068613  // addi	a2, a3, -1920
	WORD $0x00170713  // addi	a4, a4, 1
	WORD $0x01b71713  // slli	a4, a4, 27
	WORD $0x08070693  // addi	a3, a4, 128
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x5e06c657  // vmv.v.x	v12, a3
	WORD $0x00800693  // li	a3, 8
LBB0_53:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3ea5c6d7  // vslidedown.vx	v13, v10, a1
	WORD $0x42d02757  // vmv.x.s	a4, v13
	WORD $0x3ec5c6d7  // vslidedown.vx	v13, v12, a1
	WORD $0x42d027d7  // vmv.x.s	a5, v13
	WORD $0x03071713  // slli	a4, a4, 48
	WORD $0x00c7f7b3  // and	a5, a5, a2
	WORD $0x03075713  // srli	a4, a4, 48
	WORD $0x02f70733  // mul	a4, a4, a5
	WORD $0x01075713  // srli	a4, a4, 16
	WORD $0x420766d7  // vmv.s.x	v13, a4
	WORD $0x00158713  // addi	a4, a1, 1
	WORD $0x08f77057  // vsetvli	zero, a4, e16, mf2, tu, ma
	WORD $0x3ad5c5d7  // vslideup.vx	v11, v13, a1
	WORD $0x00070593  // mv	a1, a4
	BNE X14, X13, LBB0_53  // bne	a4, a3, .LBB0_53
	WORD $0x00000593  // li	a1, 0
	WORD $0x00a00613  // li	a2, 10
	WORD $0x00800693  // li	a3, 8
LBB0_55:
	WORD $0xccf0f057  // vsetivli	zero, 1, e16, mf2, ta, ma
	WORD $0x3eb5c657  // vslidedown.vx	v12, v11, a1
	WORD $0x42c02757  // vmv.x.s	a4, v12
	WORD $0x02c70733  // mul	a4, a4, a2
	WORD $0x42076657  // vmv.s.x	v12, a4
	WORD $0x00158713  // addi	a4, a1, 1
	WORD $0x08f77057  // vsetvli	zero, a4, e16, mf2, tu, ma
	WORD $0x3ac5c557  // vslideup.vx	v10, v12, a1
	WORD $0x00070593  // mv	a1, a4
	BNE X14, X13, LBB0_55  // bne	a4, a3, .LBB0_55
	WORD $0xccf47057  // vsetivli	zero, 8, e16, mf2, ta, ma
	WORD $0x0a848457  // vsub.vv	v8, v8, v9
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x96a834d7  // vsll.vi	v9, v10, 16
	WORD $0x03000593  // li	a1, 48
	WORD $0x01050533  // add	a0, a0, a6
	WORD $0xccf47057  // vsetivli	zero, 8, e16, mf2, ta, ma
	WORD $0x0ab484d7  // vsub.vv	v9, v11, v9
	WORD $0xcc887057  // vsetivli	zero, 16, e16, m1, ta, ma
	WORD $0x3a943457  // vslideup.vi	v8, v9, 8
	WORD $0x1e804457  // vmax.vx	v8, v8, zero
	WORD $0x0c707057  // vsetvli	zero, zero, e8, mf2, ta, ma
	WORD $0xba803457  // vnclipu.wi	v8, v8, 0
	WORD $0x0285c457  // vadd.vx	v8, v8, a1
	WORD $0x02050427  // vse8.v	v8, (a0)
	WORD $0x01080593  // addi	a1, a6, 16
	JMP LBB0_8  // j	.LBB0_8
Lfunc_end0:


TEXT ·__u64toa(SB), NOSPLIT, $0-24
	NO_LOCAL_POINTERS

_entry___u64toa:
	MOV 16(g), X31      // g.stack.hi
	ADD $-64, SP, X30
	BLTU X30, X31, _stack_grow___u64toa

___u64toa:
	MOV out+0(FP), X10
	MOV val+8(FP), X11
	CALL ·__u64toa_riscv64_entry__(SB)
	MOV X10, ret+16(FP)
	RET

_stack_grow___u64toa:
	MOV X1, X3      // Save return address (RA)
	CALL runtime·morestack_noctxt(SB)
	JMP _entry___u64toa

// Data section
GLOBL ·p3349f7c8cbc5d84a_LCPI0_0(SB), RODATA, $8
DATA ·p3349f7c8cbc5d84a_LCPI0_0+0(SB)/8, $0x002386f26fc0ffff
GLOBL ·p3349f7c8cbc5d84a_LCPI0_1(SB), RODATA, $8
DATA ·p3349f7c8cbc5d84a_LCPI0_1+0(SB)/8, $0x39a5652fb1137857
GLOBL ·p3349f7c8cbc5d84a_LCPI0_2(SB), RODATA, $8
DATA ·p3349f7c8cbc5d84a_LCPI0_2+0(SB)/8, $0x016345785d89ffff
GLOBL ·p3349f7c8cbc5d84a_LCPI0_3(SB), RODATA, $8
DATA ·p3349f7c8cbc5d84a_LCPI0_3+0(SB)/8, $0x0de0b6b3a763ffff
GLOBL ·p3349f7c8cbc5d84a_LCPI0_4(SB), RODATA, $8
DATA ·p3349f7c8cbc5d84a_LCPI0_4+0(SB)/8, $0x8ac7230489e7ffff
GLOBL ·p3349f7c8cbc5d84a_LCPI0_5(SB), RODATA, $8
DATA ·p3349f7c8cbc5d84a_LCPI0_5+0(SB)/8, $0xabcc77118461cefd
GLOBL ·p3349f7c8cbc5d84a_LCPI0_6(SB), RODATA, $8
DATA ·p3349f7c8cbc5d84a_LCPI0_6+0(SB)/8, $0x80003334147b20c5
GLOBL ·p3349f7c8cbc5d84a_LCPI0_7(SB), RODATA, $32
DATA ·p3349f7c8cbc5d84a_LCPI0_7+0(SB)/8, $0x03180e1d021c0100
DATA ·p3349f7c8cbc5d84a_LCPI0_7+8(SB)/8, $0x080411190f14161e
DATA ·p3349f7c8cbc5d84a_LCPI0_7+16(SB)/8, $0x07101315170d1b1f
DATA ·p3349f7c8cbc5d84a_LCPI0_7+24(SB)/8, $0x090a050b06120c1a
GLOBL ·p3349f7c8cbc5d84a_Digits(SB), RODATA, $200
DATA ·p3349f7c8cbc5d84a_Digits+0(SB)/8, $0x3330323031303030
DATA ·p3349f7c8cbc5d84a_Digits+8(SB)/8, $0x3730363035303430
DATA ·p3349f7c8cbc5d84a_Digits+16(SB)/8, $0x3131303139303830
DATA ·p3349f7c8cbc5d84a_Digits+24(SB)/8, $0x3531343133313231
DATA ·p3349f7c8cbc5d84a_Digits+32(SB)/8, $0x3931383137313631
DATA ·p3349f7c8cbc5d84a_Digits+40(SB)/8, $0x3332323231323032
DATA ·p3349f7c8cbc5d84a_Digits+48(SB)/8, $0x3732363235323432
DATA ·p3349f7c8cbc5d84a_Digits+56(SB)/8, $0x3133303339323832
DATA ·p3349f7c8cbc5d84a_Digits+64(SB)/8, $0x3533343333333233
DATA ·p3349f7c8cbc5d84a_Digits+72(SB)/8, $0x3933383337333633
DATA ·p3349f7c8cbc5d84a_Digits+80(SB)/8, $0x3334323431343034
DATA ·p3349f7c8cbc5d84a_Digits+88(SB)/8, $0x3734363435343434
DATA ·p3349f7c8cbc5d84a_Digits+96(SB)/8, $0x3135303539343834
DATA ·p3349f7c8cbc5d84a_Digits+104(SB)/8, $0x3535343533353235
DATA ·p3349f7c8cbc5d84a_Digits+112(SB)/8, $0x3935383537353635
DATA ·p3349f7c8cbc5d84a_Digits+120(SB)/8, $0x3336323631363036
DATA ·p3349f7c8cbc5d84a_Digits+128(SB)/8, $0x3736363635363436
DATA ·p3349f7c8cbc5d84a_Digits+136(SB)/8, $0x3137303739363836
DATA ·p3349f7c8cbc5d84a_Digits+144(SB)/8, $0x3537343733373237
DATA ·p3349f7c8cbc5d84a_Digits+152(SB)/8, $0x3937383737373637
DATA ·p3349f7c8cbc5d84a_Digits+160(SB)/8, $0x3338323831383038
DATA ·p3349f7c8cbc5d84a_Digits+168(SB)/8, $0x3738363835383438
DATA ·p3349f7c8cbc5d84a_Digits+176(SB)/8, $0x3139303939383838
DATA ·p3349f7c8cbc5d84a_Digits+184(SB)/8, $0x3539343933393239
DATA ·p3349f7c8cbc5d84a_Digits+192(SB)/8, $0x3939383937393639
GLOBL ·p3349f7c8cbc5d84a_VecShiftShuffles(SB), RODATA, $144
DATA ·p3349f7c8cbc5d84a_VecShiftShuffles+0(SB)/8, $0x0706050403020100
DATA ·p3349f7c8cbc5d84a_VecShiftShuffles+8(SB)/8, $0x0f0e0d0c0b0a0908
DATA ·p3349f7c8cbc5d84a_VecShiftShuffles+16(SB)/8, $0x0807060504030201
DATA ·p3349f7c8cbc5d84a_VecShiftShuffles+24(SB)/8, $0xff0f0e0d0c0b0a09
DATA ·p3349f7c8cbc5d84a_VecShiftShuffles+32(SB)/8, $0x0908070605040302
DATA ·p3349f7c8cbc5d84a_VecShiftShuffles+40(SB)/8, $0xffff0f0e0d0c0b0a
DATA ·p3349f7c8cbc5d84a_VecShiftShuffles+48(SB)/8, $0x0a09080706050403
DATA ·p3349f7c8cbc5d84a_VecShiftShuffles+56(SB)/8, $0xffffff0f0e0d0c0b
DATA ·p3349f7c8cbc5d84a_VecShiftShuffles+64(SB)/8, $0x0b0a090807060504
DATA ·p3349f7c8cbc5d84a_VecShiftShuffles+72(SB)/8, $0xffffffff0f0e0d0c
DATA ·p3349f7c8cbc5d84a_VecShiftShuffles+80(SB)/8, $0x0c0b0a0908070605
DATA ·p3349f7c8cbc5d84a_VecShiftShuffles+88(SB)/8, $0xffffffffff0f0e0d
DATA ·p3349f7c8cbc5d84a_VecShiftShuffles+96(SB)/8, $0x0d0c0b0a09080706
DATA ·p3349f7c8cbc5d84a_VecShiftShuffles+104(SB)/8, $0xffffffffffff0f0e
DATA ·p3349f7c8cbc5d84a_VecShiftShuffles+112(SB)/8, $0x0e0d0c0b0a090807
DATA ·p3349f7c8cbc5d84a_VecShiftShuffles+120(SB)/8, $0xffffffffffffff0f
DATA ·p3349f7c8cbc5d84a_VecShiftShuffles+128(SB)/8, $0x0f0e0d0c0b0a0908
DATA ·p3349f7c8cbc5d84a_VecShiftShuffles+136(SB)/8, $0xffffffffffffffff
