// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

#include "go_asm.h"
#include "funcdata.h"
#include "textflag.h"

TEXT ·__unquote_entry__(SB), NOSPLIT, $0-8
	MOV $·__unquote_riscv64_entry__(SB), A0
	MOV A0, ret+0(FP)
	RET

TEXT ·__unquote_riscv64_entry__(SB), NOSPLIT, $144
	NO_LOCAL_POINTERS
unquote:
	WORD $0xf6010113  // addi	sp, sp, -160
	WORD $0x08113c23  // sd	ra, 152(sp)
	WORD $0x08813823  // sd	s0, 144(sp)
	WORD $0x08913423  // sd	s1, 136(sp)
	WORD $0x09213023  // sd	s2, 128(sp)
	WORD $0x07313c23  // sd	s3, 120(sp)
	WORD $0x07413823  // sd	s4, 112(sp)
	WORD $0x07513423  // sd	s5, 104(sp)
	WORD $0x07613023  // sd	s6, 96(sp)
	WORD $0x05713c23  // sd	s7, 88(sp)
	WORD $0x05813823  // sd	s8, 80(sp)
	WORD $0x05913423  // sd	s9, 72(sp)
	WORD $0x05a13023  // sd	s10, 64(sp)
	WORD $0x03b13c23  // sd	s11, 56(sp)
	BEQZ X11, LBB0_29  // beqz	a1, .LBB0_29
	WORD $0x00d13823  // sd	a3, 16(sp)
	WORD $0x00177493  // andi	s1, a4, 1
	WORD $0x05c00813  // li	a6, 92
	MOV $·p579889e1908cca3a_UnquoteTab(SB), X8  // lui	s0, %hi(_UnquoteTab)
	// addi	s0, s0, %lo(_UnquoteTab) (skipped, covered by MOV address load)
	WORD $0x01000a13  // li	s4, 16
	WORD $0xfff00d13  // li	s10, -1
	WORD $0x077cb6b7  // lui	a3, 30667
	WORD $0x0c007757  // vsetvli	a4, zero, e8, m1, ta, ma
	WORD $0x42086457  // vmv.s.x	v8, a6
	WORD $0x53168693  // addi	a3, a3, 1329
	WORD $0x00d13c23  // sd	a3, 24(sp)
	WORD $0x00a13023  // sd	a0, 0(sp)
	WORD $0x00050f93  // mv	t6, a0
	WORD $0x00b13423  // sd	a1, 8(sp)
	WORD $0x00058e93  // mv	t4, a1
	WORD $0x00060593  // mv	a1, a2
	WORD $0x02c13423  // sd	a2, 40(sp)
	WORD $0x02913023  // sd	s1, 32(sp)
LBB0_2:
	WORD $0x000fc683  // lbu	a3, 0(t6)
	BNE X13, X16, LBB0_4  // bne	a3, a6, .LBB0_4
	WORD $0x00000793  // li	a5, 0
	JMP LBB0_17  // j	.LBB0_17
LBB0_4:
	WORD $0x00000693  // li	a3, 0
LBB0_5:
	WORD $0x00168713  // addi	a4, a3, 1
	WORD $0x08777057  // vsetvli	zero, a4, e8, mf2, tu, ma
	WORD $0x3a86c4d7  // vslideup.vx	v9, v8, a3
	WORD $0x00070693  // mv	a3, a4
	BNE X14, X20, LBB0_5  // bne	a4, s4, .LBB0_5
	WORD $0x000e8693  // mv	a3, t4
	WORD $0x02b13823  // sd	a1, 48(sp)
	WORD $0x00058413  // mv	s0, a1
	WORD $0x000f8493  // mv	s1, t6
	BLT X29, X20, LBB0_11  // blt	t4, s4, .LBB0_11
LBB0_7:
	WORD $0x00000793  // li	a5, 0
	WORD $0x00068a93  // mv	s5, a3
	WORD $0x0084cb03  // lbu	s6, 8(s1)
	WORD $0x0094c603  // lbu	a2, 9(s1)
	WORD $0x00a4c883  // lbu	a7, 10(s1)
	WORD $0x00b4ce03  // lbu	t3, 11(s1)
	WORD $0x00c4cb83  // lbu	s7, 12(s1)
	WORD $0x00d4c283  // lbu	t0, 13(s1)
	WORD $0x00e4c683  // lbu	a3, 14(s1)
	WORD $0x00f4c803  // lbu	a6, 15(s1)
	WORD $0x0004cc83  // lbu	s9, 0(s1)
	WORD $0x0014c303  // lbu	t1, 1(s1)
	WORD $0x0024c903  // lbu	s2, 2(s1)
	WORD $0x0034c983  // lbu	s3, 3(s1)
	WORD $0x0044c383  // lbu	t2, 4(s1)
	WORD $0x0054c503  // lbu	a0, 5(s1)
	WORD $0x0064cf03  // lbu	t5, 6(s1)
	WORD $0x0074c583  // lbu	a1, 7(s1)
	WORD $0x00f00713  // li	a4, 15
	WORD $0x00861c13  // slli	s8, a2, 8
	WORD $0x01089d93  // slli	s11, a7, 16
	WORD $0x018e1093  // slli	ra, t3, 24
	WORD $0x005406a3  // sb	t0, 13(s0)
	WORD $0x00829293  // slli	t0, t0, 8
	WORD $0x00d40723  // sb	a3, 14(s0)
	WORD $0x01069693  // slli	a3, a3, 16
	WORD $0x010407a3  // sb	a6, 15(s0)
	WORD $0x01881813  // slli	a6, a6, 24
	WORD $0x01140523  // sb	a7, 10(s0)
	WORD $0x00831893  // slli	a7, t1, 8
	WORD $0x01c405a3  // sb	t3, 11(s0)
	WORD $0x01091e13  // slli	t3, s2, 16
	WORD $0x00c404a3  // sb	a2, 9(s0)
	WORD $0x01899613  // slli	a2, s3, 24
	WORD $0x00a402a3  // sb	a0, 5(s0)
	WORD $0x00851513  // slli	a0, a0, 8
	WORD $0x01e40323  // sb	t5, 6(s0)
	WORD $0x010f1f13  // slli	t5, t5, 16
	WORD $0x00b403a3  // sb	a1, 7(s0)
	WORD $0x01859593  // slli	a1, a1, 24
	WORD $0x01740623  // sb	s7, 12(s0)
	WORD $0x01640423  // sb	s6, 8(s0)
	WORD $0x00740223  // sb	t2, 4(s0)
	WORD $0x01240123  // sb	s2, 2(s0)
	WORD $0x013401a3  // sb	s3, 3(s0)
	WORD $0x01940023  // sb	s9, 0(s0)
	WORD $0x006400a3  // sb	t1, 1(s0)
	WORD $0x016c6333  // or	t1, s8, s6
	WORD $0x01b0e933  // or	s2, ra, s11
	WORD $0x0172e2b3  // or	t0, t0, s7
	WORD $0x00d866b3  // or	a3, a6, a3
	WORD $0x0198e833  // or	a6, a7, s9
	WORD $0x01c66633  // or	a2, a2, t3
	WORD $0x00756533  // or	a0, a0, t2
	WORD $0x01e5e5b3  // or	a1, a1, t5
	WORD $0x006968b3  // or	a7, s2, t1
	WORD $0x0056e6b3  // or	a3, a3, t0
	WORD $0x01066633  // or	a2, a2, a6
	WORD $0x00b56533  // or	a0, a0, a1
	WORD $0x02069693  // slli	a3, a3, 32
	WORD $0x02051513  // slli	a0, a0, 32
	WORD $0x0116e5b3  // or	a1, a3, a7
	WORD $0x00c56533  // or	a0, a0, a2
	WORD $0xcd817057  // vsetivli	zero, 2, e64, m1, ta, ma
	WORD $0x5e054557  // vmv.v.x	v10, a0
	WORD $0x3ea5e557  // vslide1down.vx	v10, v10, a1
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62950557  // vmseq.vv	v10, v9, v10
	WORD $0x00f00693  // li	a3, 15
LBB0_8:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x42a02557  // vmv.x.s	a0, v10
	WORD $0x00d55533  // srl	a0, a0, a3
	WORD $0xfff68693  // addi	a3, a3, -1
	WORD $0x00157513  // andi	a0, a0, 1
	WORD $0x00e5153b  // sllw	a0, a0, a4
	WORD $0x00a7e7b3  // or	a5, a5, a0
	WORD $0xfff70713  // addi	a4, a4, -1
	BNE X13, X26, LBB0_8  // bne	a3, s10, .LBB0_8
	BNEZ X15, LBB0_15  // bnez	a5, .LBB0_15
	WORD $0x01048493  // addi	s1, s1, 16
	WORD $0x01040413  // addi	s0, s0, 16
	WORD $0xff0a8693  // addi	a3, s5, -16
	WORD $0x01f00513  // li	a0, 31
	BLT X10, X21, LBB0_7  // blt	a0, s5, .LBB0_7
LBB0_11:
	BEQZ X13, LBB0_34  // beqz	a3, .LBB0_34
	WORD $0x41f487b3  // sub	a5, s1, t6
	WORD $0x02813603  // ld	a2, 40(sp)
	WORD $0x03013583  // ld	a1, 48(sp)
	WORD $0x05c00813  // li	a6, 92
LBB0_13:
	WORD $0x0004c703  // lbu	a4, 0(s1)
	BEQ X14, X16, LBB0_16  // beq	a4, a6, .LBB0_16
	WORD $0xfff68693  // addi	a3, a3, -1
	WORD $0x00148493  // addi	s1, s1, 1
	WORD $0x00e40023  // sb	a4, 0(s0)
	WORD $0x00140413  // addi	s0, s0, 1
	WORD $0x00178793  // addi	a5, a5, 1
	BNEZ X13, LBB0_13  // bnez	a3, .LBB0_13
	JMP LBB0_30  // j	.LBB0_30
LBB0_15:
	WORD $0x40f0053b  // negw	a0, a5
	WORD $0x00f57533  // and	a0, a0, a5
	WORD $0x01813583  // ld	a1, 24(sp)
	WORD $0x02b50533  // mul	a0, a0, a1
	WORD $0x01b5551b  // srliw	a0, a0, 27
	MOV $·p579889e1908cca3a_LCPI0_0(SB), X11  // lui	a1, %hi(.LCPI0_0)
	// addi	a1, a1, %lo(.LCPI0_0) (skipped, covered by MOV address load)
	WORD $0x00b50533  // add	a0, a0, a1
	WORD $0x00054783  // lbu	a5, 0(a0)
	WORD $0x41f48533  // sub	a0, s1, t6
	WORD $0x00a787b3  // add	a5, a5, a0
	WORD $0x02813603  // ld	a2, 40(sp)
	WORD $0x03013583  // ld	a1, 48(sp)
	WORD $0x05c00813  // li	a6, 92
LBB0_16:
	WORD $0x02013483  // ld	s1, 32(sp)
	MOV $·p579889e1908cca3a_UnquoteTab(SB), X8  // lui	s0, %hi(_UnquoteTab)
	// addi	s0, s0, %lo(_UnquoteTab) (skipped, covered by MOV address load)
	BEQ X15, X26, LBB0_30  // beq	a5, s10, .LBB0_30
LBB0_17:
	WORD $0x00278693  // addi	a3, a5, 2
	WORD $0x40de8eb3  // sub	t4, t4, a3
	BLTZ X29, LBB0_32  // bltz	t4, .LBB0_32
	WORD $0x00df8fb3  // add	t6, t6, a3
	BNEZ X9, LBB0_21  // bnez	s1, .LBB0_21
LBB0_19:
	WORD $0xffffc503  // lbu	a0, -1(t6)
	WORD $0x00850533  // add	a0, a0, s0
	WORD $0x00054683  // lbu	a3, 0(a0)
	BEQZ X13, LBB0_33  // beqz	a3, .LBB0_33
	WORD $0x00b787b3  // add	a5, a5, a1
	WORD $0x00178593  // addi	a1, a5, 1
	WORD $0x00d78023  // sb	a3, 0(a5)
	BNEZ X29, LBB0_2  // bnez	t4, .LBB0_2
	JMP LBB0_30  // j	.LBB0_30
LBB0_21:
	WORD $0x000e869b  // sext.w	a3, t4
	BEQZ X13, LBB0_32  // beqz	a3, .LBB0_32
	WORD $0xffffc503  // lbu	a0, -1(t6)
	BNE X10, X16, LBB0_19  // bne	a0, a6, .LBB0_19
	WORD $0x000fc503  // lbu	a0, 0(t6)
	BNE X10, X16, LBB0_28  // bne	a0, a6, .LBB0_28
	WORD $0x00100513  // li	a0, 1
	BGE X10, X13, LBB0_32  // bge	a0, a3, .LBB0_32
	WORD $0x001fc683  // lbu	a3, 1(t6)
	WORD $0x02200513  // li	a0, 34
	BEQ X13, X10, LBB0_27  // beq	a3, a0, .LBB0_27
	BNE X13, X16, LBB0_35  // bne	a3, a6, .LBB0_35
LBB0_27:
	WORD $0x001f8f93  // addi	t6, t6, 1
	WORD $0xfffe8e93  // addi	t4, t4, -1
LBB0_28:
	WORD $0x001f8f93  // addi	t6, t6, 1
	WORD $0xfffe8e93  // addi	t4, t4, -1
	JMP LBB0_19  // j	.LBB0_19
LBB0_29:
	WORD $0x00000e93  // li	t4, 0
	WORD $0x00060593  // mv	a1, a2
LBB0_30:
	WORD $0x00be8eb3  // add	t4, t4, a1
	WORD $0x40ce8533  // sub	a0, t4, a2
LBB0_31:
	WORD $0x09813083  // ld	ra, 152(sp)
	WORD $0x09013403  // ld	s0, 144(sp)
	WORD $0x08813483  // ld	s1, 136(sp)
	WORD $0x08013903  // ld	s2, 128(sp)
	WORD $0x07813983  // ld	s3, 120(sp)
	WORD $0x07013a03  // ld	s4, 112(sp)
	WORD $0x06813a83  // ld	s5, 104(sp)
	WORD $0x06013b03  // ld	s6, 96(sp)
	WORD $0x05813b83  // ld	s7, 88(sp)
	WORD $0x05013c03  // ld	s8, 80(sp)
	WORD $0x04813c83  // ld	s9, 72(sp)
	WORD $0x04013d03  // ld	s10, 64(sp)
	WORD $0x03813d83  // ld	s11, 56(sp)
	WORD $0x0a010113  // addi	sp, sp, 160
	RET  // ret
LBB0_32:
	WORD $0x01013503  // ld	a0, 16(sp)
	WORD $0x00813583  // ld	a1, 8(sp)
	WORD $0x00b53023  // sd	a1, 0(a0)
	WORD $0xfff00513  // li	a0, -1
	JMP LBB0_31  // j	.LBB0_31
LBB0_33:
	WORD $0x00013503  // ld	a0, 0(sp)
	WORD $0xfff54513  // not	a0, a0
	WORD $0x01f50533  // add	a0, a0, t6
	WORD $0x01013583  // ld	a1, 16(sp)
	WORD $0x00a5b023  // sd	a0, 0(a1)
	WORD $0xffd00513  // li	a0, -3
	JMP LBB0_31  // j	.LBB0_31
LBB0_34:
	WORD $0x02813603  // ld	a2, 40(sp)
	WORD $0x03013583  // ld	a1, 48(sp)
	JMP LBB0_30  // j	.LBB0_30
LBB0_35:
	WORD $0x00013503  // ld	a0, 0(sp)
	WORD $0x40af8533  // sub	a0, t6, a0
	WORD $0x00150513  // addi	a0, a0, 1
	WORD $0x01013583  // ld	a1, 16(sp)
	WORD $0x00a5b023  // sd	a0, 0(a1)
	WORD $0xffe00513  // li	a0, -2
	JMP LBB0_31  // j	.LBB0_31
Lfunc_end0:


TEXT ·__unquote(SB), NOSPLIT, $0-48
	NO_LOCAL_POINTERS

_entry___unquote:
	MOV 16(g), X17      // g.stack.hi
	ADD $-224, SP, X16
	BLTU X16, X17, _stack_grow___unquote

___unquote:
	MOV sp+0(FP), X10
	MOV nb+8(FP), X11
	MOV dp+16(FP), X12
	MOV ep+24(FP), X13
	MOV flags+32(FP), X14
	CALL ·__unquote_riscv64_entry__(SB)
	MOV X10, ret+40(FP)
	RET

_stack_grow___unquote:
	MOV X1, X5
	CALL runtime·morestack_noctxt(SB)
	JMP _entry___unquote

// Data section
GLOBL ·p579889e1908cca3a_LCPI0_0(SB), RODATA, $32
DATA ·p579889e1908cca3a_LCPI0_0+0(SB)/8, $0x03180e1d021c0100
DATA ·p579889e1908cca3a_LCPI0_0+8(SB)/8, $0x080411190f14161e
DATA ·p579889e1908cca3a_LCPI0_0+16(SB)/8, $0x07101315170d1b1f
DATA ·p579889e1908cca3a_LCPI0_0+24(SB)/8, $0x090a050b06120c1a
GLOBL ·p579889e1908cca3a_UnquoteTab(SB), RODATA, $256
DATA ·p579889e1908cca3a_UnquoteTab+0(SB)/8, $0x0000000000000000
DATA ·p579889e1908cca3a_UnquoteTab+8(SB)/8, $0x0000000000000000
DATA ·p579889e1908cca3a_UnquoteTab+16(SB)/8, $0x0000000000000000
DATA ·p579889e1908cca3a_UnquoteTab+24(SB)/8, $0x0000000000000000
DATA ·p579889e1908cca3a_UnquoteTab+32(SB)/8, $0x0000000000220000
DATA ·p579889e1908cca3a_UnquoteTab+40(SB)/8, $0x2f00000000000000
DATA ·p579889e1908cca3a_UnquoteTab+48(SB)/8, $0x0000000000000000
DATA ·p579889e1908cca3a_UnquoteTab+56(SB)/8, $0x0000000000000000
DATA ·p579889e1908cca3a_UnquoteTab+64(SB)/8, $0x0000000000000000
DATA ·p579889e1908cca3a_UnquoteTab+72(SB)/8, $0x0000000000000000
DATA ·p579889e1908cca3a_UnquoteTab+80(SB)/8, $0x0000000000000000
DATA ·p579889e1908cca3a_UnquoteTab+88(SB)/8, $0x0000005c00000000
DATA ·p579889e1908cca3a_UnquoteTab+96(SB)/8, $0x000c000000080000
DATA ·p579889e1908cca3a_UnquoteTab+104(SB)/8, $0x000a000000000000
DATA ·p579889e1908cca3a_UnquoteTab+112(SB)/8, $0x0000ff09000d0000
DATA ·p579889e1908cca3a_UnquoteTab+120(SB)/8, $0x0000000000000000
DATA ·p579889e1908cca3a_UnquoteTab+128(SB)/8, $0x0000000000000000
DATA ·p579889e1908cca3a_UnquoteTab+136(SB)/8, $0x0000000000000000
DATA ·p579889e1908cca3a_UnquoteTab+144(SB)/8, $0x0000000000000000
DATA ·p579889e1908cca3a_UnquoteTab+152(SB)/8, $0x0000000000000000
DATA ·p579889e1908cca3a_UnquoteTab+160(SB)/8, $0x0000000000000000
DATA ·p579889e1908cca3a_UnquoteTab+168(SB)/8, $0x0000000000000000
DATA ·p579889e1908cca3a_UnquoteTab+176(SB)/8, $0x0000000000000000
DATA ·p579889e1908cca3a_UnquoteTab+184(SB)/8, $0x0000000000000000
DATA ·p579889e1908cca3a_UnquoteTab+192(SB)/8, $0x0000000000000000
DATA ·p579889e1908cca3a_UnquoteTab+200(SB)/8, $0x0000000000000000
DATA ·p579889e1908cca3a_UnquoteTab+208(SB)/8, $0x0000000000000000
DATA ·p579889e1908cca3a_UnquoteTab+216(SB)/8, $0x0000000000000000
DATA ·p579889e1908cca3a_UnquoteTab+224(SB)/8, $0x0000000000000000
DATA ·p579889e1908cca3a_UnquoteTab+232(SB)/8, $0x0000000000000000
DATA ·p579889e1908cca3a_UnquoteTab+240(SB)/8, $0x0000000000000000
DATA ·p579889e1908cca3a_UnquoteTab+248(SB)/8, $0x0000000000000000
