// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package rvv

//go:nosplit
//go:noescape
//goland:noinspection ALL
func __unquote_entry__() uintptr

var (
    _subr__unquote uintptr = __unquote_entry__() + 0
)

const (
    _stack__unquote = 160
)

var (
    _ = _subr__unquote
)

const (
    _ = _stack__unquote
)
