// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

#include "go_asm.h"
#include "funcdata.h"
#include "textflag.h"

TEXT ·__validate_utf8_entry__(SB), NOSPLIT, $0-8
	MOV $·__validate_utf8_riscv64_entry__(SB), A0
	MOV A0, ret+0(FP)
	RET

TEXT ·__validate_utf8_riscv64_entry__(SB), NOSPLIT, $32
	NO_LOCAL_POINTERS
validate_utf8:
	WORD $0xfd010113  // addi	sp, sp, -48
	WORD $0x02813423  // sd	s0, 40(sp)
	WORD $0x02913023  // sd	s1, 32(sp)
	WORD $0x01213c23  // sd	s2, 24(sp)
	WORD $0x01313823  // sd	s3, 16(sp)
	WORD $0x01413423  // sd	s4, 8(sp)
	WORD $0x00053383  // ld	t2, 0(a0)
	WORD $0x0005b783  // ld	a5, 0(a1)
	WORD $0x00853983  // ld	s3, 8(a0)
	WORD $0x007787b3  // add	a5, a5, t2
	WORD $0x007989b3  // add	s3, s3, t2
	WORD $0xffd98693  // addi	a3, s3, -3
	BGEU X15, X13, LBB0_15  // bgeu	a5, a3, .LBB0_15
	WORD $0x00c0c8b7  // lui	a7, 3084
	WORD $0x0000c337  // lui	t1, 12
	WORD $0x000032b7  // lui	t0, 3
	WORD $0x00002eb7  // lui	t4, 2
	WORD $0x00860813  // addi	a6, a2, 8
	WORD $0x00808537  // lui	a0, 2056
	WORD $0x00008437  // lui	s0, 8
	WORD $0xc0c0c737  // lui	a4, 789516
	WORD $0x808084b7  // lui	s1, 526344
	WORD $0x0f088e1b  // addiw	t3, a7, 240
	WORD $0x0e03089b  // addiw	a7, t1, 224
	WORD $0x0032829b  // addiw	t0, t0, 3
	WORD $0x00fe831b  // addiw	t1, t4, 15
	WORD $0x0e05051b  // addiw	a0, a0, 224
	WORD $0x00de8e9b  // addiw	t4, t4, 13
	WORD $0x0c040f1b  // addiw	t5, s0, 192
	WORD $0x0f870f93  // addi	t6, a4, 248
	WORD $0x00428913  // addi	s2, t0, 4
	WORD $0x0f048a1b  // addiw	s4, s1, 240
LBB0_2:
	WORD $0x00078403  // lb	s0, 0(a5)
	WORD $0x00100713  // li	a4, 1
	BLTZ X8, LBB0_4  // bltz	s0, .LBB0_4
LBB0_3:
	WORD $0x00e787b3  // add	a5, a5, a4
	BLTU X15, X13, LBB0_2  // bltu	a5, a3, .LBB0_2
	JMP LBB0_15  // j	.LBB0_15
LBB0_4:
	WORD $0x0007e403  // lwu	s0, 0(a5)
	WORD $0x01c47733  // and	a4, s0, t3
	BNE X14, X10, LBB0_7  // bne	a4, a0, .LBB0_7
	WORD $0x006474b3  // and	s1, s0, t1
	BEQ X9, X29, LBB0_7  // beq	s1, t4, .LBB0_7
	WORD $0x00300713  // li	a4, 3
	BNEZ X9, LBB0_3  // bnez	s1, .LBB0_3
LBB0_7:
	WORD $0x01147733  // and	a4, s0, a7
	BNE X14, X30, LBB0_9  // bne	a4, t5, .LBB0_9
	WORD $0x01e47493  // andi	s1, s0, 30
	WORD $0x00200713  // li	a4, 2
	BNEZ X9, LBB0_3  // bnez	s1, .LBB0_3
LBB0_9:
	WORD $0x01f47733  // and	a4, s0, t6
	WORD $0x0007071b  // sext.w	a4, a4
	BNE X14, X20, LBB0_13  // bne	a4, s4, .LBB0_13
	WORD $0x01247733  // and	a4, s0, s2
	BEQZ X14, LBB0_13  // beqz	a4, .LBB0_13
	WORD $0x00447493  // andi	s1, s0, 4
	WORD $0x00400713  // li	a4, 4
	BEQZ X9, LBB0_3  // beqz	s1, .LBB0_3
	WORD $0x00547433  // and	s0, s0, t0
	BEQZ X8, LBB0_3  // beqz	s0, .LBB0_3
LBB0_13:
	WORD $0x00063703  // ld	a4, 0(a2)
	WORD $0x00c75493  // srli	s1, a4, 12
	WORD $0x40778433  // sub	s0, a5, t2
	BNEZ X9, LBB0_34  // bnez	s1, .LBB0_34
	WORD $0x0004041b  // sext.w	s0, s0
	WORD $0x00170493  // addi	s1, a4, 1
	WORD $0x00371713  // slli	a4, a4, 3
	WORD $0x00963023  // sd	s1, 0(a2)
	WORD $0x01070733  // add	a4, a4, a6
	WORD $0x00873023  // sd	s0, 0(a4)
	WORD $0x00100713  // li	a4, 1
	JMP LBB0_3  // j	.LBB0_3
LBB0_15:
	BGEU X15, X19, LBB0_31  // bgeu	a5, s3, .LBB0_31
	WORD $0x00c0c537  // lui	a0, 3084
	WORD $0x0000c6b7  // lui	a3, 12
	WORD $0x00002e37  // lui	t3, 2
	WORD $0x00860813  // addi	a6, a2, 8
	WORD $0x00200893  // li	a7, 2
	WORD $0x00808737  // lui	a4, 2056
	WORD $0x000084b7  // lui	s1, 8
	WORD $0x0f050f1b  // addiw	t5, a0, 240
	WORD $0x0e06829b  // addiw	t0, a3, 224
	WORD $0x00fe031b  // addiw	t1, t3, 15
	WORD $0x0e070f9b  // addiw	t6, a4, 224
	WORD $0x00de0e1b  // addiw	t3, t3, 13
	WORD $0x0c048e9b  // addiw	t4, s1, 192
LBB0_17:
	WORD $0x00078503  // lb	a0, 0(a5)
	BLTZ X10, LBB0_19  // bltz	a0, .LBB0_19
	WORD $0x00178793  // addi	a5, a5, 1
	BLTU X15, X19, LBB0_17  // bltu	a5, s3, .LBB0_17
	JMP LBB0_31  // j	.LBB0_31
LBB0_19:
	WORD $0x00010223  // sb	zero, 4(sp)
	WORD $0x40f98533  // sub	a0, s3, a5
	WORD $0x00010123  // sb	zero, 2(sp)
	BLTU X10, X17, LBB0_21  // bltu	a0, a7, .LBB0_21
	WORD $0x0007c483  // lbu	s1, 0(a5)
	WORD $0x0017c403  // lbu	s0, 1(a5)
	WORD $0x00278693  // addi	a3, a5, 2
	WORD $0xffe50513  // addi	a0, a0, -2
	WORD $0x00910223  // sb	s1, 4(sp)
	WORD $0x00210713  // addi	a4, sp, 2
	BNEZ X10, LBB0_22  // bnez	a0, .LBB0_22
	JMP LBB0_23  // j	.LBB0_23
LBB0_21:
	WORD $0x00000493  // li	s1, 0
	WORD $0x00000413  // li	s0, 0
	WORD $0x00410713  // addi	a4, sp, 4
	WORD $0x00078693  // mv	a3, a5
	BEQZ X10, LBB0_23  // beqz	a0, .LBB0_23
LBB0_22:
	WORD $0x0006c503  // lbu	a0, 0(a3)
	WORD $0x00a70023  // sb	a0, 0(a4)
	WORD $0x00414483  // lbu	s1, 4(sp)
	WORD $0x00214503  // lbu	a0, 2(sp)
LBB0_23:
	WORD $0x01051513  // slli	a0, a0, 16
	WORD $0x00841413  // slli	s0, s0, 8
	WORD $0x00856533  // or	a0, a0, s0
	WORD $0x00956533  // or	a0, a0, s1
	WORD $0x01e576b3  // and	a3, a0, t5
	BNE X13, X31, LBB0_26  // bne	a3, t6, .LBB0_26
	WORD $0x00657733  // and	a4, a0, t1
	BEQ X14, X28, LBB0_26  // beq	a4, t3, .LBB0_26
	WORD $0x00300693  // li	a3, 3
	BNEZ X14, LBB0_30  // bnez	a4, .LBB0_30
LBB0_26:
	WORD $0x01e4f493  // andi	s1, s1, 30
	BEQZ X9, LBB0_28  // beqz	s1, .LBB0_28
	WORD $0x00557533  // and	a0, a0, t0
	WORD $0x00200693  // li	a3, 2
	BEQ X10, X29, LBB0_30  // beq	a0, t4, .LBB0_30
LBB0_28:
	WORD $0x00063503  // ld	a0, 0(a2)
	WORD $0x00c55713  // srli	a4, a0, 12
	WORD $0x407786b3  // sub	a3, a5, t2
	BNEZ X14, LBB0_33  // bnez	a4, .LBB0_33
	WORD $0x0006869b  // sext.w	a3, a3
	WORD $0x00150713  // addi	a4, a0, 1
	WORD $0x00351513  // slli	a0, a0, 3
	WORD $0x00e63023  // sd	a4, 0(a2)
	WORD $0x01050533  // add	a0, a0, a6
	WORD $0x00d53023  // sd	a3, 0(a0)
	WORD $0x00100693  // li	a3, 1
LBB0_30:
	WORD $0x00d787b3  // add	a5, a5, a3
	BLTU X15, X19, LBB0_17  // bltu	a5, s3, .LBB0_17
LBB0_31:
	WORD $0x00000513  // li	a0, 0
	WORD $0x40778633  // sub	a2, a5, t2
	WORD $0x00c5b023  // sd	a2, 0(a1)
LBB0_32:
	WORD $0x02813403  // ld	s0, 40(sp)
	WORD $0x02013483  // ld	s1, 32(sp)
	WORD $0x01813903  // ld	s2, 24(sp)
	WORD $0x01013983  // ld	s3, 16(sp)
	WORD $0x00813a03  // ld	s4, 8(sp)
	WORD $0x03010113  // addi	sp, sp, 48
	RET  // ret
LBB0_33:
	WORD $0x00d5b023  // sd	a3, 0(a1)
	JMP LBB0_35  // j	.LBB0_35
LBB0_34:
	WORD $0x0085b023  // sd	s0, 0(a1)
LBB0_35:
	WORD $0xfff00513  // li	a0, -1
	JMP LBB0_32  // j	.LBB0_32
Lfunc_end0:


TEXT ·__validate_utf8(SB), NOSPLIT, $0-32
	NO_LOCAL_POINTERS

_entry___validate_utf8:
	MOV 16(g), X17      // g.stack.hi
	ADD $-112, SP, X16
	BLTU X16, X17, _stack_grow___validate_utf8

___validate_utf8:
	MOV s+0(FP), X10
	MOV p+8(FP), X11
	MOV m+16(FP), X12
	CALL ·__validate_utf8_riscv64_entry__(SB)
	MOV X10, ret+24(FP)
	RET

_stack_grow___validate_utf8:
	MOV X1, X5
	CALL runtime·morestack_noctxt(SB)
	JMP _entry___validate_utf8

// Data section
GLOBL ·p33dbaaab8d4c09fa_MASK_USE_NUMBER(SB), RODATA, $4
DATA ·p33dbaaab8d4c09fa_MASK_USE_NUMBER+0(SB)/8, $0x0000000000000002
