// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

#include "go_asm.h"
#include "funcdata.h"
#include "textflag.h"

TEXT ·__validate_utf8_fast_entry__(SB), NOSPLIT, $0-8
	MOV $·__validate_utf8_fast_riscv64_entry__(SB), A0
	MOV A0, ret+0(FP)
	RET

TEXT ·__validate_utf8_fast_riscv64_entry__(SB), NOSPLIT, $16
	NO_LOCAL_POINTERS
validate_utf8_fast:
	WORD $0xfe010113  // addi	sp, sp, -32
	WORD $0x00813c23  // sd	s0, 24(sp)
	WORD $0x00913823  // sd	s1, 16(sp)
	WORD $0x00053283  // ld	t0, 0(a0)
	WORD $0x00853403  // ld	s0, 8(a0)
	WORD $0x00540433  // add	s0, s0, t0
	WORD $0xffd40593  // addi	a1, s0, -3
	WORD $0x00028613  // mv	a2, t0
	BGEU X5, X11, LBB0_14  // bgeu	t0, a1, .LBB0_14
	WORD $0x00c0c6b7  // lui	a3, 3084
	WORD $0x0000c7b7  // lui	a5, 12
	WORD $0x00003837  // lui	a6, 3
	WORD $0x00002337  // lui	t1, 2
	WORD $0x00808737  // lui	a4, 2056
	WORD $0x000084b7  // lui	s1, 8
	WORD $0xc0c0c537  // lui	a0, 789516
	WORD $0x80808637  // lui	a2, 526344
	WORD $0x0f06869b  // addiw	a3, a3, 240
	WORD $0x0e07839b  // addiw	t2, a5, 224
	WORD $0x0038081b  // addiw	a6, a6, 3
	WORD $0x00f3089b  // addiw	a7, t1, 15
	WORD $0x0e07079b  // addiw	a5, a4, 224
	WORD $0x00d3031b  // addiw	t1, t1, 13
	WORD $0x0c048f9b  // addiw	t6, s1, 192
	WORD $0x0f850e13  // addi	t3, a0, 248
	WORD $0x00480e93  // addi	t4, a6, 4
	WORD $0x0f060f1b  // addiw	t5, a2, 240
	WORD $0x00028613  // mv	a2, t0
LBB0_2:
	WORD $0x00060703  // lb	a4, 0(a2)
	WORD $0x00100513  // li	a0, 1
	BLTZ X14, LBB0_4  // bltz	a4, .LBB0_4
LBB0_3:
	WORD $0x00a60633  // add	a2, a2, a0
	BLTU X12, X11, LBB0_2  // bltu	a2, a1, .LBB0_2
	JMP LBB0_14  // j	.LBB0_14
LBB0_4:
	WORD $0x00066703  // lwu	a4, 0(a2)
	WORD $0x00d77533  // and	a0, a4, a3
	BNE X10, X15, LBB0_7  // bne	a0, a5, .LBB0_7
	WORD $0x011774b3  // and	s1, a4, a7
	BEQ X9, X6, LBB0_7  // beq	s1, t1, .LBB0_7
	WORD $0x00300513  // li	a0, 3
	BNEZ X9, LBB0_3  // bnez	s1, .LBB0_3
LBB0_7:
	WORD $0x00777533  // and	a0, a4, t2
	BNE X10, X31, LBB0_9  // bne	a0, t6, .LBB0_9
	WORD $0x01e77493  // andi	s1, a4, 30
	WORD $0x00200513  // li	a0, 2
	BNEZ X9, LBB0_3  // bnez	s1, .LBB0_3
LBB0_9:
	WORD $0x01c77533  // and	a0, a4, t3
	WORD $0x0005051b  // sext.w	a0, a0
	BNE X10, X30, LBB0_13  // bne	a0, t5, .LBB0_13
	WORD $0x01d77533  // and	a0, a4, t4
	BEQZ X10, LBB0_13  // beqz	a0, .LBB0_13
	WORD $0x00477493  // andi	s1, a4, 4
	WORD $0x00400513  // li	a0, 4
	BEQZ X9, LBB0_3  // beqz	s1, .LBB0_3
	WORD $0x01077733  // and	a4, a4, a6
	BEQZ X14, LBB0_3  // beqz	a4, .LBB0_3
LBB0_13:
	WORD $0xfff64513  // not	a0, a2
	WORD $0x00550533  // add	a0, a0, t0
	JMP LBB0_30  // j	.LBB0_30
LBB0_14:
	BGEU X12, X8, LBB0_29  // bgeu	a2, s0, .LBB0_29
	WORD $0x00c0c537  // lui	a0, 3084
	WORD $0x0000c5b7  // lui	a1, 12
	WORD $0x00002337  // lui	t1, 2
	WORD $0x00200813  // li	a6, 2
	WORD $0x008086b7  // lui	a3, 2056
	WORD $0x00008737  // lui	a4, 8
	WORD $0x0f050e9b  // addiw	t4, a0, 240
	WORD $0x0e05839b  // addiw	t2, a1, 224
	WORD $0x00f3089b  // addiw	a7, t1, 15
	WORD $0x0e068f1b  // addiw	t5, a3, 224
	WORD $0x00d3031b  // addiw	t1, t1, 13
	WORD $0x0c070e1b  // addiw	t3, a4, 192
LBB0_16:
	WORD $0x00060503  // lb	a0, 0(a2)
	BLTZ X10, LBB0_18  // bltz	a0, .LBB0_18
	WORD $0x00160613  // addi	a2, a2, 1
	JMP LBB0_28  // j	.LBB0_28
LBB0_18:
	WORD $0x00010623  // sb	zero, 12(sp)
	WORD $0x40c40533  // sub	a0, s0, a2
	WORD $0x00010523  // sb	zero, 10(sp)
	BLTU X10, X16, LBB0_20  // bltu	a0, a6, .LBB0_20
	WORD $0x00064783  // lbu	a5, 0(a2)
	WORD $0x00164583  // lbu	a1, 1(a2)
	WORD $0x00260693  // addi	a3, a2, 2
	WORD $0xffe50513  // addi	a0, a0, -2
	WORD $0x00f10623  // sb	a5, 12(sp)
	WORD $0x00a10713  // addi	a4, sp, 10
	BNEZ X10, LBB0_21  // bnez	a0, .LBB0_21
	JMP LBB0_22  // j	.LBB0_22
LBB0_20:
	WORD $0x00000793  // li	a5, 0
	WORD $0x00000593  // li	a1, 0
	WORD $0x00c10713  // addi	a4, sp, 12
	WORD $0x00060693  // mv	a3, a2
	BEQZ X10, LBB0_22  // beqz	a0, .LBB0_22
LBB0_21:
	WORD $0x0006c503  // lbu	a0, 0(a3)
	WORD $0x00a70023  // sb	a0, 0(a4)
	WORD $0x00c14783  // lbu	a5, 12(sp)
	WORD $0x00a14503  // lbu	a0, 10(sp)
LBB0_22:
	WORD $0x01051513  // slli	a0, a0, 16
	WORD $0x00859593  // slli	a1, a1, 8
	WORD $0x00b56533  // or	a0, a0, a1
	WORD $0x00f56533  // or	a0, a0, a5
	WORD $0x01d575b3  // and	a1, a0, t4
	BNE X11, X30, LBB0_25  // bne	a1, t5, .LBB0_25
	WORD $0x011576b3  // and	a3, a0, a7
	BEQ X13, X6, LBB0_25  // beq	a3, t1, .LBB0_25
	WORD $0x00300593  // li	a1, 3
	BNEZ X13, LBB0_27  // bnez	a3, .LBB0_27
LBB0_25:
	WORD $0x01e7f793  // andi	a5, a5, 30
	BEQZ X15, LBB0_13  // beqz	a5, .LBB0_13
	WORD $0x00757533  // and	a0, a0, t2
	WORD $0x00200593  // li	a1, 2
	BNE X10, X28, LBB0_13  // bne	a0, t3, .LBB0_13
LBB0_27:
	WORD $0x00b60633  // add	a2, a2, a1
LBB0_28:
	BLTU X12, X8, LBB0_16  // bltu	a2, s0, .LBB0_16
LBB0_29:
	WORD $0x00000513  // li	a0, 0
LBB0_30:
	WORD $0x01813403  // ld	s0, 24(sp)
	WORD $0x01013483  // ld	s1, 16(sp)
	WORD $0x02010113  // addi	sp, sp, 32
	RET  // ret
Lfunc_end0:


TEXT ·__validate_utf8_fast(SB), NOSPLIT, $0-16
	NO_LOCAL_POINTERS

_entry___validate_utf8_fast:
	MOV 16(g), X17      // g.stack.hi
	ADD $-96, SP, X16
	BLTU X16, X17, _stack_grow___validate_utf8_fast

___validate_utf8_fast:
	MOV s+0(FP), X10
	CALL ·__validate_utf8_fast_riscv64_entry__(SB)
	MOV X10, ret+8(FP)
	RET

_stack_grow___validate_utf8_fast:
	MOV X1, X5
	CALL runtime·morestack_noctxt(SB)
	JMP _entry___validate_utf8_fast

// Data section
GLOBL ·p71ece2afb26072ac_MASK_USE_NUMBER(SB), RODATA, $4
DATA ·p71ece2afb26072ac_MASK_USE_NUMBER+0(SB)/8, $0x0000000000000002
