// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package rvv

//go:nosplit
//go:noescape
//goland:noinspection ALL
func __validate_one_entry__() uintptr

var (
    _subr__validate_one uintptr = __validate_one_entry__() + 0
)

const (
    _stack__validate_one = 432
)

var (
    _ = _subr__validate_one
)

const (
    _ = _stack__validate_one
)
