// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package rvv

//go:nosplit
//go:noescape
//goland:noinspection ALL
func __validate_utf8_entry__() uintptr

var (
    _subr__validate_utf8 uintptr = __validate_utf8_entry__() + 0
)

const (
    _stack__validate_utf8 = 48
)

var (
    _ = _subr__validate_utf8
)

const (
    _ = _stack__validate_utf8
)
