// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package rvv

//go:nosplit
//go:noescape
//goland:noinspection ALL
func __value_entry__() uintptr

var (
    _subr__value uintptr = __value_entry__() + 0
)

const (
    _stack__value = 128
)

var (
    _ = _subr__value
)

const (
    _ = _stack__value
)
