// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

#include "go_asm.h"
#include "funcdata.h"
#include "textflag.h"

TEXT ·__vsigned_entry__(SB), NOSPLIT, $0-8
	MOV $·__vsigned_riscv64_entry__(SB), A0
	MOV A0, ret+0(FP)
	RET

TEXT ·__vsigned_riscv64_entry__(SB), NOSPLIT, $0
	NO_LOCAL_POINTERS
vsigned:
	WORD $0x0005be03  // ld	t3, 0(a1)
	WORD $0x00853383  // ld	t2, 8(a0)
	WORD $0x00900713  // li	a4, 9
	WORD $0x00e63023  // sd	a4, 0(a2)
	WORD $0x00063823  // sd	zero, 16(a2)
	WORD $0x0005b703  // ld	a4, 0(a1)
	WORD $0x00053303  // ld	t1, 0(a0)
	WORD $0x00063423  // sd	zero, 8(a2)
	WORD $0x00e63c23  // sd	a4, 24(a2)
	BGEU X28, X7, LBB0_6  // bgeu	t3, t2, .LBB0_6
	WORD $0x01c30533  // add	a0, t1, t3
	WORD $0x00054783  // lbu	a5, 0(a0)
	WORD $0x02d00513  // li	a0, 45
	WORD $0x00100813  // li	a6, 1
	BNE X15, X10, LBB0_4  // bne	a5, a0, .LBB0_4
	WORD $0x001e0e13  // addi	t3, t3, 1
	BGEU X28, X7, LBB0_6  // bgeu	t3, t2, .LBB0_6
	WORD $0x01c30533  // add	a0, t1, t3
	WORD $0x00054783  // lbu	a5, 0(a0)
	WORD $0xfff00813  // li	a6, -1
LBB0_4:
	WORD $0xfc678513  // addi	a0, a5, -58
	WORD $0xff500713  // li	a4, -11
	BLTU X14, X10, LBB0_8  // bltu	a4, a0, .LBB0_8
	WORD $0x01c5b023  // sd	t3, 0(a1)
	WORD $0xffe00513  // li	a0, -2
	JMP LBB0_7  // j	.LBB0_7
LBB0_6:
	WORD $0x0075b023  // sd	t2, 0(a1)
	WORD $0xfff00513  // li	a0, -1
LBB0_7:
	WORD $0x00a63023  // sd	a0, 0(a2)
	RET  // ret
LBB0_8:
	WORD $0x03000513  // li	a0, 48
	BNE X15, X10, LBB0_11  // bne	a5, a0, .LBB0_11
	WORD $0x01c30533  // add	a0, t1, t3
	WORD $0x00154503  // lbu	a0, 1(a0)
	WORD $0xfd250513  // addi	a0, a0, -46
	WORD $0x03700713  // li	a4, 55
	BLTU X14, X10, LBB0_24  // bltu	a4, a0, .LBB0_24
	WORD $0x00800737  // lui	a4, 2048
	WORD $0x0017071b  // addiw	a4, a4, 1
	WORD $0x03771793  // slli	a5, a4, 55
	WORD $0x00f70733  // add	a4, a4, a5
	WORD $0x00a75533  // srl	a0, a4, a0
	WORD $0x00157513  // andi	a0, a0, 1
	BEQZ X10, LBB0_24  // beqz	a0, .LBB0_24
LBB0_11:
	WORD $0x00000713  // li	a4, 0
	WORD $0x00900893  // li	a7, 9
	WORD $0x00a00293  // li	t0, 10
LBB0_12:
	BEQ X7, X28, LBB0_23  // beq	t2, t3, .LBB0_23
	WORD $0x01c307b3  // add	a5, t1, t3
	WORD $0x0007c503  // lbu	a0, 0(a5)
	WORD $0xfd050693  // addi	a3, a0, -48
	BLTU X17, X13, LBB0_17  // bltu	a7, a3, .LBB0_17
	WORD $0x025716b3  // mulh	a3, a4, t0
	WORD $0x025707b3  // mul	a5, a4, t0
	WORD $0x43f7d713  // srai	a4, a5, 63
	BNE X13, X14, LBB0_16  // bne	a3, a4, .LBB0_16
	WORD $0x00f57513  // andi	a0, a0, 15
	WORD $0x02a80533  // mul	a0, a6, a0
	WORD $0x00a78733  // add	a4, a5, a0
	WORD $0x00f726b3  // slt	a3, a4, a5
	WORD $0x00052513  // slti	a0, a0, 0
	WORD $0x001e0e13  // addi	t3, t3, 1
	BEQ X10, X13, LBB0_12  // beq	a0, a3, .LBB0_12
LBB0_16:
	WORD $0xfffe0e13  // addi	t3, t3, -1
	WORD $0x01c5b023  // sd	t3, 0(a1)
	WORD $0xffb00513  // li	a0, -5
	JMP LBB0_7  // j	.LBB0_7
LBB0_17:
	BGEU X28, X7, LBB0_22  // bgeu	t3, t2, .LBB0_22
	WORD $0x0007c503  // lbu	a0, 0(a5)
	WORD $0x02e00693  // li	a3, 46
	BEQ X10, X13, LBB0_21  // beq	a0, a3, .LBB0_21
	WORD $0x04500693  // li	a3, 69
	BEQ X10, X13, LBB0_21  // beq	a0, a3, .LBB0_21
	WORD $0x06500693  // li	a3, 101
	BNE X10, X13, LBB0_22  // bne	a0, a3, .LBB0_22
LBB0_21:
	WORD $0x01c5b023  // sd	t3, 0(a1)
	WORD $0xffa00513  // li	a0, -6
	JMP LBB0_7  // j	.LBB0_7
LBB0_22:
	WORD $0x000e0393  // mv	t2, t3
LBB0_23:
	WORD $0x0075b023  // sd	t2, 0(a1)
	WORD $0x00e63823  // sd	a4, 16(a2)
	RET  // ret
LBB0_24:
	WORD $0x001e0693  // addi	a3, t3, 1
	WORD $0x00d5b023  // sd	a3, 0(a1)
	RET  // ret
Lfunc_end0:


TEXT ·__vsigned(SB), NOSPLIT, $0-24
	NO_LOCAL_POINTERS

_entry___vsigned:
	MOV 16(g), X31      // g.stack.hi
	ADD $-64, SP, X30
	BLTU X30, X31, _stack_grow___vsigned

___vsigned:
	MOV s+0(FP), X10
	MOV p+8(FP), X11
	MOV v+16(FP), X12
	CALL ·__vsigned_riscv64_entry__(SB)
	RET

_stack_grow___vsigned:
	MOV X1, X3      // Save return address (RA)
	CALL runtime·morestack_noctxt(SB)
	JMP _entry___vsigned

// Data section
GLOBL ·p59d23546592e4117_MASK_USE_NUMBER(SB), RODATA, $4
DATA ·p59d23546592e4117_MASK_USE_NUMBER+0(SB)/8, $0x0000000000000002
