// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package rvv

//go:nosplit
//go:noescape
//goland:noinspection ALL
func __vstring_entry__() uintptr

var (
    _subr__vstring uintptr = __vstring_entry__() + 0
)

const (
    _stack__vstring = 128
)

var (
    _ = _subr__vstring
)

const (
    _ = _stack__vstring
)
