// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

#include "go_asm.h"
#include "funcdata.h"
#include "textflag.h"

TEXT ·__vstring_entry__(SB), $0-8
	MOV $·__vstring_riscv64_entry__(SB), A0
	MOV A0, ret+0(FP)
	RET

TEXT ·__vstring_riscv64_entry__(SB), $112
	NO_LOCAL_POINTERS
vstring:
	WORD $0xf8010113  // addi	sp, sp, -128
	WORD $0x06113c23  // sd	ra, 120(sp)
	WORD $0x06813823  // sd	s0, 112(sp)
	WORD $0x06913423  // sd	s1, 104(sp)
	WORD $0x07213023  // sd	s2, 96(sp)
	WORD $0x05313c23  // sd	s3, 88(sp)
	WORD $0x05413823  // sd	s4, 80(sp)
	WORD $0x05513423  // sd	s5, 72(sp)
	WORD $0x05613023  // sd	s6, 64(sp)
	WORD $0x03713c23  // sd	s7, 56(sp)
	WORD $0x03813823  // sd	s8, 48(sp)
	WORD $0x03913423  // sd	s9, 40(sp)
	WORD $0x03a13023  // sd	s10, 32(sp)
	WORD $0x01b13c23  // sd	s11, 24(sp)
	WORD $0x0005b383  // ld	t2, 0(a1)
	WORD $0x00853883  // ld	a7, 8(a0)
	WORD $0x0206f693  // andi	a3, a3, 32
	BNEZ X13, LBB0_33  // bnez	a3, .LBB0_33
	BEQ X17, X7, LBB0_151  // beq	a7, t2, .LBB0_151
	WORD $0x00000693  // li	a3, 0
	WORD $0x00053f03  // ld	t5, 0(a0)
	WORD $0x40788a33  // sub	s4, a7, t2
	WORD $0x02200513  // li	a0, 34
	WORD $0x0c007757  // vsetvli	a4, zero, e8, m1, ta, ma
	WORD $0x42056457  // vmv.s.x	v8, a0
	WORD $0x01000513  // li	a0, 16
LBB0_3:
	WORD $0x00168713  // addi	a4, a3, 1
	WORD $0x08777057  // vsetvli	zero, a4, e8, mf2, tu, ma
	WORD $0x3a86c4d7  // vslideup.vx	v9, v8, a3
	WORD $0x00070693  // mv	a3, a4
	BNE X14, X10, LBB0_3  // bne	a4, a0, .LBB0_3
	WORD $0x00000513  // li	a0, 0
	WORD $0x05c00693  // li	a3, 92
	WORD $0x0c707757  // vsetvli	a4, zero, e8, mf2, ta, ma
	WORD $0x4206e557  // vmv.s.x	v10, a3
	WORD $0x01000693  // li	a3, 16
LBB0_5:
	WORD $0x00150713  // addi	a4, a0, 1
	WORD $0x08777057  // vsetvli	zero, a4, e8, mf2, tu, ma
	WORD $0x3aa54457  // vslideup.vx	v8, v10, a0
	WORD $0x00070513  // mv	a0, a4
	BNE X14, X13, LBB0_5  // bne	a4, a3, .LBB0_5
	WORD $0x04000513  // li	a0, 64
	WORD $0x007f0ab3  // add	s5, t5, t2
	WORD $0x00000913  // li	s2, 0
	BLTU X20, X10, LBB0_91  // bltu	s4, a0, .LBB0_91
	WORD $0xfff00b13  // li	s6, -1
	MOV $·p5f6a1f9280687903_LCPI0_2(SB), X10  // lui	a0, %hi(.LCPI0_2)
	MOV $·p5f6a1f9280687903_LCPI0_3(SB), X13  // lui	a3, %hi(.LCPI0_3)
	MOV $·p5f6a1f9280687903_LCPI0_0(SB), X14  // lui	a4, %hi(.LCPI0_0)
	MOV (X10), X6  // ld	t1, %lo(.LCPI0_2)(a0)
	MOV (X13), X29  // ld	t4, %lo(.LCPI0_3)(a3)
	MOV (X14), X28  // ld	t3, %lo(.LCPI0_0)(a4)
	WORD $0x03f00f93  // li	t6, 63
	MOV $·p5f6a1f9280687903_LCPI0_1(SB), X5  // lui	t0, %hi(.LCPI0_1)
	// addi	t0, t0, %lo(.LCPI0_1) (skipped, covered by MOV address load)
	WORD $0xfff00813  // li	a6, -1
LBB0_8:
	WORD $0x00000b93  // li	s7, 0
	WORD $0x010a8993  // addi	s3, s5, 16
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x020a8687  // vle8.v	v13, (s5)
	WORD $0x020a8693  // addi	a3, s5, 32
	WORD $0x030a8713  // addi	a4, s5, 48
	WORD $0x00f00513  // li	a0, 15
	WORD $0x02098607  // vle8.v	v12, (s3)
	WORD $0x02068587  // vle8.v	v11, (a3)
	WORD $0x02070507  // vle8.v	v10, (a4)
	WORD $0x62d48757  // vmseq.vv	v14, v13, v9
	WORD $0x0c807057  // vsetvli	zero, zero, e16, m1, ta, ma
	WORD $0x42e026d7  // vmv.x.s	a3, v14
	WORD $0x00f00713  // li	a4, 15
LBB0_9:
	WORD $0x00e6d7b3  // srl	a5, a3, a4
	WORD $0xfff70713  // addi	a4, a4, -1
	WORD $0x0017f793  // andi	a5, a5, 1
	WORD $0x00a797bb  // sllw	a5, a5, a0
	WORD $0x0177ebb3  // or	s7, a5, s7
	WORD $0xfff50513  // addi	a0, a0, -1
	BNE X14, X22, LBB0_9  // bne	a4, s6, .LBB0_9
	WORD $0x00000c13  // li	s8, 0
	WORD $0x00f00513  // li	a0, 15
	WORD $0x0c707057  // vsetvli	zero, zero, e8, mf2, ta, ma
	WORD $0x62c48757  // vmseq.vv	v14, v12, v9
	WORD $0x0c807057  // vsetvli	zero, zero, e16, m1, ta, ma
	WORD $0x42e026d7  // vmv.x.s	a3, v14
	WORD $0x00f00713  // li	a4, 15
LBB0_11:
	WORD $0x00e6d7b3  // srl	a5, a3, a4
	WORD $0xfff70713  // addi	a4, a4, -1
	WORD $0x0017f793  // andi	a5, a5, 1
	WORD $0x00a797bb  // sllw	a5, a5, a0
	WORD $0x0187ec33  // or	s8, a5, s8
	WORD $0xfff50513  // addi	a0, a0, -1
	BNE X14, X22, LBB0_11  // bne	a4, s6, .LBB0_11
	WORD $0x00000c93  // li	s9, 0
	WORD $0x00f00693  // li	a3, 15
	WORD $0x0c707057  // vsetvli	zero, zero, e8, mf2, ta, ma
	WORD $0x62b48757  // vmseq.vv	v14, v11, v9
	WORD $0x00f00513  // li	a0, 15
LBB0_13:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x42e02757  // vmv.x.s	a4, v14
	WORD $0x00a75733  // srl	a4, a4, a0
	WORD $0xfff50513  // addi	a0, a0, -1
	WORD $0x00177713  // andi	a4, a4, 1
	WORD $0x00d7173b  // sllw	a4, a4, a3
	WORD $0x01976cb3  // or	s9, a4, s9
	WORD $0xfff68693  // addi	a3, a3, -1
	BNE X10, X22, LBB0_13  // bne	a0, s6, .LBB0_13
	WORD $0x00000d13  // li	s10, 0
	WORD $0x00f00513  // li	a0, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62a48757  // vmseq.vv	v14, v10, v9
	WORD $0x00f00693  // li	a3, 15
LBB0_15:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x42e02757  // vmv.x.s	a4, v14
	WORD $0x00d75733  // srl	a4, a4, a3
	WORD $0xfff68693  // addi	a3, a3, -1
	WORD $0x00177713  // andi	a4, a4, 1
	WORD $0x00a7173b  // sllw	a4, a4, a0
	WORD $0x01a76d33  // or	s10, a4, s10
	WORD $0xfff50513  // addi	a0, a0, -1
	BNE X13, X22, LBB0_15  // bne	a3, s6, .LBB0_15
	WORD $0x00000d93  // li	s11, 0
	WORD $0x00f00513  // li	a0, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62d406d7  // vmseq.vv	v13, v13, v8
	WORD $0x00f00693  // li	a3, 15
LBB0_17:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x42d02757  // vmv.x.s	a4, v13
	WORD $0x00d75733  // srl	a4, a4, a3
	WORD $0xfff68693  // addi	a3, a3, -1
	WORD $0x00177713  // andi	a4, a4, 1
	WORD $0x00a7173b  // sllw	a4, a4, a0
	WORD $0x01b76db3  // or	s11, a4, s11
	WORD $0xfff50513  // addi	a0, a0, -1
	BNE X13, X22, LBB0_17  // bne	a3, s6, .LBB0_17
	WORD $0x00000493  // li	s1, 0
	WORD $0x00f00513  // li	a0, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62c40657  // vmseq.vv	v12, v12, v8
	WORD $0x00f00693  // li	a3, 15
LBB0_19:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x42c02757  // vmv.x.s	a4, v12
	WORD $0x00d75733  // srl	a4, a4, a3
	WORD $0xfff68693  // addi	a3, a3, -1
	WORD $0x00177713  // andi	a4, a4, 1
	WORD $0x00a7173b  // sllw	a4, a4, a0
	WORD $0x00e4e4b3  // or	s1, s1, a4
	WORD $0xfff50513  // addi	a0, a0, -1
	BNE X13, X22, LBB0_19  // bne	a3, s6, .LBB0_19
	WORD $0x00000413  // li	s0, 0
	WORD $0x00f00713  // li	a4, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62b405d7  // vmseq.vv	v11, v11, v8
	WORD $0x00f00513  // li	a0, 15
LBB0_21:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x42b026d7  // vmv.x.s	a3, v11
	WORD $0x00a6d6b3  // srl	a3, a3, a0
	WORD $0xfff50513  // addi	a0, a0, -1
	WORD $0x0016f693  // andi	a3, a3, 1
	WORD $0x00e696bb  // sllw	a3, a3, a4
	WORD $0x00d46433  // or	s0, s0, a3
	WORD $0xfff70713  // addi	a4, a4, -1
	BNE X10, X22, LBB0_21  // bne	a0, s6, .LBB0_21
	WORD $0x00000713  // li	a4, 0
	WORD $0x00f00513  // li	a0, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62a40557  // vmseq.vv	v10, v10, v8
	WORD $0x00f00693  // li	a3, 15
LBB0_23:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x42a027d7  // vmv.x.s	a5, v10
	WORD $0x00d7d7b3  // srl	a5, a5, a3
	WORD $0xfff68693  // addi	a3, a3, -1
	WORD $0x0017f793  // andi	a5, a5, 1
	WORD $0x00a797bb  // sllw	a5, a5, a0
	WORD $0x00f76733  // or	a4, a4, a5
	WORD $0xfff50513  // addi	a0, a0, -1
	BNE X13, X22, LBB0_23  // bne	a3, s6, .LBB0_23
	WORD $0x030d1d13  // slli	s10, s10, 48
	WORD $0x020c9c93  // slli	s9, s9, 32
	WORD $0x030c1c13  // slli	s8, s8, 48
	WORD $0x03071713  // slli	a4, a4, 48
	WORD $0x02041413  // slli	s0, s0, 32
	WORD $0x03049493  // slli	s1, s1, 48
	WORD $0x01ac8cb3  // add	s9, s9, s10
	WORD $0x020c5513  // srli	a0, s8, 32
	WORD $0x00870733  // add	a4, a4, s0
	WORD $0x0204d493  // srli	s1, s1, 32
	WORD $0x00ace533  // or	a0, s9, a0
	WORD $0x00976733  // or	a4, a4, s1
	WORD $0x01b707b3  // add	a5, a4, s11
	WORD $0x00ab8bb3  // add	s7, s7, a0
	BNEZ X15, LBB0_28  // bnez	a5, .LBB0_28
	BNEZ X18, LBB0_30  // bnez	s2, .LBB0_30
	BNEZ X23, LBB0_31  // bnez	s7, .LBB0_31
LBB0_27:
	WORD $0xfc0a0a13  // addi	s4, s4, -64
	WORD $0x03098a93  // addi	s5, s3, 48
	BLTU X31, X20, LBB0_8  // bltu	t6, s4, .LBB0_8
	JMP LBB0_92  // j	.LBB0_92
LBB0_28:
	BNE X16, X22, LBB0_30  // bne	a6, s6, .LBB0_30
	WORD $0x40f00533  // neg	a0, a5
	WORD $0x00f57533  // and	a0, a0, a5
	WORD $0x03c50533  // mul	a0, a0, t3
	WORD $0x03a55513  // srli	a0, a0, 58
	WORD $0x00550533  // add	a0, a0, t0
	WORD $0x00054803  // lbu	a6, 0(a0)
	WORD $0x41ea8533  // sub	a0, s5, t5
	WORD $0x00a80833  // add	a6, a6, a0
LBB0_30:
	WORD $0xfff94513  // not	a0, s2
	WORD $0x0067f6b3  // and	a3, a5, t1
	WORD $0x00f57533  // and	a0, a0, a5
	WORD $0x00151713  // slli	a4, a0, 1
	WORD $0x01276733  // or	a4, a4, s2
	WORD $0xfff74793  // not	a5, a4
	WORD $0x00f6f6b3  // and	a3, a3, a5
	WORD $0x00d50533  // add	a0, a0, a3
	WORD $0x00d53933  // sltu	s2, a0, a3
	WORD $0x00151513  // slli	a0, a0, 1
	WORD $0x01d54533  // xor	a0, a0, t4
	WORD $0x00e57533  // and	a0, a0, a4
	WORD $0xfff54513  // not	a0, a0
	WORD $0x00abfbb3  // and	s7, s7, a0
	BEQZ X23, LBB0_27  // beqz	s7, .LBB0_27
LBB0_31:
	MOV $·p5f6a1f9280687903_LCPI0_0(SB), X10  // lui	a0, %hi(.LCPI0_0)
	MOV (X10), X10  // ld	a0, %lo(.LCPI0_0)(a0)
	WORD $0x417006b3  // neg	a3, s7
	WORD $0x00dbf6b3  // and	a3, s7, a3
	WORD $0x02a68533  // mul	a0, a3, a0
	WORD $0x03a55513  // srli	a0, a0, 58
	WORD $0x00550533  // add	a0, a0, t0
LBB0_32:
	WORD $0x00054503  // lbu	a0, 0(a0)
	WORD $0x41ea86b3  // sub	a3, s5, t5
	JMP LBB0_133  // j	.LBB0_133
LBB0_33:
	BEQ X17, X7, LBB0_151  // beq	a7, t2, .LBB0_151
	WORD $0x00000693  // li	a3, 0
	WORD $0x00053303  // ld	t1, 0(a0)
	WORD $0x40788a33  // sub	s4, a7, t2
	WORD $0x02200513  // li	a0, 34
	WORD $0x0c007757  // vsetvli	a4, zero, e8, m1, ta, ma
	WORD $0x42056457  // vmv.s.x	v8, a0
	WORD $0x01000513  // li	a0, 16
LBB0_35:
	WORD $0x00168713  // addi	a4, a3, 1
	WORD $0x08777057  // vsetvli	zero, a4, e8, mf2, tu, ma
	WORD $0x3a86c4d7  // vslideup.vx	v9, v8, a3
	WORD $0x00070693  // mv	a3, a4
	BNE X14, X10, LBB0_35  // bne	a4, a0, .LBB0_35
	WORD $0x00000513  // li	a0, 0
	WORD $0x05c00693  // li	a3, 92
	WORD $0x0c707757  // vsetvli	a4, zero, e8, mf2, ta, ma
	WORD $0x4206e557  // vmv.s.x	v10, a3
	WORD $0x01000693  // li	a3, 16
LBB0_37:
	WORD $0x00150713  // addi	a4, a0, 1
	WORD $0x08777057  // vsetvli	zero, a4, e8, mf2, tu, ma
	WORD $0x3aa54457  // vslideup.vx	v8, v10, a0
	WORD $0x00070513  // mv	a0, a4
	BNE X14, X13, LBB0_37  // bne	a4, a3, .LBB0_37
	WORD $0x00730ab3  // add	s5, t1, t2
	WORD $0x00000e13  // li	t3, 0
	WORD $0x04000513  // li	a0, 64
	BLTU X20, X10, LBB0_105  // bltu	s4, a0, .LBB0_105
	WORD $0xfff00b93  // li	s7, -1
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x5e0fb557  // vmv.v.i	v10, -1
	WORD $0x01000b13  // li	s6, 16
	WORD $0x01f00513  // li	a0, 31
	MOV $·p5f6a1f9280687903_LCPI0_2(SB), X13  // lui	a3, %hi(.LCPI0_2)
	MOV $·p5f6a1f9280687903_LCPI0_3(SB), X14  // lui	a4, %hi(.LCPI0_3)
	MOV $·p5f6a1f9280687903_LCPI0_0(SB), X15  // lui	a5, %hi(.LCPI0_0)
	MOV (X13), X13  // ld	a3, %lo(.LCPI0_2)(a3)
	WORD $0x00d13823  // sd	a3, 16(sp)
	MOV (X14), X13  // ld	a3, %lo(.LCPI0_3)(a4)
	WORD $0x00d13423  // sd	a3, 8(sp)
	MOV (X15), X13  // ld	a3, %lo(.LCPI0_0)(a5)
	WORD $0x00d13023  // sd	a3, 0(sp)
	WORD $0x420565d7  // vmv.s.x	v11, a0
	WORD $0x03f00913  // li	s2, 63
	WORD $0xfff00813  // li	a6, -1
LBB0_40:
	WORD $0x00000c13  // li	s8, 0
	WORD $0x010a8993  // addi	s3, s5, 16
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x020a8787  // vle8.v	v15, (s5)
	WORD $0x020a8693  // addi	a3, s5, 32
	WORD $0x030a8713  // addi	a4, s5, 48
	WORD $0x00f00513  // li	a0, 15
	WORD $0x02098707  // vle8.v	v14, (s3)
	WORD $0x02068687  // vle8.v	v13, (a3)
	WORD $0x02070607  // vle8.v	v12, (a4)
	WORD $0x62f48857  // vmseq.vv	v16, v15, v9
	WORD $0x0c807057  // vsetvli	zero, zero, e16, m1, ta, ma
	WORD $0x430026d7  // vmv.x.s	a3, v16
	WORD $0x00f00713  // li	a4, 15
LBB0_41:
	WORD $0x00e6d7b3  // srl	a5, a3, a4
	WORD $0xfff70713  // addi	a4, a4, -1
	WORD $0x0017f793  // andi	a5, a5, 1
	WORD $0x00a797bb  // sllw	a5, a5, a0
	WORD $0x0187ec33  // or	s8, a5, s8
	WORD $0xfff50513  // addi	a0, a0, -1
	BNE X14, X23, LBB0_41  // bne	a4, s7, .LBB0_41
	WORD $0x00000c93  // li	s9, 0
	WORD $0x00f00513  // li	a0, 15
	WORD $0x0c707057  // vsetvli	zero, zero, e8, mf2, ta, ma
	WORD $0x62e48857  // vmseq.vv	v16, v14, v9
	WORD $0x0c807057  // vsetvli	zero, zero, e16, m1, ta, ma
	WORD $0x430026d7  // vmv.x.s	a3, v16
	WORD $0x00f00713  // li	a4, 15
LBB0_43:
	WORD $0x00e6d7b3  // srl	a5, a3, a4
	WORD $0xfff70713  // addi	a4, a4, -1
	WORD $0x0017f793  // andi	a5, a5, 1
	WORD $0x00a797bb  // sllw	a5, a5, a0
	WORD $0x0197ecb3  // or	s9, a5, s9
	WORD $0xfff50513  // addi	a0, a0, -1
	BNE X14, X23, LBB0_43  // bne	a4, s7, .LBB0_43
	WORD $0x00000d13  // li	s10, 0
	WORD $0x00f00513  // li	a0, 15
	WORD $0x0c707057  // vsetvli	zero, zero, e8, mf2, ta, ma
	WORD $0x62d48857  // vmseq.vv	v16, v13, v9
	WORD $0x00f00693  // li	a3, 15
LBB0_45:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x43002757  // vmv.x.s	a4, v16
	WORD $0x00d75733  // srl	a4, a4, a3
	WORD $0xfff68693  // addi	a3, a3, -1
	WORD $0x00177713  // andi	a4, a4, 1
	WORD $0x00a7173b  // sllw	a4, a4, a0
	WORD $0x01a76d33  // or	s10, a4, s10
	WORD $0xfff50513  // addi	a0, a0, -1
	BNE X13, X23, LBB0_45  // bne	a3, s7, .LBB0_45
	WORD $0x00000d93  // li	s11, 0
	WORD $0x00f00513  // li	a0, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62c48857  // vmseq.vv	v16, v12, v9
	WORD $0x00f00693  // li	a3, 15
LBB0_47:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x43002757  // vmv.x.s	a4, v16
	WORD $0x00d75733  // srl	a4, a4, a3
	WORD $0xfff68693  // addi	a3, a3, -1
	WORD $0x00177713  // andi	a4, a4, 1
	WORD $0x00a7173b  // sllw	a4, a4, a0
	WORD $0x01b76db3  // or	s11, a4, s11
	WORD $0xfff50513  // addi	a0, a0, -1
	BNE X13, X23, LBB0_47  // bne	a3, s7, .LBB0_47
	WORD $0x00000093  // li	ra, 0
	WORD $0x00f00513  // li	a0, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62f40857  // vmseq.vv	v16, v15, v8
	WORD $0x00f00693  // li	a3, 15
LBB0_49:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x43002757  // vmv.x.s	a4, v16
	WORD $0x00d75733  // srl	a4, a4, a3
	WORD $0xfff68693  // addi	a3, a3, -1
	WORD $0x00177713  // andi	a4, a4, 1
	WORD $0x00a7173b  // sllw	a4, a4, a0
	WORD $0x001760b3  // or	ra, a4, ra
	WORD $0xfff50513  // addi	a0, a0, -1
	BNE X13, X23, LBB0_49  // bne	a3, s7, .LBB0_49
	WORD $0x00000f93  // li	t6, 0
	WORD $0x00f00513  // li	a0, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62e40857  // vmseq.vv	v16, v14, v8
	WORD $0x00f00693  // li	a3, 15
LBB0_51:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x43002757  // vmv.x.s	a4, v16
	WORD $0x00d75733  // srl	a4, a4, a3
	WORD $0xfff68693  // addi	a3, a3, -1
	WORD $0x00177713  // andi	a4, a4, 1
	WORD $0x00a7173b  // sllw	a4, a4, a0
	WORD $0x01f76fb3  // or	t6, a4, t6
	WORD $0xfff50513  // addi	a0, a0, -1
	BNE X13, X23, LBB0_51  // bne	a3, s7, .LBB0_51
	WORD $0x00000e93  // li	t4, 0
	WORD $0x00f00513  // li	a0, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62d40857  // vmseq.vv	v16, v13, v8
	WORD $0x00f00693  // li	a3, 15
LBB0_53:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x43002757  // vmv.x.s	a4, v16
	WORD $0x00d75733  // srl	a4, a4, a3
	WORD $0xfff68693  // addi	a3, a3, -1
	WORD $0x00177713  // andi	a4, a4, 1
	WORD $0x00a7173b  // sllw	a4, a4, a0
	WORD $0x01d76eb3  // or	t4, a4, t4
	WORD $0xfff50513  // addi	a0, a0, -1
	BNE X13, X23, LBB0_53  // bne	a3, s7, .LBB0_53
	WORD $0x00000793  // li	a5, 0
	WORD $0x00f00513  // li	a0, 15
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x62c40857  // vmseq.vv	v16, v12, v8
	WORD $0x00f00693  // li	a3, 15
LBB0_55:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x43002757  // vmv.x.s	a4, v16
	WORD $0x00d75733  // srl	a4, a4, a3
	WORD $0xfff68693  // addi	a3, a3, -1
	WORD $0x00177713  // andi	a4, a4, 1
	WORD $0x00a7173b  // sllw	a4, a4, a0
	WORD $0x00e7e7b3  // or	a5, a5, a4
	WORD $0xfff50513  // addi	a0, a0, -1
	BNE X13, X23, LBB0_55  // bne	a3, s7, .LBB0_55
	WORD $0x00000513  // li	a0, 0
LBB0_57:
	WORD $0x00150693  // addi	a3, a0, 1
	WORD $0x0876f057  // vsetvli	zero, a3, e8, mf2, tu, ma
	WORD $0x3aa54857  // vslideup.vx	v16, v10, a0
	WORD $0x00068513  // mv	a0, a3
	BNE X13, X22, LBB0_57  // bne	a3, s6, .LBB0_57
	WORD $0x00000513  // li	a0, 0
LBB0_59:
	WORD $0x00150693  // addi	a3, a0, 1
	WORD $0x0876f057  // vsetvli	zero, a3, e8, mf2, tu, ma
	WORD $0x3ab548d7  // vslideup.vx	v17, v11, a0
	WORD $0x00068513  // mv	a0, a3
	BNE X13, X22, LBB0_59  // bne	a3, s6, .LBB0_59
	WORD $0x00000493  // li	s1, 0
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x6f078857  // vmslt.vv	v16, v16, v15
	WORD $0x76f887d7  // vmsle.vv	v15, v15, v17
	WORD $0x00f00513  // li	a0, 15
	WORD $0x66f827d7  // vmand.mm	v15, v15, v16
	WORD $0x00f00693  // li	a3, 15
LBB0_61:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x42f02757  // vmv.x.s	a4, v15
	WORD $0x00d75733  // srl	a4, a4, a3
	WORD $0xfff68693  // addi	a3, a3, -1
	WORD $0x00177713  // andi	a4, a4, 1
	WORD $0x00a7173b  // sllw	a4, a4, a0
	WORD $0x00e4e4b3  // or	s1, s1, a4
	WORD $0xfff50513  // addi	a0, a0, -1
	BNE X13, X23, LBB0_61  // bne	a3, s7, .LBB0_61
	WORD $0x00000513  // li	a0, 0
LBB0_63:
	WORD $0x00150693  // addi	a3, a0, 1
	WORD $0x0876f057  // vsetvli	zero, a3, e8, mf2, tu, ma
	WORD $0x3aa547d7  // vslideup.vx	v15, v10, a0
	WORD $0x00068513  // mv	a0, a3
	BNE X13, X22, LBB0_63  // bne	a3, s6, .LBB0_63
	WORD $0x00000513  // li	a0, 0
LBB0_65:
	WORD $0x00150693  // addi	a3, a0, 1
	WORD $0x0876f057  // vsetvli	zero, a3, e8, mf2, tu, ma
	WORD $0x3ab54857  // vslideup.vx	v16, v11, a0
	WORD $0x00068513  // mv	a0, a3
	BNE X13, X22, LBB0_65  // bne	a3, s6, .LBB0_65
	WORD $0x00000f13  // li	t5, 0
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x6ef707d7  // vmslt.vv	v15, v15, v14
	WORD $0x76e80757  // vmsle.vv	v14, v14, v16
	WORD $0x00f00693  // li	a3, 15
	WORD $0x66e7a757  // vmand.mm	v14, v14, v15
	WORD $0x00f00713  // li	a4, 15
LBB0_67:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x42e02457  // vmv.x.s	s0, v14
	WORD $0x00e45433  // srl	s0, s0, a4
	WORD $0xfff70713  // addi	a4, a4, -1
	WORD $0x00147413  // andi	s0, s0, 1
	WORD $0x00d4153b  // sllw	a0, s0, a3
	WORD $0x01e56f33  // or	t5, a0, t5
	WORD $0xfff68693  // addi	a3, a3, -1
	BNE X14, X23, LBB0_67  // bne	a4, s7, .LBB0_67
	WORD $0x00000693  // li	a3, 0
LBB0_69:
	WORD $0x00168513  // addi	a0, a3, 1
	WORD $0x08757057  // vsetvli	zero, a0, e8, mf2, tu, ma
	WORD $0x3aa6c757  // vslideup.vx	v14, v10, a3
	WORD $0x00050693  // mv	a3, a0
	BNE X10, X22, LBB0_69  // bne	a0, s6, .LBB0_69
	WORD $0x00000693  // li	a3, 0
LBB0_71:
	WORD $0x00168513  // addi	a0, a3, 1
	WORD $0x08757057  // vsetvli	zero, a0, e8, mf2, tu, ma
	WORD $0x3ab6c7d7  // vslideup.vx	v15, v11, a3
	WORD $0x00050693  // mv	a3, a0
	BNE X10, X22, LBB0_71  // bne	a0, s6, .LBB0_71
	WORD $0x00000693  // li	a3, 0
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x6ee68757  // vmslt.vv	v14, v14, v13
	WORD $0x76d786d7  // vmsle.vv	v13, v13, v15
	WORD $0x00f00713  // li	a4, 15
	WORD $0x66d726d7  // vmand.mm	v13, v13, v14
	WORD $0x00f00413  // li	s0, 15
LBB0_73:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x42d02557  // vmv.x.s	a0, v13
	WORD $0x00855533  // srl	a0, a0, s0
	WORD $0xfff40413  // addi	s0, s0, -1
	WORD $0x00157513  // andi	a0, a0, 1
	WORD $0x00e5153b  // sllw	a0, a0, a4
	WORD $0x00a6e6b3  // or	a3, a3, a0
	WORD $0xfff70713  // addi	a4, a4, -1
	BNE X8, X23, LBB0_73  // bne	s0, s7, .LBB0_73
	WORD $0x00000713  // li	a4, 0
LBB0_75:
	WORD $0x00170513  // addi	a0, a4, 1
	WORD $0x08757057  // vsetvli	zero, a0, e8, mf2, tu, ma
	WORD $0x3aa746d7  // vslideup.vx	v13, v10, a4
	WORD $0x00050713  // mv	a4, a0
	BNE X10, X22, LBB0_75  // bne	a0, s6, .LBB0_75
	WORD $0x00000713  // li	a4, 0
LBB0_77:
	WORD $0x00170513  // addi	a0, a4, 1
	WORD $0x08757057  // vsetvli	zero, a0, e8, mf2, tu, ma
	WORD $0x3ab74757  // vslideup.vx	v14, v11, a4
	WORD $0x00050713  // mv	a4, a0
	BNE X10, X22, LBB0_77  // bne	a0, s6, .LBB0_77
	WORD $0x00000293  // li	t0, 0
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x6ed606d7  // vmslt.vv	v13, v13, v12
	WORD $0x76c70657  // vmsle.vv	v12, v12, v14
	WORD $0x00f00713  // li	a4, 15
	WORD $0x66c6a657  // vmand.mm	v12, v12, v13
	WORD $0x00f00413  // li	s0, 15
LBB0_79:
	WORD $0xcc80f057  // vsetivli	zero, 1, e16, m1, ta, ma
	WORD $0x42c02557  // vmv.x.s	a0, v12
	WORD $0x00855533  // srl	a0, a0, s0
	WORD $0xfff40413  // addi	s0, s0, -1
	WORD $0x00157513  // andi	a0, a0, 1
	WORD $0x00e5153b  // sllw	a0, a0, a4
	WORD $0x005562b3  // or	t0, a0, t0
	WORD $0xfff70713  // addi	a4, a4, -1
	BNE X8, X23, LBB0_79  // bne	s0, s7, .LBB0_79
	WORD $0x030d9d93  // slli	s11, s11, 48
	WORD $0x020d1d13  // slli	s10, s10, 32
	WORD $0x030c9c93  // slli	s9, s9, 48
	WORD $0x03079793  // slli	a5, a5, 48
	WORD $0x020e9e93  // slli	t4, t4, 32
	WORD $0x030f9f93  // slli	t6, t6, 48
	WORD $0x01bd0d33  // add	s10, s10, s11
	WORD $0x020cd513  // srli	a0, s9, 32
	WORD $0x01d787b3  // add	a5, a5, t4
	WORD $0x020fd713  // srli	a4, t6, 32
	WORD $0x00ad6533  // or	a0, s10, a0
	WORD $0x00f76733  // or	a4, a4, a5
	WORD $0x00e080b3  // add	ra, ra, a4
	WORD $0x00ac0c33  // add	s8, s8, a0
	BNEZ X1, LBB0_85  // bnez	ra, .LBB0_85
	BNEZ X28, LBB0_87  // bnez	t3, .LBB0_87
LBB0_82:
	WORD $0x03029293  // slli	t0, t0, 48
	WORD $0x02069693  // slli	a3, a3, 32
	WORD $0x030f1f13  // slli	t5, t5, 48
	WORD $0x005686b3  // add	a3, a3, t0
	WORD $0x020f5513  // srli	a0, t5, 32
	WORD $0x00d56533  // or	a0, a0, a3
	WORD $0x00a484b3  // add	s1, s1, a0
	BNEZ X24, LBB0_88  // bnez	s8, .LBB0_88
	BNEZ X9, LBB0_152  // bnez	s1, .LBB0_152
	WORD $0xfc0a0a13  // addi	s4, s4, -64
	WORD $0x03098a93  // addi	s5, s3, 48
	BLTU X18, X20, LBB0_40  // bltu	s2, s4, .LBB0_40
	JMP LBB0_106  // j	.LBB0_106
LBB0_85:
	BNE X16, X23, LBB0_87  // bne	a6, s7, .LBB0_87
	WORD $0x40100533  // neg	a0, ra
	WORD $0x00a0f533  // and	a0, ra, a0
	WORD $0x00013703  // ld	a4, 0(sp)
	WORD $0x02e50533  // mul	a0, a0, a4
	WORD $0x03a55513  // srli	a0, a0, 58
	MOV $·p5f6a1f9280687903_LCPI0_1(SB), X14  // lui	a4, %hi(.LCPI0_1)
	// addi	a4, a4, %lo(.LCPI0_1) (skipped, covered by MOV address load)
	WORD $0x00e50533  // add	a0, a0, a4
	WORD $0x00054803  // lbu	a6, 0(a0)
	WORD $0x406a8533  // sub	a0, s5, t1
	WORD $0x00a80833  // add	a6, a6, a0
LBB0_87:
	WORD $0xfffe4513  // not	a0, t3
	WORD $0x01013703  // ld	a4, 16(sp)
	WORD $0x00e0f733  // and	a4, ra, a4
	WORD $0x00a0f533  // and	a0, ra, a0
	WORD $0x00151793  // slli	a5, a0, 1
	WORD $0x01c7e7b3  // or	a5, a5, t3
	WORD $0xfff7c413  // not	s0, a5
	WORD $0x00877733  // and	a4, a4, s0
	WORD $0x00e50533  // add	a0, a0, a4
	WORD $0x00e53e33  // sltu	t3, a0, a4
	WORD $0x00151513  // slli	a0, a0, 1
	WORD $0x00813703  // ld	a4, 8(sp)
	WORD $0x00e54533  // xor	a0, a0, a4
	WORD $0x00f57533  // and	a0, a0, a5
	WORD $0xfff54513  // not	a0, a0
	WORD $0x00ac7c33  // and	s8, s8, a0
	JMP LBB0_82  // j	.LBB0_82
LBB0_88:
	MOV $·p5f6a1f9280687903_LCPI0_0(SB), X10  // lui	a0, %hi(.LCPI0_0)
	MOV (X10), X13  // ld	a3, %lo(.LCPI0_0)(a0)
	WORD $0x41800533  // neg	a0, s8
	WORD $0x00ac7533  // and	a0, s8, a0
	WORD $0x02d50533  // mul	a0, a0, a3
	WORD $0x03a55513  // srli	a0, a0, 58
	MOV $·p5f6a1f9280687903_LCPI0_1(SB), X15  // lui	a5, %hi(.LCPI0_1)
	// addi	a5, a5, %lo(.LCPI0_1) (skipped, covered by MOV address load)
	WORD $0x00f50533  // add	a0, a0, a5
	WORD $0x00054503  // lbu	a0, 0(a0)
	BEQZ X9, LBB0_131  // beqz	s1, .LBB0_131
	WORD $0x40900733  // neg	a4, s1
	WORD $0x00977733  // and	a4, a4, s1
	WORD $0x02d706b3  // mul	a3, a4, a3
	WORD $0x03a6d693  // srli	a3, a3, 58
	WORD $0x00f686b3  // add	a3, a3, a5
LBB0_90:
	WORD $0x0006c683  // lbu	a3, 0(a3)
	BGEU X13, X10, LBB0_132  // bgeu	a3, a0, .LBB0_132
	JMP LBB0_152  // j	.LBB0_152
LBB0_91:
	WORD $0xfff00813  // li	a6, -1
LBB0_92:
	WORD $0x02000513  // li	a0, 32
	BLTU X20, X10, LBB0_162  // bltu	s4, a0, .LBB0_162
	WORD $0x00000e13  // li	t3, 0
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x020a8587  // vle8.v	v11, (s5)
	WORD $0x010a8793  // addi	a5, s5, 16
	WORD $0x00f00693  // li	a3, 15
	WORD $0xfff00713  // li	a4, -1
	WORD $0x02078507  // vle8.v	v10, (a5)
	WORD $0x62b48657  // vmseq.vv	v12, v11, v9
	WORD $0x0c807057  // vsetvli	zero, zero, e16, m1, ta, ma
	WORD $0x42c027d7  // vmv.x.s	a5, v12
	WORD $0x00f00493  // li	s1, 15
LBB0_94:
	WORD $0x0097d433  // srl	s0, a5, s1
	WORD $0xfff48493  // addi	s1, s1, -1
	WORD $0x00147413  // andi	s0, s0, 1
	WORD $0x00d4153b  // sllw	a0, s0, a3
	WORD $0x01c56e33  // or	t3, a0, t3
	WORD $0xfff68693  // addi	a3, a3, -1
	BNE X9, X14, LBB0_94  // bne	s1, a4, .LBB0_94
	WORD $0x00000693  // li	a3, 0
	WORD $0x00f00713  // li	a4, 15
	WORD $0x0c707057  // vsetvli	zero, zero, e8, mf2, ta, ma
	WORD $0x62a484d7  // vmseq.vv	v9, v10, v9
	WORD $0xfff00793  // li	a5, -1
	WORD $0x0c807057  // vsetvli	zero, zero, e16, m1, ta, ma
	WORD $0x429024d7  // vmv.x.s	s1, v9
	WORD $0x00f00413  // li	s0, 15
LBB0_96:
	WORD $0x0084d533  // srl	a0, s1, s0
	WORD $0xfff40413  // addi	s0, s0, -1
	WORD $0x00157513  // andi	a0, a0, 1
	WORD $0x00e5153b  // sllw	a0, a0, a4
	WORD $0x00a6e6b3  // or	a3, a3, a0
	WORD $0xfff70713  // addi	a4, a4, -1
	BNE X8, X15, LBB0_96  // bne	s0, a5, .LBB0_96
	WORD $0x00000713  // li	a4, 0
	WORD $0x00f00793  // li	a5, 15
	WORD $0x0c707057  // vsetvli	zero, zero, e8, mf2, ta, ma
	WORD $0x62b404d7  // vmseq.vv	v9, v11, v8
	WORD $0xfff00293  // li	t0, -1
	WORD $0x0c807057  // vsetvli	zero, zero, e16, m1, ta, ma
	WORD $0x42902457  // vmv.x.s	s0, v9
	WORD $0x00f00493  // li	s1, 15
LBB0_98:
	WORD $0x00945533  // srl	a0, s0, s1
	WORD $0xfff48493  // addi	s1, s1, -1
	WORD $0x00157513  // andi	a0, a0, 1
	WORD $0x00f5153b  // sllw	a0, a0, a5
	WORD $0x00a76733  // or	a4, a4, a0
	WORD $0xfff78793  // addi	a5, a5, -1
	BNE X9, X5, LBB0_98  // bne	s1, t0, .LBB0_98
	WORD $0x00000793  // li	a5, 0
	WORD $0x00f00493  // li	s1, 15
	WORD $0x0c707057  // vsetvli	zero, zero, e8, mf2, ta, ma
	WORD $0x62a40457  // vmseq.vv	v8, v10, v8
	WORD $0xfff00293  // li	t0, -1
	WORD $0x0c807057  // vsetvli	zero, zero, e16, m1, ta, ma
	WORD $0x42802357  // vmv.x.s	t1, v8
	WORD $0x00f00413  // li	s0, 15
LBB0_100:
	WORD $0x00835533  // srl	a0, t1, s0
	WORD $0xfff40413  // addi	s0, s0, -1
	WORD $0x00157513  // andi	a0, a0, 1
	WORD $0x0095153b  // sllw	a0, a0, s1
	WORD $0x00a7e7b3  // or	a5, a5, a0
	WORD $0xfff48493  // addi	s1, s1, -1
	BNE X8, X5, LBB0_100  // bne	s0, t0, .LBB0_100
	WORD $0x01069693  // slli	a3, a3, 16
	WORD $0x01079793  // slli	a5, a5, 16
	WORD $0x00de0e33  // add	t3, t3, a3
	WORD $0x00e786bb  // addw	a3, a5, a4
	WORD $0x020e1513  // slli	a0, t3, 32
	WORD $0x02069713  // slli	a4, a3, 32
	WORD $0x02055513  // srli	a0, a0, 32
	WORD $0x02075713  // srli	a4, a4, 32
	BNEZ X13, LBB0_158  // bnez	a3, .LBB0_158
	BNEZ X18, LBB0_160  // bnez	s2, .LBB0_160
	BEQZ X10, LBB0_161  // beqz	a0, .LBB0_161
LBB0_104:
	MOV $·p5f6a1f9280687903_LCPI0_0(SB), X13  // lui	a3, %hi(.LCPI0_0)
	MOV (X13), X13  // ld	a3, %lo(.LCPI0_0)(a3)
	WORD $0x40a00733  // neg	a4, a0
	WORD $0x00e57533  // and	a0, a0, a4
	WORD $0x02d50533  // mul	a0, a0, a3
	WORD $0x03a55513  // srli	a0, a0, 58
	MOV $·p5f6a1f9280687903_LCPI0_1(SB), X13  // lui	a3, %hi(.LCPI0_1)
	// addi	a3, a3, %lo(.LCPI0_1) (skipped, covered by MOV address load)
	WORD $0x00d50533  // add	a0, a0, a3
	JMP LBB0_32  // j	.LBB0_32
LBB0_105:
	WORD $0xfff00813  // li	a6, -1
LBB0_106:
	WORD $0x02000513  // li	a0, 32
	BLTU X20, X10, LBB0_138  // bltu	s4, a0, .LBB0_138
	WORD $0x00000293  // li	t0, 0
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x020a8587  // vle8.v	v11, (s5)
	WORD $0x010a8713  // addi	a4, s5, 16
	WORD $0x00f00693  // li	a3, 15
	WORD $0xfff00513  // li	a0, -1
	WORD $0x02070507  // vle8.v	v10, (a4)
	WORD $0x62b48657  // vmseq.vv	v12, v11, v9
	WORD $0x0c807057  // vsetvli	zero, zero, e16, m1, ta, ma
	WORD $0x42c02757  // vmv.x.s	a4, v12
	WORD $0x00f00793  // li	a5, 15
LBB0_108:
	WORD $0x00f754b3  // srl	s1, a4, a5
	WORD $0xfff78793  // addi	a5, a5, -1
	WORD $0x0014f493  // andi	s1, s1, 1
	WORD $0x00d494bb  // sllw	s1, s1, a3
	WORD $0x0054e2b3  // or	t0, s1, t0
	WORD $0xfff68693  // addi	a3, a3, -1
	BNE X15, X10, LBB0_108  // bne	a5, a0, .LBB0_108
	WORD $0x00000f13  // li	t5, 0
	WORD $0x00f00693  // li	a3, 15
	WORD $0x0c707057  // vsetvli	zero, zero, e8, mf2, ta, ma
	WORD $0x62a484d7  // vmseq.vv	v9, v10, v9
	WORD $0xfff00513  // li	a0, -1
	WORD $0x0c807057  // vsetvli	zero, zero, e16, m1, ta, ma
	WORD $0x42902757  // vmv.x.s	a4, v9
	WORD $0x00f00793  // li	a5, 15
LBB0_110:
	WORD $0x00f754b3  // srl	s1, a4, a5
	WORD $0xfff78793  // addi	a5, a5, -1
	WORD $0x0014f493  // andi	s1, s1, 1
	WORD $0x00d494bb  // sllw	s1, s1, a3
	WORD $0x01e4ef33  // or	t5, s1, t5
	WORD $0xfff68693  // addi	a3, a3, -1
	BNE X15, X10, LBB0_110  // bne	a5, a0, .LBB0_110
	WORD $0x00000913  // li	s2, 0
	WORD $0x00f00693  // li	a3, 15
	WORD $0x0c707057  // vsetvli	zero, zero, e8, mf2, ta, ma
	WORD $0x62b404d7  // vmseq.vv	v9, v11, v8
	WORD $0xfff00513  // li	a0, -1
	WORD $0x0c807057  // vsetvli	zero, zero, e16, m1, ta, ma
	WORD $0x429027d7  // vmv.x.s	a5, v9
	WORD $0x00f00493  // li	s1, 15
LBB0_112:
	WORD $0x0097d433  // srl	s0, a5, s1
	WORD $0xfff48493  // addi	s1, s1, -1
	WORD $0x00147413  // andi	s0, s0, 1
	WORD $0x00d4173b  // sllw	a4, s0, a3
	WORD $0x01276933  // or	s2, a4, s2
	WORD $0xfff68693  // addi	a3, a3, -1
	BNE X9, X10, LBB0_112  // bne	s1, a0, .LBB0_112
	WORD $0x00000493  // li	s1, 0
	WORD $0x00f00693  // li	a3, 15
	WORD $0x0c707057  // vsetvli	zero, zero, e8, mf2, ta, ma
	WORD $0x62a40457  // vmseq.vv	v8, v10, v8
	WORD $0xfff00513  // li	a0, -1
	WORD $0x0c807057  // vsetvli	zero, zero, e16, m1, ta, ma
	WORD $0x428027d7  // vmv.x.s	a5, v8
	WORD $0x00f00413  // li	s0, 15
LBB0_114:
	WORD $0x0087d733  // srl	a4, a5, s0
	WORD $0xfff40413  // addi	s0, s0, -1
	WORD $0x00177713  // andi	a4, a4, 1
	WORD $0x00d7173b  // sllw	a4, a4, a3
	WORD $0x00e4e4b3  // or	s1, s1, a4
	WORD $0xfff68693  // addi	a3, a3, -1
	BNE X8, X10, LBB0_114  // bne	s0, a0, .LBB0_114
	WORD $0x00000513  // li	a0, 0
	WORD $0x0c707057  // vsetvli	zero, zero, e8, mf2, ta, ma
	WORD $0x5e0fb457  // vmv.v.i	v8, -1
	WORD $0x01000693  // li	a3, 16
LBB0_116:
	WORD $0x00150713  // addi	a4, a0, 1
	WORD $0x08777057  // vsetvli	zero, a4, e8, mf2, tu, ma
	WORD $0x3a8544d7  // vslideup.vx	v9, v8, a0
	WORD $0x00070513  // mv	a0, a4
	BNE X14, X13, LBB0_116  // bne	a4, a3, .LBB0_116
	WORD $0x00000513  // li	a0, 0
	WORD $0x01f00693  // li	a3, 31
	WORD $0x0c707757  // vsetvli	a4, zero, e8, mf2, ta, ma
	WORD $0x4206e6d7  // vmv.s.x	v13, a3
	WORD $0x01000693  // li	a3, 16
LBB0_118:
	WORD $0x00150713  // addi	a4, a0, 1
	WORD $0x08777057  // vsetvli	zero, a4, e8, mf2, tu, ma
	WORD $0x3ad54657  // vslideup.vx	v12, v13, a0
	WORD $0x00070513  // mv	a0, a4
	BNE X14, X13, LBB0_118  // bne	a4, a3, .LBB0_118
	WORD $0x00000793  // li	a5, 0
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x6e9584d7  // vmslt.vv	v9, v9, v11
	WORD $0x76b605d7  // vmsle.vv	v11, v11, v12
	WORD $0x00f00693  // li	a3, 15
	WORD $0xfff00e93  // li	t4, -1
	WORD $0x66b4a4d7  // vmand.mm	v9, v11, v9
	WORD $0x0c807057  // vsetvli	zero, zero, e16, m1, ta, ma
	WORD $0x42902557  // vmv.x.s	a0, v9
	WORD $0x00f00413  // li	s0, 15
LBB0_120:
	WORD $0x00855733  // srl	a4, a0, s0
	WORD $0xfff40413  // addi	s0, s0, -1
	WORD $0x00177713  // andi	a4, a4, 1
	WORD $0x00d7173b  // sllw	a4, a4, a3
	WORD $0x00e7e7b3  // or	a5, a5, a4
	WORD $0xfff68693  // addi	a3, a3, -1
	BNE X8, X29, LBB0_120  // bne	s0, t4, .LBB0_120
	WORD $0x00000513  // li	a0, 0
	WORD $0x01000693  // li	a3, 16
LBB0_122:
	WORD $0x00150713  // addi	a4, a0, 1
	WORD $0x08777057  // vsetvli	zero, a4, e8, mf2, tu, ma
	WORD $0x3a8544d7  // vslideup.vx	v9, v8, a0
	WORD $0x00070513  // mv	a0, a4
	BNE X14, X13, LBB0_122  // bne	a4, a3, .LBB0_122
	WORD $0x00000513  // li	a0, 0
	WORD $0x01f00693  // li	a3, 31
	WORD $0x0c707757  // vsetvli	a4, zero, e8, mf2, ta, ma
	WORD $0x4206e5d7  // vmv.s.x	v11, a3
	WORD $0x01000693  // li	a3, 16
LBB0_124:
	WORD $0x00150713  // addi	a4, a0, 1
	WORD $0x08777057  // vsetvli	zero, a4, e8, mf2, tu, ma
	WORD $0x3ab54457  // vslideup.vx	v8, v11, a0
	WORD $0x00070513  // mv	a0, a4
	BNE X14, X13, LBB0_124  // bne	a4, a3, .LBB0_124
	WORD $0x00000693  // li	a3, 0
	WORD $0xcc787057  // vsetivli	zero, 16, e8, mf2, ta, ma
	WORD $0x6e9504d7  // vmslt.vv	v9, v9, v10
	WORD $0x76a40457  // vmsle.vv	v8, v10, v8
	WORD $0x00f00513  // li	a0, 15
	WORD $0xfff00e93  // li	t4, -1
	WORD $0x6684a457  // vmand.mm	v8, v8, v9
	WORD $0x0c807057  // vsetvli	zero, zero, e16, m1, ta, ma
	WORD $0x42802fd7  // vmv.x.s	t6, v8
	WORD $0x00f00413  // li	s0, 15
LBB0_126:
	WORD $0x008fd733  // srl	a4, t6, s0
	WORD $0xfff40413  // addi	s0, s0, -1
	WORD $0x00177713  // andi	a4, a4, 1
	WORD $0x00a7173b  // sllw	a4, a4, a0
	WORD $0x00e6e6b3  // or	a3, a3, a4
	WORD $0xfff50513  // addi	a0, a0, -1
	BNE X8, X29, LBB0_126  // bne	s0, t4, .LBB0_126
	WORD $0x010f1f13  // slli	t5, t5, 16
	WORD $0x01049493  // slli	s1, s1, 16
	WORD $0x01e282b3  // add	t0, t0, t5
	WORD $0x0124873b  // addw	a4, s1, s2
	WORD $0x02029513  // slli	a0, t0, 32
	WORD $0x02071493  // slli	s1, a4, 32
	WORD $0x02055513  // srli	a0, a0, 32
	WORD $0x0204de93  // srli	t4, s1, 32
	WORD $0x01069693  // slli	a3, a3, 16
	BNEZ X14, LBB0_177  // bnez	a4, .LBB0_177
	BNEZ X28, LBB0_179  // bnez	t3, .LBB0_179
LBB0_129:
	WORD $0x00f686bb  // addw	a3, a3, a5
	BEQZ X10, LBB0_136  // beqz	a0, .LBB0_136
	MOV $·p5f6a1f9280687903_LCPI0_0(SB), X14  // lui	a4, %hi(.LCPI0_0)
	MOV (X14), X14  // ld	a4, %lo(.LCPI0_0)(a4)
	WORD $0x40a007b3  // neg	a5, a0
	WORD $0x00f57533  // and	a0, a0, a5
	WORD $0x02e50533  // mul	a0, a0, a4
	WORD $0x03a55513  // srli	a0, a0, 58
	MOV $·p5f6a1f9280687903_LCPI0_1(SB), X14  // lui	a4, %hi(.LCPI0_1)
	// addi	a4, a4, %lo(.LCPI0_1) (skipped, covered by MOV address load)
	WORD $0x00e50533  // add	a0, a0, a4
	WORD $0x00054503  // lbu	a0, 0(a0)
	BNEZ X13, LBB0_156  // bnez	a3, .LBB0_156
LBB0_131:
	WORD $0x04000693  // li	a3, 64
	BLTU X13, X10, LBB0_152  // bltu	a3, a0, .LBB0_152
LBB0_132:
	WORD $0x406a86b3  // sub	a3, s5, t1
LBB0_133:
	WORD $0x00d50533  // add	a0, a0, a3
LBB0_134:
	WORD $0x00150513  // addi	a0, a0, 1
	BLTZ X10, LBB0_153  // bltz	a0, .LBB0_153
LBB0_135:
	WORD $0x00a5b023  // sd	a0, 0(a1)
	WORD $0x00763823  // sd	t2, 16(a2)
	WORD $0x00700593  // li	a1, 7
	WORD $0x00a82533  // slt	a0, a6, a0
	WORD $0x00b63023  // sd	a1, 0(a2)
	WORD $0xfff50513  // addi	a0, a0, -1
	WORD $0x01056533  // or	a0, a0, a6
	WORD $0x00a63c23  // sd	a0, 24(a2)
	JMP LBB0_155  // j	.LBB0_155
LBB0_136:
	BNEZ X13, LBB0_152  // bnez	a3, .LBB0_152
	WORD $0x020a8a93  // addi	s5, s5, 32
	WORD $0xfe0a0a13  // addi	s4, s4, -32
LBB0_138:
	BNEZ X28, LBB0_184  // bnez	t3, .LBB0_184
LBB0_139:
	WORD $0xfff00513  // li	a0, -1
	BEQZ X20, LBB0_153  // beqz	s4, .LBB0_153
	WORD $0x406002b3  // neg	t0, t1
	WORD $0x02200713  // li	a4, 34
	WORD $0x05c00e13  // li	t3, 92
	WORD $0x02000493  // li	s1, 32
LBB0_141:
	WORD $0x00000693  // li	a3, 0
LBB0_142:
	WORD $0x00da8433  // add	s0, s5, a3
	WORD $0x00044783  // lbu	a5, 0(s0)
	BEQ X15, X14, LBB0_157  // beq	a5, a4, .LBB0_157
	BEQ X15, X28, LBB0_146  // beq	a5, t3, .LBB0_146
	BLTU X15, X9, LBB0_152  // bltu	a5, s1, .LBB0_152
	WORD $0x00168693  // addi	a3, a3, 1
	BNE X20, X13, LBB0_142  // bne	s4, a3, .LBB0_142
	JMP LBB0_153  // j	.LBB0_153
LBB0_146:
	WORD $0xfffa0793  // addi	a5, s4, -1
	BEQ X15, X13, LBB0_153  // beq	a5, a3, .LBB0_153
	WORD $0xfff00793  // li	a5, -1
	BNE X16, X15, LBB0_149  // bne	a6, a5, .LBB0_149
	WORD $0x00540833  // add	a6, s0, t0
LBB0_149:
	WORD $0x00240a93  // addi	s5, s0, 2
	WORD $0xffea0793  // addi	a5, s4, -2
	WORD $0x40da0a33  // sub	s4, s4, a3
	WORD $0xffea0a13  // addi	s4, s4, -2
	BNE X15, X13, LBB0_141  // bne	a5, a3, .LBB0_141
	WORD $0x00088393  // mv	t2, a7
LBB0_151:
	WORD $0xfff00513  // li	a0, -1
	JMP LBB0_154  // j	.LBB0_154
LBB0_152:
	WORD $0xffe00513  // li	a0, -2
LBB0_153:
	WORD $0x00088393  // mv	t2, a7
LBB0_154:
	WORD $0x0075b023  // sd	t2, 0(a1)
	WORD $0x00a63023  // sd	a0, 0(a2)
LBB0_155:
	WORD $0x07813083  // ld	ra, 120(sp)
	WORD $0x07013403  // ld	s0, 112(sp)
	WORD $0x06813483  // ld	s1, 104(sp)
	WORD $0x06013903  // ld	s2, 96(sp)
	WORD $0x05813983  // ld	s3, 88(sp)
	WORD $0x05013a03  // ld	s4, 80(sp)
	WORD $0x04813a83  // ld	s5, 72(sp)
	WORD $0x04013b03  // ld	s6, 64(sp)
	WORD $0x03813b83  // ld	s7, 56(sp)
	WORD $0x03013c03  // ld	s8, 48(sp)
	WORD $0x02813c83  // ld	s9, 40(sp)
	WORD $0x02013d03  // ld	s10, 32(sp)
	WORD $0x01813d83  // ld	s11, 24(sp)
	WORD $0x08010113  // addi	sp, sp, 128
	RET  // ret
LBB0_156:
	WORD $0x40d0073b  // negw	a4, a3
	WORD $0x00e6f6b3  // and	a3, a3, a4
	WORD $0x077cb737  // lui	a4, 30667
	WORD $0x53170713  // addi	a4, a4, 1329
	WORD $0x02e686b3  // mul	a3, a3, a4
	WORD $0x01b6d69b  // srliw	a3, a3, 27
	MOV $·p5f6a1f9280687903_LCPI0_4(SB), X14  // lui	a4, %hi(.LCPI0_4)
	// addi	a4, a4, %lo(.LCPI0_4) (skipped, covered by MOV address load)
	WORD $0x00e686b3  // add	a3, a3, a4
	JMP LBB0_90  // j	.LBB0_90
LBB0_157:
	WORD $0x406a8533  // sub	a0, s5, t1
	WORD $0x00d50533  // add	a0, a0, a3
	JMP LBB0_134  // j	.LBB0_134
LBB0_158:
	WORD $0xfff00793  // li	a5, -1
	BNE X16, X15, LBB0_160  // bne	a6, a5, .LBB0_160
	MOV $·p5f6a1f9280687903_LCPI0_0(SB), X15  // lui	a5, %hi(.LCPI0_0)
	MOV (X15), X15  // ld	a5, %lo(.LCPI0_0)(a5)
	WORD $0x40e004b3  // neg	s1, a4
	WORD $0x00e4f4b3  // and	s1, s1, a4
	WORD $0x02f487b3  // mul	a5, s1, a5
	WORD $0x03a7d793  // srli	a5, a5, 58
	MOV $·p5f6a1f9280687903_LCPI0_1(SB), X9  // lui	s1, %hi(.LCPI0_1)
	// addi	s1, s1, %lo(.LCPI0_1) (skipped, covered by MOV address load)
	WORD $0x009787b3  // add	a5, a5, s1
	WORD $0x0007c803  // lbu	a6, 0(a5)
	WORD $0x41ea87b3  // sub	a5, s5, t5
	WORD $0x00f80833  // add	a6, a6, a5
LBB0_160:
	WORD $0xfff94793  // not	a5, s2
	WORD $0xaaaab4b7  // lui	s1, 699051
	WORD $0x00e7f7b3  // and	a5, a5, a4
	WORD $0x55555437  // lui	s0, 349525
	WORD $0xaaa4849b  // addiw	s1, s1, -1366
	WORD $0x0096f6b3  // and	a3, a3, s1
	WORD $0x00179713  // slli	a4, a5, 1
	WORD $0x012764b3  // or	s1, a4, s2
	WORD $0xfff74713  // not	a4, a4
	WORD $0x00e6f6b3  // and	a3, a3, a4
	WORD $0x00f6873b  // addw	a4, a3, a5
	WORD $0x00d787b3  // add	a5, a5, a3
	WORD $0x0006869b  // sext.w	a3, a3
	WORD $0x00d73933  // sltu	s2, a4, a3
	WORD $0x00179793  // slli	a5, a5, 1
	WORD $0x5554069b  // addiw	a3, s0, 1365
	WORD $0x00f6c6b3  // xor	a3, a3, a5
	WORD $0x0096f6b3  // and	a3, a3, s1
	WORD $0xfff6c693  // not	a3, a3
	WORD $0x00d57533  // and	a0, a0, a3
	BNEZ X10, LBB0_104  // bnez	a0, .LBB0_104
LBB0_161:
	WORD $0x020a8a93  // addi	s5, s5, 32
	WORD $0xfe0a0a13  // addi	s4, s4, -32
LBB0_162:
	BNEZ X18, LBB0_180  // bnez	s2, .LBB0_180
	BEQZ X20, LBB0_174  // beqz	s4, .LBB0_174
LBB0_164:
	WORD $0x41e002b3  // neg	t0, t5
	WORD $0x02200713  // li	a4, 34
	WORD $0x05c00793  // li	a5, 92
LBB0_165:
	WORD $0x00000413  // li	s0, 0
LBB0_166:
	WORD $0x008a84b3  // add	s1, s5, s0
	WORD $0x0004c683  // lbu	a3, 0(s1)
	BEQ X13, X14, LBB0_173  // beq	a3, a4, .LBB0_173
	BEQ X13, X15, LBB0_169  // beq	a3, a5, .LBB0_169
	WORD $0x00140413  // addi	s0, s0, 1
	BNE X20, X8, LBB0_166  // bne	s4, s0, .LBB0_166
	JMP LBB0_175  // j	.LBB0_175
LBB0_169:
	WORD $0xfffa0513  // addi	a0, s4, -1
	BEQ X10, X8, LBB0_188  // beq	a0, s0, .LBB0_188
	WORD $0xfff00513  // li	a0, -1
	BNE X16, X10, LBB0_172  // bne	a6, a0, .LBB0_172
	WORD $0x00548833  // add	a6, s1, t0
LBB0_172:
	WORD $0x408a06b3  // sub	a3, s4, s0
	WORD $0xffea0313  // addi	t1, s4, -2
	WORD $0xffe68a13  // addi	s4, a3, -2
	WORD $0x00248a93  // addi	s5, s1, 2
	BNE X6, X8, LBB0_165  // bne	t1, s0, .LBB0_165
	JMP LBB0_153  // j	.LBB0_153
LBB0_173:
	WORD $0x00148a93  // addi	s5, s1, 1
LBB0_174:
	WORD $0x41ea8533  // sub	a0, s5, t5
	BGEZ X10, LBB0_135  // bgez	a0, .LBB0_135
	JMP LBB0_153  // j	.LBB0_153
LBB0_175:
	WORD $0x02200713  // li	a4, 34
	WORD $0xfff00513  // li	a0, -1
	BNE X13, X14, LBB0_153  // bne	a3, a4, .LBB0_153
	WORD $0x008a8ab3  // add	s5, s5, s0
	JMP LBB0_174  // j	.LBB0_174
LBB0_177:
	WORD $0xfff00413  // li	s0, -1
	BNE X16, X8, LBB0_179  // bne	a6, s0, .LBB0_179
	MOV $·p5f6a1f9280687903_LCPI0_0(SB), X8  // lui	s0, %hi(.LCPI0_0)
	MOV (X8), X16  // ld	a6, %lo(.LCPI0_0)(s0)
	WORD $0x41d00433  // neg	s0, t4
	WORD $0x008ef433  // and	s0, t4, s0
	WORD $0x03040433  // mul	s0, s0, a6
	WORD $0x03a45413  // srli	s0, s0, 58
	MOV $·p5f6a1f9280687903_LCPI0_1(SB), X9  // lui	s1, %hi(.LCPI0_1)
	// addi	s1, s1, %lo(.LCPI0_1) (skipped, covered by MOV address load)
	WORD $0x00940433  // add	s0, s0, s1
	WORD $0x00044803  // lbu	a6, 0(s0)
	WORD $0x406a8433  // sub	s0, s5, t1
	WORD $0x00880833  // add	a6, a6, s0
LBB0_179:
	WORD $0xfffe4413  // not	s0, t3
	WORD $0xaaaab2b7  // lui	t0, 699051
	WORD $0x008eff33  // and	t5, t4, s0
	WORD $0x55555eb7  // lui	t4, 349525
	WORD $0xaaa2849b  // addiw	s1, t0, -1366
	WORD $0x00977733  // and	a4, a4, s1
	WORD $0x001f1413  // slli	s0, t5, 1
	WORD $0x01c464b3  // or	s1, s0, t3
	WORD $0xfff44413  // not	s0, s0
	WORD $0x00877733  // and	a4, a4, s0
	WORD $0x01e7043b  // addw	s0, a4, t5
	WORD $0x00ef0f33  // add	t5, t5, a4
	WORD $0x0007071b  // sext.w	a4, a4
	WORD $0x00e43e33  // sltu	t3, s0, a4
	WORD $0x001f1f13  // slli	t5, t5, 1
	WORD $0x555e871b  // addiw	a4, t4, 1365
	WORD $0x00ef4733  // xor	a4, t5, a4
	WORD $0x00977733  // and	a4, a4, s1
	WORD $0xfff74713  // not	a4, a4
	WORD $0x00e57533  // and	a0, a0, a4
	JMP LBB0_129  // j	.LBB0_129
LBB0_180:
	BEQZ X20, LBB0_188  // beqz	s4, .LBB0_188
	WORD $0xfff00513  // li	a0, -1
	BNE X16, X10, LBB0_183  // bne	a6, a0, .LBB0_183
	WORD $0xffff4813  // not	a6, t5
	WORD $0x01580833  // add	a6, a6, s5
LBB0_183:
	WORD $0x001a8a93  // addi	s5, s5, 1
	WORD $0xfffa0a13  // addi	s4, s4, -1
	BNEZ X20, LBB0_164  // bnez	s4, .LBB0_164
	JMP LBB0_174  // j	.LBB0_174
LBB0_184:
	BEQZ X20, LBB0_188  // beqz	s4, .LBB0_188
	WORD $0xfff00513  // li	a0, -1
	BNE X16, X10, LBB0_187  // bne	a6, a0, .LBB0_187
	WORD $0xfff34813  // not	a6, t1
	WORD $0x01580833  // add	a6, a6, s5
LBB0_187:
	WORD $0x001a8a93  // addi	s5, s5, 1
	WORD $0xfffa0a13  // addi	s4, s4, -1
	JMP LBB0_139  // j	.LBB0_139
LBB0_188:
	WORD $0xfff00513  // li	a0, -1
	JMP LBB0_153  // j	.LBB0_153
Lfunc_end0:


TEXT ·__vstring(SB), $0-32
	NO_LOCAL_POINTERS
___vstring:
	MOV s+0(FP), X10
	MOV p+8(FP), X11
	MOV v+16(FP), X12
	MOV flags+24(FP), X13
	CALL ·__vstring_riscv64_entry__(SB)
	RET

// Data section
GLOBL ·p5f6a1f9280687903_LCPI0_0(SB), RODATA, $8
DATA ·p5f6a1f9280687903_LCPI0_0+0(SB)/8, $0x0218a392cd3d5dbf
GLOBL ·p5f6a1f9280687903_LCPI0_2(SB), RODATA, $8
DATA ·p5f6a1f9280687903_LCPI0_2+0(SB)/8, $0xaaaaaaaaaaaaaaaa
GLOBL ·p5f6a1f9280687903_LCPI0_3(SB), RODATA, $8
DATA ·p5f6a1f9280687903_LCPI0_3+0(SB)/8, $0x5555555555555555
GLOBL ·p5f6a1f9280687903_LCPI0_1(SB), RODATA, $83
DATA ·p5f6a1f9280687903_LCPI0_1+0(SB)/8, $0x30305c3030305c22
DATA ·p5f6a1f9280687903_LCPI0_1+8(SB)/8, $0x30305c3230305c31
DATA ·p5f6a1f9280687903_LCPI0_1+16(SB)/8, $0x5c725c3330305c37
DATA ·p5f6a1f9280687903_LCPI0_1+24(SB)/8, $0x30305c3332305c62
DATA ·p5f6a1f9280687903_LCPI0_1+32(SB)/8, $0x31305c3133305c34
DATA ·p5f6a1f9280687903_LCPI0_1+40(SB)/8, $0x5c745c3433305c36
DATA ·p5f6a1f9280687903_LCPI0_1+48(SB)/8, $0x305c283432305c22
DATA ·p5f6a1f9280687903_LCPI0_1+56(SB)/8, $0x305c3132305c3530
DATA ·p5f6a1f9280687903_LCPI0_1+64(SB)/8, $0x2e3731305c263233
DATA ·p5f6a1f9280687903_LCPI0_1+72(SB)/8, $0x5c6e5c303533305c
DATA ·p5f6a1f9280687903_LCPI0_1+80(SB)/8, $0x0000000000373330
GLOBL ·p5f6a1f9280687903_LCPI0_4(SB), RODATA, $32
DATA ·p5f6a1f9280687903_LCPI0_4+0(SB)/8, $0x03180e1d021c0100
DATA ·p5f6a1f9280687903_LCPI0_4+8(SB)/8, $0x080411190f14161e
DATA ·p5f6a1f9280687903_LCPI0_4+16(SB)/8, $0x07101315170d1b1f
DATA ·p5f6a1f9280687903_LCPI0_4+24(SB)/8, $0x090a050b06120c1a
GLOBL ·p5f6a1f9280687903_MASK_USE_NUMBER(SB), RODATA, $4
DATA ·p5f6a1f9280687903_MASK_USE_NUMBER+0(SB)/8, $0x0000000000000002
