// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

#include "go_asm.h"
#include "funcdata.h"
#include "textflag.h"

TEXT ·__vunsigned_entry__(SB), $0-8
	MOV $·__vunsigned_riscv64_entry__(SB), A0
	MOV A0, ret+0(FP)
	RET

TEXT ·__vunsigned_riscv64_entry__(SB), $0
	NO_LOCAL_POINTERS
vunsigned:
	WORD $0x0005b783  // ld	a5, 0(a1)
	WORD $0x00853383  // ld	t2, 8(a0)
	WORD $0x00900693  // li	a3, 9
	WORD $0x00d63023  // sd	a3, 0(a2)
	WORD $0x00063823  // sd	zero, 16(a2)
	WORD $0x0005b683  // ld	a3, 0(a1)
	WORD $0x00053303  // ld	t1, 0(a0)
	WORD $0x00063423  // sd	zero, 8(a2)
	WORD $0x00d63c23  // sd	a3, 24(a2)
	BGEU X15, X7, LBB0_3  // bgeu	a5, t2, .LBB0_3
	WORD $0x00f306b3  // add	a3, t1, a5
	WORD $0x0006c503  // lbu	a0, 0(a3)
	WORD $0x02d00713  // li	a4, 45
	BNE X10, X14, LBB0_5  // bne	a0, a4, .LBB0_5
LBB0_2:
	WORD $0x00f5b023  // sd	a5, 0(a1)
	WORD $0xffa00513  // li	a0, -6
	JMP LBB0_4  // j	.LBB0_4
LBB0_3:
	WORD $0x0075b023  // sd	t2, 0(a1)
	WORD $0xfff00513  // li	a0, -1
LBB0_4:
	WORD $0x00a63023  // sd	a0, 0(a2)
	RET  // ret
LBB0_5:
	WORD $0xfc650813  // addi	a6, a0, -58
	WORD $0xff500713  // li	a4, -11
	BLTU X14, X16, LBB0_7  // bltu	a4, a6, .LBB0_7
	WORD $0x00f5b023  // sd	a5, 0(a1)
	WORD $0xffe00513  // li	a0, -2
	JMP LBB0_4  // j	.LBB0_4
LBB0_7:
	WORD $0x03000713  // li	a4, 48
	BNE X10, X14, LBB0_10  // bne	a0, a4, .LBB0_10
	WORD $0x0016c503  // lbu	a0, 1(a3)
	WORD $0xfd250513  // addi	a0, a0, -46
	WORD $0x03700693  // li	a3, 55
	BLTU X13, X10, LBB0_25  // bltu	a3, a0, .LBB0_25
	WORD $0x008006b7  // lui	a3, 2048
	WORD $0x0016869b  // addiw	a3, a3, 1
	WORD $0x03769713  // slli	a4, a3, 55
	WORD $0x00e686b3  // add	a3, a3, a4
	WORD $0x00a6d533  // srl	a0, a3, a0
	WORD $0x00157513  // andi	a0, a0, 1
	BEQZ X10, LBB0_25  // beqz	a0, .LBB0_25
LBB0_10:
	WORD $0x00038813  // mv	a6, t2
	BLTU X15, X7, LBB0_12  // bltu	a5, t2, .LBB0_12
	WORD $0x00078813  // mv	a6, a5
LBB0_12:
	WORD $0x00000e13  // li	t3, 0
	WORD $0x00900893  // li	a7, 9
	WORD $0x00a00293  // li	t0, 10
LBB0_13:
	BEQ X16, X15, LBB0_24  // beq	a6, a5, .LBB0_24
	WORD $0x00f306b3  // add	a3, t1, a5
	WORD $0x0006c503  // lbu	a0, 0(a3)
	WORD $0xfd050713  // addi	a4, a0, -48
	BLTU X17, X14, LBB0_19  // bltu	a7, a4, .LBB0_19
	WORD $0x025e36b3  // mulhu	a3, t3, t0
	BNEZ X13, LBB0_18  // bnez	a3, .LBB0_18
	WORD $0x025e06b3  // mul	a3, t3, t0
	WORD $0xfd050513  // addi	a0, a0, -48
	WORD $0x02051513  // slli	a0, a0, 32
	WORD $0x02055513  // srli	a0, a0, 32
	WORD $0x00a68e33  // add	t3, a3, a0
	WORD $0x00de36b3  // sltu	a3, t3, a3
	WORD $0x40d00533  // neg	a0, a3
	WORD $0x00178793  // addi	a5, a5, 1
	BNE X10, X13, LBB0_18  // bne	a0, a3, .LBB0_18
	BGEZ X10, LBB0_13  // bgez	a0, .LBB0_13
LBB0_18:
	WORD $0xfff78793  // addi	a5, a5, -1
	WORD $0x00f5b023  // sd	a5, 0(a1)
	WORD $0xffb00513  // li	a0, -5
	JMP LBB0_4  // j	.LBB0_4
LBB0_19:
	BGEU X15, X7, LBB0_23  // bgeu	a5, t2, .LBB0_23
	WORD $0x0006c503  // lbu	a0, 0(a3)
	WORD $0x02e00693  // li	a3, 46
	BEQ X10, X13, LBB0_2  // beq	a0, a3, .LBB0_2
	WORD $0x04500693  // li	a3, 69
	BEQ X10, X13, LBB0_2  // beq	a0, a3, .LBB0_2
	WORD $0x06500693  // li	a3, 101
	BEQ X10, X13, LBB0_2  // beq	a0, a3, .LBB0_2
LBB0_23:
	WORD $0x00078813  // mv	a6, a5
LBB0_24:
	WORD $0x0105b023  // sd	a6, 0(a1)
	WORD $0x01c63823  // sd	t3, 16(a2)
	RET  // ret
LBB0_25:
	WORD $0x00178793  // addi	a5, a5, 1
	WORD $0x00f5b023  // sd	a5, 0(a1)
	RET  // ret
Lfunc_end0:


TEXT ·__vunsigned(SB), $0-24
	NO_LOCAL_POINTERS
___vunsigned:
	MOV s+0(FP), X10
	MOV p+8(FP), X11
	MOV v+16(FP), X12
	CALL ·__vunsigned_riscv64_entry__(SB)
	RET

// Data section
GLOBL ·p7b54be6fba460921_MASK_USE_NUMBER(SB), RODATA, $4
DATA ·p7b54be6fba460921_MASK_USE_NUMBER+0(SB)/8, $0x0000000000000002
