#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import typing
import logging
from typing import Optional

GOOS = {
    'aix', 'android', 'darwin', 'dragonfly', 'freebsd', 'hurd', 'illumos',
    'js', 'linux', 'nacl', 'netbsd', 'openbsd', 'plan9', 'solaris',
    'windows', 'zos',
}

GOARCH = {
    '386', 'amd64', 'amd64p32', 'arm', 'armbe', 'arm64', 'arm64be',
    'ppc64', 'ppc64le', 'mips', 'mipsle', 'mips64', 'mips64le',
    'mips64p32', 'mips64p32le', 'ppc', 'riscv', 'riscv64', 's390',
    's390x', 'sparc', 'sparc64', 'wasm',
}

class Subroutine:
    """
    存储关于一个 C 子程序的信息，以便在 Go 中引用。
    """
    offset: int
    stack_size: int
    go_name: Optional[str]

    def __init__(self, offset: int, stack_size: int, go_name: Optional[str] = None):
        self.offset = offset
        self.stack_size = stack_size
        self.go_name = go_name

def save_subr_refs(pkg: str, subr: dict[str, Subroutine], base: Optional[str], name: str):
    """
    将子程序引用保存到一个 Go 文件中。

    :param pkg: Go 包名。
    :param subr: 一个字典，将子程序键名映射到 Subroutine 对象。
    :param base: (已弃用) 主 TEXT 块的名称。现在从 subr 对象中获取。
    :param name: 输出文件名。
    """
    with open(name, 'w') as fp:
        print('// +build !noasm !appengine', file=fp)
        print('// Code generated by asm2asm, DO NOT EDIT.', file=fp)
        print(file=fp)
        print(f'package {pkg}', file=fp)
        print(file=fp)
        print('import "unsafe"', file=fp) # unsafe.Pointer for casting
        print(file=fp)

        # --- 生成所有需要的函数原型 ---
        # 收集所有需要声明的 Go 符号
        all_go_symbols = set()
        for item in subr.values():
            if item.go_name:
                all_go_symbols.add(item.go_name)

        if not all_go_symbols:
            logging.warning("在 save_subr_refs 中没有找到任何子程序符号，可能不会生成任何引用。")
            return

        print('//go:cgo_import_dynamic local_dummy_for_cgo_export __TEXT__ ""', file=fp)
        print(file=fp)

        # 为每个符号声明一个函数存根
        for symbol in sorted(list(all_go_symbols)):
            print('//go:nosplit', file=fp)
            print('//go:noescape', file=fp)
            print(f'func {symbol}()', file=fp)
            print(file=fp)

        # --- 生成变量引用 ---
        print('var (', file=fp)
        mlen = max((len(s) for s in subr), default=0)
        data = sorted(subr.items())

        # 为每个子程序创建一个变量，直接引用其函数符号
        for subr_name, item in data:
            if not item.go_name:
                logging.error(f"Subroutine '{subr_name}' 缺少 go_name，无法生成引用。")
                continue
            
            # 直接将函数地址转换为 uintptr
            # 注意：item.offset 应该总是 0，因为我们直接引用 TEXT 块的开头
            # 但为了兼容性，如果它非零，我们还是加上它
            print(f'    _subr_{subr_name.ljust(mlen)} = uintptr(unsafe.Pointer({item.go_name})) + {item.offset}')

        print(')', file=fp)
        print(file=fp)

        # --- 生成栈大小常量 ---
        print('const (', file=fp)
        for subr_name, item in data:
            print(f'    _stack_{subr_name} = {item.stack_size}')
        print(')', file=fp)
        print(file=fp)

        # --- 生成 "unused" 变量以避免编译错误 ---
        print('var (', file=fp)
        for subr_name, _ in data:
            print(f'    _ = _subr_{subr_name}')
        print(')', file=fp)
        print(file=fp)

        print('const (', file=fp)
        for subr_name, _ in data:
            print(f'    _ = _stack_{subr_name}')
        print(')', file=fp)

def make_subr_filename(name: str) -> str:
    name = os.path.basename(name)
    base = os.path.splitext(name)[0].rsplit('_', 2)

    if len(base) > 1 and base[-1] in GOOS:
        return f"{'_'.join(base[:-1])}_subr_{base[-1]}.go"
    elif len(base) > 1 and base[-1] in GOARCH:
        if len(base) > 2 and base[-2] in GOOS:
            return f"{'_'.join(base[:-2])}_subr_{base[-2]}_{base[-1]}.go"
        else:
            return f"{'_'.join(base[:-1])}_subr_{base[-1]}.go"
    else:
        return f"{'_'.join(base)}_subr.go"